### ISSUE TITLE
Second sticky sidebar

### ISSUE THREAD

**Issue by dimitri-koenig** [livewire/flux#10]
Hi there

This is probably more of a discussion question issue, but I'll post it anyway.

How can I add a second sidebar, like the first is the main one, and the second next to it is the sub-sidebar.

Thx
Best
Dimitri

**Comment by calebporzio** [comment]
Hmmm good question. I'll say there are no current plans to support that. Best thing to do would be to copy the contents of the sidebar component into your own "sub-sidebar" component or something, then tweak until it fits your needs.
