### ISSUE TITLE
[PRO] Sidebar issue (wire:navigate)

### ISSUE THREAD

**Issue by nox-software** [livewire/flux#101]
On smaller screens, the sidebar takes up space after navigating with `wire:navigate`.
After refreshing the page or resizing the window the layout is normal again.

![sidebar](https://github.com/user-attachments/assets/a3efd6fd-3721-4cbe-855c-6faadd27141b)

This can be fixed by replacing the boolean with a check (also used in resize event).

`x-data="{ screenLg: true }"` > `x-data="{ screenLg: window.innerWidth >= 1024 }"`

**Comment by gaiustemple** [comment]
Experiencing this also.

**Comment by cbautista103** [comment]
Also experiencing this when using the sidebar on mobile with `wire:navigate`. @nox-software, can you share where you're implementing this fix?

**Comment by nox-software** [comment]
@cbautista103 you can use `php artisan flux:publish` and choose `Layout` to publish the view.
After that, you can implement this fix in `./resources/views/flux/sidebar/index.blade.php`.

@calebporzio could you change the original file so this works by default?

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
