### ISSUE TITLE
v-pre doesn't work as an $attribute because it expands to v-pre="v-pre"

### ISSUE THREAD

**Issue by jackmcdade** [livewire/flux#102]
If you're mixing and matching Vue and Flux, setting a `v-pre` attribute on a flux component doesn't work because Vue is looking for _specifically `v-pre`, while Flux expands all null value attributes to `attr="attr"`. It would be great if there was a way to set a null attribute. 

Not critical of course because I can publish the component and add it myself, but it sure would be nice :)

Love flux so much dude you have no idea.

**Comment by joshhanley** [comment]
@jackmcdade no worries! 🙂

**Comment by joshhanley** [comment]
Bugger 😕
