### ISSUE TITLE
Validation messages not being showed in flux:input, select, etc.

### ISSUE THREAD

**Issue by joelpiccoli** [livewire/flux#105]
Hello there!
I'm facing an issue with Flux where the error messages are never shown in form validations. The red border is there, but no messages are displayed.

![Captura de tela 26 09 2024 às 12 25 25 PM](https://github.com/user-attachments/assets/a0276f69-b4b8-4bde-8c03-f0dcb734d0c3)

---

This is the partial of the form:

![Captura de tela 26 09 2024 às 12 27 51 PM](https://github.com/user-attachments/assets/481b0ffa-e15a-4d5c-8df2-c97caef40b5c)

The Form Object:

```php
class ClientsForm extends Form
{
    ....

    #[Validate('required|email|unique:client')]
    public $email = '';

    #[Validate('required|min:8|max:32')]
    public $password = '';

    ....
}
```

And where it's called:

```php
class ClientForm extends Component
{

public ClientsForm $form;

// ....

public function save()
    {
        $this->form->validate();

        $client = new Client;

        $client->name = $this->form->name;
        $client->email = $this->form->email;
        // ....
        $client->password = \Hash::make($this->form->password);
        // ....

        $client->save();

       // ....
    }
   // ....
}
```

Any ideas what am I doing wrong? xD

---

Versions I have installed:

![Captura de tela 26 09 2024 às 12 37 49 PM](https://github.com/user-attachments/assets/d832b81b-fa8d-4015-9b34-ea64df21d325)

**Comment by ryanpilbeam** [comment]
You need to add a label attribute to the `<flux:input>` element, or you can include the error manually with `<flux:error name="email" />`.

**Comment by joelpiccoli** [comment]
That's it @ryanpilbeam ! Thanks for the help! I never imagined that would be this! I'll add labels, but wouldn't it be better to offer something like an error name prop or something? Just like:

```blade
<flux:input type="email" error-bag="email" autocomplete="email" placeholder="Email" wire:model='form.email' />
```

In the case that, I don't want to use the label in my forms...

Anyways, thanks for the help man!

**Comment by lucasromanojf** [comment]
> That's it @ryanpilbeam ! Thanks for the help! I never imagined that would be this! I'll add labels, but wouldn't it be better to offer something like an error name prop or something? Just like:
> 
> ```
> <flux:input type="email" error-bag="email" autocomplete="email" placeholder="Email" wire:model='form.email' />
> ```
> 
> In the case that, I don't want to use the label in my forms...
> 
> Anyways, thanks for the help man!

You can do it by doing something like this:

`<flux:field>
    <flux:input wire:model="form.email.../>
    <flux:error name="form.email"/>
</flux:field>`

This way you don't need to add label.
