### ISSUE TITLE
🐛 Breadcrumbs item + wire=navigate doesn't work

### ISSUE THREAD

**Issue by SRWieZ** [livewire/flux#106]
Taken this code

```blade
<flux:breadcrumbs.item href="/some/internal/route" wire:navigate>
    My website
</flux:breadcrumbs.item>
```

This generates an HTML where wire:navigate is passed to the div around the `<a>` tag.

FIX: It can be fixed by moving "wire:navigate" to the `<a>` tag.

**Comment by beneyraheem** [comment]
#71

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
