### ISSUE TITLE
🎨 input.group + select variants are not showing equally

### ISSUE THREAD

**Issue by SRWieZ** [livewire/flux#108]
Maybe I'm taking the composability too far but I feel like this can be fixed

```blade
<flux:field>
    <flux:label>Repository</flux:label>
    <flux:input.group>
        <flux:select placeholder="Choose a repository..." wire:model="repository">
                <flux:option>bar</flux:option>
                <flux:option>baz</flux:option>
        </flux:select>
        <flux:button wire:click="loadRepos" type="button">
            Refresh
        </flux:button>
    </flux:input.group>
    <flux:error name="repository"/>
</flux:field>
```

Things to look at:
- Input border merging
- input right border rounded 
- "No results" always showing (I think it's because I'm laze loading $repos after the initial page load)

<img width="707" alt="Capture d’écran 2024-09-26 à 18 31 05" src="https://github.com/user-attachments/assets/4dc2e88b-2748-453f-8848-f6b5b4358160">

variant:combobox
<img width="730" alt="Capture d’écran 2024-09-26 à 18 32 27" src="https://github.com/user-attachments/assets/90e3ea47-e879-481c-b5f5-96d08b1c5d18">

variant:listbox
<img width="730" alt="Capture d’écran 2024-09-26 à 18 32 43" src="https://github.com/user-attachments/assets/e75cf751-0e43-4d3a-bf49-d369f016d9c5">

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
