### ISSUE TITLE
Opt Out of Dark Mode on Publish

### ISSUE THREAD

**Issue by rossvasquez** [livewire/flux#11]
Dark mode is a great feature baked into TailwindCSS and provides an easy interface towards a11y and individual preferences. However, in my use case we will use Flux with clients that have no desire for dark and light mode.

When components are published, it would be nice to have a flag like `--no-dark` to reduce some of the tailwind clutter in an extended component.

The most glaring issue would be doubling the package size unless this could be parsed out programmatically.

Just a DevEx thought. Loving Flux over WireUI so far though, thank you for all the hard work!

**Comment by rzv-me** [comment]
the fastest way to fix this to add this to your tailwind config:
```javascript
export default {
    darkMode: ['variant', [
        '&:is(body.dark *)',
    ]],
//    .....
}
```
this way only if the body contains the `dark` class will the dark variant modifiers apply

**Comment by rossvasquez** [comment]
@rzv-me I appreciate your willingness to offer some help! However, this issue is related to developer experience around `dark:` classes presence in custom components via the publish feature. It is not an issue that affects any sort of performance or expectation of applied styles. Rather, for readability and cross-team work; the `dark:` modifiers may be confusing when an app doesn't utilize dark mode. My current solution is to delete them all manually upon publishing a new component. This will get tedious over time though in a rapid development environment.

**Comment by rzv-me** [comment]
I agree with you. I created a version of `src/Console/PublishCommand.php` that strips all the dark mode classes. 

If @calebporzio is interested I can create a PR for him to check

**Comment by calebporzio** [comment]
Yeah, I could see the need for something like that. For now I would say use the provided snippet, or this configuration: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually, and leave it.

I have no plans to offer that type of customization out of the box right now to keep things tightly scoped. Thanks
