### ISSUE TITLE
Default select component not applying name attribute 

### ISSUE THREAD

**Issue by beneyraheem** [livewire/flux#118]
### Issue: `default select` Not Handling `name` Attribute

- The `select` component in FluxUI does not work with the `name` attribute as expected. 

### Example Code:
```blade
<flux:select name="industry" placeholder="Choose industry...">
    <flux:option>Photography</flux:option>
    <flux:option>Design services</flux:option>
    <flux:option>Web development</flux:option>
    <flux:option>Accounting</flux:option>
    <flux:option>Legal services</flux:option>
    <flux:option>Consulting</flux:option>
    <flux:option>Other</flux:option>
</flux:select>
```

### Expected Fix:
- Apply `name` like in the `input` component: `@isset($name) name="{{ $name }}" @endisset`.

**Comment by patrykszady** [comment]
https://github.com/livewire/flux/issues/91

@persist('toast')
    <flux:toast />
    @endpersist

**Comment by patrykszady** [comment]
--my comment was meant for another Issue. ignore this.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
