### ISSUE TITLE
Typo in Select Documentation

### ISSUE THREAD

**Issue by lovenick** [livewire/flux#12]
Not sure if there's a way to PR the docs.

On the Select component page, the first example has a typo of ```<flex:option...``` vs ```<flux:option...```

https://fluxui.dev/components/select

**Comment by rzv-me** [comment]
yea, the first option of the first code sample is `<flex:option>Photography</flux:option>`

**Comment by bensherred** [comment]
A PR has been opened to fix this so. Thank you
