### ISSUE TITLE
Scrollbar appears on Table Head

### ISSUE THREAD

**Issue by unnathianalytics** [livewire/flux#120]
In blank table this scroll bar on table head appears
![image](https://github.com/user-attachments/assets/2772851d-add8-4ced-adba-599ed0645510)

But with while the table has data, it disappears
![image](https://github.com/user-attachments/assets/44e3df5f-a4ed-4640-be19-96ecdbc4c8cd)

Is this CSS issue form my code or from Flux ?

**Comment by 3adeling** [comment]
please share your code

**Comment by Illizian** [comment]
I've noticed this too. It's when the `<tbody>` is empty.
```html
<flux:table>
    <flux:columns>
        <flux:column>Column</flux:column>
    </flux:columns>

    <flux:rows>
        @php
            $empty = []
         @endphp
        @foreach([] as $item)
          <flux:row>
            {{ $item }}
          </flux:row>
        @endforeach
    </flux:rows>
</flux:table>
```

**Comment by joshhanley** [comment]
@unnathianalytics and @Illizian thanks for reporting! I have submitted a PR to fix this.
