### ISSUE TITLE
checkbox with :disabled visually disabled, stil clickable

### ISSUE THREAD

**Issue by lotje-kinable** [livewire/flux#124]
When you use :disabled (Blade dynamic attribute syntax) with a Livewire property (bool), the checkboxex are visually disabled but still clickable untill there is a full page refresh (and the other way around when it is no longer disabled) see the video.

I also added my code snippet, because maybe I am not using :disabled correctly. Behaviour is the same for both snippets. 

https://github.com/user-attachments/assets/e06081c1-02b6-434e-8fb9-0d60a618e98b

`<flux:checkbox.group :disabled='$isLoodswezen' label="Status">
       <flux:checkbox  wire:model.live="toActivate" label="Nog te activeren ({{ count($this->to_activate_users) }})" />
        <flux:checkbox wire:model.live="isActive" label="Actief ({{ count($this->active_users) }})" />
         <flux:checkbox wire:model.live="isDeactivated" label="Gedeactiveerd ({{ count($this->deactivated_users) }})" />
     </flux:checkbox.group>`
     
     
     
     ` <flux:checkbox.group label="Status">
                <flux:checkbox :disabled='$isLoodswezen' wire:model.live="toActivate" label="Nog te activeren ({{ count($this->to_activate_users) }})" />
                <flux:checkbox :disabled='$isLoodswezen' wire:model.live="isActive" label="Actief ({{ count($this->active_users) }})" />
                <flux:checkbox :disabled='$isLoodswezen' wire:model.live="isDeactivated" label="Gedeactiveerd ({{ count($this->deactivated_users) }})" />
            </flux:checkbox.group>`
            
Thanks!

**Comment by 3adeling** [comment]
don't use single quotation. use double quotation instead `"`

```
<flux:checkbox.group label="Status">
    <flux:checkbox :disabled="$isLoodswezen" wire:model.live="toActivate" label="Nog te activeren ({{ count($this->to_activate_users) }})" />
    <flux:checkbox :disabled="$isLoodswezen" wire:model.live="isActive" label="Actief ({{ count($this->active_users) }})" />
    <flux:checkbox :disabled="$isLoodswezen" wire:model.live="isDeactivated" label="Gedeactiveerd ({{ count($this->deactivated_users) }})" />
</flux:checkbox.group>
```

**Comment by lotje-kinable** [comment]
@3adeling Sadly using double quotes makes no difference... thanks though!

**Comment by lotje-kinable** [comment]
Update:

the 'label/text' is clickable after :disabled=false, but the checkboxes aren't. 

so: 
1. disabled=true
checkbox clickable, label/text not
2. refresh
nothing clickable
3. disabled=false
checkbox not clickable, label/text is clickable
4. refresh
everything clickable

**Comment by patrykszady** [comment]
same here

**Comment by jeffchown** [comment]
@calebporzio Could this be a problem with the underlying Alpine code?
I'm experiencing the same issue when using the x-radio Alpine UI Headless radio component

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
