### ISSUE TITLE
Autocomplete stops working after typing value with no options

### ISSUE THREAD

**Issue by youmustwearface** [livewire/flux#13]
1. In the docs, type "a" > offers Alabama...
2. Type "aa" > offers nothing
3. Delete input
4. Type "a" > offers nothing

Works again after reload of course.

**Comment by rzv-me** [comment]
for me it works, can you write a few more details? maybe check the console to see if there are any errors?

**Comment by youmustwearface** [comment]
It works in Chrome 129.0.6668.59. Works in Firefox 123.0b1 with broken layout. Does not work in Safari 18.0.

Nothing in console.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
