### ISSUE TITLE
inset not working in table cell?

### ISSUE THREAD

**Issue by brouwersron** [livewire/flux#151]
I'm following along on the demo project Caleb made a video about on x. In his video the alignment looks good, but in my project it seems that insset is not correctly working, the is my stripped cell:

```
<flux:row>
    <flux:cell>
        <flux:button size="sm" variant="ghost" icon="ellipsis-horizontal" inset="top bottom"/>
    </flux:cell>
</flux:row>
```

Without inset, the alignment looks good:

https://i.imgur.com/Fo9pMxT.png

But after adding inset like in the code above, it looks like this:

https://i.imgur.com/TGnxFkx.png

It seems that the bottom alignment is not working?

**Comment by dicktornfeldt** [comment]
Just had the same issue here. Solved it by doing this:
```
<flux:cell>
    <div class="flex">
        <flux:spacer />
        <flux:button variant="ghost" size="sm" icon="ellipsis-horizontal" inset="top bottom" />
    </div>
</flux:cell>
```

Ugly hack, but if you can't wait for it to be fixed, it's a way to fix it.

**Comment by calebporzio** [comment]
Hmmm this is a side effect of the display type of `td`. The issue would be resolved if the `<flux:cell>` element was flex by default, however I'm not sure that's a great idea at this point.

I'm going to close this in favor of doing the following for inset to work.

```html
<flux:cell class="flex">...</flux:cell>
```

Let's keep an eye on this though.
