### ISSUE TITLE
[navbar - header] can't inject @asset() into logo=""

### ISSUE THREAD

**Issue by helderneves91** [livewire/flux#152]
Hello, I'm using the layout provided in the docs, header version.

Take this line of code:
`<flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" name="Acme Inc." class="max-lg:hidden dark:hidden" />`

In `logo=""`, if I replace it with `<flux:brand href="#" logo="{{ asset("app_assets/logos/logo1.png") }}" name="{{ config('app.name') }}" class="max-lg:hidden dark:hidden" />`, the navbar becomes white, basically all items disappear.

**But** if I hard-code the link, it works as expected.

<img width="1728" alt="Captura de ecrã 2024-09-27, às 18 38 21" src="https://github.com/user-attachments/assets/f45488a5-ef1d-4cd6-9141-2238ebc5adf4">

**Comment by idealerror** [comment]
Use `:logo=""` instead of `logo=""`

**Comment by helderneves91** [comment]
> Use `:logo=""` instead of `logo=""`

Hi, doesn't work.

**Comment by idealerror** [comment]
That's not a very helpful response.  What didn't work?

```php
<flux:brand href="#" :logo="asset('app_assets/logos/logo1.png')" :name="config('app.name')" textSize="text-xl" class="px-2 dark:hidden" />
```

**Comment by helderneves91** [comment]
> That's not a very helpful response. What didn't work?
> 
> ```
> <flux:brand href="#" :logo="asset('app_assets/logos/logo1.png')" :name="config('app.name')" textSize="text-xl" class="px-2 dark:hidden" />
> ```

Was using {{ }} , `:logo="asset('app_assets/logos/logo1.png')"` works as expected.
Just mailed this to the support, since it's not documented.

Thanks @idealerror 🫡

**Comment by ju5t** [comment]
@helderneves91 so you're saying:

```blade
<flux:brand href="#" :logo="asset('app_assets/logos/logo1.png')" />
```

works, but

```blade
<flux:brand href="#" logo="{{ asset('app_assets/logos/logo1.png') }}" />
```

does not? That's very unlikely, as this just normal Blade, not Flux. About that, the `:logo` shorthand is not something Flux specific either. It's [Blade's short attribute syntax](https://laravel.com/docs/11.x/blade#short-attribute-syntax).

**Comment by helderneves91** [comment]
> @helderneves91 so you're saying:
> 
> ```
> <flux:brand href="#" :logo="asset('app_assets/logos/logo1.png')" />
> ```
> 
> works, but
> 
> ```
> <flux:brand href="#" logo="{{ asset('app_assets/logos/logo1.png') }}" />
> ```
> 
> does not? That's very unlikely, as this just normal Blade, not Flux. About that, the `:logo` shorthand is not something Flux specific either. It's [Blade's short attribute syntax](https://laravel.com/docs/11.x/blade#short-attribute-syntax).

Hi, yeee... doesn't make sense.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
