### ISSUE TITLE
[navbar - header] if the name is empty , logo doesn't appear

### ISSUE THREAD

**Issue by helderneves91** [livewire/flux#153]
Hello, I'm using the layout provided in the docs, header version.

Take this line of code:
`<flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" name="Acme Inc." class="max-lg:hidden dark:hidden" />`

In name="Acme Inc.", if I replace it with `name=""` (empty), the logo disappears and show's the logo url.

<img width="251" alt="Captura de ecrã 2024-09-27, às 18 53 01" src="https://github.com/user-attachments/assets/1e517463-19e2-4188-8d8b-085b806e7830">

I have the solution, just doesn't really know If I can post it since it's a closed-source package 🤨

**Comment by idealerror** [comment]
Confirming this is a bug.  

The fix should be to update the `<?php else: ?>` in `flux:brand` to use the same code when a name is not present.

```php
<?php else: ?>
    <a href="{{ $href }}" {{ $attributes->class($classes) }} data-flux-brand>
        <div class="size-8 rounded overflow-hidden">
            <?php if (is_string($logo)): ?>
                <img src="{{ $logo }}" />
            <?php else: ?>
                {{ $logo ?? $slot }}
            <?php endif; ?>
        </div>
    </a>
<?php endif; ?>
```

**Comment by helderneves91** [comment]
Yes, was what I tried.
An hack is to pass just a space, `name=" "`.

I will live with the hack and wait for the brand file to be patched.

**Comment by idealerror** [comment]
You should keep this issue open so it can be fixed.

**Comment by ju5t** [comment]
If you don't want the name, just leave out the prop. There is no need for it to be there if you don't want it.

This is perfectly fine.

```blade
<flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" class="max-lg:hidden dark:hidden" />
```

**Comment by helderneves91** [comment]
> If you don't want the name, just leave out the prop. There is no need for it to be there if you don't want it.
> 
> This is perfectly fine.
> 
> ```
> <flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" class="max-lg:hidden dark:hidden" />
> ```

Hi, please try to replicate the issue.

**Comment by ju5t** [comment]
Ah, sorry, I misread the issue. You're right. @idealerror has the correct solution here.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
