### ISSUE TITLE
Errors with components based on custom elements

### ISSUE THREAD

**Issue by nissicreative** [livewire/flux#154]
I am just getting started with Flux and running into issues with the components that are based on custom elements (radios, checkboxes, switches...)

They don't render correctly and the browser console logs errors like:
`Uncaught TypeError: Cannot read properties of undefined (reading '_durableAttributeObserver')`
and
`Uncaught NotSupportedError: Failed to construct 'CustomElement': The result must not have attributesUnderstand this error`

I am attaching a screenshot of the console output.

iMac 3.8 GHz 8-Core Intel Core i7
macOS 14.6.1 (23G93)
Chrome Version 129.0.6668.60 (Official Build) (x86_64)
Safari Version 17.6 (19618.3.11.11.5)

![CleanShot 2024-09-27 at 13 46 06](https://github.com/user-attachments/assets/883d18a6-550b-49f1-9efe-667e5104c745)

**Comment by jeffchown** [comment]
@nissicreative Can you share some code too?

**Comment by calebporzio** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps to reproduce. Then, we will be happy to help.

**Comment by ju5t** [comment]
Although we didn't have the `NotSupportedError`, the `_durableAttributeObserver` error can show up if you have two `flux:field` inside another `flux:field`.

**Comment by magarrent** [comment]
Hey! Same here: **Uncaught NotSupportedError: Failed to construct 'CustomElement': The result must not have attributes**

Just pasted the tabs from the docs:

```
<flux:tab.group>
    <flux:tabs>
        <flux:tab name="profile" icon="user">Profile</flux:tab>
        <flux:tab name="account" icon="cog-6-tooth">Account</flux:tab>
        <flux:tab name="billing" icon="banknotes">Billing</flux:tab>
    </flux:tabs>

    <flux:tab.panel name="profile">...</flux:tab.panel>
    <flux:tab.panel name="account">...</flux:tab.panel>
    <flux:tab.panel name="billing">...</flux:tab.panel>
</flux:tab.group>
```

**Comment by colinmac17** [comment]
@nissicreative @calebporzio hey!

I was able to reproduce on the latest flux with this code. If I remove the flux:description, the error goes away. Not sure if I'm doing something wrong?

```
<flux:field class="col-span-2">
                        <flux:textarea
                            wire:model="form.bio"
                            label="About me"
                        />
                        <flux:description>Tell coaches about yourself. What makes you unique? What are your goals? What are you looking for in a college How can you help their team/program?</flux:description>
                        <flux:error name="form.bio" />
                    </flux:field>
```

Error:
```
flux.min.js?id=5b5b9c60:125 Uncaught TypeError: Cannot read properties of undefined (reading '_durableAttributeObserver')
    at u (flux.min.js?id=5b5b9c60:125:8689)
    at t.associateDescription (flux.min.js?id=5b5b9c60:125:70511)
    at ai.mount (flux.min.js?id=5b5b9c60:125:71413)
    at flux.min.js?id=5b5b9c60:125:9887
```

**Comment by jeffchown** [comment]
@colinmac17 No issue/error with your code here.

![Image](https://github.com/user-attachments/assets/37d27d31-f556-4877-97da-9f9634880fd1)
