### ISSUE TITLE
Docs: Installation note to run php artisan route:cache

### ISSUE THREAD

**Issue by mauritskorse** [livewire/flux#16]
Took me half an hour to figure out I had to call `php artisan route:cache` to make the flux/flux.js route work.
Maybe add it to the docs?

**Comment by joshhanley** [comment]
@mauritskorse it should work without running `php artisan route:cache`, and works fine for me without caching.

I'm going to close this for now, but if you find what the problem is, feel free to reopen or open a new issue.
