### ISSUE TITLE
flux:navbar with child flux:dropdown item can't be highlighted as "current"

### ISSUE THREAD

**Issue by ibnIrshad** [livewire/flux#162]
See the following code. If you have a `flux:dropdown` within a `flux:navbar`, then setting the "current" attribute on the `navbar.item` doesn't work. The reason is because the `current` attribute requires the `href` attribute to be set. But you can't set an `href` attribute on a dropdown because it then breaks the dropdown.

**Scenario 1: "current" doesn't work, but the dropdown works**

```html
<flux:navbar>
    <flux:dropdown>
        <flux:navbar.item icon-trailing="chevron-down" current>Account</flux:navbar.item>
    </flux:dropdown>
</flux:navbar>
```
**Scenario 2: "current" works but then the dropdown doesn't work**

```html
<flux:navbar>
    <flux:dropdown>
        <flux:navbar.item icon-trailing="chevron-down" current href="#">Account</flux:navbar.item>
    </flux:dropdown>
</flux:navbar>
```

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
