### ISSUE TITLE
flux:select does not allow for an "@if" statement.

### ISSUE THREAD

**Issue by lcallif** [livewire/flux#166]
Same result inside and outside a flux Modal.  

The following results in an error:     syntax error, unexpected token "endif"
                            <flux:select name="industry" placeholder="Choose industry...">
                                @foreach($refviews->where('theType','=','ynType') as $theVal)
                                    <flux:option value="{{ $theVal->id }}"
                                            @if ($bomcomponent->id == $theVal->id) SELECTED @endif>
                                        {{ $theVal->shortDescription }}</flux:option>
                                @endforeach
                            </flux:select>

The following kind of works as expected inside the Modal, works as expected outside the Modal. More in a separate bug entry.
                                <label>
                                {{ __('Taxable ?') }}
                                </label>
                                <x-bct-fancyselect
                                    wire:model="inputs.{{ $loop->index }}.typeId">
                                </x-bct-fancyselect>
                                <option >-- Taxable Selection is Required --</option>
                                @foreach($refviews->where('theType','=','ynType') as $theVal)
                                    <option value="{{ $theVal->id }}"
                                    @if ($bomcomponent->id == $theVal->id) SELECTED @endif>
                                        {{ $theVal->shortDescription }}</option>
                                @endforeach
                                </select>

Hopefully I didn't miss something in the manual stating this needs to be done in a different way.  If so, I apologize.

**Comment by codeldev** [comment]
Assumeing this is not being used with wire:model, I tested the following which worked fine:


```
    <flux:select name="industry" placeholder="Choose industry...">
        @foreach($this->data as $key => $label)
            <flux:option value="{{ $key }}" :selected="($key === 3)">
                {{ $label }}
            </flux:option>
        @Endforeach
    </flux:select>
```

Hope that helps

**Comment by joshhanley** [comment]
@lcallif Blade doesn't allow you to put `@if` tags on components, so Flux won't work either.

You need to use the `:selected=...` syntax.

**Comment by lcallif** [comment]
Blade does allow for the @if tags in a component.  The following is an example of what I have been using for quite some time now, with no issues.  So far, the only place I have been having a problem is when I use it within a Modal.  

<option value="{{ $theVal->id }}" @if ($bomcomponent->id == $theVal->id) SELECTED @endif>

Once I take the @if ($bomcomponent->id == $theVal->id) SELECTED @endif  section out then the error goes away.

Howeverrrrrr, changing the syntax is no problem.  Especially since it resolves the error.

Thank you.

Ummmmmm, since the workaround works for me, but "@if...."  doesn't work, I am not sure if this bug report should have remained open.

I have a solution so I am a happy camper.  Thank you joshhanley.

**Comment by codeldev** [comment]
@lcallif 

While it may have worked for you previously, the [Laravel docs](https://laravel.com/docs/11.x/blade#passing-data-to-components) do state:

"PHP expressions and variables should be passed to the component via attributes that use the : character as a prefix:"

```
<x-alert type="error" :message="$message"/>
```

So I would not call this a bug as your usage was not intended.

Using :selected is a lot cleaner than @if anyway :) (imo).

Either way, you have a working & 'intended' solution.

**Comment by joshhanley** [comment]
@lcallif can you show me a working example of a blade component working with `@if` because I can't get it working?

I just tested this and it doesn't work:

```blade
<div>
    <x-test @if(true) selected @endif />
</div>
```

If you can give me some code that works, I will happily re-open this as it would be a bug in Flux 🙂

**Comment by lcallif** [comment]
Hopefully the following example assists....  And yes, I agree with you about the :selected being cleaner.  I am in the process of adding in code for all of my forms to allow for Modals.  I will be changing all of the @if statements in the select areas to use the :selected.  What the heck, I am already doing a considerable amount of work on them, I may as well change it at the same time.

The simplest example
----------------------
                    <div class="input flex flex-col w-fit static">
                        <label
                        <x-bct-fancylabel></x-bct-fancylabel>
                        @error('typeId') text-red-500 @endif">
                        @error('typeId')
                            {{ __($message) }}
                            <br>
                        @else
                            {{ __('Customer Type') }}*
                        @endif
                        </label>
                        <x-bct-fancyselect
                            wire:model="typeId">
                        </x-bct-fancyselect>
                        <option>-- Customer Type is Required --</option>
                        @foreach($refviews->where('theType','customerType') as $theVal)
                            <option @if ($theVal->id == $customers->typeId) Selected @endif
                                     value="{{ $theVal->id }}">{{ $theVal->shortDescription }}</option>
                        @endforeach
                        </select>
                    </div>


bct-fancylabel
---------------
class = "text-black text-lg font-semibold relative top-2 px-[6px] bg-[#e8e8e8] ml-2 w-fit

bct-fancyselect
----------------
@props(['disabled' => false])

<select {{ $disabled ? 'disabled' : '' }}
    {!! $attributes->merge(['class' => 'px-3 py-3.5 h-17 border-2 border-black focus:border-indigo-500
        focus:ring-indigo-500 rounded-md border-blue-400 px-[10px] py-[20px] text-lg bg-[#e8e8e8] border-2
        rounded-[5px] w-[340px]
        focus:outline-black placeholder:text-black/25']) !!}>

**Comment by lcallif** [comment]
Hopefully the following example assists.... And yes, I agree with you about the :selected being cleaner. I am in the process of adding in code for all of my forms to allow for Modals. I will be changing all of the @if statements in the select areas to use the :selected. What the heck, I am already doing a considerable amount of work on them, I may as well change it at the same time.

The simplest example
```php
                <div class="input flex flex-col w-fit static">
                    <label
                    <x-bct-fancylabel></x-bct-fancylabel>
                    @error('typeId') text-red-500 @endif">
                    @error('typeId')
                        {{ __($message) }}
                        <br>
                    @else
                        {{ __('Customer Type') }}*
                    @endif
                    </label>
                    <x-bct-fancyselect
                        wire:model="typeId">
                    </x-bct-fancyselect>
                    <option>-- Customer Type is Required --</option>
                    @foreach($refviews->where('theType','customerType') as $theVal)
                        <option @if ($theVal->id == $customers->typeId) Selected @endif
                                 value="{{ $theVal->id }}">{{ $theVal->shortDescription }}</option>
                    @endforeach
                    </select>
                </div>
```
bct-fancylabel
--------------
```php
class = "text-black text-lg font-semibold relative top-2 px-[6px] bg-[#e8e8e8] ml-2 w-fit
```
bct-fancyselect
----------------
``` php
@props(['disabled' => false])

<select {{ $disabled ? 'disabled' : '' }}
{!! $attributes->merge(['class' => 'px-3 py-3.5 h-17 border-2 border-black focus:border-indigo-500
focus:ring-indigo-500 rounded-md border-blue-400 px-[10px] py-[20px] text-lg bg-[#e8e8e8] border-2
rounded-[5px] w-[340px]
focus:outline-black placeholder:text-black/25']) !!}>
```

**Comment by joshhanley** [comment]
@lcallif sorry I think I didn't explain myself well. You can't use `@if` when calling a blade component ie inside `<x-my-component>`. You can still use `@if` inside the component itself.

It doesn't look like you are using `@if` when calling your blade components in the latest code you shared, which is different to the original issue where you were.

Just to be clear this does not work for blade components or flux (as flux is just blade components:

```blade
{{-- This won't work --}}
<x-my-component @if(true) selected @endif />

{{-- This won't work either --}}
<flux:input @if(true) selected @endif />
```
