### ISSUE TITLE
Select does not display the row marked as "Select".  Nor does it have thee row marked with a check.

### ISSUE THREAD

**Issue by lcallif** [livewire/flux#167]
The following works as expected outside the Modal, but not inside the Modal.
                                <label>
                                {{ __('Taxable ?') }}
                                </label>
                                <x-bct-fancyselect
                                    wire:model="inputs.{{ $loop->index }}.typeId">
                                </x-bct-fancyselect>
                                <option >-- Taxable Selection is Required --</option>
                                @foreach($refviews->where('theType','=','ynType') as $theVal)
                                    <option value="{{ $theVal->id }}"
                                    @if ($inputs[$loop->index]['taxableId'] == $theVal->id) SELECTED @endif>
                                        {{ $theVal->shortDescription }}</option>
                                @endforeach
                                </select>

Inside the Modal the row that is marked as "SELECTED" does not appear to the User as being Selected: The selected row is not displayed, rather the "Taxable Selection is Required" row is displayed.  None of the rows are marked with a check next to it.

Looking at the webpage's source shows that the row is selected as expected.

Livewire Component
  - The following is the array being used for the wire:model value and for determining if the option value is to be marked as selected
       foreach ($this->bomcomponents as $getbomcomponent) {
            array_push($this->inputs, [
                "title" => $getbomcomponent->title,
                "price" => $getbomcomponent->price,
                "typeId" => $getbomcomponent->typeId,
                "description" => $getbomcomponent->description,
                "labormaterialboth" => $getbomcomponent->labormaterialboth,
                "taxableId"   => $getbomcomponent->taxableId,
            ]);
        }

![Screen Shot 2024-09-28 at 11 30 15 PM](https://github.com/user-attachments/assets/7e8a5155-0eff-48f3-af00-b344f96d8fab)
![Screen Shot 2024-09-28 at 11 27 34 PM](https://github.com/user-attachments/assets/a005f9bc-a253-4c27-b69c-0ca4bd7af026)

**Comment by lcallif** [comment]
And the solution is to use 
    placeholder="Taxable Selection is Required"
instead of 
    <option selected value="0">-- Taxable Type is Required --</option>

This solution actually takes care of this issue and slims down the validation used in the Livewire Component.

Thank you Josh for inadvertently, or purposely, showing me this solution.  

Yeahhhhhhhhhhhhhhh

**Comment by joshhanley** [comment]
@lcallif heh, no worries (indvertantly) 😁

Also in future, hen you paste code into github, you need to surround it in triple back ticks and then specify the file type like php or blade. It provides code highlighting and makes it much easier for us to read 🙂

For example
\```php
\\ PHP code here
\```

\```blade
\\ HTML and blade code here
\```
