### ISSUE TITLE
Cannot use wire:model on <flux:autocomplete>

### ISSUE THREAD

**Issue by mauritskorse** [livewire/flux#17]
When trying to wire model the autocomplete component I get the error 1`Cannot use wire:model on <flux:autocomplete>`.
Also tried it with the example in the docs.

(using Laravel 11.)

**Comment by WanderingDaniel** [comment]
Can replicate using Laravel 10.

**Comment by idealerror** [comment]
It looks like this is hardcoded into the autocomplete stub:

```php
Flux::disallowWireModel($attributes, 'flux:autocomplete');
```

**Comment by joshhanley** [comment]
@mauritskorse thanks for reporting, I have opened a PR https://github.com/livewire/flux-pro/pull/5 to fix this on the Flux Pro (private) repo.

**Comment by christopherarter** [comment]
Apologies if this is a dumb question, but will this fix be available as a flux-pro version bump? I see it's been closed but not sure if the PR is merged or what the normal bug fix flow will be for the pro stuff. (I'm also encountering this bug on flux-pro)

Thanks!

**Comment by tanshiqi** [comment]
It looks like the problem still exists

**Comment by joshhanley** [comment]
The fix for this has now been released in Flux Pro v1.0.1, so please update.
