### ISSUE TITLE
Button with Icon prop, vs. Button with Icon inside

### ISSUE THREAD

**Issue by Illizian** [livewire/flux#170]
I've discovered either an issue, or a requirement 😆...

The following is an example of the problem I am trying to solve/report:
```html
<flux:button size="sm" variant="danger" wire:click="delete()">
    <flux:icon.x-mark wire:loading.remove wire:target="delete" />
    <flux:icon.loading wire:loading wire:target="delete" />
</button>

<flux:button size="sm" variant="danger" icon="x-mark" wire:click="delete()" />
```

The first `<flux:button />` is one in which the icon changes to the loading icon whilst we await a livewire action. The second is just a simple button that will simply send the action.

Unfortunately (for me), they look different:

![Screenshot 2024-09-29 at 11 53 35](https://github.com/user-attachments/assets/2c3e344d-dc35-4dc5-ac9f-ed3ee8892c44)

This is due to the second (hidden) loading icon in the first button - which is quite challenging.

**Comment by Illizian** [comment]
This is primarily a "challenge" within Livewire itself, but I'd greatly appreciate your input before we close and move to a livewire solution.

**Comment by jeffchown** [comment]
@Illizian In the `flux:button` code it looks like it adds the `micro` variant to the icon by default.  Have you tried `<flux:icon.x-mark wire:loading.remove wire:target="delete" variant="micro" />` to see if it looks more like a match?

**Comment by Illizian** [comment]
> @Illizian In the `flux:button` code it looks like it adds the `micro` variant to the icon by default. Have you tried `<flux:icon.x-mark wire:loading.remove wire:target="delete" variant="micro" />` to see if it looks more like a match?

Good call, but unfortunately not
![Screenshot 2024-09-29 at 14 49 34](https://github.com/user-attachments/assets/6c653879-fb63-4e72-bdaa-afe1e7196170)

**Comment by jeffchown** [comment]
Hmmm... The other thing that the `views/flux/button/index.php` blade does is check for a button with no content and assigns true to `$square` (via `$square ??= empty((string) $slot);`).  This `$square` value is then used to adjust the padding in a square button based on the button's size variant.

If you check out the code in `view/flux/button/index.php` you should be able to determine what the icon (I'd try `mini` next) and padding settings should be for your first button to match the 2nd button's appearance.

**Comment by calebporzio** [comment]
Yeah thanks Jeff, this is what the `square` prop is intended for: https://fluxui.dev/components/button#square

![CleanShot 2024-09-29 at 16 44 50@2x](https://github.com/user-attachments/assets/073a1b91-6a9e-4e32-9a7b-956fe68d19f7)

![CleanShot 2024-09-29 at 16 45 54@2x](https://github.com/user-attachments/assets/52710300-5585-4afe-9611-3dfd6f784033)

**Comment by calebporzio** [comment]
And like Jeff said, you can add the `micro` variant to the icons to make them match the intended icon size if you want.
