### ISSUE TITLE
Card padding

### ISSUE THREAD

**Issue by brouwersron** [livewire/flux#172]
I'm trying to build the kanban board: https://fluxui.dev/demo/kanban - And I am using the dark mode only right now.

Here is the code for the flux:card:

```
  <flux:card class="dark:bg-zinc-800 p-3 space-y-2">
      <div class="flex gap-2">
          <flux:badge size="sm" color="red">Bug</flux:badge>
      </div>
  </flux:card>
```

This produces the first card in the screenshot below (the background is changed but the padding remains the default):

https://i.imgur.com/HZzSkGt.png

In the second card on the screenshot I simply used a div instead of flux:card. Maybe I am missing something or is it a bug that the padding always stays 6, like the blade template?

```
@php
$classes = Flux::classes()
    ->add('p-6 rounded-xl')
    ->add('bg-white dark:bg-white/10')
    ->add('border border-zinc-200 dark:border-white/10')
@endphp
```

**Comment by brouwersron** [comment]
Then I believe this is not a bug but just me :) Thanks!

**Comment by jeffchown** [comment]
You're welcome, @brouwersron 👍
