### ISSUE TITLE
Flux Radio Group not working properly when wired with wire:model.live

### ISSUE THREAD

**Issue by lonebadger99** [livewire/flux#173]
<flux:radio.group wire:model.live="relationship_type">
                        <flux:radio
                            value="Familiar"
                            label="Familiar"
                        />
                        <flux:radio
                            value="Other"
                            label="Other"
                        />
</flux:radio.group>

When wired like this, the radio button works but it resets every time you select something. So if you have Familiar selected and then select Other, it shows the selection changing to other and then clears the selection so none is selected. It works ok with wire:model but not with wire:model.live. I´m using v1.0.2.

**Comment by calebporzio** [comment]
Ah thank you for the report. This has been fixed and will be available in the next release. Thanks!
