### ISSUE TITLE
<flux:header> and <flux:sidebar> not working in separate component

### ISSUE THREAD

**Issue by azizabbas** [livewire/flux#174]
I copied Header code from here: https://fluxui.dev/layouts/header and put it in app.blade.php layout file as instructed.

Now, I am trying to separate the navigation which is implemented using  `<flex:header>` and `<flux:sidebar>` but it is miss-aligned because we have to wrap it around a <div> element.

So, how exactly we can put top navigation into separate component? Is there any `<flux>` element that can replace `<div>`

screenshot also attached.

<img width="1381" alt="Screenshot 2024-09-29 at 19 32 11" src="https://github.com/user-attachments/assets/af1eb69e-aeb4-42a2-a7a8-1bc8c6b1f15d">
<img width="1381" alt="Screenshot 2024-09-29 at 19 32 47" src="https://github.com/user-attachments/assets/41dc17ac-0f97-4b87-9d88-7628cb12b8d3">

**Comment by calebporzio** [comment]
Hi there, I just tried to recreate the problem and couldn't. 

Please submit a github gist of code that I can copy and paste into a volt component to recreate your problem.

![CleanShot 2024-09-29 at 12 25 04@2x](https://github.com/user-attachments/assets/1406e11c-1f26-4e71-b3b8-13ef4e6a283c)

**Comment by azizabbas** [comment]
Hi Caleb, thanks for your reply.

Here is gist link as you requested: https://gist.github.com/azizabbas/db3405aabb225dc67b58dbcfd86a7c79

Also, when I am creating two separate components for `<flux:header>` and `<flex:sidebar>` then it is working as expected. Maybe that information helps.

**Comment by calebporzio** [comment]
Ah, ok, thank you for the response.

So what you are doing is kind of a hack, but fortunately there is a way to make it work. Just add the `contents` Tailwind class to the root div of the Livewire component and it should fix all the grid positioning issues:

![CleanShot 2024-09-29 at 16 42 11@2x](https://github.com/user-attachments/assets/1dcfaa75-51f0-4d3c-902c-213b5c40acbb)

![CleanShot 2024-09-29 at 16 42 56@2x](https://github.com/user-attachments/assets/71b200fe-7813-49e4-8967-7ab242e000ad)

**Comment by azizabbas** [comment]
Thank you so much for your time and Support.
