### ISSUE TITLE
Checkbox validation errors displayed incorectly

### ISSUE THREAD

**Issue by orchidcode** [livewire/flux#175]
Displaying validation errors causes the checkbox label to be displayed incorrectly.

```
<flux:checkbox wire:model='terms' label="{{ __('By completing this registration, you hereby agree to our General Terms and Conditions, and to our Data privacy policy.') }}" />
```

<img width="487" alt="Zrzut ekranu 2024-09-29 o 18 44 51" src="https://github.com/user-attachments/assets/b64da848-81ed-4e4f-8640-66e4e0524c4a">

**Comment by calebporzio** [comment]
Thanks for the report, this has been fixed and will be in the next release
