### ISSUE TITLE
Click away to dismiss a Modal

### ISSUE THREAD

**Issue by mauricekindermann** [livewire/flux#181]
Right now you can close modals using ESC or the X button. That's tricky my users (many/most are 50+). Any chance we could get an option to allow the ability to click away? 

I personally think this should be the default (since it is dismissable, just not in all ways you expect), but if you have reasons for it being the way it is, then something like `canClickAway, default=false;` would be great.

```blade
<flux:modal name="example-modal" canClickAway="true">
    <!-- Modal stuff -->
</flux:modal>
```

**Comment by dicktornfeldt** [comment]
This is already a feature request here: #131

**Comment by joshhanley** [comment]
@mauricekindermann yep @dicktornfeldt is correct, we already have #131 as a feature request, so going to close this issue.
