### ISSUE TITLE
"Icon-Button" wire:click adds space to the left.

### ISSUE THREAD

**Issue by philippbuerger** [livewire/flux#183]
Hey, I'm using a simple button with only an icon in it. Works fine but when I'm adding a `wire:click` to the button there appears a weird space to the right of the icon:

`
<flux:button
    icon="plus"
    wire:click="$set('urlCount', {{ $urlCount + 1 }})"
/>
`

![Bildschirmfoto 2024-09-30 um 14 28 21](https://github.com/user-attachments/assets/3326411b-8c62-4c9a-9da2-f9b72f17e1a7)

**Comment by joshhanley** [comment]
@philippbuerger try using the `square` attribute when you're only using an icon. https://fluxui.dev/components/button#square

Going to close this, feel free to reopen if you feel there is still a bug.

**Comment by philippbuerger** [comment]
Hi @joshhanley that works, thank you. Wondering why it is documented the way I wrote it:

https://fluxui.dev/components/button#icons

**Comment by joshhanley** [comment]
@philippbuerger probably just a bug with the documentation, I will update it.

**Comment by philippbuerger** [comment]
Maybe it can be fixed in the component itself? Would be great to use it that way

**Comment by joshhanley** [comment]
@philippbuerger yeah feel free to submit a feature request 🙂

**Comment by philippbuerger** [comment]
@joshhanley maybe I will 🤓
