### ISSUE TITLE
Missing viewable/copyable/clearable for input fields in Documentation

### ISSUE THREAD

**Issue by DonCamillo11** [livewire/flux#184]
I couldn't find the viewable/copyable/clearable properties for input fields in the documentation. I only know about it because I saw it in the talk.

**Comment by joshhanley** [comment]
@DonCamillo11 not sure exactly what you mean. Can you provide some links/ screenshots? Thanks!

**Comment by DonCamillo11** [comment]
Starting from minute 14:10 in Calebs Laracon Talk, he is talking about vieable/clearable and copyable input fields.

<img width="1067" alt="Bildschirmfoto 2024-09-30 um 14 37 43" src="https://github.com/user-attachments/assets/99029f64-2787-456f-967f-608e85b674b4">

[https://youtu.be/31pBMi0UdYE?feature=shared&t=850](url)

**Comment by jeffchown** [comment]
To help, these files exist in the flux/input/group/ directory (ignore the index.php):

<img width="230" alt="image" src="https://github.com/user-attachments/assets/5ba67136-f6d8-44ed-83ff-a0e62fc82aa5">

**Comment by calebporzio** [comment]
Good call, just added them for you: https://fluxui.dev/components/input#clearable,-copyable,-and-viewable-inputs
