### ISSUE TITLE
Clipboard button throwing Alpine error in documentation

### ISSUE THREAD

**Issue by benjibee** [livewire/flux#189]
Attempting to copy code examples from the documentation throws the following error in the console:

```js
module.esm.js:433 Alpine Expression Error: Cannot read properties of null (reading 'copy')

Expression: "$el.closest('.relative').querySelector('code-candy').copy(); $el.parentElement.setAttribute('data-copied', ''); setTimeout(() => $el.parentElement.removeAttribute('data-copied'), 2000)"
```
I've tested this in Google Chrome and Firefox on the https://fluxui.dev/layouts/header page.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and is public.
