### ISSUE TITLE
A way to check an `accordion.item`'s open/closed state

### ISSUE THREAD

**Issue by jeffchown** [livewire/flux#19]
Loving Flux, @calebporzio !

Question: Is there a way to check whether an `accordion.item` is open or closed?

e.g. `$el.isOpen` or something like that?

I want the accordion.item's heading to change according to the item's state.

Thanks.

**Comment by jeffchown** [comment]
Found it.  Closing issue/question.

**Comment by igmltd** [comment]
> Found it. Closing issue/question.

What was the solution?

**Comment by jeffchown** [comment]
@igmltd The Flux accordion component uses an Alpine `open` var, so you can check that var in your code, e.g.:

```
<flux:accordion.heading>
  <span x-show="open">Open Heading</span>
  <span x-cloak x-show="! open">Closed Heading</span>
</flux:accordion.heading>
```
