### ISSUE TITLE
`size` attribute on `<flux:input />` conflicts with native size attribute.

### ISSUE THREAD

**Issue by MartijnCuppens** [livewire/flux#193]
It's not possible to render a size attribute on the `<flux:input>` because it conflicts with the size option.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size

Input
```html
<flux:input size="5" />
```

Expected
```html
<input size="5" ... />
```

Result
```html
<input ... />
```

A semi solution would be to check the type of `size`, and if it is a number, add the `size` attribute to the `<input />`

**Comment by calebporzio** [comment]
Ah good catch - for now I'm just detecting if the `size` prop is numeric, and then passing it through to input and select. Good catch again, thanks.
