### ISSUE TITLE
Accordions use `<div>`s instead of `<detail>`s, which disables find in page functionality.

### ISSUE THREAD

**Issue by MartijnCuppens** [livewire/flux#194]
`<detail>` elements open automatically when you use in-page search, to test this out you can search for "something"  (second time) here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details.

<img width="990" alt="image" src="https://github.com/user-attachments/assets/bafe2897-7a7c-447e-9d38-1f00f9dc7abd">

This functionality is lacking from the accordion component.

**Comment by calebporzio** [comment]
Oh that's cool - right now we're going to stick with our custom ui-disclosure element, however, I could be convinced to switch to details in the next major version. The reason we didn't go with it to begin with is they don't have a way to transition them open and closed.
