### ISSUE TITLE
Breadcrumbs Unresponsive with wire:navigate

### ISSUE THREAD

**Issue by cbautista103** [livewire/flux#199]
When using breadcrumbs as outlined in the docs `<flux:breadcrumbs.item href="/" icon="home" />`, breadcrumbs navigation functions as expected. When adding `wire:navigate`, the breadcrumb renders the <a> tag correctly in the DOM (and the browser status bar, for instance, can tell that the correct link exists in the DOM), but clicking the link produces no action in the browser.

**Comment by cbautista103** [comment]
Duplicate of #71

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
