### ISSUE TITLE
Class Merging Bug in Flux Pro Select Listbox Variant

### ISSUE THREAD

**Issue by rossvasquez** [livewire/flux#20]
Issue affecting pro select component variant listbox border-radius when size is overridden from default

**Steps to reproduce**
1. Publish select component
2. Observe Tailwind border-radius class applied to all variants on `line 13` of `flux/select/button.blade.php`
3. Observe Tailwind border-radius' applied to size variants starting on `line 17` of `flux/select/button.blade.php`
4. Create a test component: `<flux:select variant="listbox" />`
5. Query styles in browser tools for class mentioned in step 2
6. Observe that regardless of variant, `line 13` radius is applied

It is my understanding that TailwindCSS applies styles based on their order in the generated css file, not the `classList`.

**Comment by patrykszady** [comment]
https://github.com/livewire/flux/issues/60
https://github.com/livewire/flux/issues/100

**Comment by calebporzio** [comment]
Good catch - fixed!
