### ISSUE TITLE
Meaning of "selectable" prop on table/table row

### ISSUE THREAD

**Issue by slovenianGooner** [livewire/flux#200]
Hi,

what is the meaning of the "selectable" on `<flux:table>` and other child components. It displays a checkbox, but there is no docs for that and also no way of binding that to a `wire:model`.

Currently I do it in a hacky way by wrapping the table into a `<flux:checkbox.group>` and adding a `<flux:checkbox>` myself.

```php
        <flux:checkbox.group wire:model="selectedRows">
            <flux:table>
                <flux:columns>
                    <flux:column class="!pl-3">
                        <flux:checkbox.all/>
                    </flux:column>
                </flux:columns>

                <flux:rows>
                    @foreach($this->orders as $order)
                        <flux:row :key="$order->id"
                                  class="has-[[data-flux-checkbox][data-checked]]:bg-zinc-100
                                         has-[[data-flux-checkbox][data-checked]]:dark:bg-zinc-600/75">
                            <flux:cell class="!pl-3">
                                <flux:checkbox value="{{ $order->id }}"/>
                            </flux:cell> 
                        </flux:row>
                    @endforeach
               </flux:rows>
           </flux:table>
        </flux:checkbox.group>
```

The expected behaviour based on the available props on `<flux:table>` component would be:

```php
<flux:table selectable wire:model="selectedRows">
```

which would replicate the same behaviour as above.

**Comment by calebporzio** [comment]
Sorry that wasn't meant to go into production (it's undocumented) - I removed it from Flux in the next release

**Comment by pkeogan** [comment]
@calebporzio since your removing that feature, do you have a 'flux' approved pattern to implement what @slovenianGooner is trying to accomplish?

**Comment by pkeogan** [comment]
@slovenianGooner I found a better work around: see my reply here https://github.com/livewire/flux/issues/336#issuecomment-2402912022
