### ISSUE TITLE
New loading indicator not visible on button

### ISSUE THREAD

**Issue by DonCamillo11** [livewire/flux#201]
The new loading indicator on buttons is not working for me. Updated to 1.0.4 but the loading indicator won’t show up and the text is still visible. I haven't published any components. Tested also the way from Calebs newsletter https://gist.github.com/calebporzio/ff706c4c646b4f3afa76fb2549737ba8 but it doesn't work either.

**Comment by calebporzio** [comment]
Please re-submit with a copy and pastable code snippet
