### ISSUE TITLE
Radios lacking arrow key navigation

### ISSUE THREAD

**Issue by MartijnCuppens** [livewire/flux#203]
Arrow key navigation doesn't work on the radio inputs. It does seem to work once you are navigating with tab (see video below).

https://github.com/user-attachments/assets/11b11cf6-e66a-46e8-b4ae-ef89c4216d8f

https://fluxui.dev/components/radio

```html
<flux:radio.group wire:model="payment" label="Select your payment method">
    <flux:radio value="cc" label="Credit Card" checked />
    <flux:radio value="paypal" label="Paypal" />
    <flux:radio value="ach" label="Bank transfer" />
</flux:radio.group>
```

The tabs component does seem to support arrow navigation without the need of "switching to a keyboard user".

**Comment by joshhanley** [comment]
@MartijnCuppens thanks for reporting, I just tested this on the latest version of Flux v1.0.6 and arrow navigation is working as expected, so I'm going to close this. Please update and test it locally (as the docs may be out of date).

**Comment by MartijnCuppens** [comment]
I still encounter this issue. I've installed version `1.0.6` and ran `php artisan cache:clear`. The issue is also still present on the docs site (which might be an older version indeed, idk).

To be clear, I'll explain my reproduction steps:
1. Use the snippet on the docs site locally or just go to the docs site to test it out: https://fluxui.dev/components/radio
2. After you click "Paypal" (click is important here), you should be able to use up/down keys to select another value. As you can see in the video, that doesn't work as the page scrolls up and down.
3. Once you press the tabkey and navigate to the next radio buttons, the navigation does suddenly work like expected.

**Comment by joshhanley** [comment]
@MartijnCuppens ah right yeah I understand. I guess it's not a huge issue as it does work if you are already using keyboard navigation, just not mouse-keyboard navigation 😆. Feel free to reopen if you think it's something we should look into.

**Comment by joshhanley** [comment]
@MartijnCuppens yep, fair. I've reopened it for you

**Comment by calebporzio** [comment]
I decided to support programmatically focusing the radio when clicking the label so that this keyboard navigation works. The reason I didn't originally, was browsers will now always show the focus ring even when a user is using their mouse which feels yucky and non-native. However, this is really the only option until `focusVisible` option is added to browsers, which it may never be: https://caniuse.com/?search=focusVisible
