### ISSUE TITLE
Add `pointer-events-none` to input icons that aren't interactive

### ISSUE THREAD

**Issue by MartijnCuppens** [livewire/flux#204]
I once saw my mom clicking on the magnifying glass icon when she wanted to select a search input field. Should we add `pointer-events-none` to decorative icons (icons that aren't buttons or have tooltips) to help out all mothers in the same situation?

```html
<flux:input icon="magnifying-glass" placeholder="Search orders" />
```

<img width="418" alt="image" src="https://github.com/user-attachments/assets/368f3918-6bed-4a3a-995a-f9015f516a20">

**Comment by calebporzio** [comment]
Great suggestion, implemented!
