### ISSUE TITLE
[tables] Dialog opens multiple times

### ISSUE THREAD

**Issue by darviscommerce** [livewire/flux#206]
I used the same code as Caleb in the featured movie, but I am experiencing an issue where the dialog opens multiple times.

Maybe I’m doing something wrong, but I suggest adding the correct example with the tables, as I think this is a feature that will be used a lot. :)

<img width="877" alt="Scherm­afbeelding 2024-10-01 om 12 13 58" src="https://github.com/user-attachments/assets/17ea3451-c02c-4f64-b754-8f3593c9b552">

```blade
<flux:table :paginate="$items">
    <flux:columns>
        <flux:column></flux:column>
        <flux:column sortable :sorted="$sortCol === 'firstname'" :direction="$sortAsc" wire:click="sort('firstname')">Name</flux:column>
        <flux:column sortable :sorted="$sortCol === 'email'" :direction="$sortAsc" wire:click="sort('email')">Email</flux:column>
    </flux:columns>
    <flux:rows id="sortable">
        @foreach ($items as $item)
            <flux:row :key="$item->id" data-id="{{ $item->id }}">
                <flux:cell class="sorthandle">
                    <i class="fa-solid fa-sort"></i>
                </flux:cell>
                <flux:cell>{{ $item->firstname }}</flux:cell>
                <flux:cell>{{ $item->email }}</flux:cell>
                <flux:cell align="right">
                    <flux:dropdown align="end" offset="-15">
                        <flux:button icon="ellipsis-horizontal" size="sm" variant="ghost" inset="top bottom" />
                        <flux:menu class="min-w-32">
                            <flux:menu.item icon="eye" href="{{ route('contactperson.read', ['contactperson' => $item]) }}">View</flux:menu.item>
                            <flux:menu.item wire:click="remove" icon="trash" variant="danger">Delete</flux:menu.item>
                        </flux:menu>
                    </flux:dropdown>
                    <flux:modal name="member-remove" class="min-w-[22rem]">
                        <form class="space-y-6" wire:submit="$parent.remove({{ $item->id }})">
                            <div>
                                <flux:heading size="lg">Delete?</flux:heading>
                                <flux:subheading>
                                    <p>Sure you want to delete <strong>{{ $item->title }}</strong>?</p>
                                </flux:subheading>
                            </div>
                            <div class="flex">
                                <flux:spacer />
                                <flux:modal.close>
                                    <flux:button variant="ghost" class="mr-3">Cancel</flux:button>
                                </flux:modal.close>
                                <flux:button type="submit" variant="danger">Delete</flux:button>
                            </div>
                        </form>
                    </flux:modal>
                </flux:cell>
            </flux:row>
        @endforeach
    </flux:rows>
</flux:table>

**Comment by alexmanase** [comment]
Can you show the video and the timestamp?

**Comment by skatecram** [comment]
Currently, when you call Flux::modal('member-remove')->show();, it opens all modals with the name "member-remove".
To ensure each modal has a unique name, you can assign names dynamically using the item's ID, like: 
`name="member-remove-{{ $item->id }}".`


Here's a possible solution:

Update the modal definition in your Blade template:

Delete button:
```blade
<flux:menu.item wire:click="remove({{ $item->email }})" icon="trash" variant="danger">Delete</flux:menu.item>
```

Modal:
```blade
<flux:modal name="member-remove-{{ $item->id }}" class="min-w-[22rem]">
```

Modify the remove function to handle unique modal names:
```php
public function remove($itemId)
{
    Flux::modal('member-remove-' . $itemId)->show();
}
```

**Comment by lloydowen** [comment]
If it were me, i'd launch the modal using listeners and pass the `$id` as a property on dispatch. Then the Modal (Separate livewire component) sets its self up with the ID on the listened to event.
Something like this...
Triggering component:
```php
public function editAddressHistory($key)
{
    $this->dispatch('update-address-history', $key,  $this->address_history[$key]);
}
 ```

Modal:
```php
#[On('update-address-history')]
public function edit($key, $form): void
{
    $this->key = $key;
    $this->form->fill($form);
    $this->modal('address-history-modal')->show();
}
```

**Comment by skatecram** [comment]
> If it were me, i'd launch the modal using listeners and pass the `$id` as a property on dispatch. Then the Modal (Separate livewire component) sets its self up with the ID on the listened to event.
> 
> I'm not sure how Caleb would launch a modal with data, but it seemed inefficient to load a modal for every row in a table for example.
> 
> Something like this... Triggering component:
> 
> ```
> public function editAddressHistory($key)
> {
>     $this->dispatch('update-address-history', $key,  $this->address_history[$key]);
> }
> ```
> 
> Modal:
> 
> ```
> #[On('update-address-history')]
> public function edit($key, $form): void
> {
>     $this->key = $key;
>     $this->form->fill($form);
>     $this->modal('address-history-modal')->show();
> }
> ```
I also prefer this way

**Comment by darviscommerce** [comment]
> Currently, when you call Flux::modal('member-remove')->show();, it opens all modals with the name "member-remove". To ensure each modal has a unique name, you can assign names dynamically using the item's ID, like: `name="member-remove-{{ $item->id }}".`
> 
> Here's a possible solution:
> 
> Update the modal definition in your Blade template:
> 
> Delete button:
> 
> ```
> <flux:menu.item wire:click="remove({{ $item->id }})" icon="trash" variant="danger">Delete</flux:menu.item>
> ```
> 
> Modal:
> 
> ```
> <flux:modal name="member-remove-{{ $item->id }}" class="min-w-[22rem]">
> ```
> 
> Modify the remove function to handle unique modal names:
> 
> ```
> public function remove($itemId)
> {
>     Flux::modal('member-remove-' . $itemId)->show();
> }
> ```

Thanks a lot, but this is not working for me 😬
As said before my code is an exact copy of @calebporzio his [video](https://vimeo.com/1011642608/478575dea1?share=copy)
And i love that clean code 😍😍

**Comment by darviscommerce** [comment]
> In his video, all modals open, but you can't see them because they all have the same width. In your example, you can see the modal behind because you have output the title in the modal, which changes the modal width.

I actually didn't notice that.
That would mean that unfortunately it doesn't work as well (now) as it does on the film 😢

**Comment by skatecram** [comment]
It works wenn you use unique names in this aproche.

Reference is made to this here::
https://github.com/livewire/flux/issues/43#issuecomment-2371024857

**Comment by darviscommerce** [comment]
Thanks all, it's not as easy as i hoped ;)

I can now see that a separate component has been created, within which the Modal is called...

Also, check out the code from the video via this link:
[https://github.com/livewire/flux-app/blob/main/resources/views/livewire/team/members.blade.php](https://github.com/livewire/flux-app/blob/main/resources/views/livewire/team/members.blade.php)

```blade
<flux:table class="mt-8">
    <flux:columns>
        <flux:column>Name</flux:column>
        <flux:column>Email</flux:column>
        <flux:column>Role</flux:column>
        <flux:column></flux:column>
    </flux:columns>

    <flux:rows>
        @foreach ($team->members as $member)
            <livewire:team.member :$member :key="$member->id" />
        @endforeach
    </flux:rows>
</flux:table>
