### ISSUE TITLE
Autosizing textarea doesn't work in safari or firefox

### ISSUE THREAD

**Issue by benshawuk** [livewire/flux#21]
Tested in Chrome (MacOS) - works.
However, Safari and Firefox don't observe the autosize behaviour.

**Comment by rzv-me** [comment]
I think the reason this doesn't work, is that `field-sizing` css property is not supported in Safari & Firefox: 

https://developer.mozilla.org/en-US/docs/Web/CSS/field-sizing
https://caniuse.com/?search=field-sizing

**Comment by calebporzio** [comment]
Thanks @rzv-me!

I added a note to the docs:

![CleanShot 2024-09-24 at 21 53 48@2x](https://github.com/user-attachments/assets/d3b59d0a-249b-44e2-8b88-2e3a3f576508)
