### ISSUE TITLE
Clicking on a searchable select inside a dropdown menu closes dropdown menu

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/flux#212]
Hello,

consider a searchable select inside a dropdown. If I click the select to search or select an option, the dropdown menu closes immediately.

**Comment by joshhanley** [comment]
@lucasromanojf please provide code that we can copy and paste to replicate the issue and if possible a screen capture so we can see what is going on (using something like https://gifcap.dev/). I'm going to close this for now, feel free to reopen once you have added details. Thanks!

**Comment by lucasromanojf** [comment]
Hello @joshhanley 

Here is the example Volt component code:

```
<?php

use function Livewire\Volt\{state};

state('test')->url();

?>

<div>
    <flux:dropdown>
        <flux:button variant="ghost" class="!bg-gray-100" icon="adjustments-horizontal"/>

        <flux:menu class="px-3 py-2 pb-3">
            <flux:select searchable variant="listbox" size="sm" label="Test select" wire:model.live="test" placeholder="Select an option">
                <x-slot name="search">
                    <flux:select.search class="border-0 focus:border-zinc-200 focus:ring-0" />
                </x-slot>

                <flux:option value="">All</flux:option>
                <flux:option value="1">Option One</flux:option>
                <flux:option value="2">Option Two</flux:option>
                <flux:option value="3">Option Three</flux:option>
            </flux:select>
        </flux:menu>
    </flux:dropdown>
</div>
```

And here is the screen capture:

![Image](https://github.com/user-attachments/assets/a559c72c-f123-42b8-8789-f35eafb20696)

**Comment by joshhanley** [comment]
@lucasromanojf I saw you created a new issue, were you not able to reopen this issue?

**Comment by lucasromanojf** [comment]
@joshhanley I don't have permission to reopen the issue.

**Comment by joshhanley** [comment]
@lucasromanojf ah ok, no worries I thought people could do that.
