### ISSUE TITLE
Rename icon to _icon on flux:input does not prevent the component from showing an icon

### ISSUE THREAD

**Issue by jensolafkoch** [livewire/flux#213]
A lot of people (including me) use underscores to temporarily deactivate Tag-Properties like in:

```
<flux:input
   type="text"
   size="xl"
   label="Some label"
   _description="Some bla"
   wire:model.live.debounce.600ms="toBeAnagrammed"
   x-ref="firstInput"
   _icon="document-text"
>
```

That doesn't work prop "icon", probably some trimming issue with the prop name? "xicon" and "x_icon" do work, but pure underscores are visually much better to distinguish from other properties. 

Same does work for "description" and "_description" so probably an isolated problem related to "icon"?

**Comment by calebporzio** [comment]
Hmmm this is very curious behavior. I can't quite pin it down! However, this is more likely a nuance of Blade itself than Flux so I'm going to close this.

**Comment by jensolafkoch** [comment]
Okay, thanks for checking!

Than it's probably a Blade bug – I can see no reason why a prop named "_anyprop" should be detected as "anyprop". Could be related to detecting things like ":anyprop" and some glitch in a regex or so? Just a wild guess, I'm no Blade expert though.
