### ISSUE TITLE
[buttons] bad alignment when using wire:click

### ISSUE THREAD

**Issue by helderneves91** [livewire/flux#215]
Hi,

Let's considered this, which works fine and the icon is in the center.
`<flux:button icon="arrow-down-tray"></flux:button>`

This code will break the button and align the icon to the left:
`<flux:button wire:click="export_exam_report('{{ $exam->electrocardiogram_uuid }}')" icon="arrow-down-tray"></flux:button>`

<img width="213" alt="Captura de ecrã 2024-10-01, às 17 17 25" src="https://github.com/user-attachments/assets/96c791a9-4885-49dd-a01f-135cf63d76b1">

**Comment by helderneves91** [comment]
I'll leave this issue open to be analyzed.

I will use this as a workaround:
```
<flux:button wire:click="export_exam_report('{{ $exam->electrocardiogram_uuid }}')" size="sm">
    <flux:icon.arrow-down-tray variant="mini" />
</flux:button>
```

<img width="213" alt="Captura de ecrã 2024-10-01, às 17 25 18" src="https://github.com/user-attachments/assets/6b02e398-f98c-4474-af70-554853b5c679">

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
