### ISSUE TITLE
Wrong link to Docs in GitHub

### ISSUE THREAD

**Issue by jensolafkoch** [livewire/flux#216]
The link to the Flux Docs on [](https://github.com/livewire/flux/issues/new/choose) relays to the main Flux page, not the docs.

**Comment by calebporzio** [comment]
Please provide a link to what you are referring to. Thanks

**Comment by jensolafkoch** [comment]
When you open a "New Issue" here: [](https://github.com/livewire/flux/issues), the link at the bottom points to [](https://fluxui.dev/) instead of the docs (as the link says): [](https://fluxui.dev/docs/).

**Comment by joshhanley** [comment]
@jensolafkoch thanks! This has been fixed.
