### ISSUE TITLE
[inputs] input.date misleading color when in dark mode

### ISSUE THREAD

**Issue by helderneves91** [livewire/flux#226]
Hi,

When using light mode, the color of the input placeholder is OK, example:
![Image](https://github.com/user-attachments/assets/76023c1c-c19e-4884-889f-4588c07ea383)

When using dark mode the color is too vivid, should be more darker, otherwise the placeholder looks like an actual value. Example:
![Image](https://github.com/user-attachments/assets/4a84caa9-d0a0-472e-996c-c001d928c6a2)

Now with value:
![Image](https://github.com/user-attachments/assets/888bb0f7-a534-40b8-a2af-1e689c2db71f)

**Comment by joshhanley** [comment]
@helderneves91 looks fine to me, what browser and OS are you using?

![Image](https://github.com/user-attachments/assets/05e25509-978a-4a2c-bb1b-f15a3eb1b074)

![Image](https://github.com/user-attachments/assets/59ea4124-4f9f-482e-81f7-55def37e0064)

**Comment by helderneves91** [comment]
Hi @joshhanley , MacOS/safari, latest.
Looks good but now test with an actual value, the color will be more greyed out...

**Comment by calebporzio** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps to reproduce. Then, we will be happy to help.
