### ISSUE TITLE
Modals unable to close

### ISSUE THREAD

**Issue by omniith** [livewire/flux#228]
Hi, I put a modal in a brand new livewire component. Direct copy paste first example. Opening of modal has no issues, but unable to close when clicking the close X button. Did the same with the flyout example, unable to close. ESC button works. This is on flux pro 1.04

**Comment by joshhanley** [comment]
@omniith thanks for reporting. I just tested this on v1.0.4 and it is working as expected. Have you configured Flux scripts and styles in your layout?

I'm going to close this for now, but if you are still having issues, please share your layout file, your component class and view, and your route, as well as a screenshot of what you are currently seeing and reopen the isssue.

Thanks!

**Comment by omniith** [comment]
i'm so sorry, i had an import issue, all is working well on the modal now.

**Comment by lcallif** [comment]
What was your import issue and how did you fix it, please.  I have the first modal working as wanted/expected, but not others on the same form.

**Comment by omniith** [comment]
> What was your import issue and how did you fix it, please. I have the first modal working as wanted/expected, but not others on the same form.

i declared flux in other components, so i included in the main layout file and all works.
