### ISSUE TITLE
navlist.item active only works with direct links and not routes

### ISSUE THREAD

**Issue by idealerror** [livewire/flux#23]
I'm not sure if this is a feature request or a bug but if you specify a route instead of a direct link in a navbar item, the navbar item will not become active.   This is documented [here](https://fluxui.dev/components/navbar#detecting-the-current-page), but doesn't specifically mention that routes cannot be used.

Does not show as active:
```php
<flux:navlist.item href="{{ route('news') }}">Latest News</flux:navlist.item>
```

Shows as active:
```php
<flux:navlist.item href="/news">Latest News</flux:navlist.item>
```

**Comment by joshhanley** [comment]
@idealerror thanks for reporting! I have opened a PR #26 with a fix.
