### ISSUE TITLE
Use of 'icon-variant' breaks icon 'size' in buttons

### ISSUE THREAD

**Issue by christianheidorn** [livewire/flux#230]
Here's sample markup of a toolbar that I am working:
```html
<flux:button.group class="w-full mx-auto justify-center">
    <flux:button size="xs" icon="eye"></flux:button>
    <flux:button size="xs" icon="hand-thumb-up" icon-variant="outline"></flux:button>
    <flux:button size="xs" icon="heart" icon-variant="outline"></flux:button>
    <flux:button size="xs" icon="clipboard"></flux:button>
    <flux:button size="xs" icon="pencil-square"></flux:button>
    <flux:button size="xs" icon="folder-arrow-down"></flux:button>
    <flux:button size="xs" icon="trash"></flux:button>
</flux:button.group>
```

To illustrate the difference, I've applied icon-variant="outline" to two of the buttons. As you can see in the screenshot below, it breaks the size definitions and simply reverts to default sizing.

![Image](https://github.com/user-attachments/assets/71874d6d-e2b5-4a3a-8fd1-69ea965790cc)

**Comment by calebporzio** [comment]
Thanks for the report. Each icon variant is specifically designed to be used at it's default size. Mixing outline and solid variants is not recommended - therefore I recommend you do something like this for more full control:

```html
<flux:button square>
    <flux:icon.heart variant="outline" class="size-?" />
</flux:button>
```

**Comment by christianheidorn** [comment]
@calebporzio Thanks for the tip.

It wasn't my objective to mix solid and outline icons within the same toolbar. I was just trying to highlight the fact that when you apply `icon-variant` to buttons with an icon, it ignores the button's `size` attribute. Whereas, if you set an `icon-variant`, it adjusts the size perfectly.

Your suggested workaround works but it feels like the treatment of solid icons versus any other variant is somewhat inconsistent in this case.
