### ISSUE TITLE
Radio Button default "checked" option not working when using wire:model

### ISSUE THREAD

**Issue by azizabbas** [livewire/flux#231]
Hi,

I have just noticed that as soon I use `wire:model` on a Radio group, default "checked" is not working anymore.

Here is gist for code snippet: https://gist.github.com/azizabbas/69b870038b4a320037511ca37927c8c8

and

here is screenshot on how form is looking:

![Image](https://github.com/user-attachments/assets/a8752b22-f760-482f-87de-b2895e417271)

**Comment by joshhanley** [comment]
@azizabbas once you add `wire:model` Livewire will control the checked value for you. So you need to make sure you set your public property to the value you want checked. Going to close this, but feel free to reopen if you think there is still a bug.

**Comment by azizabbas** [comment]
Thanks for your reply @joshhanley 

It is working now.
