### ISSUE TITLE
New loading indicator not visible on button

### ISSUE THREAD

**Issue by DonCamillo11** [livewire/flux#233]
The new loading indicator on buttons is not working for me. Here is the code snippet I’m using to test the button:
`<flux:button type="submit">
    Save changes
</flux:button>`

Updated to flux v1.0.6. Tailwind is v3.4.13 and Livewire v3.5.9, no components published.
As you can see here, the button is disabled but the text does not fade out and the loading indicator does not fade in.

![Image](https://github.com/user-attachments/assets/a47f9942-14c9-4650-8bcf-9b3a0b852a17)

**Comment by joshhanley** [comment]
@DonCamillo11 can you please share your code for the demonstration in the screenshot (remove anything not relevant to the issue) so we can replicate it? Thanks!

**Comment by DonCamillo11** [comment]
This is a simple but non working code snippet.
Component:
```
namespace App\Livewire\Documents;

use Livewire\Component;

class DocumentCreate extends Component
{


    public function save()
    {
        sleep(5);
        dd("test");
    }
}
```

Blade:
```
<div>
    <form wire:submit="save">
        <flux:button type="submit">
            Save changes
        </flux:button>
    </form>
</div>
```
Result:
![Image](https://github.com/user-attachments/assets/86b0e5c8-b65b-4eba-ae62-aebb267c6b53)


Button is disabled, but the loading indicator is not visible


Blade:
```
<div>
    <form wire:submit="save">
        <flux:button wire:click="save">
            Save changes
        </flux:button>
    </form>
</div>
```
Result:
![Image](https://github.com/user-attachments/assets/614a3c46-e8af-494f-8588-69d41ed60038)

Button is not disabled either

**Comment by calebporzio** [comment]
What @helderneves91  said - I just tested this again and it works fine.
