### ISSUE TITLE
name="whatever" attribute on select please

### ISSUE THREAD

**Issue by knorthfield** [livewire/flux#234]
I noticed when you add wire:model="email", for example to an input it outputs name="email" on the final rendered input html.

But this does not happen on the select component. Could that be added?

**Comment by patrykszady** [comment]
I believe this was fixed in 1.0.7. see changelog below
https://changelog.anystack.sh/flux-pro    
"[Support name attribute on native select](https://github.com/livewire/flux-pro/commit/812bc14e19a72a97e09676665488f3b11b8db2f5)"

**Comment by knorthfield** [comment]
Yes it was, what quick customer service!
