### ISSUE TITLE
Scrolling not working after closing modal

### ISSUE THREAD

**Issue by mauritskorse** [livewire/flux#236]
Scrolling using the scroll wheel on the area where a modal used to be does not scroll the page anymore once the modal was closed.

https://github.com/user-attachments/assets/fcb1bc87-982e-4d2b-83dc-bc67833e0af8

**Comment by calebporzio** [comment]
Wow, that is really weird. I tried reproducing it and couldn't. Please re-submit with copy/pastable code that I can reproduce the problem in. Otherwise, I'll keep my eyes open for it to happen in a way that I can reproduce and fix myself. Thanks

**Comment by mauritskorse** [comment]
Okay, after some trying, it seems that when adding certain classes to the modal various issues occur.
My modal code from the example above had:

```html
<flux:modal name="instellingen" class="flex flex-col space-y-6 min-w-v-1/3 !max-w-v-4/5">
        ...
</flux:modal>
```

moving `flex flex-col space-y-6` into a div within the modal seems to fix the scrolling issue
```html
<flux:modal name="instellingen" class="min-w-v-1/3 !max-w-v-4/5">
        <div class="flex flex-col space-y-6">
                ...
        </div>
</flux:modal>
```
