### ISSUE TITLE
Clicking on a searchable select inside a dropdown menu closes dropdown menu

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/flux#238]
Hello,

consider a searchable select inside a dropdown. If I click the select to search or select an option, the dropdown menu closes immediately.

Here is the example Volt component code:

```
<?php

use function Livewire\Volt\{state};

state('test')->url();

?>

<div>
    <flux:dropdown>
        <flux:button variant="ghost" class="!bg-gray-100" icon="adjustments-horizontal"/>

        <flux:menu class="px-3 py-2 pb-3">
            <flux:select searchable variant="listbox" size="sm" label="Test select" wire:model.live="test" placeholder="Select an option">
                <x-slot name="search">
                    <flux:select.search class="border-0 focus:border-zinc-200 focus:ring-0" />
                </x-slot>

                <flux:option value="">All</flux:option>
                <flux:option value="1">Option One</flux:option>
                <flux:option value="2">Option Two</flux:option>
                <flux:option value="3">Option Three</flux:option>
            </flux:select>
        </flux:menu>
    </flux:dropdown>
</div>
```

And here is the screen capture:

![Image](https://github.com/user-attachments/assets/42dbeb37-bec8-4764-92af-40964a7d4255)

Thanks

**Comment by joshhanley** [comment]
@lucasromanojf this discussion #130 might be related, as I think it's what you would need to get the searchable select working in the dropdown.

**Comment by lucasromanojf** [comment]
> [@lucasromanojf](https://github.com/lucasromanojf) this discussion [#130](https://github.com/livewire/flux/discussions/130) might be related, as I think it's what you would need to get the searchable select working in the dropdown.

Yes, it might be related. Once it is available I can make a new test to see if it works.

**Comment by calebporzio** [comment]
Ok, so `<flux:select>` isn't meant to be nested inside `<flux:menu>`. Instead use `<flux:navmenu>` and the select should work.

However it will lose it's anchor positioning because of wire:model.live. When the request comes back it will wipe the style attributes applied by floating UI.

I'll keep digging on this, but hopefully this helps a little bit

**Comment by calebporzio** [comment]
I fixed a couple of issues. All anchor positioned elements like dropdowns and such won't lose anchoring with `wire:model.live`. Also I made it so you CAN use select elements inside of menus, although I'm not sure I recommend it.

Thanks for the report!
