### ISSUE TITLE
disclosureWalker is not properly skipping ui-disclosure elements

### ISSUE THREAD

**Issue by rzv-me** [livewire/flux#24]
I think the function `disclosureWalker` is not properly skipping `ui-disclosure` components

maybe
```javascript
// this 
if (!el.localName == "ui-disclosure") return skip();
// should be this
 if (el.localName !== "ui-disclosure") return skip();
```

**Comment by joshhanley** [comment]
@rzv-me thanks for reporting! Can you provide some code that demonstrates the issue so we can replicate it and get it fixed? Thanks!

**Comment by rzv-me** [comment]
not sure how to  "replicate" this. as this is obviously a mistake

in `livewire/flux-pro/js/disclosure.js`
``` javascript
    disclosureWalker() {
        return walker(this, (el, { skip, reject }) => {
            if (el instanceof UIDisclosureGroup && el !== this) return reject()
            if (! el.localName === 'ui-disclosure') return skip()
        })
    }
```


how can `!el.localName` ever strict equal `"ui-disclosure"`, the intention is to skip any element that isn't "ui-disclosure".

**Comment by calebporzio** [comment]
Thanks for the report, @rzv-me, but like Josh said, we will need you to point us to this code manifesting in a tangible issue to address it given the current workload.
