### ISSUE TITLE
[Table] in dark-mode no visual difference for active page in pagination

### ISSUE THREAD

**Issue by ultimateBusiness** [livewire/flux#246]
You can see the active page "3":

![Image](https://github.com/user-attachments/assets/566391a5-85ae-43fa-ac63-6c6bdd16becc)

But in dark-mode there is no difference - still page "3" active:

![Image](https://github.com/user-attachments/assets/74fb0af1-4642-4d17-a4d6-ccee7720c87f)

**Comment by helderneves91** [comment]
Same on date inputs

**Comment by calebporzio** [comment]
Good call - fixed!
