### ISSUE TITLE
Open modal allows the page scroll

### ISSUE THREAD

**Issue by taner** [livewire/flux#25]
When the modal is open you can scroll the page below.
The behavior can be seen in the examples here: https://fluxui.dev/components/modal

I believe you shouldn't be able to scroll the page below when the modal is open.

**Comment by patrykszady** [comment]
I love the way it is. If you'd like it to disable scroll, I'm sure there's a way (or there will be) to disable it. More of a feature request than an issue.

**Comment by patrykszady** [comment]
`variant="scroll/no_scroll" ` would be cool to make everyone happy.

flux/modal/index.blade.php
`@props([
    'variant' => 'default(scroll)',
])`

**Comment by calebporzio** [comment]
Yeah, this is the default behavior of the `<dialog>` element. I'm sure the browser vendors had good reason for allowing scroll so at this point, I'd like to just stick with the defaults. Thanks!
