### ISSUE TITLE
Dropdown not closing on click

### ISSUE THREAD

**Issue by DonCamillo11** [livewire/flux#253]
I would have expected a dropdown to close when clicked on the dropdown button itself. Is there a reason why this isn't the case?
A dropdown is only closing on an outside click.

**Comment by helderneves91** [comment]
Can you share the code to replicate the issue?

**Comment by DonCamillo11** [comment]
This is my dropdown.
```
<flux:dropdown>
    <flux:button wire:click.prevent.stop square icon="ellipsis-horizontal"  variant="ghost"></flux:button>
    <flux:menu>
        <flux:menu.item icon="pencil-square">Save</flux:menu.item>
        <flux:menu.item icon="document-duplicate">Duplicate</flux:menu.item>
        <flux:menu.item icon="trash" variant="danger">Delete</flux:menu.item>
    </flux:menu>
</flux:dropdown>
```
But you can replicate on the docs https://fluxui.dev/components/dropdown. It’s the same behaviour.

**Comment by helderneves91** [comment]
Well, I tested and the dropdown closes if I click in any option.

Do `composer update` to update flux and delete any published flux stubs

**Comment by DonCamillo11** [comment]
I don't mean the options in the dropdown. I mean the dropdown button itself. Usually you can close the dropdown the same way as you opened it.

**Comment by omniith** [comment]
I tested as well, no issues on my side for closing the dropdown. Best you share your layouts or work on a separate layout file and put flux dropdown there to see where is the issue while comparing to your existing.

**Comment by vincentcordel** [comment]
Is there a reason why it's not implemented?
This is the default behaviour in most UI components elsewhere...

**Comment by 0hra** [comment]
I would like to see this as well.

**Comment by calebporzio** [comment]
Fixing this is a high priority. It's not trivial because of the way the `[popover]` attribute behaves by default. But we will fix this in short order.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
