### ISSUE TITLE
Clearable input only clears input value without upading binded Livewire property

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/flux#255]
Below is an example code. You can see that the input is cleared, but the Livewire property binded to the input is not cleared. I've configured to show the "test" property on URL to make it easier to see.

```
<?php

use function Livewire\Volt\{state};

state('test')->url();

?>

<div>
    <flux:input wire:model.live="test" clearable/>
</div>
```

Here is a screen recording for easier understanding:

![Image](https://github.com/user-attachments/assets/52166d51-ecb5-43b7-bfe7-3f93caa9022d)

Thanks!

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
