### ISSUE TITLE
button-or-link.blade.php, href property issue

### ISSUE THREAD

**Issue by Jaiieq** [livewire/flux#256]
### Environment:

- Laravel 11.26.0
- Flux 1.0.6
- PHP 8.3.2
- Windows IIS Server

### Issue:

The href property is not correctly generating the link when using "{{ route('foobar' }}" but does when its manually entered.

### Example URL and Route:  

- domaon.com/site_name
- Route::get('foo',  [BarController::class, 'baz'])->name('foobar');

### Output:

Using the above Example URL and Route:

When using the named route , the URL generated removes 'site_name': **domain.com/foo**
When using a manual link of 'foo', the URL generated is; **domain.com/site_name/foo**

### The fix:

On line 8 of button-or-link, I reversed the ternary from

`$href = $href ? (string) str($href)->after(trim(config('app.url'), '/')) : $href;`

to

`$href = $href ? $href : (string) str($href)->after(trim(config("app.url"), "/"));`

### Conclusion:

At least in environments, Windows in particular in my case, where there are multiple tenants using the same base domain (domain.com/site1, domain.com/site2, etc). the above fix generates the correct URL with both the route() method and manually.

I also cloned the code to my mac with Herd installed and the above change seemed to work just fine as well.

**Comment by Jaiieq** [comment]
Just realized that this breaks the auto highlighting of the currently selected navlist.item.  Looking into it further.

**Comment by patrykszady** [comment]
> Just realized that this breaks the auto highlighting of the currently selected navlist.item. Looking into it further.

Update to 1.0.7 just so you’re diagnosing on the learners version.

**Comment by calebporzio** [comment]
Thanks for the report - please provide a copy/pastable snippet I can just plop in my app to reproduce and I'll be happy to take a look. Thanks again!
