### ISSUE TITLE
[pagination] text "entries" should be "results" to be consistent with Laravel

### ISSUE THREAD

**Issue by helderneves91** [livewire/flux#261]
Sup!!!
File `pagination.blade.php`.

To be consistent with `Laravel Pagination`, `__('entries')`should be renamed to `__('results')`.
This will ensure that packages like [https://github.com/Laravel-Lang/lang](url) use the right key to automatically translate the text.

Otherwise, people would need to create a new translation for entries.

I'm Portuguese, so the locale is `pt`.
The translated pagination text is: `A mostrar 1 até 25 de 48 entries`

**Comment by calebporzio** [comment]
I agree, good point. Fixed!
