### ISSUE TITLE
Focus state on checked checkboxes and radiobuttons

### ISSUE THREAD

**Issue by mauritskorse** [livewire/flux#262]
It is awesome how well flux works using your keyboard only. 

However, when navigating through the ui using a keyboard, it is impossible to see whether I focussed on a checkbox or radiobutton that is currently checked. On pages with many of such input fieldsyou lose your way quite easily using the keyboard.

One of these checkboxes is focussed, but I can't tell which one:
![Image](https://github.com/user-attachments/assets/4bb0509e-1414-4b96-94a6-82dbd540634c)

Only now we know where we are: 
![Image](https://github.com/user-attachments/assets/d12b5989-de2a-490c-aae4-975c674249f2)

**Comment by joshhanley** [comment]
@mauritskorse thanks for reporting! I just tested this and I can see a blue focus outline in my browser. Can you confirm what OS and Browser you are using? Can you also test with the latest version of Flux and let us know how it goes?

![Image](https://github.com/user-attachments/assets/07cbb872-3d05-4ad0-b373-3d2cbca6d55b)


Thanks

**Comment by calebporzio** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps to reproduce. Please include any Blade variable definitions that are used. Then, we will be happy to help.

**Comment by mauritskorse** [comment]
Yes I have this on the lastest version of Flux, as well as on the flux website.
I am on Windows, dark mode. tried with Vivaldi, Bing, Chrome and  Firefox.

On Firefox it works. So it seems to be an issue with chrome-based browser here. Adding the following in devtools gives me the correct behaviour in chrome
```
ui-checkbox:focus-visible {
  outline: 2px solid blue
}
```
