### ISSUE TITLE
Tabs Documentation for Flush Variant

### ISSUE THREAD

**Issue by jpangborn** [livewire/flux#263]
The Flux documentation on Tabs includes a section on Padded Edges (https://fluxui.dev/components/tabs#padded-edges) that indicates the default is with no padding and that padding can be added via Tailwind classes. From the launch screenshot (at 7:25) and my tests, the default should be with padding and with a `flush` variant that removes the padding. The flush edges documentation section is missing. (The launch screencast showed the documentation for the flush variant at 7:43.)

**Comment by bzarzuela** [comment]
I think they went with flush as default and padded as opt-in after that screencast was recorded.

**Comment by jpangborn** [comment]
I should have checked the code again after update=ing. There was still a reference to the flush variant in the 1.0.0 code, but it is gone now. And removing `variant="flush"` no longer changes the tabs.
