### ISSUE TITLE
Alignment on select options that wrap lines

### ISSUE THREAD

**Issue by mauritskorse** [livewire/flux#270]
On a select listbox, when having options that are pretty long, they do not align well on the left side.

![Image](https://github.com/user-attachments/assets/6b2855eb-b91c-4511-8223-48a328d483a2)

changing the following in option.blade.php fixes it for me:
```diff
-        <div class="w-6 [ui-selected_&]:hidden">
+        <div class="w-6 min-w-6">
            <flux:icon variant="mini" icon="check" class="hidden group-data-[selected]/option:block" />
        </div>
```

Adding some truncation to the selected item would also be preferable. Currently the select tries to resize to fit the entire selected item.

**Comment by joshhanley** [comment]
@mauritskorse thanks for reporting! I have submitted a PR to fix this.
