### ISSUE TITLE
How to capture Modal close event

### ISSUE THREAD

**Issue by azizabbas** [livewire/flux#271]
Hi,

I was wondering if I can capture Modal close event. 

For example, if I am using a Delete confirmation Modal. How I can capture click on little close icon on top right of the Modal?

![Image](https://github.com/user-attachments/assets/2c302bf5-3e51-4bb8-a19a-083607b258d9)

Thanks for your help and support so far.

Aziz Abbas

**Comment by dayemsiddiqui** [comment]
Hi you can use wire:click and call your relevant livewire method when the close button is clicked

**Comment by azizabbas** [comment]
Hi,

Thanks for your reply on this one.

Actually, I am asking about the little **cross icon** on top-right corner of the box.

Seems like we don't have any control on that icon.

Thanks again

**Comment by bzarzuela** [comment]
Caleb mentioned that he uses <dialog> for modals. If you can acquire a reference to it, you can add a listener as described in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#examples

**Comment by azizabbas** [comment]
Are you saying that we have to go back to javascript to capture this is one tiny thing. Well, this is bit annoying

**Comment by ju5t** [comment]
@azizabbas you could register an on click on elements on the `data-flux-modal-close` attribute too. It doesn't get much easier than that. And you can always override the the `flux:modal.close` to emit a JS event if it's more common.

This isn't a bug though, it's better to post these things in discussions.

**Comment by azizabbas** [comment]
Thank you all for taking your time and reply to my post.

I know how javascript works but I am using Livewire/Flux so that I dont have to write javascript. At least that is what I want at most :)

Anyways, I published related Modal code and remove that little cross icon and now everything is under my control.

Hopefully, in future versions of Flux we have more options and control on Modal and other components.

**Comment by joshhanley** [comment]
@azizabbas thanks for reporting! I have submitted a PR to fix this.

**Comment by calebporzio** [comment]
Going to close this as there are a handful of userland ways to do this and the actual reason this is needed wasn't mentioned. Thanks!
