### ISSUE TITLE
Input field; kbd and clearable attributes stack

### ISSUE THREAD

**Issue by dudelisius** [livewire/flux#276]
When an input field uses the kbd attribute and the clearable attribute at the same time the close icon is stacked on top of the keyboard key. 

Would be nice if the kdb text would be pushed to the left making room for the close icon. 

Code to reproduce; 

`<flux:input kbd="⌘K" clearable/>`

Screenshot; 

![Image](https://github.com/user-attachments/assets/598f7b3d-0203-4109-a15d-e197f30954b8)

**Comment by dudelisius** [comment]
For anyone reading this, a way to get the same functionalities, it does work to set the input type to search (type="search"). This will add a clear button natively in the browser.

![Image](https://github.com/user-attachments/assets/f93acec5-08f3-46b1-8068-915903ab9339)

**Comment by joshhanley** [comment]
@dudelisius thanks for reporting! I have submitted a PR to fix this.

**Comment by calebporzio** [comment]
supporting multiple trailing icons is not trivial and I'm not sure the extra internal complexity (and runtime overhead) is worth it. Knowing `input[type="search"]` offers a "clearable" alternative, I'm going to say no for now and close this. Thanks.
