### ISSUE TITLE
Don't strip domain from href in button

### ISSUE THREAD

**Issue by knorthfield** [livewire/flux#277]
Providing an absolute URL to href on a button will strip the domain and make it a relative url if it matches APP_URL in the .env file.

`<flux:button href="https://example.com/page/51afd1de">Page</flux:button>`

Generates: `<a href="/page/51afd1de">`

Whereas I believe it should just pass through the full URL.

For example, when generating links on subdomains they link to a page on the subdomain rather than the plain domain.

**Comment by nuernbergerA** [comment]
button-or-link.blade.php

```php
@props([
    'type' => 'button',
    'current' => null,
    'href' => null,
])

@php
$href = str($href)->startsWith(trim(config('app.url')) ? (string) str($href)->after(trim(config('app.url'), '/')) : $href;

if ($href === '') {
    $href = '/';
}

$current = $current === null ? ($href ? request()->is($href === '/' ? '/' : trim($href, '/')) : false) : $current;
@endphp

<?php if ($href): ?>
    {{-- We are using e() here to escape the href attribute value instead of "{{ }}" because the latter will escape the entire attribute value, including the "&" character... --}}
    <a href="{!! e($href) !!}" {{ $attributes->merge(['data-current' => $current]) }}>
        {{ $slot }}
    </a>
<?php else: ?>
    <button {{ $attributes->merge(['type' => $type, 'data-current' => $current]) }}>
        {{ $slot }}
    </button>
<?php endif; ?>
```

**Comment by calebporzio** [comment]
Thanks Adrian!

**Comment by knorthfield** [comment]
What about sub domains?

Imagine we are on `docs.fluxui.dev` and we want to link to `fluxui.dev/pricing`

```
<flux:button href="https://fluxui.dev/pricing">Pricing</flux:button>
<a href="/pricing">
```

The link on sub domain will take a user to `https://docs.fluxui.dev/pricing` not `https://fluxui.dev/pricing`

Just curious why we're stripping the `app.url` at all? Isn't it the responsibilty of the dev to pass the correct link to the component?

Many thanks!

**Comment by nuernbergerA** [comment]
striping is needed to prevent `wire:navigate` issues
