### ISSUE TITLE
Button-or-link breaks urls with ampersands when in variable.

### ISSUE THREAD

**Issue by bernhardh** [livewire/flux#279]
# Description
When using the `button-or-link` component, the "&" in urls when comming from variables is html encoded and therefore broken.

# Steps to reproduce
```
@php($url = "/?search=test&page=2")
<flux:button :href="$url">Default</flux:button>
```
Resulting in the following url: `/?search=test&amp;page=2`.

# Workaround
You have to wrap it in HtmlString, to make it work:
```
@php($url = new \Illuminate\Support\HtmlString("/?search=test&page=2"))
<flux:button :href="$url">Default</flux:button>
```

# Affected version
I am currently on `v1.0.7`

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.

**Comment by kerkness** [comment]
I think there is a regression on this issue

```
  @php
    
    $testvalues = [
      'ham' => 'bam',
      'bam' => 'fam',
      'fam' => 'jam'
    ];

    $urlA = 'https://test.com?'.http_build_query($testvalues);
    $urlB = new HtmlString('https://test.com?'.http_build_query($testvalues));

  @endphp

  <flux:button href="{{ $urlA }}">Test A</flux:button>
  <flux:button href="{{ $urlB }}">Test B</flux:button>

```

$urlA in the example above will render with `&amp;`    in the URL, but $urlB is fine.
