### ISSUE TITLE
Issue with component

### ISSUE THREAD

**Issue by vnshah** [livewire/flux#280]
We are having trouble with <select> component. We are not able to select the value that is already selected (in the database) on the edit form page. We tried with following components:

Searchable select
Custom select

`@for ($i = 0; $i < $product_count; $i++)

<div class="flex items-center py-4 gap-x-3">

<div class="inline-flex gap-x-3 items-center">

{{-- <flux:button variant="danger" size="xs" icon="trash" wire:click='removeProduct({{ $i }})' /> --}}

<flux:heading>{{ $i + 1 }}</flux:heading>

</div>

<flux:select variant="listbox" value="{{ $order_products[$i]['product_id'] ?? '' }}"

wire:model="order_products.{{ $i }}.product_id" wire:key="product_id_{{ $i }}"

x-on:change="$wire.addProduct({{ $i }}, $event.target.value)" searchable

placeholder="Choose product" class="w-full">

<x-slot name="search">

<flux:select.search placeholder="Search..." />

</x-slot>

@foreach ($this->products as $product)

<flux:option value="{{ $product->id }}" :selected="$product - > id == $order_products[$i]['product_id']">

<flux:avatar size="xs" src="{!! $product->image !!}" /> &nbsp;

{{ $product->name }}

</flux:option>

@endforeach

</flux:select>

<flux:input type="number" value="{{ $order_products[$i]['quantity'] ?? '' }}"

@input.debounce.500ms="$wire.addQuantity({{ $i }}, $event.target.value)"

placeholder="Enter quantity" class="w-1/3" />

<flux:button size="sm" icon="x-mark" variant="ghost" inset />

<flux:input type="number" placeholder="Enter price" value="{{ $order_products[$i]['price'] ?? '' }}"

@input.debounce.500ms="$wire.addPrice({{ $i }}, $event.target.value)" class="w-1/3" />

{{-- <flux:input type="text" placeholder="Total" class="w-1/3" readonly /> --}}

<flux:heading class="w-1/4">

{{ Number::currency($order_products[$i]['total'] ?? '0.00', in: env('APP_CURRENCY', 'INR')) }}

</flux:heading>

</div>

@endfor`

**Comment by ju5t** [comment]
Can you please use code formatting? This is incredibly tough to read. 

It helps if can you add a more thorough description. What did you expect, what did you get, and what errors are you seeing? And to class it as an issue you probably want to share code in a bit more isolation rather than posting a large loop.
