### ISSUE TITLE
Typo in the docs for adding Inter to tailwind.config.js

### ISSUE THREAD

**Issue by jeffreysimms** [livewire/flux#285]
There is a typo in the docs for adding Inter to tailwind.config.js

https://fluxui.dev/docs/installation#getting-started

```js
module.exports = {
    ...
    theme: [
        fontFamily: {
            sans: ['Inter', 'sans-serif'],
        },
    ],
}
```

but should be

```js
module.exports = {
    ...
    theme: {
        fontFamily: {
            sans: ['Inter', 'sans-serif'],
        },
    },
}
```

CWS Team, OCIO, Memorial University

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
