### ISSUE TITLE
Button group with dropdown button not showing nicely

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/flux#287]
Hello,

When using a button group with one of the buttons being a dropdown trigger, the group is not shown nicely

Example code:

```
<flux:button.group>
    <flux:dropdown>
        <flux:button icon-trailing="chevron-down">Options</flux:button>

        <flux:menu>
            <flux:menu.item icon="plus">An option</flux:menu.item>
        </flux:menu>
    </flux:dropdown>

    <flux:button>Another button</flux:button>
</flux:button.group>
```

Screenshot:

![Image](https://github.com/user-attachments/assets/9020fbda-b470-4e20-b146-464d5cf18264)

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
