### ISSUE TITLE
Error in the Documentation Submenus

### ISSUE THREAD

**Issue by gustavosobrinho01** [livewire/flux#288]
When accessing the documentation, several submenus are either unresponsive or redirecting to the wrong topic, as shown in the images below.

![Image](https://github.com/user-attachments/assets/d78f1cc9-7d79-4335-866f-3e403f87b1f9)
![Image](https://github.com/user-attachments/assets/7893d8f0-e1b2-4a04-9853-4de7cc2c4e82)

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
