### ISSUE TITLE
Buttons inside of clearable, copyable, and viewable inputs don't size down on smaller inputs

### ISSUE THREAD

**Issue by benjibee** [livewire/flux#289]
When using the `clearable`, `copyable` or `viewable` attributes with an input with sizes `sm` or `xs` the button doesn't scale down to match the size of the input.

Here's a normal sized input with a clearable button (hovered):

![](https://github.com/user-attachments/assets/ec158fde-a52f-4460-b33e-2e498146933b)

Here's an input with  a size of `sm`:

![](https://github.com/user-attachments/assets/ed2845c6-29d8-47e8-8843-e94944d18b35)

Copy / pasteable example of a small input:

```blade
<flux:input
    icon="magnifying-glass"
    placeholder="Search…"
    variant="filled"
    size="sm"
    clearable
    class="max-w-64 my-20"
/>
```

### My current fix

Adding the following snippet to _`input/index.blade.php`_ works well, but I can't open a PR on Flux Pro :)

```php
$buttonSize = match ($size) {
    'sm', 'xs', => 'xs',  // no `xxs` exists but `xs` is still pretty big for an `xs` input.
    default => 'sm',
};
```
```blade
<flux:input.clearable size="{{ $buttonSize }}" />
```

Here's how a small, clearable, input looks after these adjustments:

![](https://github.com/user-attachments/assets/70c19e95-1349-42f2-a789-4cbfc226f340)

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
