### ISSUE TITLE
Empty Sidebar area is appearing when using wire.navigate on mobile

### ISSUE THREAD

**Issue by bakubay** [livewire/flux#295]
Hi there! 👋

* When i try to use wire.navigate on my mobile screen, sidebar space appears pusing everything to the right.

`<x-lay-layout>
<flux:button wire:navigate href="{{any link)}}">Go to  page with wire:navigate</flux:button> 
</x-lay-layout>`

![Image](https://github.com/user-attachments/assets/e8d4b6e7-0212-4452-8cad-f001d0532bf8)

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
