### ISSUE TITLE
Column sort indicators are getting cut-off by overflow-hidden on first column

### ISSUE THREAD

**Issue by benjibee** [livewire/flux#296]
In the following snippet of a table if I add `sortable` to the first column the button that is shown is cut off on the left side.

```blade
<flux:table>
    <flux:columns>
        <flux:column sortable>Customer</flux:column>
        <flux:column>Date</flux:column>
        <flux:column>Status</flux:column>
        <flux:column>Amount</flux:column>
    </flux:columns>

    <flux:rows>
        <flux:row>
            <flux:cell>Lindsey Aminoff</flux:cell>
            <flux:cell>Jul 29, 10:45 AM</flux:cell>
            <flux:cell>
                <flux:badge color="green" size="sm" inset="top bottom">Paid</flux:badge>
            </flux:cell>
            <flux:cell variant="strong">$49.00</flux:cell>
        </flux:row>
    </flux:rows>
</flux:table>
```

![Image](https://github.com/user-attachments/assets/c8822156-ab40-4220-bf80-44bc82e6f710)

## Possible Fix

Only applying the padding resets if the column isn't sortable fixes it, though it may not match with other overall design ideas you're going for.

```php
// stubs/resources/views/flux/column.blade.php:9

$classes = Flux::classes()
    ->add('py-3 px-3')
    ->add($sortable ? '' : 'first:pl-0 last:pr-0')
    ->add('text-left text-sm font-medium text-zinc-800 dark:text-white')
    ->add($align === 'right' ? 'group/right-align' : '')
    ;
```

![Image](https://github.com/user-attachments/assets/574e36f5-8977-4deb-afda-a631daf7540d)

**Comment by joshhanley** [comment]
@benjibee thanks for reporting! I have submitted a PR to fix this.

**Comment by philippbuerger** [comment]
Hi this not merged right? I'm still having this issue in my table.

**Comment by joshhanley** [comment]
@philippbuerger Not yet

**Comment by calebporzio** [comment]
I wanted to find a less invasive fix, so to fix the problem, I removed the background in the column heading so that you don't notice the overflow.

Thanks!

https://github.com/user-attachments/assets/9de97124-6bd3-4ca0-aba1-ceb240a32bb5

**Comment by stoutZero** [comment]
> I wanted to find a less invasive fix, so to fix the problem, I removed the background in the column heading so that you don't notice the overflow.
> 
> Thanks!
> 
>  CleanShot.2024-10-24.at.07.25.55.mp4

What about borders for when the table is in a container?

![Image](https://github.com/user-attachments/assets/bbac72c2-5df0-4267-8504-4e2ffc5b3894)

Some people prefer all borders on their tables... is there no way to make the `first:ps-0 last:pe-0` optional / overriden?

**Comment by joshhanley** [comment]
@stoutZero you can just use Tailwind to override them, add `class="first:ps-3! last:pe-3!"` to the component calls.

**Comment by stoutZero** [comment]
> [@stoutZero](https://github.com/stoutZero) you can just use Tailwind to override them, add `class="first:ps-3! last:pe-3!"` to the component calls.

Yeah, I know that, that's what I ended up doing, not really the point.
Before long because I want to override other people's design preferences, my blade files are littered with tailwind override classes...
And I paid money for this, for the  privilege to mess up my own files...
Hah... forget it... the author already making money off me... he ain't gonna listen...

**Comment by joshhanley** [comment]
@stoutZero not sure what you are going on about. I'm part of the Flux team and it's my job to help out on issues. So I'm not sure why you think we're not listening or doing anything. We put a lot of effort into ensuring Flux works (just look at our release history), so I'd appreciate that if you have an issue, we have a civilised discussion first before you start accusing us of not listening or trying to make Flux better.

That being said, I don't understand what the issue/ point is. Can you please explain exactly what it is that you're after? I personally don't see any problems with overriding styles using Tailwind, but we're open to other ideas if you have something that you'd prefer.

**Comment by benjibee** [comment]
> [@stoutZero](https://github.com/stoutZero) not sure what you are going on about. I'm part of the Flux team and it's my job to help out on issues. So I'm not sure why you think we're not listening or doing anything. We put a lot of effort into ensuring Flux works (just look at our release history), so I'd appreciate that if you have an issue, we have a civilised discussion first before you start accusing us of not listening or trying to make Flux better.
> 
> That being said, I don't understand what the issue/ point is. Can you please explain exactly what it is that you're after? I personally don't see any problems with overriding styles using Tailwind, but we're open to other ideas if you have something that you'd prefer.

Patience of a saint, over here. Thank you @joshhanley :)

**Comment by joshhanley** [comment]
@benjibee thanks! I try my best 😊
