### ISSUE TITLE
Select Listbox Variant not selecting current option when lazy loaded (or nested)

### ISSUE THREAD

**Issue by itsgrimace** [livewire/flux#299]
As per title,
Minimal code example here (sorry no volt).

Component: BrokenSelect.php

```
<?php

namespace App\Livewire;

use Livewire\Component;
use Livewire\Attributes\Lazy;

#[Lazy]
class BrokenSelect extends Component
{
    public $test = 'Accounting';

    public function render()
    {
        return view('livewire.broken-select');
    }
}
```
View: broken-select.blade.php
```
<div>
    @json($test)
    <flux:select variant="listbox" searchable placeholder="Choose industries..." wire:model='test'>
        <x-slot name="search">
            <flux:select.search placeholder="Search..." />
        </x-slot>

        <flux:option>Photography</flux:option>
        <flux:option>Design services</flux:option>
        <flux:option>Web development</flux:option>
        <flux:option>Accounting</flux:option>
        <flux:option>Legal services</flux:option>
        <flux:option>Consulting</flux:option>
        <flux:option>Other</flux:option>
    </flux:select>
</div>
```
Json printer shows "Accounting"
Select shows "Choose industries..."

**Comment by WorthLMS** [comment]
This is in the process of being worked on and/or fixed. #60  #90

**Comment by itsgrimace** [comment]
Current version 1.0.8.

The issue resolved in #60 is related but not identical, these components are not applying the #[Lazy] attribute.
Tested variants;
Using wire:init to call setting function works
Using $wire.dispatch("setTest"); in script tag works
If BrokenSelect is a child component rendered conditionally on a parent component the issue is also present.

If you need me to mock up a minimal example for this I can easily enough.

**Comment by helderneves91** [comment]
Make sure you don't have old flux components published.

**Comment by itsgrimace** [comment]
> Make sure you don't have old flux components published.

I have not published the assets, js version matches the manifest files in 1.0.8.
Are you not encountering the same problem per my code example?
Should I perhaps mark this as PRO version?

**Comment by calebporzio** [comment]
No, this is fine - I can reproduce the error:

```php
<?php

use Livewire\Volt\Component;

new
#[\Livewire\Attributes\Lazy]
class extends Component {
    public $test = 'Accounting';
}

?>

<div class="space-y-4">
    <div>
        @json($test)
        <flux:select variant="listbox" searchable placeholder="Choose industries..." wire:model='test'>
            <x-slot name="search">
                <flux:select.search placeholder="Search..." />
            </x-slot>

            <flux:option>Photography</flux:option>
            <flux:option>Design services</flux:option>
            <flux:option>Web development</flux:option>
            <flux:option>Accounting</flux:option>
            <flux:option>Legal services</flux:option>
            <flux:option>Consulting</flux:option>
            <flux:option>Other</flux:option>
        </flux:select>
    </div>
</div>

```

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
