### ISSUE TITLE
Input mask includes mask characters instead of raw value

### ISSUE THREAD

**Issue by bzarzuela** [livewire/flux#301]
How do I get the unmasked value when using input mask?

`<flux:input wire:model.blur="mobile_number" label="Mobile Number" type="tel" mask="(9999) 999 9999"  />`

The property's value includes the mask characters "(0917) 555 1234" instead of "09175551234".

Although it's not noted in the documentation, my expectation is that masking is only to guide the user's input.

**Comment by joelpiccoli** [comment]
I think you'll have to handle it by yourself, which is not that complicated at all. All you need to do is strip everything you don't want from the string. I'm do that with phones and documents in an app I'm building with Flux using the [model accessors](https://laravel.com/docs/11.x/eloquent-mutators#defining-an-accessor).

**Comment by wevertondcl** [comment]
@joelpiccoli Are you storing on database the masked string? Like: "(0917) 555 1234" instead of "09175551234"?
Never saw that, cause you are storing unnecessary characters....
I think the best way is to make a custom Rule Validation, than when storing the input, use Model Mutator to remove the mask...

**Comment by calebporzio** [comment]
I've heard this feature request before and I could see the use, however, you can remove them before handling the data AND this is actually a request for the Alpine plugin. Not really a Flux thing as Flux just passes this value through to Alpine's mask plugin.
