### ISSUE TITLE
Select size does not work in combination with a variant

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#303]
This is a copy of #68 but with a copy/pasteable example.

It looks like `size` has no effect if you use the `listbox` variant.

```blade
<flux:select size="sm" variant="listbox" placeholder="Choose industries...">
    <flux:option>Photography</flux:option>
    <flux:option>Design services</flux:option>
</flux:select>
```

This has been tested on a fresh Laravel installation with Flux 1.0.8.

![Image](https://github.com/user-attachments/assets/d6eaeb55-c058-4aa6-83f6-96370e85d898)

**Comment by calebporzio** [comment]
Good catch, fixed!
