### ISSUE TITLE
Console warnings (Firefox browser)

### ISSUE THREAD

**Issue by 0hra** [livewire/flux#310]
I am re-submitting this issue with more information as requested (Issue #88)
I have a fresh bare bones installation of Laravel with Livewire + TailwindCSS + Flux (All installed exactly as described in their respective docs). 

This is the laravel welcome.blade.php file:

```
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
        @fluxStyles
    </head>
    <body>
        @fluxScripts
    </body>
</html>
```

I am running the latest Firefox version, 131.0 (aarch64) on MacOS.

When I inspect the page in Firefox and open the "Console" tab and refresh the page, these warnings are displayed:
![Image](https://github.com/user-attachments/assets/a5df4cbd-ed0e-45ae-893a-4c1aadb0a2b8)

The first warning refers to this:

```
closest(el, condition) {
      return;
      let walker2 = this.from(el).walker;
      while (walker2.currentNode) {
        if (condition(walker2.currentNode)) return walker2.currentNode;
        walker2.parentNode();
      }
    }
```

And the second warning refers to this:
```
function mouseIsExclusivelyInsideSafeArea(triggerRect, panelRect, x, y) {
    return !mouseIsOverTrigger(triggerRect, x, y) && !mouseIsOverPanel(panelRect, x, y);
    return true;
  }
```

**Comment by benjibee** [comment]
@calebporzio The issue here is that the referenced methods have logic after the `return` statement. Only Firefox shows a console warning for this type of mistake. It's probably good to address the underlying issue anyway. Here's an example:

```js
// js/utils.js:71

closest(el, condition) {
    return;
    let walker2 = this.from(el).walker;
    while (walker2.currentNode) {
        if (condition(walker2.currentNode)) return walker2.currentNode;
        walker2.parentNode();
    }
}
```

**Comment by calebporzio** [comment]
Good catch, thank you for making this easy.
