### ISSUE TITLE
Table not published after flux:publish --all

### ISSUE THREAD

**Issue by NickSB** [livewire/flux#316]
Hi there,

table.blade.php is not published after command `php artisan flux:publish --all`.

Solution:
Rename and move from `stubs/resources/views/flux/table.blade.php` to `stubs/resources/views/flux/table/index.blade.php`

Greetings,
Nick

**Comment by helderneves91** [comment]
I think the stubs doesn't overwrite existing ones.
Check https://github.com/livewire/flux/pull/302

**Comment by joshhanley** [comment]
@NickSB thanks for reporting! I have submitted a PR #302 to fix this.
