### ISSUE TITLE
Sticky custom select dropdown on scroll.

### ISSUE THREAD

**Issue by AlexanderFalkenberg** [livewire/flux#317]
The custom select dropdown sticks to the top when scrolling (see screenshot).

Seems like a bug to me, or is it possible to disable this behaviour?

![Image](https://github.com/user-attachments/assets/4b666eec-83ab-4ea4-bb46-c6bd5b4b29e7)

**Comment by calebporzio** [comment]
Thanks for the report - this is related to #110, so I'm going to close this so that we only have one issue dealing with this. The real fix is locking scroll when select popovers are open (just like a native select does) - thanks again
