### ISSUE TITLE
data-flux-modal is not working

### ISSUE THREAD

**Issue by BubeDameKoenig** [livewire/flux#318]
It looks to me as if the values from `[data-flux-modal]` are not being transferred to the `<dialog>`.

```css
[data-flux-modal] {
    @apply !text-red-500 !font-normal;
}
``` 

```blade
<flux:modal name="test" class="md:max-w-lg">
    Test
</flux:modal>
```

**Comment by ju5t** [comment]
When you're using `@apply` you should probably use `!important` rather than prefixing Tailwind classes. The prefix is for classes you apply inline to an element, `@apply` is like 'standard' CSS.

Have you tested if that works for you? I can't test it myself at the moment.

**Comment by BubeDameKoenig** [comment]
This leads to the following error message:
`The `!important` class does not exist. If `!important` is a custom class, make sure it is defined within a `@layer` directive.`

**Comment by ju5t** [comment]
Can you share what you did exactly?

**Comment by calebporzio** [comment]
Do `[data-flux-model] > dialog` instead? Otherwise, it's just a matter of getting the CSS right - so closing this. thanks everyone.
