### ISSUE TITLE
Focus state on navbar item

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#319]
I know you're not going to fiddle to outlines/focus states for now, but perhaps this one is worth fixing anyway. There's an outline added to the border on the bottom. Apart from it not looking great, it doesn't add much for accessibility either as the button itself is already highlighted.

Perhaps it's possible to remove the focus state from this border?

![Image](https://github.com/user-attachments/assets/0a522f75-31d2-48f4-af75-e6b24d9f53b0)

Screenshot is taken from https://fluxui.dev/demo/header.

**Comment by calebporzio** [comment]
Ah yeah that DOES look a little weird. I tinkered to see if I could apply `outline: none;` to only that border element, however, Chrome doesn't seem to honor that on a psuedo element (::after). Given that difficulty, I'm going to pass on improving this for now. Maybe we can circle back if it comes back up. Thanks for the report!
