### ISSUE TITLE
input autofocus not working with wire:navigate

### ISSUE THREAD

**Issue by vincentcordel** [livewire/flux#322]
When using an input, if autofocus is set, it only works when refreshing the page but not with wire:navigate.

A workaround is:
```
        <flux:input wire:model="title" label="Title" autofocus /> // not working with wire:navigate
        <flux:input wire:model="title" label="Title" x-data="{ trapped: true }" x-trap="trapped" />
```

**Comment by dimitri-koenig** [comment]
My solution is different. Since i have multiple places where autofocus could be needed at any given time, I use an Alpine directive:

```js
Alpine.directive('autofocus', el => setTimeout(() => el.focus(), 0));
````

Usable like this:

```html
<flux:input x-autofocus />
```

**Comment by vincentcordel** [comment]
thanks!

**Comment by calebporzio** [comment]
Going to close this because this is a Livewire issue and not a Flux issue right? Please re-open if this is somehow only broken on flux inputs. Thanks!
