### ISSUE TITLE
When using wire:navigate `data-sashed` is not set after navigation

### ISSUE THREAD

**Issue by lloydowen** [livewire/flux#323]
Hey,

Hard to explain what's going on, but when using wire:navigate with sidebar navigation an empty container appears where the sidebar would be.

I've noticed when using wire:navigate the `data-stashed` attribute has been removed on the sidebar. On hard refreshes this works fine.

It looks like this when navigating with `wire:navigate` set:

![Image](https://github.com/user-attachments/assets/1749c782-39b5-457f-a576-9f77ecc04a14)

I have noticed it's likely something to do with `x-bind:data-stashed="! screenLg"`

```html
<div 
class="[grid-area:sidebar] z-[1] flex flex-col gap-4 [:where(&amp;)]:w-64 p-4 max-lg:[&amp;[data-mobile-cloak]]:hidden [[data-show-stashed-sidebar]_&amp;]:!translate-x-0 lg:!translate-x-0 !z-20 data-[stashed]:!left-0 data-[stashed]:!fixed data-[stashed]:!top-0 data-[stashed]:!min-h-dvh data-[stashed]:!max-h-dvh lg:hidden bg-zinc-50 dark:bg-zinc-900 border-r border-zinc-200 dark:border-zinc-700 transition-transform" 
x-bind:data-stashed="! screenLg"
 x-resize.document="screenLg = window.innerWidth >= 1024" 
x-init="$el.style.transform = 'translateX(-100%)'; $el.removeAttribute('data-mobile-cloak'); $el.classList.add('transition-transform')" x-data="{ screenLg: true }"
 data-flux-sidebar="" 
style="transform: translateX(-100%);" 
data-stashed="true">
```

But after wire navigating that attribute is missing completely. 

This only seems to happen when setting the responsive browser to iPhone 14 Pro Max. 

A temporary fix i've permanently set the stashed attribute:

```html
<flux:sidebar stashable x-bind:data-stashed="true"></flux:sidebar>
```

**Comment by pkeogan** [comment]
per the changelog v1.0.8 fixed this

I was still having the same issue, after running a `composer update`

I then ran

```
php artisan cache:clear
php artisan view:clear
npm update
```

and I no longer have the issue. Im sure your `view`` is just cached.

**Comment by lloydowen** [comment]
Ah yeah, my bad! thanks @pkeogan 👍
