### ISSUE TITLE
Input clearable not working on wire:model.blur

### ISSUE THREAD

**Issue by emanuelnogueiras** [livewire/flux#324]
Hello everyone!

I’d like to report an issue I’ve encountered with an input control in Flux. When using it with wire:model.blur, the clearable attribute doesn’t work as expected. However, it does work correctly with wire:model.live, but fails to respond properly when used with wire:model.blur.

v1.0.8

Thanks!

**Comment by locii** [comment]
I'm not able to get clearable to work with any of the binding methods. v1.0.8

`<flux:input clearable icon="magnifying-glass" placeholder="Start typing to search for a message." wire:model.live="search" class="mb-4"/>`

**Comment by jeffchown** [comment]
I couldn't reproduce the issue.  The example above worked fine in my Flux test app. (v1.0.8)

Have you cleared the laravel cache and view cache? (`php artisan cache:clear && php artisan view:clear`) and deleted, then republished, any previously published Flux components?

**Comment by locii** [comment]
Oh yep my apologies. Rookie mistake. Cache cleared this. Thanks

**Comment by calebporzio** [comment]
Thanks @jeffchown !
