### ISSUE TITLE
flux:heading sizes

### ISSUE THREAD

**Issue by MOA-TI** [livewire/flux#325]
Hi there! 👋

Sorry you hit a problem with Flux.

The heading sizes in `<flux:heading>` don't seem to make much sense...

- `size="base"` uses `"text-sm"` class.

- `size="lg"` uses `"text-base"` class.

- `size="xl"` uses `"text-2xl"` class.

There is no way to use `"text-xl"` class for headings.

Wouldn't it be easier to understand if there were a direct relationship between the value of the size attribute in `<flux:heading>` and the associated class?

**Comment by ju5t** [comment]
In Caleb's talk at Laracon he [talked about headings](https://youtu.be/31pBMi0UdYE?t=1207). Perhaps that gives more info. .

**Comment by MOA-TI** [comment]
IMHO, it may make sense when using <flux:heading> to define the headers of a page, but it definitely doesn't make much sense when using it inside a card or a modal.

**Comment by calebporzio** [comment]
we have settled on 3 common sizes to keep it simple. If you want, you can always override the size using class="!text-*"
