### ISSUE TITLE
Placeholder attribute doesn't work in select elements with dynamically generated options

### ISSUE THREAD

**Issue by jlevers** [livewire/flux#333]
### Problem

When using a select box with dynamically generated options and a model key attached, the `placeholder` field is not applied, and the first option in the select appears in the select box in a disabled state.

### Code to reproduce

**Blade template**

```blade
<div class="mx-auto flex items-center w-1/2 mt-8 p-12 bg-white">
    <flux:select
        wire:model="selectedColor"
        placeholder="Choose a color..."
        :filter="false"
    >
        @foreach ($colors as $color)
        <flux:option wire:key="{{ $color }}" value="{{ $color }}">{{ $color }}</flux:option>
        @endforeach
    </flux:select>
</div>
```

**Livewire component**

```php
<?php

namespace App\Livewire;

use Livewire\Component;

class ColorPicker extends Component
{
    public array $colors = ['red', 'green', 'blue', 'yellow', 'purple', 'orange', 'pink', 'brown', 'gray'];
    public string $selectedColor;

    public function render()
    {
        return view('livewire.color-picker');
    }
}
```

Here's how this renders:

![Image](https://github.com/user-attachments/assets/1a5bb662-5641-4efc-b60a-f91650abf6a2)

I can fake a placeholder with the code below, but would expect the `placeholder` attribute to still work if I'm passing dynamic options.

```blade
<div class="mx-auto flex items-center w-1/2 mt-8 p-8 bg-white">
    <flux:select
        wire:model="selectedColor"
        :filter="false"
    >
        <flux:option value="" disabled selected>Choose a color...</flux:option>
        @foreach ($colors as $color)
        <flux:option wire:key="{{ $color }}" value="{{ $color }}">{{ $color }}</flux:option>
        @endforeach
    </flux:select>
</div>
```

```php
<?php

namespace App\Livewire;

use Livewire\Component;

class ColorPicker extends Component
{
    public array $colors = ['red', 'green', 'blue', 'yellow', 'purple', 'orange', 'pink', 'brown', 'gray'];
    public string $selectedColor = '';

    public function render()
    {
        return view('livewire.color-picker');
    }
}
```

![Image](https://github.com/user-attachments/assets/19309865-5ded-4a7e-9442-a320353ce3a8)

**Comment by jeffchown** [comment]
@jlevers If you set the default value of `$selectedColor` to '' (e.g. `public string $selectedColor = '';` in the component), the placeholder should be displayed (works in my test using your initial code) without the need for the `<flux:option value="" disabled selected>Choose a color...</flux:option>`

**Comment by jlevers** [comment]
Ah, thanks! Ok, follow-up question: what I actually would like to do is have the `$selectedColor` attribute be a model, something like `public Color $selectedColor`. Is there a way to use that same fix you suggested with a model class? I tried making the `$selectedColor` attribute nullable and initializing it to `null`, but that didn't get the placeholder to show up.

**Comment by jeffchown** [comment]
@jlevers Without knowing more about what you're trying to do, it's tough to help.  I don't think you could easily do what you're asking and have the `$selectedColor` bound to the `flux:select` via `wire:model`.

**Comment by jlevers** [comment]
Mm, ok, the ID-based option is probably the best solution for me. Thanks again for your help!
