### ISSUE TITLE
space between buttons with tooltips not working

### ISSUE THREAD

**Issue by nielseulink** [livewire/flux#337]
Spacing between buttons is lost when an tooltip is used:

![Image](https://github.com/user-attachments/assets/b31a8a7d-ee22-4d58-8705-0c14fd1897ed)

Example with code:

![Image](https://github.com/user-attachments/assets/64d0181c-02b4-482d-87f5-2a66fe60b24e)

```blade
<div class="flex space-x-4">
    <flux:button tooltip="tooltip 1">bttn 1</flux:button>
    <flux:button tooltip="tooltip 2">bttn 2</flux:button>
</div>
```

working example without tooltip:

![Image](https://github.com/user-attachments/assets/a9a38ef5-cafe-4eea-a4fd-74309ddabc00)

```blade
<div class="flex space-x-4">
    <flux:button>bttn 1</flux:button>
    <flux:button>bttn 2</flux:button>
</div>
```

**Comment by nielseulink** [comment]
Ooh and for those who also run into this problem, a workaround might be to wrap the buttons in their own div:

```blade
<div class="flex space-x-4">
    <div x-show="$wire.active_filters > 0">
        <flux:button tooltip="Reset the filters" icon="tabler.filter-off" wire:click="resetFilters"></flux:button>
    </div>
    <div x-show="$wire.sortCol">
        <flux:button tooltip="Reset the table sort" icon="tabler.table-off" wire:click="resetSort"></flux:button>
    </div>
</div>
```

**Comment by jeffchown** [comment]
@nielseulink Looks like your `div` wrapping workaround is exactly what you have to do in this case as the markup created by a button with a tooltip, wraps the button with a `<ui-tooltip></ui-tooltip>` to facilitate the popover needed and this will of course stop your `space-x-4` from being applied to your `<flux:button>`s.

```
<ui-tooltip position="top center" data-flux-tooltip="">
    <button type="button" class="relative inline-flex items-center font-medium justify-center gap-2 whitespace-nowrap disabled:opacity-75 dark:disabled:opacity-75 disabled:cursor-default disabled:pointer-events-none h-10 text-sm rounded-lg px-4  bg-white hover:bg-zinc-50 dark:bg-zinc-700 dark:hover:bg-zinc-600/75 text-zinc-800 dark:text-white border border-zinc-200 hover:border-zinc-200 border-b-zinc-300/80 dark:border-zinc-600 dark:hover:border-zinc-600 shadow-sm [[data-flux-button-group]_&amp;]:border-l-0 [[data-flux-button-group]_&amp;:first-child]:border-l-[1px]" data-flux-button="data-flux-button" data-flux-group-target="data-flux-group-target" tooltip="tooltip 1" aria-controls="lofi-tooltip-e6d499ef84036" aria-expanded="false" aria-describedby="lofi-tooltip-e6d499ef84036">
        bttn 1
    </button>

            <div popover="" class="relative py-2 px-2.5 rounded-md text-xs text-white font-medium bg-zinc-800 dark:bg-zinc-700 dark:border dark:border-white/10 p-0 overflow-visible" data-flux-tooltip-content="" id="lofi-tooltip-e6d499ef84036" role="tooltip">
    tooltip 1

    </div>
</ui-tooltip>
```

**Comment by jeffchown** [comment]
You're welcome @nielseulink .

Maybe @calebporzio can update the `flux:button` code to wrap everything with a `<div>` for `<flux:button>`s with `tooltip`s - that would preserve the styling/spacing in your example (which is one I use on a regular basis as well).

Not sure if that change would cause issues in other situations...

**Comment by jeffchown** [comment]
FYI I had a look at @calebporzio 's demo on https://fluxui.dev/components/tooltip - scroll down to the one with the 4 cog buttons.

He wraps them with `<div class="grid grid-cols-4 gap-16">` to create the spacing (instead of `<div class="flex space-x-4">`) - tried that in my test and it worked.

So, your example would turn into:

```
<div class="flex"> {{-- to avoid a full screen width grid and full column-width buttons --}}
    <div class="grid grid-cols-2 gap-4">
        <flux:button>bttn 1</flux:button>
        <flux:button>bttn 2</flux:button>
    </div>
</div>
```

That's an alternative approach.

**Comment by nielseulink** [comment]
@jeffchown Ah cool, didn't think of looking at the example in the documentation... Should do that more myself.
In my case this will not be a solution since the number of columns is variable in my component. But this may work for others.

**Comment by jeffchown** [comment]
Yeah, they come in handy sometimes.

Gotcha, @nielseulink 

While this would add some complexity initially, you could create your own component to wrap a multiple, variable # of buttons then use conditional `grid-cols-#` classes in that component.

Something that would then be easily called in your app like this:

```
<x-my-button-group button-count="2">
    <flux:button>bttn 1</flux:button>
    <flux:button>bttn 2</flux:button>
</x-my-button-group>
```

Then the component could check the `buttonCount` via:

```
<div class="flex">
    <div 
        @class([
            "grid gap-4",
            "grid-cols-2" => "$buttonCount == 2",
            "grid-cols-3" => "$buttonCount == 3",
            "grid-cols-4" => "$buttonCount == 4",
            "grid-cols-5" => "$buttonCount == 5",
        ])
    >
        {{ $slot }}
    </div>
</div>
```

Just a thought ;)

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
