### ISSUE TITLE
Flux Button as Link - bug when using route() in href

### ISSUE THREAD

**Issue by mricketts** [livewire/flux#343]
Hello,

When using flux:button as a link with route() and key value pairs, the resulting url has a duplicate protocol specified:

```php
<flux:button href="{{ route('my-route', ['key' => '1Q0yOGPAWwi9fK91aTT7I338']) }}">
    Button Text
</flux:button>
```
**Result:**  `http://localhost:8000/:8000/my-specified-route?key=1Q0yOGPAWwi9fK91aTT7I338`

The problem still exists when specifying a route without any additional data:  `{{ route('my-route') }}`

Was working properly yesterday on v1.0.0 but I updated to v1.0.8 tonight.

Much love!

**Comment by jeffchown** [comment]
@mricketts I pasted your example into a clean Flux test app I use and it worked correctly for me.
What do you have `APP_URL` set to in your `.env` file?

**Comment by mricketts** [comment]
@jeffchown Hm, alright thank you, I'll investigate deeper and report back what I find.

`APP_URL=http://localhost`

Were you running v1.0.8 in your test, too?

**Comment by jeffchown** [comment]
@mricketts Yup.  Flux v1.0.8.  After you upgraded to 1.0.8, did you make sure you deleted, then republished any flux components you had published? (that one 'bit' me a while back).

**Comment by mricketts** [comment]
@jeffchown Yeah, I never published any of the vendor files so we're good there.

Looks like the problem occurs when running in a local environment via `php artisan serve` (or any other approach that uses a port in the url to serve the app I suppose).

The supplied url `$href` is being trimmed in `/stubs/resources/views/flux/button-or-link.blade.php` but doesn't take the port into account if one exists:

```php
// button-or-link.blade.php : line 8
$href = str($href)->startsWith(trim(config('app.url')))
    ? (string) str($href)->after(trim(config('app.url'), '/'))
    : $href;
```

I'll let a better coder determine what an appropriate solution might be, but for now I fixed this myself temporarily by parsing the url and stripping the port before handing it off to the existing trimming function on line 8:

```php
// Added this right above the original trimming function
if (str($href)->startsWith(trim(config('app.url')))) {
    $hrefParsed = parse_url($href);
    if (isset($hrefParsed['port'])) {
        $href = str_replace(':'.$hrefParsed['port'], '', $href);
    }
}

// Original trimming function
$href = str($href)->startsWith(trim(config('app.url')))
    ? (string) str($href)->after(trim(config('app.url'), '/'))
    : $href;
```

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
