### ISSUE TITLE
Tooltip not set via Alpine x-bind

### ISSUE THREAD

**Issue by Kturva** [livewire/flux#344]
Tooltip content appears to not work when set via alpine using x-bind:

```php
<?php

use Livewire\Volt\Component;

new class extends Component
{
    //
}; ?>

<div x-data="{tooltip_text: 'X-bound text'}">
    <flux:tooltip x-bind:content="tooltip_text">
        <flux:button x-text="tooltip_text"></flux:button>
    </flux:tooltip>
    <flux:tooltip content="Regular content">
        <flux:button>Regular content</flux:button>
    </flux:tooltip>
</div>
```

**Comment by igmltd** [comment]
Does it work if you place it on a span?

**Comment by calebporzio** [comment]
Sorry that wont work - the "content" prop on flux:tooltip is a Blade property (server side). Currently flux doesn't support Dynamic tooltips. You can achieve this however by examining the source of the tooltip component and tweaking it by hand. Sorry.
