### ISSUE TITLE
Input copyable doesn't work.

### ISSUE THREAD

**Issue by ckissi** [livewire/flux#349]
I've tried the sample code from the docs:

`<flux:input icon="key" value="FLUX-1234-5678-ABCD-EFGH" readonly copyable />`

But it doesn't copy the content into the clipboard.

Other examples work:

```
<flux:input placeholder="Search orders" clearable />
<flux:input type="password" value="password" viewable />
```

Tried in Chrome and Firefox.

**Comment by ThomasEnssner** [comment]
This will only work on secure pages. So it only works using https.

**Comment by ckissi** [comment]
Thanks

> This will only work on secure pages. So it only works using https.

Thanks! Worked!

**Comment by iapparatus** [comment]
> This will only work on secure pages. So it only works using https.

A note on the docs would be nice ;)

**Comment by joshhanley** [comment]
@iapparatus if it were a Flux limitation, then I'd agree, but it's actually a javascript limitation which is documented here https://developer.mozilla.org/en-US/docs/Web/API/Clipboard

<img width="806" alt="Image" src="https://github.com/user-attachments/assets/3afa3572-00d7-461b-b59e-d4b5e9c71d4c" />

**Comment by snapey** [comment]
Agree. A simple note in the docs would have avoided a trip here, eg;

> copyable	 -  If true, displays a copy button to copy the input's content (https only)

**Comment by joshhanley** [comment]
@snapey yep fair. Thanks, I've added that and it will be in the next release.
