### ISSUE TITLE
Undefined variable $size in copyable/viewable/clearable input field

### ISSUE THREAD

**Issue by DonCamillo11** [livewire/flux#352]
After one of the last updates I have a problem using the copyable input field
`<flux:input class="basis-1/2" readonly value="{{ $url }}" copyable/>`

I'm getting the error 
`Undefined variable $size`

After publishing the input stubs it is working, but without published stubs it won’t work.

**Comment by jeffchown** [comment]
@DonCamillo11 If I just paste your `flux:input` example into a fresh app with Flux Pro installed and *no* published stubs, it works for me (no $size error).

Maybe if you share more code, it will provide more context.

**Comment by DonCamillo11** [comment]
It is working now after clearing the vie cache with
`php artisan view:clear`
