### ISSUE TITLE
flux:input value false when used inside flux:accordion when using exclusive

### ISSUE THREAD

**Issue by MatsKruger** [livewire/flux#356]
When adding a flux:input inside a flux:accordion with the exclusive attribute, the value of the input is set to false.
I figured out it is because of the disclosure script setting all elements value in the accordion to false. 
It is inside `UIDisclosureGroup` -> `boot` -> `on(this, 'lofi-disclosable-change')`

Blade Example
```blade
 <flux:accordion exclusive>
    <flux:accordion.item expanded>
        <flux:accordion.heading>What's your refund policy?</flux:accordion.heading>

        <flux:accordion.content>
            <flux:input label="Name" value="John Doe" />
            <flux:input label="Age" />
        </flux:accordion.content>
    </flux:accordion.item>
</flux:accordion>
```
![Image](https://github.com/user-attachments/assets/f689f49a-efa9-43d1-b8de-4e6758147835)

**Comment by MatsKruger** [comment]
That is true that if using wire:model it works as expected but for me only if i add the expanded attribute on the first on. As soon as i expand another they are set to false again.

**Comment by jeffchown** [comment]
@MatsKruger I've been able to recreate what you describe with the `exclusive` being the culprit.

**Comment by calebporzio** [comment]
This is so weird, I can reproduce it, but can't figure it out. Will keep digging - thanks for the report.

**Comment by MatsKruger** [comment]
Hi @jeffchown  and @calebporzio 
I tried to figure this out and looked throgh some of the code to get an idea of where it could stem from.

There is this function `disclosureWalker` inside `disclosure.js`. 
The function looks like this
``` js
disclosureWalker() {
    return walker(this, (el, { skip, reject }) => {
        if (el instanceof UIDisclosureGroup && el !== this) return reject()
        if (! el.localName === 'ui-disclosure') return skip()
    })
}
```
The `! el.localName ` will always return false unless it is a falsy value in this case i guess an empty thring.
So either we could add parantheses after the ! like so `! (el.localName === 'ui-disclosure')` or preferably `el.localName !== 'ui-disclosure'`.

The changed function
```js
disclosureWalker() {
    return walker(this, (el, { skip, reject }) => {
        if (el instanceof UIDisclosureGroup && el !== this) return reject()
        if (el.localName !== 'ui-disclosure') return skip()
    })
}
```
There could be a reason that you made it the way that you do. The only conclution i can tell is that it works on my end when i make the change.

**Comment by calebporzio** [comment]
Ah you beat me to it - just came to here to say that lol. So silly haha. Fixed and will be in the next release. Thanks a lot for the work on that!

**Comment by MatsKruger** [comment]
Thats perfect. 
Thank you.
And thank you for such an awesome library
