### ISSUE TITLE
Undefined variable $size when using clearable, viewable, copyable or expandable

### ISSUE THREAD

**Issue by wenfei-huang** [livewire/flux#363]
I tried to use the following lines from the docs:

```html
<flux:input placeholder="Search orders" clearable />
<flux:input type="password" value="password" viewable />
<flux:input icon="key" value="FLUX-1234-5678-ABCD-EFGH" readonly copyable />
``` 

I only get the error when adding clearable, viewable, copyable or expandable to a flux Input, all giving the error with "Undefined variable $size" .
I think the problem lies how this corresponding view uses the size attributes (for example in folder vendor / livewire / flux-pro / stubs / resources / views / flux / input / viewable.blade.php):

```blade
<flux:button
    :$attributes
    :size="$size === 'sm' ? 'xs' : 'sm'"
>
``` 

if i change this into
```blade
 :size="$attributes['size'] === 'sm' ? 'xs' : 'sm'"
``` 

it works again.

**Comment by jeffchown** [comment]
@wenfei-huang Have you checked issue https://github.com/livewire/flux/issues/352 ?
