### ISSUE TITLE
Combobox and listbox select variants only match start of value when searching

### ISSUE THREAD

**Issue by jeppeolesen** [livewire/flux#364]
When using the `<flux:select variant="combobox|listbox" />`, search only matches the start of the option value.

Fx when searching for 'Porzio' in the component below, no results will be returned.

```
<flux:select variant="combobox">
    <flux:option>Taylor Otwell</flux:option>
    <flux:option>Caleb Porzio</flux:option>
    <flux:option>Josh Hanley</flux:option>
    <flux:option>Nunu Maduro</flux:option>
</flux:select>
```

This is due to filterable.js:42 using `startsWith()`:

```
matches(el, search) {
    return el.textContent.toLowerCase().trim().startsWith(search.toLowerCase().trim())
}
```

It can be fixed by using `includes` instead:

```
matches(el, search) {
    return el.textContent.toLowerCase().trim().includes(search.toLowerCase().trim())
}
```

**Comment by MartijnCuppens** [comment]
Alternatively, we could use a "starts with per word approach".

Take this example:
```html
<flux:select variant="combobox">
    <flux:option>Olivia Smith</flux:option>
    <flux:option>Amelia Gonzalez</flux:option>
    <flux:option>Harper Anderson</flux:option>
    <flux:option>Josh Hanley</flux:option>
    <flux:option>Nunu Maduro</flux:option>
</flux:select>
```

If you type `a`, you'll probably searching for "Amelia Gonzalez" or "Harper Anderson", but "Olivia Smith" and "Josh Hanley" are also shown. Made a simple demo with more examples to show the issue: https://codepen.io/MartijnCuppens/pen/abemrqL?editors=1011.

I only split the words with a space, but maybe other separators could be interesting too (-_/). We'll also have to take brackets into account (probably just remove them in the search string) :

```html
<flux:select variant="combobox">
    <flux:option>Soccer</flux:option>
    <flux:option>American football</flux:option>
    <flux:option>Tennis/Padel</flux:option>
    <flux:option>Roundnet (Spikeball)</flux:option>
</flux:select>
```
Expected results:
`a`: American football
`f`: American football
`p`: Tennis/Padel
`s`: Soccer, Roundnet (Spikeball)

**Comment by jeffchown** [comment]
This is being discussed here too https://github.com/livewire/flux/discussions/126

**Comment by calebporzio** [comment]
Thanks for this simple solution. This is a better default and will be in the next Flux release.
