### ISSUE TITLE
Modal not opening.

### ISSUE THREAD

**Issue by GuidoVeltmaat** [livewire/flux#369]
Hi there! 👋 

I dont know whats happening here but hope you be able to shine a liight?

Made a test site for this following steps from [Flux/install](https://fluxui.dev/docs/installation) up an including step 5.
Took out Laravel's default content from the welcome page and replaced it with: 

```
 <flux:main>
    <div class="flex items-center justify-center h-screen">
        <div class="p-8 rounded-lg bg-gray-500/20 space-y-8">
            <flux:heading level="1" size="lg">Hello Fluxer!</flux:heading>
            <flux:subheading>
                <flux:modal.trigger name="opendarnit">
                    <flux:button>open modal</flux:button>
                </flux:modal.trigger>
                <flux:modal name="opendarnit" class="min-w-[22rem] space-y-6">
                    <div>
                    <flux:heading size="lg">NOW you see me?</flux:heading>
                    </div>
                </flux:modal>
            </flux:subheading>
        </div>
    </div>
</flux:main>
```

HOst it on [https://diafragmaat.nl/](https://diafragmaat.nl/) and  no modal pops up.

**Comment by jeffchown** [comment]
@GuidoVeltmaat I pasted your example into my Flux test app and it worked for me.

One thing it might be is that you have no Livewire component or explicit Alpine `x-data` on the page anywhere.

Can you try changing `<div class="flex items-center justify-center h-screen">` to 
`<div x-data="" class="flex items-center justify-center h-screen">` and see if that works?

**Comment by GuidoVeltmaat** [comment]
@jeffchown yes, thats it!

So am i correct in saying `x-data=""`  is always needed for just the flux:modal? Cause no [examples](https://fluxui.dev/components/modal) have it.

All other Flux components work fine without it as far as i can see.

**Comment by jeffchown** [comment]
Great @GuidoVeltmaat ! 

It is not always needed, it is only when you are adding a Flux component that depends upon some Alpine-related functionality in a place on a page or blade file where there is no parent `<div>`s' `x-data` reference/usage (either 'hidden' in another Flux or Alpine component  e.g. inside an `accordion` component, or when you add `x-data` on your own for some Alpine functionality)

Not the best explanation, but I hope it helps.

**Comment by jeffchown** [comment]
UPDATE: @GuidoVeltmaat I see that @calebporzio just posted v1.0.9 3 hours ago and one of the changes is `Support modals outside of Livewire/Alpine components` - maybe that will address your initial issue without the need of the `x-data` addition...

**Comment by camiant** [comment]
> UPDATE: [@GuidoVeltmaat](https://github.com/GuidoVeltmaat) I see that [@calebporzio](https://github.com/calebporzio) just posted v1.0.9 3 hours ago and one of the changes is `Support modals outside of Livewire/Alpine components` - maybe that will address your initial issue without the need of the `x-data` addition...

even on v1.0.9 `x-data` is required on the container tag for modal to work correctly

**Comment by jeffchown** [comment]
@camiant After you upgraded to 1.0.9, did you make sure you cleared the `view:cache` and deleted, then republished any flux components you had published? (that one 'bit' me a while back when I had an issue with accordion).

**Comment by GuidoVeltmaat** [comment]
v1.0.9 fixed this for me indeed. 

Ive not had any components published. So  i did the `composer update livewire/flux livewire/flux-pro` & `php artisan view:clear` then removed the `x-data=""`.  

Modal opens now with example code in my first post. 👍

**Comment by acamiletti** [comment]
> [@camiant](https://github.com/camiant) After you upgraded to 1.0.9, did you make sure you cleared the `view:cache` and deleted, then republished any flux components you had published?

I did `view:cache` without re-publishing components... 😅
Now it works like a charm!
