### ISSUE TITLE
flux:input/flux:radio Component doesn't respect checked/disabled

### ISSUE THREAD

**Issue by challgren** [livewire/flux#37]
When using flux:radio the :checked property is not respected

```
<flux:radio.group wire:model="yesno">
    <flux:radio wire:model="yesno" value="1" label="Yes" :disabled="$na_input" :checked="$yesno"/>
    <flux:radio wire:model="yesno" value="0" label="No" :disabled="$na_input" :checked="!$yesno"/>
</flux:radio.group>
```

Results in no radio box checked if the model $yesno is set to true/false

```
<flux:radio.group wire:model="yesno">
    <flux:radio wire:model="yesno" value="1" label="Yes" :disabled="$na_input" checked />
    <flux:radio wire:model="yesno" value="0" label="No" :disabled="$na_input" />
</flux:radio.group>
```

This code also doesn't have any radio group checked

**Comment by challgren** [comment]
This also occurs with `disabled`

**Comment by voicecode-bv** [comment]
I've also experienced this with a group of checkboxes

**Comment by calebporzio** [comment]
Before I investigate, I should say, you aren't meant to have wire:model on both the group AND the items... only the group OR the items. `wire:model` on the group will bind an array of the group's values, and each item will bind a boolean value.

So please remove the `wire:model` attributes on each checkbox, only keep it on the group, and resubmit this issue if it still persists. thanks!

**Comment by challgren** [comment]
I removed the `wire:model` on each `flux:radio` and still the issue persists. I also removed the `wire:model` from the `flux:radio.group` and it still exists either way. Is it possible the radio group/radio box not work with a boolean backed variable in the component?

**Comment by voicecode-bv** [comment]
Same issue for me, using a boolean backed variable. 

```
<div class="col-span-6 sm:col-span-4" x-show="hasTeams" x-cloak>
    <flux:checkbox.group wire:model="selectedTeams" label="Selecteer de deelnemende teams">
        @foreach($teams as $team)
        <flux:checkbox :label="$team->name" :value="$team->id" />
        @endforeach
    </flux:checkbox.group>
</div>
```

**Comment by mauritskorse** [comment]
For me it worked when I just let wire:model do its job. You have to remove all disabled and checked properties from the radio elements.
