### ISSUE TITLE
[toast] can't do anything while the toast is open - v1.0.9

### ISSUE THREAD

**Issue by helderneves91** [livewire/flux#371]
Hi there!

In version 1.0.9, while toast is active, can't copy text / open select inputs... Basically can't do anything while it's open.
After dismiss, everything starts working.

On layout:
`<flux:toast />`

On component:
```
<flux:select placeholder="Choose industry...">
    <flux:option>Photography</flux:option>
    <flux:option>Design services</flux:option>
    <flux:option>Web development</flux:option>
    <flux:option>Accounting</flux:option>
    <flux:option>Legal services</flux:option>
    <flux:option>Consulting</flux:option>
    <flux:option>Other</flux:option>
</flux:select>

Flux::toast('toast test');
```

EDIT 1: cache is cleared and flux stubs aren't published.

**Comment by calebporzio** [comment]
Hmmm... just tested this locally and it works fine. What browser?

**Comment by helderneves91** [comment]
Hey, MacOS/Safari, latest.

**Comment by helderneves91** [comment]
Hey, check this out:
https://github.com/user-attachments/assets/59be66c9-7348-42b4-a125-ef54434589ec

**Comment by LasseRafn** [comment]
Can confirm , see screenshot from docs, the popover container/popover itself is a dialog that takes up the entire page (orange)

![Image](https://github.com/user-attachments/assets/a19c43b7-80d9-4770-8c7e-cae23ee93acf)

**Comment by calebporzio** [comment]
Hmm I guess Safari handles dialog.showPopover differently than Chrome. I'll switch to a <div> in the next release. Fixed.

**Comment by helderneves91** [comment]
Thanks! Waiting for it :)
