### ISSUE TITLE
Toast variant prop not working

### ISSUE THREAD

**Issue by jgriggs-sluh** [livewire/flux#374]
The variant prop for toasts does not seem to be working in 1.0.9. The following code is producing a normal, non variant toast with a heading and text. If I'm formatting incorrectly, I'm happy to be corrected.

    public function toastTest()
    {
        Flux::toast(variant: 'success',heading: 'Success!',text: 'Sign created successfully',);
    }

**Comment by helderneves91** [comment]
Looks like you have an unnecessary comma in the end `successfully',);`.

Try:
`Flux::toast(variant: 'success',heading: 'Success!',text: 'Sign created successfully');`

**Comment by jeffchown** [comment]
@jgriggs-sluh Your code works in my Flux test app:

![Image](https://github.com/user-attachments/assets/652fc375-d7d8-4d3f-89f7-0696efc7f1e3)

**Comment by jgriggs-sluh** [comment]
> Try: `Flux::toast(variant: 'success',heading: 'Success!',text: 'Sign created successfully');`
> 
> If you have published flux stubs, delete them and try again.

You got me. Gah. I had published the stub in 1.0.8 because toasts weren't working at all and I wanted to look it over. Forgot to remove it once I updated to 1.0.9. Can report working properly. Closing. Thank you all.
