### ISSUE TITLE
input.group doesn't show validation errors

### ISSUE THREAD

**Issue by helderneves91** [livewire/flux#375]
Hi there!

So, basically I have a modal with a form which contains a single input group.

Livewire component:
```
class Conversation extends Component
{
    #[Validate('required|string|min:8', as: 'question')]
    public string $question = '';

    public function render()
    {
        return view('livewire.artificial-intelligence-conversations.conversation');
    }

    public function ask ()
    {
        $this->validate();
    }
}

```

Blade component:
```
<div>

    <flux:modal.trigger name="modal1">
        <flux:button variant="ghost" icon="magnifying-glass"></flux:button>
    </flux:modal.trigger>

    <flux:modal name="modal1" class="md:w-full space-y-6">
        <div>
            <flux:heading size="lg">Title</flux:heading>
            <flux:subheading>description</flux:subheading>
        </div>

        <form wire:submit="ask" class="space-y-6">

            @csrf
            @method('post')

            <flux:input.group>
                <flux:input wire:model.live="question" placeholder="Ask AI" />
                <flux:button type="submit" icon="paper-airplane"></flux:button>
            </flux:input.group>

        </form>


    </flux:modal>

</div>
```

Results in:
![Image](https://github.com/user-attachments/assets/0b1e5789-77b0-42f4-9b47-77d0adc5744b)

Normal inputs works as expected.
Hope to get this fixed asap, since this kind of components doesn't look good with a line containing an input and another the button. In this case I prefer a group.

Thanks.

**Comment by helderneves91** [comment]
Well... if I put a label on the inputs, it will show errors but the group won't be a group anymore.

```
<flux:input.group>
    <flux:input wire:model.live="question" label="111" placeholder="Ask AI" />

    <flux:button type="submit" icon="paper-airplane"></flux:button>
</flux:input.group>
```

Results in:
![Image](https://github.com/user-attachments/assets/2775ceeb-f635-4582-ae8e-485915dc6268)

**Comment by jeffchown** [comment]
@helderneves91 You have to wrap the whole `flux:input.group` in a `flux:field` so you can manually show the error. e.g.:

```
<flux:field>
    <flux:input.group>
        <flux:input wire:model.live="question" placeholder="Ask AI" />
        <flux:button type="submit" icon="paper-airplane"></flux:button>
    </flux:input.group>

    <flux:error name="question" />
</flux:field>
```

**Comment by calebporzio** [comment]
Thank you @jeffchown

**Comment by helderneves91** [comment]
> [@helderneves91](https://github.com/helderneves91) You have to wrap the whole `flux:input.group` in a `flux:field` so you can manually show the error. e.g.:
> 
> ```
> <flux:field>
>     <flux:input.group>
>         <flux:input wire:model.live="question" placeholder="Ask AI" />
>         <flux:button type="submit" icon="paper-airplane"></flux:button>
>     </flux:input.group>
> 
>     <flux:error name="question" />
> </flux:field>
> ```

Thanks!

**Comment by jeffchown** [comment]
You're welcome, @helderneves91 !
