### ISSUE TITLE
Flux sidebar.toggle breaks ACT rule "Button has non-empty accessible name"

### ISSUE THREAD

**Issue by lonebadger99** [livewire/flux#376]
Using the Sidebar or Header example provided in the documentation:

<flux:sidebar.toggle class="lg:hidden" icon="bars-2" inset="left" />

This line generates code that breaks the ACT Rule "[Button has non-empty accessible name](https://www.w3.org/WAI/standards-guidelines/act/rules/97a4e1/)". It should either have text content or a aria-label (aria-label="text content").

**Comment by calebporzio** [comment]
Good call, thanks! - fixed
