### ISSUE TITLE
Modals always show scrollbars on Windows

### ISSUE THREAD

**Issue by MarioPerini** [livewire/flux#380]
Thanks for the great Flux UI. I just want to let you know about a styling issue in the docs. You probably already know it but i did not found an open issue to the topic.

I'm using Chrome version 129.0.6668.90 on a Windows machine and on your modal component I get scrollbars. They disappear while scrolling.
![Image](https://github.com/user-attachments/assets/005bfc45-7187-4de9-8b24-ea200b4fca52)

I also tested it in Microsoft Edge version 129.0.2792.79 and got the same behavior. 
A colleague who is also working on a windows machine confirmed the same behavior on his machine.

Works fine in Firefox version 131.0
Works fine in Opera One (version: 114.0.5282.21)

It works on a colleague's Mac:
- Safari 17.6
- Arc 1.63.0
- Chrome 129.0.6668.70 
- Firefox Developer Edition 123.0b5

**Comment by calebporzio** [comment]
Thank you for testing this on the mac as well to confirm it's only Windows.

I plan on addressing this and will leave this issue open until we do.

**Comment by danielrona** [comment]
On W11 and Chrome Versions 129.0.6668.101 and 130.0.6723.59 I could not replicate this.

@MarioPerini is this still an issue for you after updating Chrome?

![Image](https://github.com/user-attachments/assets/b91a5326-046e-4db7-97e3-1ec699290e41)

**Comment by MarioPerini** [comment]
W11Pro Chrome 130.0.6723.59 still the same
![Image](https://github.com/user-attachments/assets/1ab79b80-ada2-402a-9e50-109b47c79ca7)

Also tested on W10Home, with current chrome build: no issue

**Comment by patrykszady** [comment]
I use Edge on Windows and dont have this issue. Chrome only issue?

**Comment by MarioPerini** [comment]
> I use Edge on Windows and dont have this issue. Chrome only issue?

Chromium only, but Edge is chromium based and show scrollbar too.

Since it appears to not be an issue on every machine, i want to provide more details about my machine.

OS: Windows 11 Pro 23H2 build 22631.4317

Microsoft Edge for Business Version 130.0.2849.46 64-Bit:
![Image](https://github.com/user-attachments/assets/8e3cd046-52b4-4528-b464-e5f0405e5aba)

Microsoft Edge for Business Version 130.0.2849.52 64-Bit:
![Image](https://github.com/user-attachments/assets/6a72b8ba-f18a-4214-89cc-c94e08aea079)

**Comment by danielrona** [comment]
I tested it on Microsoft Edge Version 130.0.2849.52 and no scrollbars either.

I'm at 4k with 150% also on 64-bit Windows 11 Pro 23H2 22631.4317 with Windows Feature Experience Pack 1000.22700.1041.0

@MarioPerini  you have any AntiVirus/Firewall/Extensions installed that might cause this?

**Comment by MarioPerini** [comment]
> I tested it on Microsoft Edge Version 130.0.2849.52 and no scrollbars either.
> 
> I'm at 4k with 150% also on 64-bit Windows 11 Pro 23H2 22631.4317 with Windows Feature Experience Pack 1000.22700.1041.0
> 
> [@MarioPerini](https://github.com/MarioPerini) you have any AntiVirus/Firewall/Extensions installed that might cause this?

I have Windows Feature Experience Pack 1000.22700.1041.0 too.

No AntiVirus or Firewall other then Microsoft Defender. But i now feel stupid, i have not tested without Extensions assumed i don't have Extensions in Edge but was wrong and its gone without RoboForm. Same in Chrome.
