### ISSUE TITLE
Adding `disabled` to submit button shows loading animation

### ISSUE THREAD

**Issue by ahscc** [livewire/flux#383]
Version: v1.0.9

When adding `disabled` to a submit button the loading icon is displayed. Adding to a default button only disables the button as expected.

You might want to disable the submit button if you are validating inputs as they are being filled.

![Image](https://github.com/user-attachments/assets/67e3868f-cb16-45b9-950d-a401646511ac)

Example:
```html
<div class="p-4">
    <p>Default button</p>
    <flux:button disabled>Button</flux:button>

    <p>Submit button</p>
    <form>
        <flux:button type="submit" disabled>Submit</flux:button>
    </form>
</div>
```

**Comment by jeffchown** [comment]
Good catch, @ahscc - and I have an exact use case for disabling a submit button while a user fills out a lengthly form, so this would confuse them.

I guess I could leave the submit button enabled and allow the validation to kick in should they submit early, but in this case I prefer to leave the submit button disabled as a visual cue that the user has more work to do in the form.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
