### ISSUE TITLE
description-trailing not displayed when input lacks label or description

### ISSUE THREAD

**Issue by MOA-TI** [livewire/flux#389]
Hi!

When an input field has no label or no description, description-trailing is not displayed, as seen in the second input of the first row.

```
<div class="grid grid-cols-3 gap-4">
    <flux:input description="description"/>
    <flux:input description-trailing="description-trailing"/>
    <flux:input description="description" description-trailing="description-trailing"/>
</div>

<div class="grid grid-cols-3 gap-4">
    <flux:input label="label" description="description"/>
    <flux:input label="label" description-trailing="description-trailing"/>
    <flux:input label="label" description="description" description-trailing="description-trailing"/>
</div>
```

![Image](https://github.com/user-attachments/assets/1c89aea8-e49d-4c28-b3e2-c5b444000f85)

**Comment by calebporzio** [comment]
I don't think we're going to support this scenario. Please instead use the long-form for input fields to add your trailing description with no label:

https://fluxui.dev/components/input#longhand
