### ISSUE TITLE
[PRO] profile with chevron by default?

### ISSUE THREAD

**Issue by andreilungeanu** [livewire/flux#39]
I’m a bit confused about why a chevron is displayed on the <flux:profile> component without a dropdown. According to the documentation [here](https://fluxui.dev/demo/header-with-sidebar), it seems that the expected usage should include a dropdown.

The example provided in the documentation shows: (header)

`        <flux:profile avatar="https://fluxui.dev/img/demo/user.png" />`

However, it would be clearer if it were structured like this:
```
        <flux:dropdown position="bottom" align="end">
            <flux:profile avatar="https://fluxui.dev/img/demo/user.png" name="Olivia Martin" />

            <flux:navmenu>
                <flux:navmenu.item href="#" icon="user">Account</flux:navmenu.item>
                <flux:navmenu.item href="#" icon="credit-card">Billing</flux:navmenu.item>
                <flux:navmenu.item href="#" icon="arrow-right-start-on-rectangle">Logout</flux:navmenu.item>
            </flux:navmenu>
        </flux:dropdown>
```

Alternatively, updating the profile.blade.php stub because now is true by default.
```
  @props([
    'chevron' => null,
...
])
```

**Comment by gjsman** [comment]
I'm confused why `<flux:profile>` doesn't have a documentation page to begin with...

**Comment by joshhanley** [comment]
@andreilungeanu thanks for reporting! This has been fixed now and the profile now has a dropdown. So I'm going to close this.

**Comment by andreilungeanu** [comment]
Thanks

To follow the same idea from the documentation at https://fluxui.dev/components/dropdown#navigation-menus, I believe it would be preferable to use navmenu.item instead of menu.item, although they are similar in functionality.

This ensures consistency with the documentation.
