### ISSUE TITLE
Stashable sticky Sidebar stops working once a toast is displayed

### ISSUE THREAD

**Issue by RiadhKHEDHIRI** [livewire/flux#390]
I used the demo code for the Header. I resized the window to show the side menu. The Sidebar works fine until a toast is displayed. The overlay is shown, but the Sidebar is not anymore. I have to refresh the page to make it work again. I use Firefox with v1.0.9

**Comment by calebporzio** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps to reproduce. Please include any Blade variable definitions that are used. Then, we will be happy to help.
