### ISSUE TITLE
Table cell dropdown menu displacement

### ISSUE THREAD

**Issue by omniith** [livewire/flux#391]
Hi team,

I just upgraded to livewire 3.5.10 and the dropdown menu from table cell displaced itself after briefly appearing at the original position and places itself in the center of the browser.

```
<flux:table>
    <flux:columns>
        <flux:column>Name</flux:column>
        <flux:column>Department</flux:column>
        <flux:column>Roles</flux:column>
    </flux:columns>
    <flux:rows>
        <flux:row>
            <flux:cell class="flex items-center gap-3">user's name</flux:cell>
            <flux:cell>department name</flux:cell>
            <flux:cell>roles</flux:cell>
            <flux:cell class="grid justify-items-end">
                <flux:dropdown>
                    <flux:button wire:click="loadUser" :loading="false" variant="ghost" size="sm" icon="ellipsis-horizontal" inset="top bottom"></flux:button>
                    <flux:menu>
                        <flux:menu.group heading="Edit">
                            <flux:modal.trigger name="edit-roles">
                                <flux:menu.item>Roles</flux:menu.item>
                            </flux:modal.trigger>
                            <flux:menu.item>Department</flux:menu.item>
                        </flux:menu.group>
                        <flux:menu.group>
                            <flux:menu.item variant="danger">Delete</flux:menu.item>
                        </flux:menu.group>
                    </flux:menu>
                </flux:dropdown>
            </flux:cell>
        </flux:row>
        @endforeach
    </flux:rows>
</flux:table>
```

**Comment by ju5t** [comment]
@omniith can you share copy-pasteable code without any variables? And can you share a screenshot of what's happening?

**Comment by omniith** [comment]
@ju5t thanks for replying, I've found out that 
`wire:click="loadUser('{{ $user->id }}')"`
in the flux:button within the flux:dropdown is causing the issue.
![Image](https://github.com/user-attachments/assets/0cafbefa-852a-404b-8645-b5d86fdf496b)
![Image](https://github.com/user-attachments/assets/5e1e4613-065c-4c66-8dff-0bbde1213211)

**Comment by calebporzio** [comment]
Ah, what's happening here is that Livewire is refreshing the HTML because of `wire:click`. When the new HTML comes back from the server it doesn't have the "anchor positioning" styling to absolutely position the dropdown next to the trigger and Livewire wipes out those styles resetting the positioning of the dropdown.

I don't have a solution off hand, but will work on it and leave this open until I think of a good fix for it. Thanks.

**Comment by calebporzio** [comment]
Ok, this has been fixed and will be in the next version of Flux. Thanks everyone.
