### ISSUE TITLE
Listbox grows in flex box when option text is longer

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#392]
We use Flux in our own internal components. In some cases, we may want to add an icon, tooltip or dropdown next to a select. This often looks like something along the lines of the below.

```blade
<div class="flex space-x-2">
    <flux:select variant="listbox" size="sm" placeholder="Choose industries...">
        <flux:option>PhotographyPhotographyPhotographyPhotographyPhotography</flux:option>
        <flux:option>Design services</flux:option>
    </flux:select>
    <div>icon</div>
</div>
```

When a larger string is selected it pushes the icon to the right. This doesn't happen when I remove the listbox variant.

![Image](https://github.com/user-attachments/assets/ac0dd621-7140-4dc2-b8dc-ffa6ca3b185a)

**Comment by jeffchown** [comment]
@ju5t Isn't that partly because you got a wrapping `<div>` that sets `flex`?

I tried your example and see what you describe, then added a `flex-none` to the `flux:select` and it stayed a fixed width. e.g.
`<flux:select variant="listbox" size="sm" placeholder="Choose industries..." class="flex-none">`

Basically, with the wrapping `flex`, I think you'll need to explicitly set the width of the `flux:select` to get the best result.  e.g. `w-[200px]`

**Comment by ju5t** [comment]
@jeffchown it is.

I just tried `flex-none` but it still pushes the icon away. Unfortunately, setting an explicit width is not what we want, we want the element to grow to its available space, no matter if the icon is there or not. 

Both the native `select` and the `flux:select` do not have this issue.

**Comment by jeffchown** [comment]
@ju5t I see.

I played with it some more and was able to get the result you describe via `<flux:select variant="listbox" size="sm" placeholder="Choose industries..." class="flex-1 truncate">`

While some changes might be needed in the `listbox` variant to get it to behave the same as the `select` and `flux:select`, this is a workaround that seems to create the desired result.

As @calebporzio says, CSS is hard.  

I've learned more CSS from deep-diving into some of the fancy CSS used in some of the Flux components and still feel 'in the weeds' sometimes.

**Comment by ju5t** [comment]
@jeffchown ah thanks, that's it! I tried some things with `truncate` before but never thought of combining it with `flex-1`. Thanks a lot!

> As @calebporzio says, CSS is hard.

It is, it's incredibly hard. It makes you appreciate the incredible work Caleb did with Flux. 

I think I'll leave this issue open for now, just in case it's worth fixing in Flux itself. Perhaps the layout shift of the option itself can be looked at too. 

![Image](https://github.com/user-attachments/assets/3b26497f-00b8-4bc4-92a7-911b761cdf42)
 
Thanks again!

**Comment by jeffchown** [comment]
> [@jeffchown](https://github.com/jeffchown) ah thanks, that's it! I tried some things with `truncate` before but never thought of combining it with `flex-1`. Thanks a lot!
> 
> > As [@calebporzio](https://github.com/calebporzio) says, CSS is hard.
> 
> It is, it's incredibly hard. It makes you appreciate the incredible work Caleb did with Flux.
> 
> I think I'll leave this issue open for now, just in case it's worth fixing in Flux itself. Perhaps the layout shift of the option itself can be looked at too.
> 
> ![Image](https://github.com/user-attachments/assets/3b26497f-00b8-4bc4-92a7-911b761cdf42)
> 
> Thanks again!

You're welcome, @ju5t !

I hadn't thought of it either until I started experimenting with your code.
Yes, @calebporzio and team have done a fantastic job with Flux 🎉

Re: the layout shift - after diving the DOM, it looks like, when the `select` is restricted to a width narrower than the `Photography...` option, when that option is *not* selected (e.g. no checkmark to its left), the length of the `option`'s text takes over the `hidden` area to its left that is meant to leave room for that checkmark.  You can see this by making it `selected` by default and see how it lines up with the `Design services` option when `Photo...` is checked:

`<flux:option selected>PhotographyPhotographyPhotographyPhotographyPhotography</flux:option>`

I'm sure there's a way to fix this in the CSS but I will bow to the greater CSS-skills of @calebporzio and his team on this one.

**Comment by calebporzio** [comment]
Thanks for this report, and your help on it @jeffchown. Fixed and will be in the next release

![Image](https://github.com/user-attachments/assets/8cb25ab8-d9d0-48e2-acdc-21a6046f5b0e)
![Image](https://github.com/user-attachments/assets/315e0d21-e20e-4e8c-95f4-c540673446d3)
