### ISSUE TITLE
Button default variant

### ISSUE THREAD

**Issue by Hesesses** [livewire/flux#394]
Hello,

`<flux:button :variant="$type == \App\Enums\NewsType::Global ? 'primary' : ''">Global</flux:button>`

if variant is '' or null, it should use the "default" variant. Now getting an error `Unhandled match case ''`

**Comment by roadsend** [comment]
i had this issue too.. i think default is outline so you can use that.

**Comment by jeffchown** [comment]
@Hesesses I tried your example, then substituted `null`, e.g. 

`<flux:button :variant="'one' == 'two' ? 'primary' : null">Global</flux:button>`

or, ,in your case:

`<flux:button :variant="$type == \App\Enums\NewsType::Global ? 'primary' : null">Global</flux:button>`

and it worked as desired.

**Comment by Hesesses** [comment]
I was 100% sure I tried this with null, but you are right, it works
