### ISSUE TITLE
Flux:Button forced to display square if value is explicit 0

### ISSUE THREAD

**Issue by NickSB** [livewire/flux#395]
Hello,

If flux:button receive a value with 0 (zero), button is forced to display as square.

Example:
<flux:button icon="hashtag" variant="ghost">0</flux:button>

Real life scenario:
<flux:button icon="hashtag" variant="ghost">{{ $item->customers()->count() }}</flux:button>

Result:
![Image](https://github.com/user-attachments/assets/3712cfb3-43b7-4faa-a263-8fa3b5ce6f22)

Possible solution: 
Check exclusive if value is 0.

$square ??= ((string) $slot) !== '0' && empty((string) $slot);

**Comment by jeffchown** [comment]
@NickSB A workaround for now is to add `:square="false"` to your `flex:button`:
`<flux:button icon="hashtag" variant="ghost" :square="false">0</flux:button>`

**Comment by calebporzio** [comment]
Good catch - fixed
