### ISSUE TITLE
Toast prevents clicks all over the page (Safari)

### ISSUE THREAD

**Issue by lefrancois** [livewire/flux#396]
Hey there! 👋

Since 1.0.9 toasts prevent from clicking anywhere on the page (even in your docs).

Tested on Mac and Safari 18.0.1.
Chrome is working fine.

Thanks for checking!

**Comment by jeffchown** [comment]
Looks like @calebporzio has fixed this (in next release) - see https://github.com/livewire/flux/issues/371

**Comment by lefrancois** [comment]
Oh yeah, perfect. 🙂🙃
