### ISSUE TITLE
Header with only a logo and not a name

### ISSUE THREAD

**Issue by jcc5018** [livewire/flux#398]
Not sure if I am doing things wrong, but I'm trying to modify the code samples you have. 

If I use your default brand component 

```
 <flux:brand href="{{route('home')}}" name="{{app(App\Settings\SiteSettings::class)->site_name}}"
                logo="{{ asset('media/'.app(App\Settings\SiteSettings::class)->site_icon)}}"

                class="max-lg:hidden dark:hidden"/>
    <flux:brand href="{{route('home')}}" name="{{app(App\Settings\SiteSettings::class)->site_name}}"
                logo="{{ asset('media/'.app(App\Settings\SiteSettings::class)->site_icon)}}"
                class="max-lg:!hidden hidden dark:flex"/>

```
your sample on https://fluxui.dev/layouts/header  shows a small icon with a text based name. 

Although this may be great for some people, there does not seem to be a way to only have a logo without the name. If I were to remove the name property, the uploaded logo would be a very small rendering to fit within the icon space, when my logo is 200px by 60px

```
<flux:brand href="{{route('home')}}" 
                logo="{{ asset('media/'.app(App\Settings\SiteSettings::class)->site_logo)}}"

                class="max-lg:hidden dark:hidden"/>
    <flux:brand href="{{route('home')}}" 
                logo="{{ asset('media/'.app(App\Settings\SiteSettings::class)->site_logo)}}"
                class="max-lg:!hidden hidden dark:flex"/>

```
Top navigation is what I'm replacing with your components. The bottom nav, is the result of the above code:

![Image](https://github.com/user-attachments/assets/a9e5416f-672d-4608-a70c-b8f46bac7b0f)

Is there a good way to address this without changing things up too much in the component code?

**Comment by calebporzio** [comment]
I think in cases like this you're better off skipping the <flux:brand> component and manually styling this brand logo - shouldn't be to complicated. The brand component is just there for convenience.
