### ISSUE TITLE
Components rendering but without styles

### ISSUE THREAD

**Issue by erswelljustin** [livewire/flux#40]
The issue I am facing is that I get the components rendering without any styles. I have followed the standard documented process for a new Laravel project with Livewire and Tailwind. I am also using Laravel Herd. I am not using Vite or any starter kit.

These are the steps I have gone through.

Laravel install
`cd ~/Herd`
`laravel new flux-test`

Livewire install
`cd flux-test`
`composer require livewire/livewire`

Tailwind install
`npm install -D tailwindcss postcss autoprefixer`
`npx tailwindcss init -p`

Then from the Flux docs I followed the instructions (Attached is my `welcome.blade.php`, 'tailwind.config.js`, `flux-ui.blade.php`) The flux components render but there are no styles applied (Attached is a screenshot)

**Edit:** I of course added the flux system using the instructions from the docs inclusive of my licence based tasks
`composer config repositories.flux-pro composer https://composer.fluxui.dev`
`composer config http-basic.composer.fluxui.dev {my-registered-email} {my-license-key}`
`composer require livewire/flux-pro`

`tailwind.config.js`
```
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./vendor/livewire/flux-pro/stubs/**/*.blade.php",
    "./vendor/livewire/flux/stubs/**/*.blade.php",
  ],
  theme: {
    fontFamily: {
        sans: ['Inter', 'sans-serif'],
    },
    extend: {},
  },
  plugins: [],
}
```

`welcome.blade.php`
```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Flux Test</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400..600&display=swap" rel="stylesheet">

        @fluxStyles
    </head>
    <body class="font-sans antialiased dark:bg-black dark:text-white/50">
        <livewire:flux-ui/>
        @fluxScripts
    </body>
</html>
```

`flux-ui.blade.php`
```
<div>
    <flux:card class="space-y-6">
        <div>
            <flux:heading size="lg">Log in to your account</flux:heading>
            <flux:subheading>Welcome back!</flux:subheading>
        </div>

        <div class="space-y-6">
            <flux:input label="Email" type="email" placeholder="Your email address" />

            <flux:field>
                <flux:label class="flex justify-between">
                    Password

                    <flux:link href="#" variant="subtle">Forgot password?</flux:link>
                </flux:label>

                <flux:input type="password" placeholder="Your password" />

                <flux:error name="password" />
            </flux:field>
        </div>

        <div class="space-y-2">
            <flux:button variant="primary" class="w-full">Log in</flux:button>

            <flux:button variant="ghost" class="w-full">Sign up for a new account</flux:button>
        </div>
    </flux:card>
</div>
```
![Flux-Component-Rendered-No-Styles](https://github.com/user-attachments/assets/0e4b0c0b-6600-45e0-9004-97616d7c1785)
![Laravel-New-Project-Database](https://github.com/user-attachments/assets/f9d88fea-c733-4bce-a061-a07c6392a215)
![Laravel-New-Project](https://github.com/user-attachments/assets/50d3fcac-b4f3-436b-9f54-b9a0a385e05d)

**Comment by joshhanley** [comment]
@erswelljustin as you are using Tailwind through NPM, you will need to use Vite.

Add `@vite(['resources/css/app.css', 'resources/js/app.js'])` just before your closing `</head>` tag. https://laravel.com/docs/11.x/vite#loading-your-scripts-and-styles

Then run `npm run dev` and refresh your browser, and hopefully it should work 🙂

**Comment by erswelljustin** [comment]
@joshhanley Just done that and I am afraid it hasn't changed the problem

```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Flux Test</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400..600&display=swap" rel="stylesheet">

        @fluxStyles
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans antialiased dark:bg-black dark:text-white/50">
        <livewire:flux-ui/>
        @fluxScripts
    </body>
</html>
```

**Comment by erswelljustin** [comment]
@joshhanley I am an idiot I missed a step in the tailwind setup
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

in `app.css`

My apologies and thanks for your patience

**Comment by joshhanley** [comment]
@erswelljustin hmm, maybe try switching `@fluxStyles` and `@vite`, maybe that will then work?

```blade
        @vite(['resources/css/app.css', 'resources/js/app.js'])
        @fluxStyles
    </head>
```

**Comment by joshhanley** [comment]
@erswelljustin ah perfect! Thanks for sharing what fixed it
