### ISSUE TITLE
Problem with Modal and Toast when dispatching event

### ISSUE THREAD

**Issue by azizabbas** [livewire/flux#402]
Hi,

I have been facing this issue for two days now but i finally figure it out the problem. 

When I am dispatching an event inside a Modal or along with Toast its breaking my datatable pagination along with other wire:click registers.

I have attached a video showing how it is behaving and also uploaded respective code files on GIST:

Video: https://github.com/user-attachments/assets/6048e43d-699f-463d-ad4d-59d5f11a3d65

Gist: https://gist.github.com/azizabbas/dad90f58c0ea9b5f87464de68dc54c9a

I have also attached a file showing Livewire and Alpine errors in browser console.

![Image](https://github.com/user-attachments/assets/771ed10f-c477-4fa6-9d3b-fb688b1dd5af)

Please let me know if any other information required.

Thanks

**Comment by calebporzio** [comment]
Hi there, thanks for this report - unfortunately it is too difficult to reproduce without the necessary models you reference in the gist. If you can, please narrow this issue down to more simple code that I can copy and paste into my app without any extra class references. Thanks - closing for now.

**Comment by azizabbas** [comment]
Hi Caleb,

Thanks for your reply. 

I have created new gist that you can copy paste and reproduce that javascript error I mentioned above.

https://gist.github.com/azizabbas/156bdb5c3639a724e85959ad7ad8aa5d

1. Click on **Open Dialog** button
2. Then, click clic **Cancel and Close** button inside Dialog
3. You can see javascript error inside browser console which is already attached to the Issue. 
4. You can also watch this video on how this error is causing issues with registered Livewire Actions: https://github.com/user-attachments/assets/6048e43d-699f-463d-ad4d-59d5f11a3d65

I hope it helps to regenerate the bug.

Thanks
