### ISSUE TITLE
Setting Old Value in <flux:select>

### ISSUE THREAD

**Issue by beneyraheem** [livewire/flux#405]
The issue arises when attempting to restore the previously selected value after form validation fails.

Example:
```
<flux:select :filter="false" name="test">
    @foreach ($options as $option)
        <flux:option wire:key="{{ $option->id }}" value="{{ $option->value }}">
            {{ $option->label }}
        </flux:option>
    @endforeach
</flux:select>
```

In Laravel, I’d typically use:
```
<option value="{{ $option->id  }}" @selected(old('test') == $option->id )>
    {{ $version }}
</option>
```

However, this approach doesn’t seem to work with FluxUI.

Tried Setting selected using old() in Blade:

> @selected(old('test') == $option->id )

- Expected Behavior: It should set the old value based on old() after form submission errors.
- Actual Behavior: No old value is set, and the select always defaults to the placeholder.

**Comment by beneyraheem** [comment]
managed to set the old like this, but I am not sure this is the correct way

> selected="{!! old('test', $option->id) == $option->id !!}"

**Comment by raftia** [comment]
Hi @beneyraheem , you need to add your wire:model to the select to be in sync.

Hope that helps.

**Comment by beneyraheem** [comment]
@raftia I am tring to add it outside livewire, just blade. Livewire it works

**Comment by beneyraheem** [comment]
I have tried, got php error, 

I can use <option> and it works, instead of <flux:option>

**Comment by jeffchown** [comment]
@beneyraheem Have you tried:

`<flux:option wire:key="{{ $option->id }}" value="{{ $option->value }}" :selected="old('test') == $option->id">`

**Comment by beneyraheem** [comment]
@jeffchown it works, I tried it before, my autoformat mess it always. Thank you, great help.

```
<flux:select name="country" label="Country" placeholder="Choose country...">
    @foreach ($countries as $country)
      <flux:option wire:key="{{ $country->id }}"
        :selected="old('country') == $country->id" value="{{ $country->id }}">
        {{ $country->name }}
      </flux:option>
    @endforeach
</flux:select>
```

**Comment by jeffchown** [comment]
You're welcome, @beneyraheem !

I also had to switch from `@` directives to `:` dynamic attributes when updating to Flux.
There's more about this in the Flux docs here: https://fluxui.dev/docs/patterns#blade-components-vs-html-elements

**Comment by beneyraheem** [comment]
Ah ha, Thank you so much 🙏
