### ISSUE TITLE
Another Problem with Flux Toast

### ISSUE THREAD

**Issue by azizabbas** [livewire/flux#406]
Hi,

This is another issue I am reporting with `Flux:toast`

After recent updates I have noticed that default position of `Flux:toast` have been moved to **top-left** and despite using `position` attribute its not moving an inch from **top-left**

Thanks

**Comment by igmltd** [comment]
Had a similar issue but was just a cache thing

**Comment by azizabbas** [comment]
Thanks for your reply.

It is indeed an issue with cache and Vite :)
