### ISSUE TITLE
Add mx-1 and rounded-t-md to search.blade.php

### ISSUE THREAD

**Issue by dajoeberlei** [livewire/flux#410]
Hi there,

sorry dunno how to contribute to the component because its not in the public repository. But the search blade that is being used in the `<flux:select.search />` component needs a rounded-t-md and a px margin.

Without: (Current Flux State)
![Image](https://github.com/user-attachments/assets/99356c5a-d34c-4106-bc47-155ebd0dc173)

With:
![Image](https://github.com/user-attachments/assets/447ab4a8-5b47-4e73-9272-88d3201f3b55)

I added the last line to the Flux::classes in my search.blade.php file:
```php
@php
$classes = Flux::classes()
    ->add('h-10 w-full flex items-center px-3 py-2')
    ->add('font-medium text-sm text-zinc-800 dark:text-white')
    ->add('pl-9') // Make room for magnifying glass icon...
    ->add($closable ? 'pr-9' : '') // Make room for close button...
    ->add('outline-none')
    ->add('border-b border-zinc-200 dark:border-zinc-600')
    ->add('bg-white dark:bg-zinc-700')
    ->add('rounded-t-md mt-px mx-px') // add this line
    ;
@endphp
```

**Comment by razvantirboaca** [comment]
Hi! I solved this issue by not requiring @tailwindcss/forms anymore. It's not a Flux thing, it's css coming from the plugin.

**Comment by dajoeberlei** [comment]
@razvantirboaca oh interesting. I haven't thought it through completely yet, but I guess you can argue that if you fully rely on flux, that tailwind forms is never necessarily needed right?

**Comment by razvantirboaca** [comment]
@dajoeberlei yes, exactly! That's my thinking as well :)
