### ISSUE TITLE
Wrong character encoding in labels when translating strings with __()

### ISSUE THREAD

**Issue by MiguelLaforest** [livewire/flux#420]
Wrong character encoding in labels when translating strings with __()
![Image](https://github.com/user-attachments/assets/db46dcc7-a523-4ec2-a28d-07311ab857cf)

```blade
 // Causes the issue
<flux:input wire:model="location_name" label="{{ __('Location name') }}"/>
 // Causes the issue too, ':' solves it in my non-flux components
<flux:input wire:model="location_name" :label="__('Location name')"/>
 // Not good either
<flux:input wire:model="location_name" :label="__('Location\'s name')"/>
// Works!
<flux:input wire:model="location_name" label="Nom de l'emplacement"/>
 ```
fr.json
```json
{
    "Location name": "Nom de l'emplacement",
}
```

**Comment by MiguelLaforest** [comment]
Translation file [...\resources\lang\fr.json] contains an invalid JSON structure.
Inside the file I get an "Illegal escape sequence" error

**Comment by danielrona** [comment]
Since flux is always using `{{ $slot }}` you'll have to use `label="{!! __('Your string') !!}"`

so instead of:
`<flux:input wire:model="location_name" label="{{ __('Location name') }}"/>`

you use:
`<flux:input wire:model="location_name" label="{!! __('Location name') !!}"/>`


If you use `{{ }}` it will always be wrong, because `{{ }}` will run htmlentities, you would have to use `{!! !!}`

See: https://laravel.com/docs/5.1/blade#displaying-data

**Comment by ju5t** [comment]
> If you use {{ }} it will always be wrong, because {{ }} will run htmlentities, you would have to use {!! !!}

`{!! !!}` is discouraged as it's insecure, and you shouldn't have to use it.

You should be able to use an apostrophe. `{{ }}` will not strip it, and neither will slots. I can replicate the issue you're having on a fresh install, but it works just fine with any other anonymous Blade component. Please don't use `{!! !!}`.

Something else is going on. Perhaps its the Flux tag compiler?

**Comment by danielrona** [comment]
`{!! !!}` in user generated content might have a security impact, translation files, usually, are not user generated or at the very least should be pre-approved content so there shouldn't be any security issues with that.

if you pass ' thru htmlentities you end up with &#039;

**Comment by ju5t** [comment]
Laravel doesn't use `htmlentities()`. It uses `htmlspecialchars`. It uses `e()` under the hood to encode strings. This is also used by the component attribute bag which means the attribute bag holds the encoded value.

I'm pretty sure it's related to how the attribute bag is being passed to `flux:with-field`. I've done some source diving but got stuck. 

And as @MiguelLaforest mentioned, this problem doesn't show up with non-Flux components.

**Comment by MiguelLaforest** [comment]
@ju5t Yeah, exactly. To be fair, my issue isn't that I don't know why it's happening, solved that pretty quickly by decoding the label attribute in the input component.

```blade
if(is_string($attributes['label'])) {
    $attributes['label'] = html_entity_decode($attributes['label']);
}
```
Maybe I should have been more clear. I thought Caleb might pop by and give a reason why it has to be this way or quickly solve the issue so that we don't have to hack it like this or use {!! !!} everywhere. I doubt its a security reason, otherwise regular components and the other Flux components should do the same, unless I'm missing something. Anyway, if it is a security reason, I think it should be on me to implement some security if I was using user provided code, not be there by default when not needed.

**Comment by ju5t** [comment]
@MiguelLaforest don't get me wrong, I'm with you on this. I think it's a bug. You shouldn't have to use `{!! !!}` or anything else for that matter. If it works in non-Flux components, I think it should work with Flux too.

I tried to find the cause to make it easier for Caleb, that's all :)
