### ISSUE TITLE
Invalid Input Styling

### ISSUE THREAD

**Issue by Jaiieq** [livewire/flux#421]
Not sure if this is a bug or by design, but when using a <flux:input> with a prefix or suffix on an invalid input, the border does not include either the prefix or suffix part of the input and makes it look a little disjointed.

![Image](https://github.com/user-attachments/assets/234a59a1-1e04-4816-b429-f7332a426d2c)

**Comment by Jaiieq** [comment]
Forgot the code sample!

```blade
<flux:field>
     <flux:input.group>
          <flux:input.group.prefix>$</flux:input.group.prefix>
               <flux:input wire:model='funding' type="text" placeholder="Automatically Calculated" invalid> 
          </flux:input>
     </flux:input.group>
     <flux:error name="funding" />
</flux:field>
```

**Comment by Jaiieq** [comment]
Forgot to add code!  Here is a simple code example of the above screenshot:

```blade
<flux:field>
    <flux:input.group>
        <flux:input.group.prefix>$</flux:input.group.prefix>
        <flux:input type="text" invalid />
        </flux:input>
    </flux:input.group>
    <flux:error name="funding" />
</flux:field>
```

**Comment by calebporzio** [comment]
Good catch, I added some code to account for invalid states on inputs and show the full borders when that happens. Thanks!

![Image](https://github.com/user-attachments/assets/52452b13-c07b-47d3-8a79-cc8226d51b23)
