### ISSUE TITLE
Searchable select closes itself when wired to a property

### ISSUE THREAD

**Issue by squaredpx** [livewire/flux#424]
Hi 👋!!

I think I've hit a bug in the latest flux version (v1.0.10). Using the `searchable select` component with the `flux:select.search` wired to a Livewire property causes the select to close itself as soon as the property is updated and the search property is reset. It worked fine in v1.0.9

```blade
<flux:select variant="listbox" searchable placeholder="Choose industries...">
    <x-slot name="search">
        <flux:select.search placeholder="Search..." wire:model.live="search"/>
    </x-slot>

    <flux:option>Photography</flux:option>
    <flux:option>Design services</flux:option>
    <flux:option>Web development</flux:option>
    <flux:option>Accounting</flux:option>
    <flux:option>Legal services</flux:option>
    <flux:option>Consulting</flux:option>
    <flux:option>Other</flux:option>
</flux:select>
``` 

This code block is the searchable select component from the Flux docs with just the `wire:model.live="search"`  added to the `flux:select.search` component. Using this code inside a Livewire component triggers this issue.

![Image](https://github.com/user-attachments/assets/d4b383dd-f96b-4d56-9662-a19d815a8553)

**Comment by ju5t** [comment]
You should add `wire:model` to `<flux:select>`. I'm surprised this worked before.

**Comment by squaredpx** [comment]
> You should add `wire:model` to `<flux:select>`. I'm surprised this worked before.

But it's not the same... Ok, the code example was a simplification and it does not matter if I wire the property to the select, but in the real example where I found the issue, the select options are generated dynamically, the `<flux:select>` has the `:filter="false"` property and I need to wire the property to the search field so I can intercept the search value and generate the options dynamically from the results of an API call. If I wire the property to the select component I can not intercept the searched string, I only get the selected value once it's selected... unless I'm missing something.

**Comment by squaredpx** [comment]
I think #428 is the exact same problem

**Comment by ju5t** [comment]
@squaredpx got it, the example didn't have `:filter` so I thought you were using it as a normal listbox.

**Comment by calebporzio** [comment]
Ah I see what the break was. I have it fixed - I'll tag ASAP because it's a pressing issue. Thanks!

**Comment by calebporzio** [comment]
Just tagged: v1.0.11
