### ISSUE TITLE
Custom select component with dynamic options and :filter="false" closes prematurely after v1.0.10 update

### ISSUE THREAD

**Issue by lordisp** [livewire/flux#428]
I encountered an issue with the custom select component after updating from `v1.0.9` to `v1.0.10`. Specifically, the component is not functioning as expected when `:filter="false"` is used, and a dynamic search is performed.

**Expected Behavior (v1.0.9):**
In v1.0.9, when text is entered into the search field, an event is triggered to search (e.g., wire:model.live.debounce.1000ms="search"), and shortly after, the results are populated into the dropdown list. The dropdown remains open while the user interacts with the search field and results.

**Current Behavior (v1.0.10):**
After upgrading to v1.0.10, the dropdown list closes immediately after entering text in the search field, making it impossible for users to select an option from the dynamically populated list.

**Steps to Reproduce:**

1. Use a custom select component with dynamic options and set :filter="false".
2. Enter text into the search field.
3. Observe that the dropdown closes automatically in v1.0.10.

```blade
<flux:select :filter="false" variant="listbox" searchable>
    <x-slot name="search">
        <flux:select.search wire:model.live.debounce.500ms="search" placeholder="Search..." class="border-0">
            <x-slot:icon>
                <flux:icon.magnifying-glass wire:loading.class="hidden" class="size-4"/>
                <flux:icon.loading wire:loading.class.remove="hidden" class="hidden size-4"/>
            </x-slot>
        </flux:select.search>
    </x-slot>
    @foreach ($users as $user)
        <flux:option wire:key="{{ $user['id'] }}" value="{{ $user['id'] }}">
            <div class="flex flex-col justify-start overflow-hidden">
                <div class="whitespace-nowrap">{{ $user['displayName'] }}</div>
                <div class="whitespace-nowrap text-xs" class="text-sm">{{ $user['userPrincipalName'] }}</div>
            </div>
        </flux:option>
    @endforeach
</flux:select>

```

I’ve attached two screen recordings demonstrating the behavior:
- [v1.0.9 - Working as expected](https://github.com/user-attachments/assets/9e42a119-b37b-4945-b634-ab1d36f6f78c)
- [v1.0.10 - Dropdown closing after text input](https://github.com/user-attachments/assets/bccddda3-a156-4af1-af61-530a04e66a36)

**Comment by icundin** [comment]
Same issue here after updating to v1.0.10

**Comment by KenGuggelmeyer** [comment]
Likewise

**Comment by calebporzio** [comment]
Fixed it and will tag a new release immediately, thank you. ref #424

**Comment by calebporzio** [comment]
Just tagged: v1.0.11

**Comment by lordisp** [comment]
@calebporzio the issue is still present in v1.0.14
