### ISSUE TITLE
Allow to set radio button as untabbable

### ISSUE THREAD

**Issue by slovenianGooner** [livewire/flux#431]
Hi there! 👋

Is there a way to set a radio button as untabbable? I've source-dived the `radio.js` code and it seems it could work by setting the `tabindex="-1"` on the `<ui-radio>` element, but sadly it doesn't work.

I've tried modifying the blade file `radio/index.blade.php` by adding the attribute, but to no effect. The `tabindex` is always set to `0`.

```php
<ui-radio {{ $attributes->class($classes) }} data-flux-control data-flux-radio tabindex="-1">
        <div class="hidden size-2 rounded-full bg-white dark:bg-zinc-800"></div>
</ui-radio>
```

By reading these lines of code in `radio.js` I would assume that if `tabindex` is already set, it would default to what is set.

```js
if (! this.el.hasAttribute('tabindex')) {
            this.options().tabbable ? this.tabbable() : this.untabbable()
}
```

The practical application of the problem is in the below video. I focus on inputs then when focusing on the radio button it automatically changes the value for me because I have set `wire:model.live` on the radio group.

https://github.com/user-attachments/assets/e4597b40-18fa-4aac-ab47-bdb02fd12a13

The expected syntax would be the following:

```php
<flux:radio value="standard" class="[&[data-checked]>div]:!hidden !size-3" tabindex="-1"/>
```

Thanks for the response.

**Comment by calebporzio** [comment]
Hi there, I think I tried to recreate this locally when you posted on twitter. Can you do two things for me:

* Provide a copy/pastable Volt component (or just enough Blade) to reproduce
* Upgrade flux to v1.0.11 to make sure this isn't something we already fixed

Thanks!

**Comment by slovenianGooner** [comment]
Hey,

here's a Volt component that reproduces the issue. Actually, the problem only occurs when the wire:model.live is on two different radio groups covering the same property.

```php
<?php

new class extends \Livewire\Volt\Component {
    public string $prop = '';
    public string $state = 'one';

    public function updatedState()
    {
        dump($this->state);
    }
}

?>
<div>
    <div class="space-y-6">
        <flux:input wire:model="prop" label="Sample input" autofocus />

        <flux:radio.group wire:model.live="state">
            <flux:radio value="one" label="One" />
        </flux:radio.group>

        <flux:radio.group wire:model.live="state">
            <flux:radio value="two" label="Two" />
        </flux:radio.group>
    </div>
</div>
```

I do it this way, because in previous example, the each radio group is in it's own `<flux:cell>`.

```html
<flux:cell>
     <flux:radio.group wire:model.live="marketState">
                    <flux:radio value="standard" class="[&[data-checked]>div]:!hidden !size-3" tabindex="-1"/>
                </flux:radio.group>
</flux:cell>
<flux:cell>
     <flux:radio.group wire:model.live="marketState">
                    <flux:radio value="option" class="[&[data-checked]>div]:!hidden !size-3" tabindex="-1"/>
                </flux:radio.group>
</flux:cell>
```

I may be doing it wrong, so the tabbable thing is not really an issue. :)

**Comment by calebporzio** [comment]
Ah I see, the reason this is happening, is that it's standard behavior for a radio group to select the first item if it has no selection and is being tabbed into.

I see that you want to separate them between table cells, but if you want to do that, maybe reach for something else? I'm not really sure how we could support this without breaking expected behavior.

Hope you find a solution, and sorry I can't be more of a helpl.

**Comment by slovenianGooner** [comment]
OK, solved it - don't know if it's a flux thing, or a Livewire thing, god knows. Anyways, the Livewire component that had the table was lazy loaded. Once I removed that it works as it should. Just spent the past hour trying to find what's wrong.

Could it be something with loading the JS? Not sure.

Anyhow, consider this solved, but just as info as to what the problem actually was.

Thanks!
