### ISSUE TITLE
Radio button loses focus when live

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#438]
The radio button is losing focus when using `wire:model.live`. It happens after you switch the selected radio button with your arrow keys. It's a bit difficult to show in a screenshot unfortunately.

```blade
<?php

use function Livewire\Volt\{state};

state(['payment' => 'paypal']);

?>

<div>
    <flux:radio.group wire:model.live="payment" label="Select your payment method">
        <flux:radio value="cc" label="Credit Card" checked />
        <flux:radio value="paypal" label="Paypal" />
        <flux:radio value="ach" label="Bank transfer" />
    </flux:radio.group>
</div>
```

**Comment by calebporzio** [comment]
This is really odd - I couldn't figure out the true underlying cause - but I added a patch in the Blade that fixes it. Hopefully at some point we can figure out why the `tabindex` attribute is getting wiped out by Livewire requests, but for now,  this fixes the problem.
