### ISSUE TITLE
Suggestion: Easily configurable color variants

### ISSUE THREAD

**Issue by ttrushin** [livewire/flux#44]
The Tailwind `zinc` color seems to be used as the "primary" color throughout the entire project. Ideally we wouldn't have to publish every single component just to change the primary color. 

It would be nice if a custom color name like `primary` were used throughout Flux instead of zinc, and instructions were added to the docs to add a custom color called "primary" to the Tailwind config (which devs already have to modify), which one could just default to `colors.zinc` if desired, or change at will.

**Comment by challgren** [comment]
You could override the class with !border-indigo-200, that's what I've been doing but it's a pain

**Comment by ttrushin** [comment]
@challgren Definitely possible, however some of the components use extremely custom things like calculated shadows in the button component. It would be quite painful to override everything. 
```blade
->add(match ($variant) { // Shadows...
        'primary' => 'shadow-[inset_0px_1px_theme(colors.zinc.900),inset_0px_2px_theme(colors.white/.15)] dark:shadow-none',
    })
``` 

@troccoli Yep, I thought about that, but for the reasons you stated that becomes undesirable pretty fast.

**Comment by ttrushin** [comment]
@calebporzio This feels like a perfect tweak to make to this component library to allow for a beautiful customization experience without requiring users to publish and carefully tweak every single component that has variants.

**Comment by calebporzio** [comment]
I understand many people want this. I think my answer for right now is going to be either publish all the views, or rather tweak your tailwind config to use a different color palette instead of `zinc`. 

I'm not saying "no", just "no right now" if that makes sense. Thanks!

**Comment by cbaconnier** [comment]
@calebporzio Could it be easier to add a variant like `branding` that uses a branding color we can tweak in tailwind config?
It's not much, but with that we can already have a quick touch of colors for the buttons, navbar items, ...

Chaning `zinc`in tailwindcss is probably not what we want when we need at touch of blue for the color identity. 😆 

![Image](https://github.com/user-attachments/assets/4903c8b4-ecb2-4d12-9f31-d4e715533c66)


By simply adding a branding variant, it's not perfect, but it does the work pretty well IMO.
```
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                branding: {
                    100: '#E3F8FF',
                    200: '#B3ECFF',
                    300: '#81DEFD',
                    400: '#5ED0FA',
                    500: '#40C3F7',
                    600: '#2BB0ED',
                    700: '#1992D4',
                    800: '#127FBF',
                    900: '#0B69A3',
                },
            },
        },
    },

```
![Image](https://github.com/user-attachments/assets/9cecb1cd-4443-46d9-bb08-5548a566a1cd)
![Image](https://github.com/user-attachments/assets/22423c46-02ef-48de-af49-e83ff40a78df)
