### ISSUE TITLE
flux:brand breaks WCAG 2.1 "Non-text Content (Level A)" Criterion #378 - Still persists after release 1.0.10.

### ISSUE THREAD

**Issue by lonebadger99** [livewire/flux#440]
Previously closed issue is still not resolved. Maybe the issue was wrongly closed or the code not included in the release?

[https://github.com/livewire/flux/issues/378](https://github.com/livewire/flux/issues/378)

**Comment by joshhanley** [comment]
@lonebadger99 this was fixed after 1.0.10 was released, so this will be in the next release. So going to close this for now.

**Comment by joshhanley** [comment]
@lonebadger99 Nah we close them once we fix them. Otherwise it's hard to keep track of issues we have/ haven't fixed (regardless of if they have been tagged or not).

Sweet thanks!
