### ISSUE TITLE
Tooltip content (slot) is hidden if tooltip is empty

### ISSUE THREAD

**Issue by LasseRafn** [livewire/flux#443]
Hi there! 👋

Sorry you hit a problem with Flux.

This will display blank/nothing, because `content` is empty:

```
<flux:tooltip content="">
    <flux:button icon="cog-6-tooth" icon-variant="outline" />
</flux:tooltip>
```

I don't know if it qualifies as a bug, or perhaps just needs to be documented. It broke our prod as we conditionally add tooltip text like so:

```
<flux:tooltip :content="is_draft ? 'Book' : ''">
    <flux:button icon="cog-6-tooth" icon-variant="outline" />
</flux:tooltip>
```

which, when `is_draft = false` would hide the button entirely.

**Comment by jeffchown** [comment]
@LasseRafn I had something strange(r) happen when I tried your code.

My button did show up, even with `content=""` for the wrapping `flux:tooltip` **but** when I hovered over the button, it 'jumped' around the page.

https://github.com/user-attachments/assets/9cdecca6-5f8b-463d-b23a-5a7c51d668d4

**Comment by jeffchown** [comment]
@LasseRafn When I refactor your code to: `<flux:button icon="cog-6-tooth" icon-variant="outline" tooltip="" />` it works as expected either with a non-blank or blank tooltip.

Hopefully that works for your use-case.

**Comment by calebporzio** [comment]
Ok, so there were a couple broken things. Now, if you set content to an empty string (`content=""`), it will display the tooltip, but just empty. if it's missing or null, the tooltip won't be rendered at all, but the button will. Hope this does it, thanks!

**Comment by jeffchown** [comment]
Thanks, @calebporzio !
