### ISSUE TITLE
yoyoyo in pagination

### ISSUE THREAD

**Issue by jcerdan** [livewire/flux#449]
Hi,

in last release 1.0.11
there's a "yoyoyo" in 

```livewire/flux-pro/stubs/resources/views/flux/pagination.blade.php```

line 50.

Let's change it for a "Wazaaaa" ;-)

**Comment by helderneves91** [comment]
Oh dear...
![Image](https://github.com/user-attachments/assets/0050f94c-1881-4734-abf0-74f40473d22c)

**Comment by azizabbas** [comment]
Yeah I was about to report this bug. Here are screenshots to help:

![Image](https://github.com/user-attachments/assets/aac864d7-ca60-4739-9b0f-1e3e9bcdd0bd)

![Image](https://github.com/user-attachments/assets/daababfc-a538-4d4a-969e-68d515b1d9a7)

**Comment by calebporzio** [comment]
Oh damn, that is NOT good - c'mon Caleb. Just emergency tagged v1.0.12 - sorry for the slop, usually I'm more careful than that.

**Comment by azizabbas** [comment]
Thanks for quick fix but pagination styles seems broken:

![Image](https://github.com/user-attachments/assets/ba400070-9240-494c-b63b-31468e307164)
