### ISSUE TITLE
Pagination Style seems broken after recent update

### ISSUE THREAD

**Issue by azizabbas** [livewire/flux#451]
Hi,

It seems like pagination style is broken:

![Image](https://github.com/user-attachments/assets/52fbf018-e41e-4a04-82ad-e54fd2945fa6)

This was showing like this since **yoyoyo** glitch, that glitch is fixed though but pagination style still looks like this.

Thanks

**Comment by calebporzio** [comment]
Dangit, fixed and tagged - thanks for letting me know
