### ISSUE TITLE
accordion.heading's `<span>` makes `w-full` usage of headings impossible

### ISSUE THREAD

**Issue by jeffchown** [livewire/flux#454]
This is more of a (hopefully very simple) wish list item to enable access to the full width of an `accordion.heading`

I have a need to create a heading with a right-justified `completed_at` in an `accordion.heading`, e.g.:

```
<flux:card>
    <flux:accordion>
        <flux:accordion.item transition>
            <flux:accordion.heading>
                <div class="!w-full flex items-center justify-between mx-2">
                    <div>
                        Perform Initial Interview
                    </div>

                    <div>
                        Completed on 2024-10-17 @ 12:30pm
                    </div>
                </div>
            </flux:accordion.heading>

            <flux:accordion.content>
                Interview notes...
            </flux:accordion.content>
        </flux:accordion.item>
    </flux:accordion>
</flux:card>
```

which displays like this:

![Image](https://github.com/user-attachments/assets/3216108e-8ae5-405a-8485-85572e444f25)

Based on my code I would expect it to display like this:

![Image](https://github.com/user-attachments/assets/d06c6563-c189-4c98-9120-2a7853fd37f1)

If I publish the accordion component and change the `<span>` in the `accordion.heading` Blade file from:

`<span>{{ $slot }}</span>`

to 

`<span class="flex-1">{{ $slot }}</span>`

all works as expected.

As I'd like not to have to republish the `accordion` component after each Flux update, I was wondering if the above change could be added as a default to give us access to the entire `accordion.heading`'s width.

Thanks!

**Comment by calebporzio** [comment]
Totally makes sense - done.

**Comment by jeffchown** [comment]
Great!  Thanks, @calebporzio 👍
