### ISSUE TITLE
Checkbox and switch state loss

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#455]
Livewire does not get any state information from the checkbox and switch component. The `updates` list/array stays empty in an XHR request. 

This error appeared since v1.0.11. v1.0.10 does not have this issue.

```blade
<?php

use function Livewire\Volt\{state};

state(['checked' => false]);

?>

<div>
    <flux:checkbox wire:model.live="checked" />
    <div>@json($checked)</div>
</div>
```

**Comment by danielrona** [comment]
@ju5t update to livewire 3.5.12 will fix this see https://github.com/livewire/flux/pulls

**Comment by ju5t** [comment]
@danielrona thanks!
