### ISSUE TITLE
Tooltip on Table Row

### ISSUE THREAD

**Issue by mschuyler** [livewire/flux#458]
Tooltip doesn't work on a table row. Below is a contrived example for testing.

```
    <flux:table>
        <flux:columns>
            <flux:column>Data</flux:column>
        </flux:columns>
        <flux:rows>
            <flux:tooltip content="Tooltip Content">
                <flux:row>
                    <flux:cell>Data</flux:cell>
                </flux:row>
            </flux:tooltip>
        </flux:rows>
    </flux:table>
```

Wasn't sure if I should put it in as a discussion but this seems more like a bug than feature. Would expect the tooltip to be centered on the row on hover.

Using 1.0.14. Recompiled assets, cleared cache, etc.

**Comment by joshhanley** [comment]
@mschuyler the reason is adding a tooltip element in the middle of a table means the html table is invalid. As `tbody` (flux:rows) should only contain rows.

Try this instead:

```blade
<flux:table>
    <flux:columns>
        <flux:column>Data</flux:column>
    </flux:columns>
    <flux:rows>
        <flux:row>
            <flux:cell>
                <flux:tooltip content="Tooltip Content">
                    <p>Data</p>
                </flux:tooltip>
            </flux:cell>
        </flux:row>
    </flux:rows>
</flux:table>
```
