### ISSUE TITLE
Select not working inside a modal with variant set

### ISSUE THREAD

**Issue by ryanpilbeam** [livewire/flux#46]
Using the select inside a modal doesn't render the options.

It looks like the variant set on the modal leaks into the option.blade.php component and attempts to render a custom `<ui-option>` tag inside of a `<select>`

**Comment by joshhanley** [comment]
@ryanpilbeam thanks for reporting! Could you please share some code so we can easily replicate the issue? Thanks!

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
