### ISSUE TITLE
Flux styles problem

### ISSUE THREAD

**Issue by soyCristianRico** [livewire/flux#461]
Hello, I’m having issues using Flux on my website [rukaudit.com](http://rukaudit.com/).

To provide some context, I should mention that I’m using Larafast, which incorporates DaisyUI, and then I installed Flux manually. Right now, I’m using both tools while waiting for some of the more basic components from DaisyUI to be added.

The problem:

1. The styles don’t look right locally.

I used the accordion for the FAQs, and the text was white. On a white background, it was barely visible. I had to fix this by adding a span in the extended version of the accordion to change the color of the heading and subheading.

2. The toast has a dark color, instead of the light color from the Docs.

3. During deployment, I had to install Flux via SSH because it required authentication.

I’m not sure if this is the ideal behavior.

4. The design breaks in production.

After deployment, the accordions sometimes don’t display correctly in production.

I’m using Laravel Forge. After running npm run build, there are times when the accordions don’t have the correct style – they break in a very ugly way, making them unreadable.

I have to access via SSH and run npm run build again to fix it – which is quite strange.

I’m using Laravel Forge for deployment, and I’ve already included npm run build in my deployment script.

```
cd /home/forge/rukaudit.com

git fetch --all
git reset --hard origin/$FORGE_SITE_BRANCH
$FORGE_COMPOSER install --no-dev --no-interaction --prefer-dist --optimize-autoloader

( flock -w 10 9 || exit 1
    echo 'Restarting FPM...'; sudo -S service $FORGE_PHP_FPM reload ) 9>/tmp/fpmlock

if [ -f artisan ]; then
    $FORGE_PHP artisan migrate --force
fi

php artisan cache:clear
php artisan generate:sitemap

npm install
npm run build
```

I also added @fluxScripts in the body and @fluxStyles in the head.

Here’s my accordion code for reference:

```
<flux:accordion.item>
                                                <flux:accordion.heading>
                                                    <span class="text-gray-950 text-base">
                                                        {{ __('home.faqs.faq_5.heading') }}
                                                    </span>
                                                </flux:accordion.heading>

                                                <flux:accordion.content>
                                                    <span class="text-gray-600 text-base">
                                                        {!! __('home.faqs.faq_5.subheading') !!}
                                                    </span>
                                                </flux:accordion.content>
                                            </flux:accordion.item>
```

![Image](https://github.com/user-attachments/assets/5ef92de1-1f7c-494b-9a7c-bcca98d41e4f)

Additionally, I’ve attached a few images – two after deployment and two after manually running npm run build on the server.

![Image](https://github.com/user-attachments/assets/dbd71d42-5ce3-4898-9234-27fafd9bbe24)
![Image](https://github.com/user-attachments/assets/62941f66-94bf-4647-82e1-760ec7f66067)
![Image](https://github.com/user-attachments/assets/0d5981a0-8d32-406d-8b2a-9970f27fa9bd)
![Image](https://github.com/user-attachments/assets/1c968eb0-052f-4f23-8273-401c3e10cefa)

One thought:
Could this be a dark mode issue? DaisyUI uses light mode by default, while Flux switches to dark mode. However, the accordion issue – which is not color-related – doesn’t seem to be tied to dark mode.

I’d really appreciate any help in resolving these issues!

Thanks!

**Comment by ju5t** [comment]
I wouldn't combine two UI frameworks in the same site. There's a chance they have different ideas which can cause conflicts. For example, you can't use Tailwind's Form plugin either because it has different defaults.

If you're missing things in Flux I'd probably wait with its implementation before going live. 

For clarity, it's probably better to raise individual issues instead of 4 in one go.

**Comment by lotje-kinable** [comment]
Hi @soyCristianRico for authentication with Laravel Forge see [https://fluxui.dev/docs/installation](url) 'Activating using Laravel Forge' and for tailwind dark mode, it must be set to 'selector' (see the docs 'Using dark mode'). Maybe setting it to 'selector' will solve some of the darkMode issues.

**Comment by karakhanyans** [comment]
> Hi [@soyCristianRico](https://github.com/soyCristianRico) for authentication with Laravel Forge see [https://fluxui.dev/docs/installation](url) 'Activating using Laravel Forge' and for tailwind dark mode, it must be set to 'selector' (see the docs 'Using dark mode'). Maybe setting it to 'selector' will solve some of the darkMode issues.

@soyCristianRico Serg here from Larafast.

This is must, to be able to get the flux-pro version, make sure you have it for production. 

DaisyUI should not interfere Flux's styles, they both use TailwindCSS, but in case you want your flux components (buttons for example) use DaisyUI, you need to modify the flux:button component. 

Feel free to reach me out via email to discuss this further on Larafast + Flux case.

**Comment by ju5t** [comment]
@karakhanyans Tailwind Form's uses Tailwind too, but it still breaks Flux in some aspects. It's not unlikely other UI frameworks do as well. I don't think it's a given that any UI framework is or should be compatible with Flux.

> I used the accordion for the FAQs, and the text was white. On a white background, it was barely visible. I had to fix this by adding a span in the extended version of the accordion to change the color of the heading and subheading.

This seems to be fine on a fresh install with Flux + Daisy UI. I haven't used any of the Daisy components in that test though.

I think @lotje-kinable answered all other questions.

**Comment by soyCristianRico** [comment]
Awesome, thanks everyone for your responses, and sorry for not opening four separate tickets. This is my second time using GitHub Issues, so I’m not very familiar with it yet.

I’ll try uninstalling DaisyUI and also take a look at the Forge tutorial. Can’t believe I didn’t notice it was already published!

I’ll post an update here soon.

Best regards!
