### ISSUE TITLE
Modal backgroud scolling with open Dropdown, Autocomplete, Select* inside Modal

### ISSUE THREAD

**Issue by marcheffels** [livewire/flux#463]
Hi there! 👋

The open content scrolling with the Background if a Dropdown, Autocomplete or Select with variant listbox or combobox inside an Modal.

```
<flux:modal name="test-modal" class="md:w-96">
    <flux:autocomplete wire:model="state" label="Autocomplete">
        <flux:autocomplete.item>Alabama</flux:autocomplete.item>
        <flux:autocomplete.item>Arkansas</flux:autocomplete.item>
        <flux:autocomplete.item>California</flux:autocomplete.item>
    </flux:autocomplete>
</flux:modal>
```

![Image](https://github.com/user-attachments/assets/8bb1984e-d44a-4207-8db9-849d8dfa45a9) ![Image](https://github.com/user-attachments/assets/0f9a265a-e890-414b-bc83-f5ac5a62112f)

Thanks!

**Comment by jeffchown** [comment]
@marcheffels This is a know issue and I believe related to https://github.com/livewire/flux/issues/110
