### ISSUE TITLE
Vertical spacing not working properly

### ISSUE THREAD

**Issue by sandervanhooft** [livewire/flux#464]
Hi,

While tinkering with Flux I ran into the following.

I've wired up a fresh Laravel app and installed Flux last Tuesday, using Jetstream & Livewire.

Did I understand correctly from your/Caleb's conference talk that Flux takes care of the vertical spacing between input fields and other components?

Somehow it looks like this here with the default styling:

![Image](https://github.com/user-attachments/assets/0c4cfc7f-f340-4876-9f95-ef2205b59f5d)

I.e. notice how close the input label is to the previous input element above.

I've tried:
- reinstalling, npm rebuilds etc.
- swapping order of imports (@livewireStyles, @fluxStyles)
- using container elements like flux:page as it was in the conference talk, but that seems unavailable.
- rebuilding without tailwind forms

Here's a gist with all related files to reproduce the issue: https://gist.github.com/sandervanhooft/6a728eb94325e876c89d95fe827df8d3

**Comment by sandervanhooft** [comment]
I noticed in the Flux UI docs source code that a grid is used to deal the spacing, which solves the problem.

```html
<div class="grid gap-6">

... inputs go here                    

</div>
```

I am just not sure: is this the intended way? If so, it would make sense to clearly state this in the docs somewhere.

**Comment by sandervanhooft** [comment]
Alternatively, something like a flux:fieldset component may be helpful

**Comment by joshhanley** [comment]
@sandervanhooft I don't think Flux is meant to take care of vertical spacing as that can be app specific. See this for more details https://x.com/calebporzio/status/1837495368843436266?s=46&t=Vs1iQlf0Plw2mIIzmbA7iQ

**Comment by sandervanhooft** [comment]
Thanks @joshhanley.  Makes sense. I think I got confused a bit by the online talk, showing differences in vertical spacing on mobile vs desktop.

**Comment by joshhanley** [comment]
@sandervanhooft Ah no worries. I'm going to reopen this for now so Caleb can see it.

@calebporzio do you think it's worth adding the spacing philosophies from that tweet to the Flux docs?

**Comment by sandervanhooft** [comment]
I also discussed this in the team here. We think it makes sense to state this reasoning clearly on the principles page.

**Comment by sandervanhooft** [comment]
Especially that grid spacing technique is super helpful

**Comment by calebporzio** [comment]
Good call @sandervanhooft. I added a new section that will be up in the next couple days.

![Image](https://github.com/user-attachments/assets/d77a1a25-e027-451b-a367-75d16b582e60)

**Comment by sandervanhooft** [comment]
Awesome! And loving the support vibes here!
