### ISSUE TITLE
v1.0.14: a select inside a button group is no longer full width

### ISSUE THREAD

**Issue by lotje-kinable** [livewire/flux#465]
Hi

After upgrading to v1.0.14 a select inside a button group is no longer full width. I tried w-full but I can't get it to go back to full size.

Note: changing/removing searchable, :filter="false" had no effect. 

![Image](https://github.com/user-attachments/assets/51d11ab9-c5b7-4f33-a6d9-2624c30d1d70)
![Image](https://github.com/user-attachments/assets/647c0de3-664f-4ac2-80a9-45cb531059b1)

### Volt component

```
<?php
use Livewire\Attributes\{Title};
use Livewire\Volt\Component;

new

#[Title('Playground')]

class extends Component {

    public $selectedOptionId;

    public $options;

    public $query = '';

    public function mount()
    {

    $this->options = collect([
            (object)['id' => 1, 'name' => 'foo'],
            (object)['id' => 2, 'name' => 'bar'],
            (object)['id' => 3, 'name' => 'baz'],
        ]);
    }

    public function search()
    {

        $searchTerms = explode(' ', $this->query);
        $this->options = $this->options->filter(function ($item) use ($searchTerms) {
            return collect($searchTerms)->contains(function ($term) use ($item) {
                return stripos($item->name, $term) !== false;
            });
        });

    }

    public function clear()
    {
        $this->selectedOptionId = null;
        $this->query = '';
    }


    public function submit()
    {
        $this->selectedOptionId = null;
        $this->query = '';
    }

}; ?>

<div>

    <flux:modal.trigger name="edit-profile">
        <flux:button>Open test modal with search</flux:button>
    </flux:modal.trigger>

    <flux:modal name="edit-profile" class="space-y-6 md:w-96">
        <div>
            <flux:heading size="lg">Update profile</flux:heading>
            <flux:subheading>Make changes to your personal details.</flux:subheading>
        </div>

        <div class="mt-3 space-x-0 space-y-3 lg:space-y-3 lg:space-x-0 lg:mt-0">

            <flux:label class="mb-3 text-sm font-medium select-none text-zinc-800 dark:text-white">Options</flux:label>

            <flux:button.group>

                <flux:select
                    variant="listbox"
                    searchable
                    placeholder="Zoeken"
                    wire:model.live="selectedOptionId"
                    :filter="false"
                >
                    <x-slot name="search">
                        <flux:select.search placeholder="Zoeken" wire:model="query" wire:keyup="search" />
                    </x-slot>
                    @foreach($options as $option)
                        <flux:option wire:key='option-{{ $option->id }}' value="{{ $option->id }}"> {{ $option->name }}</flux:option>
                    @endforeach

                    @if(empty($query))
                    <flux:option disabled value="">...</flux:option>
                    @endif
                </flux:select>

                <flux:button wire:click="clear" tooltip="Clear selection" icon="x-mark"></flux:button>

            </flux:button.group>

        </div>

        <div class="flex">
            <flux:spacer />

            <flux:button type="submit" variant="primary">Save changes</flux:button>
        </div>
    </flux:modal>

</div>


```

Thanks Caleb and team!!

**Comment by ju5t** [comment]
@lotje-kinable I've just tested this but can't replicate it on a fresh install. Did you run `npm run build` after updating?

**Comment by lotje-kinable** [comment]
@ju5t Thanks, I did, and I just did it again, but nothing changed. But to be honest I'm also having a weird thing with a stashable, sticky sidebar see the second part of issue:  [#403 ](https://github.com/livewire/flux/issues/403) When on mobile screen, the sidebar opens after click but everything is disabled/grayed out, not just the background. 

I can't just do a fresh install, because I implementing it in a project I've been working on for over 2 year which I have been upgrading to Laravel 10 (latest version) and Livewire 3 (latest version).

**Comment by jeffchown** [comment]
@lotje-kinable Do you have [tailwind/forms](https://github.com/tailwindlabs/tailwindcss-forms) installed? (I had to remove it to solve some of my Flux issues)

Also, did you delete/re-publish and published Flux components after upgrading?

Lastly, have you cleared the view cache via `php artisan view:clear`

**Comment by lotje-kinable** [comment]
@jeffchown 
Yes, I removed tailwind/forms (Breeze forms are not styled anymore, so it is definitely uninstalled) two versions ago. 
I did a composer update and a npm run build and then a dev
I have not published any components
and I did a php artisan optimise:clear (which includes a view:clear)

**Comment by patrykszady** [comment]
Same here.

**Comment by ju5t** [comment]
Maybe it's browser/OS related? I just tested on MacOS with Chrome, Safari and Firefox and haven't been able to replicate but I wouldn't know what could cause it otherwise.

**Comment by jeffchown** [comment]
@lotje-kinable I just tested your initial Volt component and have the same issue.  It looks like the `flux:select` is behanving like it is `w-auto` as it shrinks when I choose an option.

(A clean Flux test app, with all of the latest version of Livewire and Flux v1.0.14)

**Comment by lotje-kinable** [comment]
@jeffchown I am happy that other people can actually replicate this (because I've had some weird issues, like with the sidebar), thanks for looking into it! 

For now, a div with w-full on it, around the select, makes it visually ok and it's usuable. Also added a  {{-- todo: remove div w-full from select --}}. 


```
    <div class="mt-3 space-x-0 space-y-3 lg:space-y-3 lg:space-x-0 lg:mt-0">

            <flux:label class="mb-3 text-sm font-medium select-none text-zinc-800 dark:text-white">Options</flux:label>

            <flux:button.group>


                <div class="w-full">
                     {{-- todo: remove div w-full from select --}}

                    <flux:select
                        variant="listbox"
                        placeholder="Zoeken"
                        wire:model.live="selectedOptionId"
                        {{-- :filter="false" --}}
                    >
                        <x-slot name="search">
                            <flux:select.search placeholder="Zoeken" wire:model="query" wire:keyup="search" />
                        </x-slot>
                        @foreach($options as $option)
                            <flux:option wire:key='option-{{ $option->id }}' value="{{ $option->id }}"> {{ $option->name }}</flux:option>
                        @endforeach

                        @if(empty($query))
                        <flux:option disabled value="">...</flux:option>
                        @endif
                    </flux:select>

                </div>

                <flux:button wire:click="clear" tooltip="Clear selection" icon="x-mark"></flux:button>

            </flux:button.group>

        </div>
```

thanks again!

**Comment by jeffchown** [comment]
That makes perfect sense @lotje-kinable - the `select` with `variant="listbox"` expands into multiple blocks (`<div>`s, etc.) so you'd need to wrap the whole thing to create a `w-full` 'mini-container' for the select.

```

```
