### ISSUE TITLE
Docs: Missing 'subtle' in Button variants list

### ISSUE THREAD

**Issue by matthewpaulking** [livewire/flux#466]
I was digging into the Flux docs and noticed a minor thing on the Button page: The 'subtle' button variant isn't as well-documented as it probably should be. It's in an example in the 'Icons' section, but not explicitly mentioned in the 'Variants' section.

![Image](https://github.com/user-attachments/assets/d90d8770-3e1d-4b4f-b194-ff889851cf43)

**Comment by calebporzio** [comment]
Good catch. My thinking at the time was: the only reason I added "subtle" was for icon buttons, so maybe discourage wider use by only including it contextually. But I realize this just burying helpful info.

This will be live in the next couple days:

![Image](https://github.com/user-attachments/assets/fe39a47e-be97-4cae-9989-7a504560cff4)
