### ISSUE TITLE
Checkbox wire:model not working

### ISSUE THREAD

**Issue by fabioserembe** [livewire/flux#467]
Hi there! 👋

The checkbox seems not working as expected.

### To reproduce the issue:
In Livewire component I have
`public $terms = false;`
and the validation
`'terms' => 'accepted'`

In blade comonent I have
`<flux:checkbox wire:model.live="terms"/>`

When I check the checkbox, the `$terms` remaining `false`.

Can anyone help me?
Thank you!

**Comment by jeffchown** [comment]
@fabioserembe Your example works as expected in my Flux test app.

Aside from echoing `{{ $terms }}` in my app, I decided to test https://github.com/wire-elements/wire-spy to check the `$terms` value.

**Comment by CodeAn** [comment]
Same issue here. Using flux 1.0.14. Even when copying the exact code from the doc, including checkbox group. Worked fine before I updated today.

**Comment by jeffchown** [comment]
@CodeAn The examples from the docs won't trigger a Livewire update without either a `submit` action or by changing `wire:model` to `wire:model.live`, so, the value will remain `false` until then.  Try:

```
<flux:checkbox wire:model.live="terms" label="I agree to the terms and conditions" />
```

**Comment by CodeAn** [comment]
> [@CodeAn](https://github.com/CodeAn) The examples from the docs won't trigger a Livewire update without either a `<form wire:submit.prevent="save">` (or something similar) or by changing `wire:model` to `wire:model.live`, so, the value will remain `false` until then. Try:
> 
> ```
> <flux:checkbox wire:model.live="terms" label="I agree to the terms and conditions" />
> ```

Apologies, I'll be a bit more precise.

blade file:
`<div class="lg:col-span-12">
    <x-page.header title="Test" />
    <form wire:submit="updateConfigurations" class="space-y-6 max-w-lg px-6">
        <flux:tab.group class="">
            <flux:tabs>
                <flux:tab name="organizations">{{ __('Customers') }}</flux:tab>
                <flux:tab name="assignments">{{ __('Assignments') }}</flux:tab>
                <flux:tab name="billing">Billing</flux:tab>
            </flux:tabs>

            <flux:tab.panel name="organizations">
            
            </flux:tab.panel>
            <flux:tab.panel name="assignments">
            <flux:checkbox wire:model="terms" label="I agree to the terms and conditions" />
            <x-reference-data-dropdown :label="__('Created default status')" type="ASSIGNMENT_STATUS" model="assignments_created_default_status_id" edit="true" />
            </flux:tab.panel>
            <flux:tab.panel name="billing">...</flux:tab.panel>
        </flux:tab.group>

        <flux:button type="submit" variant="primary">{{ __('Save settings') }}</flux:button>
    </form>
</div>`

And the component file
```
<?php

namespace App\Livewire\Settings;

use Livewire\Component;
use App\Helpers\ConfigHelper;
use Flux\Flux;

class Configurations extends Component
{
    public $assignments_created_default_status_id;
    public $organizations_show_credit_check;
    public $terms;

    public function mount()
    {
        // Fetch the current configuration values using the ConfigHelper
        $this->assignments_created_default_status_id = ConfigHelper::get('assignments.created_default_status_id', 1);
        $this->organizations_show_credit_check = ConfigHelper::get('organizations.show_credit_check', false);
    }

    public function updateConfigurations()
    {
        dd($this);
        // Update the configuration values
        ConfigHelper::write('assignments.created_default_status_id', $this->assignments_created_default_status_id);
        ConfigHelper::write('organizations.show_credit_check', $this->organizations_show_credit_check);
        ConfigHelper::write('terms', $this->terms);

        Flux::toast(variant: 'success', text: __('Configurations updated successfully!'));
    }

    public function render()
    {
        return view('livewire.settings.configurations');
    }
}

```


Result:
![Image](https://github.com/user-attachments/assets/6504c58f-9f02-400e-8b5d-fae69b46cffb)

**Comment by ju5t** [comment]
Make sure you've updated to Livewire 3.5.12. You'd probably also want to run `npm run build`.

**Comment by CodeAn** [comment]
Yep, all packages are up to date. Running Livewire 3.5.12; flux 1.0.14. All commands ran. Still same result.

**Comment by ju5t** [comment]
That's strange. I had the same issue yesterday and after upgrading to Livewire v3.5.12 my issues were solved. 

Can you share what you're seeing in your network tab? You should see an update request which contains an `updates` list/array. Please post here what's i it.

**Comment by CodeAn** [comment]
Yeah, it is strange. I thought it was working with v1.0.10, or the default values in the config file were the same. Today it was different so I noticed it.

The request:
![Image](https://github.com/user-attachments/assets/97df2901-ee2d-4888-93c0-d1e17f5b6f5c)

**Comment by jeffchown** [comment]
@CodeAn One thing I noticed in your code, shouldn't `<form wire:submit="updateConfigurations"...` be `<form wire:submit.prevent="updateConfigurations"...` to avoid a default submit POST action which will reload the page after the `updateConfigurations` is called?

**Comment by fabioserembe** [comment]
I have updated Livewire to v3.5.12 and now it works.

Thank you! :)

**Comment by DinoVincent** [comment]
Currently have the same issue. 
livewire/flux-pro  v1.0.19   
livewire/livewire   v3.5.12

`            <flux:accordion transition class="mt-3">
                @foreach ($portals as $portal)
                    @if($portal->id == 2)
                    <flux:accordion.item heading="{{ $portal->name }}">
                        <flux:checkbox.group wire:model="selects">
                            @foreach ($categoriesFromPortals[$portal->id] as $category)
                                    <flux:checkbox value="{{ $category->id }}" label="{{$category->name}}" />
                            @endforeach
                        </flux:checkbox.group>
                    </flux:accordion.item>
                    @endif
                @endforeach
            </flux:accordion>
`


On click there is no network activity.
![Image](https://github.com/user-attachments/assets/a11e2a7e-7999-4532-b2f2-b7327ad79009)

**Comment by DinoVincent** [comment]
> @DinoVincent that's because you've used `wire:model` instead of `wire:model.live`. See: https://livewire.laravel.com/docs/wire-model.
> 
> > If you tried this in your browser and are confused why the title isn't automatically updating, it's because Livewire only updates a component when an "action" is submitted—like pressing a submit button—not when a user types into a field. This cuts down on network requests and improves performance. To enable "live" updating as a user types, you can use wire:model.live instead.
> 

Unfortunately I also tried .live and it also doesn't seem to send a network request upon clicking.

**Comment by ju5t** [comment]
@DinoVincent can you share the full code so we can replicate it? Preferably as a Volt component so it's easy to copy and paste.

**Comment by DinoVincent** [comment]
I made a new page with just an example from the docs, used both wire:model.live and wire:model both result in no server requests after pressing. only if I wire the individual checkboxes (which is what I preferably don't want)

```
<div>
    {{ $notifications }}
    <flux:checkbox.group wire:model.live="notifications" label="Notifications">
        <flux:checkbox label="Push notifications" value="push" />
        <flux:checkbox label="Email" value="email" />
        <flux:checkbox label="In-app alerts" value="app" />
        <flux:checkbox label="SMS" value="sms" />
    </flux:checkbox.group>
</div>

```


```
<?php

namespace App\Livewire;

use Livewire\Component;

class Test extends Component
{
    public $notifications;

    public function render()
    {
        return view('livewire.test');
    }
}
```

And my layout:
```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <style>
        html {
            scroll-behavior: smooth;
        }
    </style>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=inter:400,500,600&display=swap" rel="stylesheet" />

    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    <!-- Styles -->
    @fluxStyles
    @livewireStyles

</head>

<body class="font-sans antialiased">
    <x-banner />

    <div class="min-h-screen bg-gray-100 dark:bg-gray-900">
        @livewire('navigation-menu')
        @livewire('sidebar-menu')
        <!-- Page Heading -->
        @if (isset($header))
            <header class="bg-white dark:bg-gray-800 shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>
        @endif

        <!-- Page Content -->
        <main>
            {{ $slot }}
        </main>
    </div>

    @stack('modals')
    @fluxScripts
    @livewireScripts

</body>

</html>
```

All caches are cleared. I really see no other options...

**Comment by ju5t** [comment]
@DinoVincent ok, there seem to be two issues. I've raised a new issue for this: https://github.com/livewire/flux/issues/585.
