### ISSUE TITLE
Flux Table Pagination Error

### ISSUE THREAD

**Issue by kemdo25** [livewire/flux#470]
Hi there! 👋

flux table pagination issue: if i remove pagination and loading data normally it working
i got message livewire component not supported, i tried either way to fix out but not working
Property type not supported in Livewire for property: [{"current_page":1,"data":[{"id":1,"tax_identification_number":"135202665","certificate_number":"167610021","company_name":"King Charcoal Africa 
if it concern: among fields i have json which hold very large object

my livewire property:

```
          #[Computed]
              public function getCompanies()
              {
                  $query = OilCompany::query();
                  if ($this->sortBy) {
                      $query->orderBy($this->sortBy, $this->sortDirection);
                  }
                  $this->companies = $query->paginate(5);
              }
```

flux table component:

 ```
   <flux:table :paginate="$this->companies" >
                                  <flux:columns>
                                      .....
                                  </flux:columns>
          
                                  <flux:rows>
          
                                      @foreach ($this->companies as $c)
                                          <flux:row>
                                             ...
                                              
                                          </flux:row>
                                      @endforeach
          
                                  </flux:rows>
           </flux:table>
```

my livewire component called within laravel view:

```
<x-app-layout title="Company Registration" is-sidebar-open="true" is-header-blur="true">
    @livewire('registration.reg-company-wire');
</x-app-layout>
```

**Comment by jeffchown** [comment]
@kemdo25 Quick question based on your code...

Since your computed property is:

```
#[Computed]
public function getCompanies()
```

instead of this line in your table component:
```
<flux:table :paginate="$this->companies">
```

shouldn't it be:
```
<flux:table :paginate="$this->getCompanies">
```

**Comment by jeffchown** [comment]
@kemdo25 Have you tried removing your property's `companies` property, renaming the computed property to `companies()` (to replace the removed property) and returning the paginated collection directly from the computed property's method?:

```
#[Computed]
public function companies()
{
    $query = OilCompany::query();
    if ($this->sortBy) {
        $query->orderBy($this->sortBy, $this->sortDirection);
    }
    return $query->paginate(5);
}
```

**Comment by calebporzio** [comment]
Thanks @jeffchown, that's the right answer, closing this.

**Comment by jeffchown** [comment]
You're welcome, @calebporzio

**Comment by kemdo25** [comment]
thanks so much its working
