### ISSUE TITLE
Disabled Button Still Triggers Modal When Tooltip is Present

### ISSUE THREAD

**Issue by lordisp** [livewire/flux#478]
When a button is disabled using the `:disabled` attribute within a `flux:modal.trigger` component, the button is visually disabled and clicking on it should not trigger any action as expected. However, if a `tooltip` attribute is added to the button, clicking the disabled button will still open the modal.

**Steps to Reproduce**
1. Create a flux:modal.trigger component with a flux:button inside it.
2. Set the :disabled attribute of the flux:button based on a boolean variable (e.g., $readonly).
3. Add a tooltip attribute to the flux:button.
4. Click the disabled button.

**Expected Behavior**
The modal should not open when the button is disabled, regardless of whether the `tooltip` attribute is present or not.

**Actual Behavior**
The modal opens even though the button is disabled, but only if the `tooltip` attribute is present. If the `tooltip` is removed, the modal does not open as expected.

```blade
<flux:modal.trigger name="edit-members">
    <flux:button :disabled="$readonly" tooltip="Edit members of this group">
        Members @if(!$readonly) ({{ count($form->members) }}) @endif
    </flux:button>
</flux:modal.trigger>

<flux:modal name="edit-members" variant="flyout" class="space-y-6">
    <!-- rest of the modal content -->
</flux:modal>
```

**Comment by jeffchown** [comment]
@lordisp That's an interesting one... Nice catch.  Same result here.
