### ISSUE TITLE
Component flux:sidebar.toggle do not hide the sidebar

### ISSUE THREAD

**Issue by mclgms** [livewire/flux#483]
I'm using the SideBar component and it has the flux:sidebar.toggle. 
But when I click on it, the sidebar isn't hidden. 
I copied exactly the code from the example in the documentation. 
Besides the @fluxScripts directives in the body of the page, is there anything else?

I installed it following the documentation.

Do I need to add any additional javascript code?

Code:
`<flux:header class="lg:hidden">
    <flux:sidebar.toggle class="lg:hidden" icon="bars-2" inset="left"/>

    <flux:spacer/>
`
Screen
![Image](https://github.com/user-attachments/assets/1be6d13d-55de-4ea6-bb8d-507f371fff7b)

**Comment by igmltd** [comment]
<head>
    ...
    @fluxStyles
</head>

<body>
    ...
    @fluxScripts
</body>

Both scripts and styles is needed

**Comment by mclgms** [comment]
Yes, but they are in the code. See.

head
![Image](https://github.com/user-attachments/assets/ad9c52bf-23c2-415a-9057-9796b5bf3328)

body
![Image](https://github.com/user-attachments/assets/dba5bb1a-0aa1-4a97-b5fb-38fd8c5e465b)

**Comment by mclgms** [comment]
One detail. The sidebar is in the body of the layout "layouts/app.blade.php" and despite rendering the code it looks like it's incorrect. Am I using it correctly? See the image below.

![Image](https://github.com/user-attachments/assets/70a50fb1-2ee7-4655-9cd9-1446dec9b1bb)

**Comment by jeffchown** [comment]
@mclgms It's difficult to help with only small code samples, can you please post a full code example that is easy to cut & paste and recreate?

**Comment by mclgms** [comment]
Hello, here is the complete code and what I'm using.

`
        "php": "^8.2",
        "laravel/framework": "^11.9",
        "laravel/jetstream": "^5.3",
        "laravel/sanctum": "^4.0",
        "laravel/tinker": "^2.9",
        "livewire/flux-pro": "^1.0",
        "livewire/livewire": "^3.0"
`

`<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    
    <link rel="preconnect" href="https://fonts.bunny.net">
    {{--        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />--}}
    <link href="https://fonts.bunny.net/css?family=inter:400,500,600&display=swap" rel="stylesheet"/>

    
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    
    @fluxStyles
</head>
<body class="min-h-screen bg-white dark:bg-zinc-800">

<flux:sidebar sticky stashable class="bg-zinc-50 dark:bg-zinc-900 border-r border-zinc-200 dark:border-zinc-700">
    {{--    <flux:sidebar.toggle class="lg:hidden" icon="x-mark"/>--}}
    <span class="dark:!text-white">Projeto Teste</span>
    <flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" name="Acme Inc." class="px-2 dark:hidden"/>
    <flux:brand href="#" logo="https://fluxui.dev/img/demo/dark-mode-logo.png" name="Acme Inc."
                class="px-2 hidden dark:flex"/>

    <flux:input as="button" variant="filled" placeholder="Search..." icon="magnifying-glass"/>

    <flux:navlist variant="outline">
        <flux:navlist.item icon="home" href="#" current>Home</flux:navlist.item>
        <flux:navlist.item icon="inbox" badge="12" href="#">Inbox</flux:navlist.item>
        <flux:navlist.item icon="document-text" href="#">Documents</flux:navlist.item>
        <flux:navlist.item icon="calendar" href="#">Calendar</flux:navlist.item>

        <flux:navlist.group expandable heading="Favorites" class="hidden lg:grid">
            <flux:navlist.item href="#">Marketing site</flux:navlist.item>
            <flux:navlist.item href="#">Android app</flux:navlist.item>
            <flux:navlist.item href="#">Brand guidelines</flux:navlist.item>
        </flux:navlist.group>
    </flux:navlist>

    <flux:spacer/>

    <flux:navlist variant="outline">
        <flux:navlist.item icon="cog-6-tooth" href="#">Settings</flux:navlist.item>
        <flux:navlist.item icon="information-circle" href="#">Help</flux:navlist.item>
    </flux:navlist>

    <flux:dropdown position="top" align="start" class="max-lg:hidden">
        <flux:profile avatar="https://fluxui.dev/img/demo/user.png" name="Olivia Martin"/>

        <flux:menu>
            <flux:menu.radio.group>
                <flux:menu.radio checked>Olivia Martin</flux:menu.radio>
                <flux:menu.radio>Truly Delta</flux:menu.radio>
            </flux:menu.radio.group>

            <flux:menu.separator/>

            <flux:menu.item icon="arrow-right-start-on-rectangle">Logout</flux:menu.item>
        </flux:menu>
    </flux:dropdown>
</flux:sidebar>

<flux:header class="lg:hidden">
    <flux:sidebar.toggle class="lg:hidden" icon="bars-2" inset="left"/>

    <flux:spacer/>

    <flux:dropdown position="top" alignt="start">
        <flux:profile avatar="https://fluxui.dev/img/demo/user.png"/>

        <flux:menu>
            <flux:menu.radio.group>
                <flux:menu.radio checked>Olivia Martin</flux:menu.radio>
                <flux:menu.radio>Truly Delta</flux:menu.radio>
            </flux:menu.radio.group>

            <flux:menu.separator/>

            <flux:menu.item icon="arrow-right-start-on-rectangle">Logout</flux:menu.item>
        </flux:menu>
    </flux:dropdown>
</flux:header>


    <flux:main>
        {{$slot}}
    </flux:main>
@fluxScripts
</body>
</html>
`

**Comment by jeffchown** [comment]
@mclgms Unfortunately, that's still not a full copy of the code/file.

Also, when formatting code blocks over multiple lines in GitHub, you need to wrap them in '```' (triple backticks) so your code doesn't get broken up as yours did above.

**Comment by mclgms** [comment]
Now I believe I sent it correctly.

`<!DOCTYPE html>`
`<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">`
`<head>`
`    <meta charset="utf-8">`
`    <meta name="viewport" content="width=device-width, initial-scale=1">`
`    <meta name="csrf-token" content="{{ csrf_token() }}">`
`    <title>{{ config('app.name', 'Laravel') }}</title>`
`    <!-- Fonts -->`
`    <link rel="preconnect" href="https://fonts.bunny.net">`
`    <link href="https://fonts.bunny.net/css?family=inter:400,500,600&display=swap" rel="stylesheet"/>`
`    <!-- Scripts -->`
`    @vite(['resources/css/app.css', 'resources/js/app.js'])`
`    <!-- Styles -->`
`    @fluxStyles`
`</head>`
`<body class="min-h-screen bg-white dark:bg-zinc-800">`
`    <flux:sidebar sticky stashable class="bg-zinc-50 dark:bg-zinc-900 border-r border-zinc-200 dark:border-zinc-700">`
`        <flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" name="Acme Inc." class="px-2 dark:hidden"/>`
`        <flux:brand href="#" logo="https://fluxui.dev/img/demo/dark-mode-logo.png" name="Acme Inc."  class="px-2 hidden dark:flex"/>`
`        <flux:input as="button" variant="filled" placeholder="Search..." icon="magnifying-glass"/>`
`        <flux:navlist variant="outline">`
`            <flux:navlist.item icon="home" href="#" current>Home</flux:navlist.item>`
`            <flux:navlist.item icon="inbox" badge="12" href="#">Inbox</flux:navlist.item>`
`            <flux:navlist.item icon="document-text" href="#">Documents</flux:navlist.item>`
`            <flux:navlist.item icon="calendar" href="#">Calendar</flux:navlist.item>`
`        </flux:navlist>`
`        <flux:spacer/>`
`        <flux:spacer/>`
`        <flux:navlist variant="outline">`
`            <flux:navlist.item icon="cog-6-tooth" href="#">Settings</flux:navlist.item>`
`            <flux:navlist.item icon="information-circle" href="#">Help</flux:navlist.item>`
`        </flux:navlist>`
`        <flux:dropdown position="top" align="start" class="max-lg:hidden">`
`            <flux:profile avatar="https://fluxui.dev/img/demo/user.png" name="Olivia Martin"/>`
`            <flux:menu>`
`                <flux:menu.radio.group>`
`                    <flux:menu.radio checked>Olivia Martin</flux:menu.radio>`
`                    <flux:menu.radio>Truly Delta</flux:menu.radio>`
`                </flux:menu.radio.group>`
`                <flux:menu.separator/>`
`                <flux:menu.item icon="arrow-right-start-on-rectangle">Logout</flux:menu.item>`
`            </flux:menu>`
`        </flux:dropdown>`
`    </flux:sidebar>`
`    <flux:header class="lg:hidden">`
`        <flux:sidebar.toggle class="lg:hidden" icon="bars-2" inset="left"/>`
`        <flux:spacer/>`
`        <flux:dropdown position="top" alignt="start">`
`            <flux:profile avatar="https://fluxui.dev/img/demo/user.png"/>`
`            <flux:menu>`
`                <flux:menu.radio.group>`
`                    <flux:menu.radio checked>Olivia Martin</flux:menu.radio>`
`                    <flux:menu.radio>Truly Delta</flux:menu.radio>`
`                </flux:menu.radio.group>`
`                <flux:menu.separator/>`
`                <flux:menu.item icon="arrow-right-start-on-rectangle">Logout</flux:menu.item>`
`            </flux:menu>`
`        </flux:dropdown>`
`    </flux:header>`
`    <flux:main>`
`        {{$slot}}`
`    </flux:main>`
`    @fluxScripts`
`</body>`
`</html>`

**Comment by jeffchown** [comment]
Thanks for reposting @mclgms - I think you wrapped each line in 3 backticks, but it is possible to cut & paste now.
For the future, you only need 3 backticks at the top, then the bottom of the **entire** code block, like this, then GitHub will put a handy button in the top-right corner for everyone to use to copy the code:

```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=inter:400,500,600&display=swap" rel="stylesheet"/>
    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <!-- Styles -->
    @fluxStyles
</head>
<body class="min-h-screen bg-white dark:bg-zinc-800">
    <flux:sidebar sticky stashable class="bg-zinc-50 dark:bg-zinc-900 border-r border-zinc-200 dark:border-zinc-700">
        <flux:brand href="#" logo="https://fluxui.dev/img/demo/logo.png" name="Acme Inc." class="px-2 dark:hidden"/>
        <flux:brand href="#" logo="https://fluxui.dev/img/demo/dark-mode-logo.png" name="Acme Inc."  class="px-2 hidden dark:flex"/>
        <flux:input as="button" variant="filled" placeholder="Search..." icon="magnifying-glass"/>
        <flux:navlist variant="outline">
            <flux:navlist.item icon="home" href="#" current>Home</flux:navlist.item>
            <flux:navlist.item icon="inbox" badge="12" href="#">Inbox</flux:navlist.item>
            <flux:navlist.item icon="document-text" href="#">Documents</flux:navlist.item>
            <flux:navlist.item icon="calendar" href="#">Calendar</flux:navlist.item>
        </flux:navlist>
        <flux:spacer/>
        <flux:spacer/>
        <flux:navlist variant="outline">
            <flux:navlist.item icon="cog-6-tooth" href="#">Settings</flux:navlist.item>
            <flux:navlist.item icon="information-circle" href="#">Help</flux:navlist.item>
        </flux:navlist>
        <flux:dropdown position="top" align="start" class="max-lg:hidden">
            <flux:profile avatar="https://fluxui.dev/img/demo/user.png" name="Olivia Martin"/>
            <flux:menu>
                <flux:menu.radio.group>
                    <flux:menu.radio checked>Olivia Martin</flux:menu.radio>
                    <flux:menu.radio>Truly Delta</flux:menu.radio>
                </flux:menu.radio.group>
                <flux:menu.separator/>
                <flux:menu.item icon="arrow-right-start-on-rectangle">Logout</flux:menu.item>
            </flux:menu>
        </flux:dropdown>
    </flux:sidebar>
    <flux:header class="lg:hidden">
        <flux:sidebar.toggle class="lg:hidden" icon="bars-2" inset="left"/>
        <flux:spacer/>
        <flux:dropdown position="top" alignt="start">
            <flux:profile avatar="https://fluxui.dev/img/demo/user.png"/>
            <flux:menu>
                <flux:menu.radio.group>
                    <flux:menu.radio checked>Olivia Martin</flux:menu.radio>
                    <flux:menu.radio>Truly Delta</flux:menu.radio>
                </flux:menu.radio.group>
                <flux:menu.separator/>
                <flux:menu.item icon="arrow-right-start-on-rectangle">Logout</flux:menu.item>
            </flux:menu>
        </flux:dropdown>
    </flux:header>
    <flux:main>
        {{$slot}}
    </flux:main>
    @fluxScripts
</body>
</html>
```

**Comment by mclgms** [comment]
Ok @jeffchown 
I will do that, thanks for the information.

**Comment by mclgms** [comment]
Okay, but if you look at the code I passed, @fluxScripts is in the body according to the documentation. And even so, flxu:sidebar.toggle doesn't work. The events related to dropdown work normally.

I'll try to rewrite it manually without copying the example code and return it here.

**Comment by jeffchown** [comment]
Hi @mclgms - I did see your `@fluxScripts` - when researching your issue and testing a copy & paste of the demo code, I ran into the missing `@fluxScripts` from the demo code and wanted to let @calebporzio know about it.

With respect to your code, it doesn't seem to be an exact copy of the demo and I'm not quite sure what you are trying to describe.

If you try one of the sidebar demos in the docs: https://fluxui.dev/layouts/sidebar
and click on the Fullscreen button, then resize your browser until the sidebar hides itself, you'll see the double-bar button to show the sidebar, then you'll see the X icon in the top-left to close the sidebar.

**Comment by mclgms** [comment]
@jeffchown 
I refactored the code and built it and now it's working. In fact, I had expressed myself wrong. The button to open or close the "sidebar" was always on the screen even when using the correct tailwind directives. I recreated app.blade.php, ran 'npm run build' and now it's working as it should.
Thanks!
