### ISSUE TITLE
Multiple buttons in flux:dropdown component not working simultaneously

### ISSUE THREAD

**Issue by zuberkz** [livewire/flux#488]
Hi there! 👋

Sorry you hit a problem with Flux.

There is an issue with the flux:dropdown component where only one trigger (button) works when multiple flux:button elements are specified. Specifically, if I have two or more flux:button elements — one for desktop and one for mobile — only one trigger works, and the other is ignored. Ideally, I would like all buttons to function as dropdown triggers, depending on the screen size or situation.

Additionally, it would be useful to have the ability to use other elements, not just flux:button, as triggers for the dropdown, allowing for more flexibility in design.

### Code Example:

```html
<flux:dropdown>
    <flux:button variant="ghost" class="!text-white hidden md:block">
        City: <span>{{ $selectedCityTitle }}</span>
    </flux:button>

    <flux:button class="!bg-primary !border-primary rounded-md md:hidden !text-white" icon-trailing="globe-asia-australia"></flux:button>

    <flux:menu>
        @foreach($cities as $city)
            <flux:menu.item wire:key="{{ $city->id }}" wire:click="selectCity({{ $city->id }})">{{ $city->title }}</flux:menu.item>
        @endforeach
    </flux:menu>
</flux:dropdown>
```

### Expected Behavior:

- All flux:button elements should be able to trigger the dropdown, regardless of the number of buttons or their visibility.
- The component should allow other types of elements (such as <a>, <div>, etc.) to be used as a dropdown trigger, instead of limiting it to flux:button.

### Actual Behavior:

- Only one trigger works when multiple buttons are present (either desktop or mobile).
- It's currently not possible to specify other elements as triggers.

### Steps to Reproduce:

- Place two or more flux:button elements inside a flux:dropdown component.
- Add hidden md:block for desktop and md:hidden for mobile to the buttons.
- Try clicking the buttons in their respective viewports.
- Could you please help resolve this issue and provide more flexibility with trigger elements?

**Comment by jeffchown** [comment]
@zuberkz Based on the dropdown demos on the docs page (https://fluxui.dev/components/dropdown) and the composability of Flux, it looks like the first child element of a `<flux:dropdown>` is assumed to be the trigger.

I assume it would be a challenging task (and create some pretty complicated code) to change the `flux:dropdown` component to account for **possible** multiple triggers of multiple possible types.

Can you use something like this?:

```
<flux:button>
    <div class="hidden md:block">
        Menu
    </div>

    <div class="md:hidden">
        <flux:icon.globe-asia-australia />
    </div>
</flux:button>
```

I realize it is not exactly like your example, but with some CSS, you should be able to get pretty close.

**Comment by zuberkz** [comment]
It work!

``` HTML
<flux:dropdown>
        <flux:button class="!bg-primary !border-primary rounded-md lg:!bg-transparent lg:!border-transparent lg:px-0 lg:py-0">

            <div class="hidden md:block !bg-transparent !text-white">
                Город: <span>{{ $selectedCityTitle }}</span>
            </div>
            
            <div class="md:hidden !text-white">
                <flux:icon.globe-asia-australia />
            </div>
        </flux:button>

        <flux:menu>
            @foreach($cities as $city)
                <flux:menu.radio wire:key="{{ $city->id }}"
                                 :checked="$selectedCity === $city->id"
                                 wire:click.prevent="selectCity({{ $city->id }})">{{ $city->title }}</flux:menu.radio>
            @endforeach
        </flux:menu>
</flux:dropdown>
```

**Comment by jeffchown** [comment]
Great! @zuberkz
