### ISSUE TITLE
No spacing between table cells

### ISSUE THREAD

**Issue by lucasromanojf** [livewire/flux#49]
When using tables in small screens, if table cell content uses its full width, there's no spacing between the cells, which can be confusing for the user. 

You can see it in the screenshot below. In the second row, the "Nome", "E-mail" and "Perfil administrativo" columns contents have no spacing between them. The first column ("Código") has some spacing, but I had to add manually using CSS.

![Captura de Tela 2024-09-24 às 14 00 20](https://github.com/user-attachments/assets/ef8e812e-46a2-47a4-9a1d-bec2b027ff3a)

**Comment by patrykszady** [comment]
![Screenshot 2024-09-24 172522](https://github.com/user-attachments/assets/71ea7f98-de0e-44c7-88ca-b7e9f434d995)
Same here.

**Comment by CitizenBeta** [comment]
> ![Screenshot 2024-09-24 172522](https://github.com/user-attachments/assets/71ea7f98-de0e-44c7-88ca-b7e9f434d995) Same here.

Can we pause for a moment and reflect on the beautiful line art here?

**Comment by calebporzio** [comment]
![Image](https://github.com/user-attachments/assets/b8b34c18-27d4-46fc-8139-87e19eb3fe26)

I believe this has been fixed - plz re-open if I'm wrong. But please provide copy/pastable code snippets

**Comment by lucasromanojf** [comment]
Hello @calebporzio, yes it is fixed already, thank you
