### ISSUE TITLE
What happened with Toast in version 1.0.15?

### ISSUE THREAD

**Issue by MOA-TI** [livewire/flux#491]
Hi there!

While reviewing the changes in version 1.0.15, I noticed that a significant amount of code has been removed, including the ability to customize the position and the data-* attributes used for styling the appearance with CSS.

Is this an issue with the new version, or am I doing something wrong?

Regardless, you’re doing an excellent job. Thank you for your hard work!

![Image](https://github.com/user-attachments/assets/f0314f7d-665a-4419-a6a2-a25e67776ad4)

Prior to version 1.0.15, this code displayed the toasts in the top-right corner of the screen. Now, it no longer works…
```
@persist('toast')
<flux:toast position="top right" class="pt-20"/>
@endpersist
```

The data-flux-toast-dialog attribute enables us to customize the appearance of the toast using CSS, depending on the selected variant…

```
[data-flux-toast-dialog][data-variant="info"] div {
        @apply bg-blue-100 !text-blue-800;
}

[data-flux-toast-dialog][data-variant="success"] div {
        @apply bg-green-200;
}

[data-flux-toast-dialog][data-variant="warning"] div {
        @apply bg-yellow-200;
}

[data-flux-toast-dialog][data-variant="danger"] div {
        @apply bg-red-200;
}
```

**Comment by jeffchown** [comment]
@MOA-TI See my issue post: https://github.com/livewire/flux/issues/492

**Comment by jeffchown** [comment]
See my latest update to issue: https://github.com/livewire/flux/issues/492

**Comment by calebporzio** [comment]
Sorry, please upgrade to v1.0.16 - should be all set
