### ISSUE TITLE
Trying to update to v1.0.15 actually downgraded flux-pro

### ISSUE THREAD

**Issue by jeffchown** [livewire/flux#492]
Hi @calebporzio - when I ran a `composer update` just now, flux updated to v1.0.15 just fine, but flux-pro gave me this:
`Downgrading livewire/flux-pro (1.0.14 => 1.0.4)`

I assume this is **not** by design? ;)

And, not sure if it's related, but I also got this: `Downgrading laravel/prompts (v0.3.1 => v0.2.1)`

**Comment by jeffchown** [comment]
When I update my composer.json per:

"livewire/flux-pro": "^1.0.14",

and re-run `composer update`, I get this:

`- Downgrading livewire/flux (v1.0.15 => v1.0.14): Checking out 35cb51a96f from cache
  - Upgrading livewire/flux-pro (1.0.4 => 1.0.15): Extracting archive`

**Comment by jeffchown** [comment]
UPDATE:  When I edit my `composer.json` and remove the `"livewire/flux": "^1.0",` line (a left-over from an initial free installation before my Flux pro purchase), and rerun `composer update` all updates as expected.

Maybe an outdated dependency in `livewire/flux` repo?

**Comment by jeffchown** [comment]
> Shoot, the composer.json change to update the flux version requirement didn't get made to livewire/flux-pro.
> 
> Can you test again and let me know if it's worked now (on v1.0.16)?

Yup, all good now.  Thanks @calebporzio !

```
  - Upgrading livewire/flux (v1.0.14 => v1.0.16)
  - Upgrading livewire/flux-pro (1.0.15 => 1.0.16)
```

**Comment by nielseulink** [comment]
> Shoot, the composer.json change to update the flux version requirement didn't get made to livewire/flux-pro.
> 
> Can you test again and let me know if it's worked now (on v1.0.16)?

It's working just fine now 🚀

**Comment by calebporzio** [comment]
Great, thanks for the following up!
