### ISSUE TITLE
Undefined variable $size error for input

### ISSUE THREAD

**Issue by aydinza** [livewire/flux#507]
Hey guys,

After updating to .16 yesterday, I tried to login. The login page does not load due to this error, and shows the password input.

`Undefined variable $size`

this line highlighted

` <flux:input name="password" type="password" label="{{ __('Password') }}" required
                    autocomplete="current-password" viewable />`

I tried adding size="sm", but still not working.

This is a jetstream project.

BR

**Comment by lotje-kinable** [comment]
Hi @aydinza maybe you can try the default from the docs, and see if the error goes away? 

<flux:input type="password" value="password" viewable />

**Comment by joshhanley** [comment]
@aydinza can you please share a screenshot of the error and also share your code your page that has the error? Thanks!
