### ISSUE TITLE
Switch w/ label automatically uses container's full width

### ISSUE THREAD

**Issue by jeffchown** [livewire/flux#509]
I'm not sure if this is new to Flux v1.0.17 or it existed before.

When I add a `flux:switch` with a label to my form, the switch expands to the full width to look like this:

![Image](https://github.com/user-attachments/assets/ea97900a-28a5-46bf-9f02-12220c7ed755)

e.g.:

```
<div>
    <flux:checkbox wire:model="isChecked" label="Checkbox" />
    <flux:switch wire:model="isSwitched" label="Switch" />
</div>
```

with, of course, the appropriate properties added to my component via:

```
public bool $isChecked = false;
public bool $isSwitched = false;
```

**Comment by jeffchown** [comment]
A workaround for now is to wrap the `flux:switch`es with a `<div class="w-min">` - but this will create messy markup on pages where I use a lot of switches.

**Comment by joshhanley** [comment]
@jeffchown I'm pretty sure it's designed that way, because if you had a bunch of switches, you'd want them to all line up on the right hand side.

**Comment by jeffchown** [comment]
@joshhanley OK.  If that's the case, wouldn't hurt to put a little note in the switch docs to remind people they have to control the switches' container's width (so no one expects them to be left-justified)

**Comment by joshhanley** [comment]
@joshhanley yeah fair, do you think that might be covered by this principal? https://fluxui.dev/docs/principles#we-style,-you-space

**Comment by jeffchown** [comment]
@joshhanley One could argue that `Notice how Flux handles the styling of individual components, but leaves the spacing and layout to you.` could lead to an expectation that the switches and their labels to be left-justified (like the checkboxes) unless you wanted to 'space'/'lay them out' (horrible grammar ;)) them differently, like e.g.:

```
<flux:field class="w-full flex justify-between">
    <flux:label>Enable notifications</flux:label>

    <flux:switch wire:model.live="notifications" />
</flux:field>
```

which is actually what I expected/how I interpreted things.

**Comment by jeffchown** [comment]
@joshhanley Maybe the fact that it can be open to interpretation means a short note in the Switch docs re: default styling wouldn't hurt (for anyone that might possibly think like me ;)

**Comment by calebporzio** [comment]
I added a new section in the docs for this so that people can just copy/past:

![Image](https://github.com/user-attachments/assets/642076e0-77f3-4a9a-b39c-01b39f125469)

https://fluxui.dev/components/switch#left-aligned

**Comment by jeffchown** [comment]
Perfect.  Thanks @calebporzio , @joshhanley !
