### ISSUE TITLE
[PRO] Dropdown + Profile weird focus state depending on where user clicks

### ISSUE THREAD

**Issue by LasseRafn** [livewire/flux#51]
If you click the name it appears that the dropdown menu gets focused, but if I click away from the name it does not. Keyboard navigation works for both cases, only difference is that the outline appears when clicking name, but not when clicking blank or chevron.

Browser: Safari 17.6, macOS 14.6.1

https://github.com/user-attachments/assets/98f691e0-4bf1-4698-97bb-631d97da21dc

**Comment by joshhanley** [comment]
@LasseRafn thanks for reporting! For some reason your video isn't working. Can you re-upload it? Thanks!

**Comment by LasseRafn** [comment]
@joshhanley weird! try this, https://share.cleanshot.com/Fk1wHZBC

https://github.com/user-attachments/assets/5f7ea7a7-9445-4a33-88b8-ee6cc079643e

**Comment by joshhanley** [comment]
@LasseRafn thanks for reporting! I have submitted a PR #400 with a fix.

**Comment by calebporzio** [comment]
Thanks @joshhanley!
