### ISSUE TITLE
Checkboxes Select All when using array

### ISSUE THREAD

**Issue by robs007** [livewire/flux#518]
I'm trying to use checkboxes in a table with a wire:model array. When selecting one box, all boxes are selected and return true or false instead of adding the value to the array. It works fine if I just use a standard checkbox. Maybe this is by design, or I'm doing something incorrectly.

public $selectedIds = [];

                                        <flux:table>
                                            <flux:row>
                                                <flux:column>
                                                    <flux:checkbox wire:model.live="selectedIds" value="1345" />
                                                </flux:column>
                                            </flux:row>
                                            <flux:row>
                                                <flux:column>
                                                    <flux:checkbox wire:model.live="selectedIds" value="135" />
                                                </flux:column>
                                            </flux:row>
                                        </flux:table>

Thank you!

**Comment by jeffchown** [comment]
@robs007 Your code works as expected for me.  Are you sure you are running Livewire 3.5.12 and Flux 1.0.17?

And, after updating, have you?:

- deleted `resources/views/flux` directory (to make sure you don't have any old published versions of any Flux components)
- `php artisan view:clear`
- `npm run dev`

**Comment by robs007** [comment]
It works now; I had updates flux but not livewire. Updating everything did the trick.
Thanks

**Comment by calebporzio** [comment]
Thanks @jeffchown for checking on that
