### ISSUE TITLE
flux:botton not submitting when in flux:tabs

### ISSUE THREAD

**Issue by aydinza** [livewire/flux#523]
I have a CreateCompany.php livewire class, and a CreateForm.php form for this. the create-company.blade.php livewire component has a form. This form is in flux:tabs. No matter what I try, it does not submit the form. The validation errors are not showing up when the button clicked without filling any input.

I tried using a standard button. Do you think it's because the form is in tabs?

**Comment by calebporzio** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps to reproduce. Please include any Blade variable definitions that are used. Then, we will be happy to help.
