### ISSUE TITLE
flux:tabs first tab behaves different

### ISSUE THREAD

**Issue by aydinza** [livewire/flux#524]
I try to use the tabs component. The first tab tend to be larger than the others and flashes in the screen. But the following ones have the same sizes, so only the tab content changes. I have exact same styling. any rule applied to the first child?

**Comment by calebporzio** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps to reproduce. Please include any Blade variable definitions that are used. Then, we will be happy to help.
