### ISSUE TITLE
Shorthand props pattern only for input?

### ISSUE THREAD

**Issue by vincentcordel** [livewire/flux#527]
In a form, I use the input component which creates flux field, input & error.

However for all other form components (textarea, select,...), I have to create the full code:
```
<flux:field>
    <flux:label>Content</flux:label>
    <flux:textarea rows="8" wire:model="content" x-autofocus/>
    <flux:error name="content"/>
</flux:field>
```

It'd be nice to be able to use the shorthand syntax for all form fields.

**Comment by jeffchown** [comment]
@vincentcordel I'm not sure why say you have to create the full code for textareas, selects, etc.

You can use the same shorthand for those as well, e.g.:

`<flux:textarea wire:model="comments" label="Comments" rows="auto" />`

**Comment by calebporzio** [comment]
Yep, @jeffchown is right, every input supports that shorthand syntax. Thanks @jeffchown
