### ISSUE TITLE
&amp; on flux:navlist.item

### ISSUE THREAD

**Issue by FortuneV13** [livewire/flux#529]
`&amp;` is being added to the URL when using laravels route to define the URL in a navlist.item

`<flux:navlist.item href="{{route('salesmen-forecast.index',['user_id'=>$selectedUser,'page_category'=>'live_stats_turnover','year'=>date('Y')])}}"  > Salesmen Forecast</flux:navlist.item>`

results in:
`/salesmen-forecast?user_id=33&amp;page_category=live_stats_turnover&amp;year=2024`

**Comment by jeffchown** [comment]
@FortuneV13 I believe this was fix a few versions ago.  What version are your Livewire and Flux? (`composer show`)

**Comment by jeffchown** [comment]
Possibly

**Comment by joshhanley** [comment]
@FortuneV13 for it to work correctly you do need to use the `:href="route()"` syntax. But I can confirm there is still a bug with `navlist.item`. I've submitted a PR with a fix.

**Comment by joshhanley** [comment]
Turns out any component that accepts an href is having this issue. So I've submitted a PR #536 to Flux in addition to the PR I mentioned above to Flux Pro.

**Comment by calebporzio** [comment]
Closing because this has been fixed.

**Comment by joshhanley** [comment]
@FortuneV13 Fixed as at Caleb's message. But is hasn't been released yet.
