### ISSUE TITLE
Flux blade directives won't work with Laravel Vapor

### ISSUE THREAD

**Issue by idealerror** [livewire/flux#53]
The current functionality hardcodes links to the Flux CSS/JS public published files:

@fluxStyles:
```
return '<link rel="stylesheet" href="/flux/flux.css?id='. $versionHash . '">';
```

@fluxScripts:
```
return '<script src="/flux/flux.min.js?id='. $versionHash . '" data-navigate-once></script>';
```

This won't work in Laravel Vapor as Vapor does not serve files directly from public and utilizes CloudFront/S3 to serve the files.  Relevant doc here: https://docs.vapor.build/projects/deployments.html#assets

**Potential options to fix this:**

1. Utilize `asset()`
2. Bundle with vite

**Comment by alxndrmlr** [comment]
Following! We're on Vapor as well and will be diving into flux (when we can)

Appreciate all the hard work on this Caleb really stoked to get rolling

**Comment by ttrushin** [comment]
Would love to be able to bundle with Vite

**Comment by trungpv1601** [comment]
👀

**Comment by alxndrmlr** [comment]
@idealerror have you been able to work around this yet? I was about to dive in today on this. Seems like we should be able to just write our own asset() include in blade templates rather than using `@fluxScripts` and `@fluxSyles`

**Comment by idealerror** [comment]
I have not yet.  I'm still working in local and have not attempted any fixes for Vapor.

**Comment by alxndrmlr** [comment]
@idealerror I'm going to start demoing some stuff the deploying but it seems like it should work

```
 public function registerAssetRoutes()
    {
        Route::get('/flux/flux.css', function () {
            return Flux::pro()
                ? $this->pretendResponseIsFile(__DIR__.'/../../flux-pro/dist/flux.css', 'text/css')
                : $this->pretendResponseIsFile(__DIR__.'/../../flux/dist/flux-lite.css', 'text/css');
        });

        Route::get('/flux/flux.js', function () {
            return Flux::pro()
                ? $this->pretendResponseIsFile(__DIR__.'/../../flux-pro/dist/flux.js', 'text/javascript')
                : $this->pretendResponseIsFile(__DIR__.'/../../flux/dist/flux-lite.min.js', 'text/javascript');
        });

        Route::get('/flux/flux.min.js', function () {
            return Flux::pro()
                ? $this->pretendResponseIsFile(__DIR__.'/../../flux-pro/dist/flux.min.js', 'text/javascript')
                : $this->pretendResponseIsFile(__DIR__.'/../../flux/dist/flux-lite.min.js', 'text/javascript');
        });
    }
    
    ```
    
    Those links aren't actual files they are routes

**Comment by alxndrmlr** [comment]
@idealerror this is a non-issue, just shipped to vapor and its all good. The routes for the .css and .js don't serve files.

That said, I could see a desire to want to bundle this into vite, however given all the other stuff Caleb/Josh and the team could be cooking up right now I think that's a non-priority at the moment. I think this can be closed as non-issue so it doesn't confuse other people looking at the repo who haven't dug into the conversation we had.
