### ISSUE TITLE
Button component is escaping href

### ISSUE THREAD

**Issue by nissicreative** [livewire/flux#535]
I honestly don't know if this is intended behavior or a bug, but I am trying to generate a link to a signed S3 URL, and it is double-escaping the `href` attribute, causing the link's authorization to fail.

```php
// MyModel.php
public function getUrlAttribute(): string
{
    return Storage::disk('uploads')->temporaryUrl($this->path, now()->addMinutes(30));
}
```

This does *not* work (it converts `&` to `&amp;` in the href):
```blade
<flux:button href="{{ $file->url }}">View File</flux:button>
```

This *does* work (preserves the `&` characters):
```blade
<flux:button href="{!! $file->url !!}">View File</flux:button>
```
...but muscle memory and standard `<a>` tag behavior is double curly braces. 🙂

FWIW, I published the `button-or-link` stub and made this change, which does allow me to use double curly braces as in the first example, but there may be other drawbacks:
```blade
<?php if ($href): ?>
    {{-- We are using new \Illuminate\Support\HtmlString() here to avoid double escaping the href attribute value... --}}
    <a href="{{ new \Illuminate\Support\HtmlString($href) }}" {{ $attributes->merge(['data-current' => $current]) }}>
        {{ $slot }}
    </a>
<?php else: ?>
    <button {{ $attributes->merge(['type' => $type, 'data-current' => $current]) }}>
        {{ $slot }}
    </button>
<?php endif; ?>
```

Thanks again for making great stuff!

**Comment by joshhanley** [comment]
@nissicreative thanks for reporting! This is a similar issue to #529 but that issue relates to Flux Pro components where as this one is a Flux component. So I have submitted a PR #536 to fix this too.

**Comment by nicolaslefresne** [comment]
@joshhanley jumping on that for a quick parenthesis because I've never found an answer: would you consider best practice to always use the `:href=""` syntax instead of `href="{{ }}"` whenever possible?

**Comment by joshhanley** [comment]
@nicolaslefresne well it depends. `:href=""` tells blade to execute the code when it gets passed into the component.

Where as `href="{{}}"` is a blade echo, which gets executed before the component is rendered.

`{{}}` under the hood uses the `e()` function which escapes everything, hence why it causes issues with formatting urls, so in this particular instance `:href` is better. Plus it's shorter and nicer to read without `{{}}`.

Hope that all makes sense 🙂

**Comment by nicolaslefresne** [comment]
@joshhanley thank you for the useful precisions!

**Comment by nissicreative** [comment]
@joshhanley thanks for the quick response and detailed explanation. I like the `:href` solution but unfortunately my Blade formatter often mangles contents, making them `:href="$object - > attribute"`. Not a compelling argument, I know! 🙂
