### ISSUE TITLE
Select on mobile

### ISSUE THREAD

**Issue by jesperbjoernandersen** [livewire/flux#537]
There are some general tweaks for mobile.

Both searchable and combobox select keeps input as focus, and selects all input inf there's any, if the dropdown is open and you press e.g the menu. This ends up highlighting text or just shows the select cursor behind the menu, iphone at least. The same issues are true for Autocomplete component.

The dropdowns of custom select overlaps the input. Not sure if this is intended, if it's aimed to mimic native behaviour, it's incorrect.

In general, all custom selects keep their "dropdown" open when scrolling. I'm not sure if this is intended, but native select behaviour on desktop is locking scroll, making the page unscrollable when select is open. On mobile, when you start scrolling, it'll close. Again, on Iphone at least.

Not sure if it's just on the fluxui.dev component page, but combobox is hard to unfocus on mobile.

Lastly, a little feature request for custom selects. An attribute to make it "clearable" would be nice

**Comment by calebporzio** [comment]
Thanks for these reports. "grab bag" issues like this are too hard for us to sift through. Can you please submit individual issues with reproducible code for each bug and put any feature requests in the discussions area? Thanks.
