### ISSUE TITLE
wire:focus and wire:blur not working on select

### ISSUE THREAD

**Issue by marchampson** [livewire/flux#541]
Hi, I can't see this answered elsewhere but apologies if it has. Both wire:focus and blur don't appear to be available in the select component. This may be by design but I've used these in my codebase and now I've swapped old selects for flux:select things aren't playing nicely:

```
<?php

use Flux\Flux;
use Livewire\Attributes\On;
use Livewire\Volt\Component;

new class extends Component {

    public $industry;
    public $normalStatus = 'unlocked';
    public $fluxStatus = 'unlocked';

    public function lock($select)
    {
        $this->{$select . 'Status'} = 'locked';
    }

    public function unlock($select)
    {
        $this->{$select . 'Status'} = 'unlocked';
    }
}; ?>

<div xmlns:flux="http://www.w3.org/1999/html">
    <flux:card>
    <flux:heading size="lg">Normal Select - this will update the status</flux:heading>
    {{ $normalStatus }}
    <select wire:focus="lock('normal')" wire:blur="unlock('normal')">
        <option value="1">Option 1</option>
        <option value="2">Option 2</option>
        <option value="3">Option 3</option>
    </select>
    </flux:card>
    <flux:card>
    <flux:heading size="lg">Flux Select - this won't update</flux:heading>
    {{ $fluxStatus }}
        <flux:select wire:model="industry" placeholder="Choose industry...">
            <flux:option>Photography</flux:option>
            <flux:option>Design services</flux:option>
            <flux:option>Web development</flux:option>
            <flux:option>Accounting</flux:option>
            <flux:option>Legal services</flux:option>
            <flux:option>Consulting</flux:option>
            <flux:option>Other</flux:option>
        </flux:select>
    </flux:card>
</div>
```
Running latest and no published views:
╰─ composer show | grep flux                                                                                                                                                                                         ─╯
livewire/flux                                1.0.18           The official UI component library for Livewire.
livewire/flux-pro                            1.0.18           The pro version of Flux, the official UI component library for Livewire.

Thanks

**Comment by jeffchown** [comment]
@marchampson I'm not familiar with `wire:focus` or `wire:blur` - I know of `wire:model.blur`.
Can you share a link to the docs re: both?

**Comment by jeffchown** [comment]
@marchampson After a little searching, I found one StackOverflow question referring to `wire:focus`, etc. I didn't realize `wire:` made that possible.

When I want to respond to focus, blur, etc., I go the Alpine route.  As Livewire 3 is Alpine under-the-hood, and Flux of course leverages that, have you tried replacing your `wire:focus="lock('normal')"` with `x-on:focus="$wire.lock('normal')"`?

**Comment by marchampson** [comment]
Hey @jeffchown - thanks for jumping in again. 

Just realised I've been a numpty and included the wrong code. My flux:select didn't even have wire:focus/blur on. The basic flux:select DOES work:

```
<?php

use Flux\Flux;
use Livewire\Attributes\On;
use Livewire\Volt\Component;

new class extends Component {

    public $industry;
    public $normalStatus = 'unlocked';
    public $fluxStatus = 'unlocked';

    public function lock($select)
    {
        $this->{$select.'Status'} = 'locked';
    }

    public function unlock($select)
    {
        $this->{$select.'Status'} = 'unlocked';
    }
}; ?>

<div xmlns:flux="http://www.w3.org/1999/html" x-data>
    <flux:card>
        <flux:heading size="lg">Normal Select</flux:heading>
        {{ $normalStatus }}
        <select wire:focus="lock('normal')" wire:blur="unlock('normal')">
            <option value="1">Option 1</option>
            <option value="2">Option 2</option>
            <option value="3">Option 3</option>
        </select>
    </flux:card>
    <flux:card>
        <flux:heading size="lg">Flux Select - basic</flux:heading>
        {{ $fluxStatus }}
        <flux:select wire:focus="lock('flux')" wire:blur="unlock('flux')">
            <flux:option>Photography</flux:option>
            <flux:option>Design services</flux:option>
            <flux:option>Web development</flux:option>
            <flux:option>Accounting</flux:option>
            <flux:option>Legal services</flux:option>
            <flux:option>Consulting</flux:option>
            <flux:option>Other</flux:option>
        </flux:select>
    </flux:card>
    <flux:card>
        <flux:heading size="lg">Flux Select - listbox</flux:heading>
        {{ $fluxStatus }}
        <flux:select wire:focus="lock('flux')" wire:blur="unlock('flux')" variant="listbox" searchable
                     placeholder="Choose industries...">
            <flux:option>Photography</flux:option>
            <flux:option>Design services</flux:option>
            <flux:option>Web development</flux:option>
            <flux:option>Accounting</flux:option>
            <flux:option>Legal services</flux:option>
            <flux:option>Consulting</flux:option>
            <flux:option>Other</flux:option>
        </flux:select>
    </flux:card>
</div>
```
However if I try and make it a searchable listbox, which I'm using in my application it doesn't open. I tried x-on:focus in my application and still no change. 

I do need this to work on searchable selects. Does the above code work for you?  The 3rd listbox select doesn't work at all for me?

Thanks!

**Comment by marchampson** [comment]
But you're absolutely right @jeffchown with regards to **x-on:focus** it certainly works when used on the basic selects:

```
<flux:card>
        <flux:heading size="lg">Flux Select - basic</flux:heading>
        {{ $fluxStatus }}
        <flux:select x-on:focus="$wire.lock('flux')" x-on:blur="$wire.unlock('flux')">
            <flux:option>Photography</flux:option>
            <flux:option>Design services</flux:option>
            <flux:option>Web development</flux:option>
            <flux:option>Accounting</flux:option>
            <flux:option>Legal services</flux:option>
            <flux:option>Consulting</flux:option>
            <flux:option>Other</flux:option>
        </flux:select>
    </flux:card>
```

**Comment by jeffchown** [comment]
@marchampson I noticed your first snippet was incomplete, but knew what you meant to send :) 

I'll try your updated code and let you know.  
I'm pretty sure I understand why this is happening and don't expect the 'locked' on the searchable listbox to work, but I'll confirm.

**Comment by jeffchown** [comment]
@marchampson I tried your code and got the same results.  First 2 selects worked, 3rd didn't.

To the best of my understanding (@calebporzio and @joshhanley are the experts of course), this is because the first 2 examples are native `<select>`s which have all of the focus-related awareness and code built-in.

The `variant="listbox"` example actually becomes a `<ui-select>` element (you can see when inspecting the element using the browser's developer tools) which doesn't seem to fire or respond to any focus-related events.

To confirm this, I added an `id` to each version of the select like this:

```
        <flux:select
            id="test2"
            variant="listbox"
            searchable
            placeholder="Choose industries..."
        >
            <flux:option>Photography</flux:option>
            <flux:option>Design services</flux:option>
            <flux:option>Web development</flux:option>
            <flux:option>Accounting</flux:option>
            <flux:option>Legal services</flux:option>
            <flux:option>Consulting</flux:option>
            <flux:option>Other</flux:option>
        </flux:select>
```

then in the browser's dev tools console, tried to set the select as focused via:

`document.getElementById("test2").focus();`

For the first 2, the selects were focused successfully.  For the 3rd (listbox variant) it did not receive focus.

So, I'm not sure if there's code in the Flux `<ui-select>` code re: focus states or not, or what's involved to set, and respond to, focus events in such a custom input control, but this is as far as I can go :)

Maybe, as a workaround, there's another way to accomplish what you are trying to accomplish in an operational sense.
What are you try to accomplish with the locked/unlocked detection?

**Comment by marchampson** [comment]
Thanks @jeffchown - simply locking and unlocking. Multiple users look at the same form and I lock elements so updates don't get overridden. Possibly overkill but I introduced it and people liked it so I can't really take it away now. 

I previously used select2 and the wire:focus and blur worked well. 

I've sort of got around it with wire:click and wire:change, but if you don't change the option, just open and close the select, then the lock remains until it times out. 

Thanks,
Marc

**Comment by jeffchown** [comment]
@marchampson I suspected something like that.  When I've had to implement something similar, I've always ended up finding it simpler (and easier to maintain) to lock a whole page/form at a time.  Maybe that's not possible in your case, but it does make the code *much* easier - and it has the added benefit of not relying on js.

**Comment by jeffchown** [comment]
I had a suspicion and have also confirmed that the listbox variant also does not respond to `autofocus`

**Comment by marchampson** [comment]
Thanks @jeffchown really appreciate your help and time on this. 

I think I'll block out form sections for now. That should still achieve the desired effect. 

I'll leave this open to see if @calebporzio has anything to add, or if this is something the listbox may be able to do in a future release.

**Comment by jeffchown** [comment]
You're welcome, @marchampson !

That sounds like a good idea.

I'll be interested in @calebporzio 's feedback on this too.

**Comment by calebporzio** [comment]
Yeah, the tricky part is the custom select deconstructs the button from the listbox so it's hard to know what to forward attributes to.

Here is the fix: to use the button slot to attach whatever listeners you want directly to the button. 

```html
<flux:select variant="listbox" searchable>
            <x-slot name="button">
                <flux:select.button wire:focus="lock('flux')" wire:blur="unlock('flux')"  placeholder="Choose industry..." />
            </x-slot>

            <flux:option>Photography</flux:option>
            <flux:option>Design services</flux:option>
            <flux:option>Web development</flux:option>
            <flux:option>Accounting</flux:option>
            <flux:option>Legal services</flux:option>
            <flux:option>Consulting</flux:option>
            <flux:option>Other</flux:option>
        </flux:select>
```

Here's the docs where this pattern came from: https://fluxui.dev/components/select#the-button-slot

Hope this help!

**Comment by marchampson** [comment]
Thanks @calebporzio a bit late in the UK but will try this out tomorrow. Thanks for jumping in and detailing the fix.

**Comment by jeffchown** [comment]
Very interesting, @calebporzio.  Speaks to the composable design of Flux - Thanks!

**Comment by jeffchown** [comment]
@calebporzio Just tried it on @marchampson 's original code and it worked 👍   Thanks.

**Comment by marchampson** [comment]
Thanks @jeffchown and of course @calebporzio - just tried on my original code and can confirm it all works. Just added into my application in one place and working too. Appreciate the help. Top men!
