### ISSUE TITLE
Missing translations for items search

### ISSUE THREAD

**Issue by mnabialek** [livewire/flux#546]
Hi there

In the following files:

- resources/views/flux/options.blade.php
- resources/views/flux/select/variants/combobox.blade.php

there is `No results` text without possibility to translate it. Probably it should be replaced with `{!! __('No results found') !!}` to make it possible to use custom translations.

Btw any possibility to create MR to flux-pro repository or the only way is to create issues here and wait until they will be implemented in other repo?

**Comment by calebporzio** [comment]
Good catch, fixed and will be in the next release.
