### ISSUE TITLE
@fluxStyles in the head section is displaying: @fluxStyles

### ISSUE THREAD

**Issue by lcallif** [livewire/flux#55]
I am using the flux:accordion example which is also displaying all the text as a paragraph.

I have tailwindcss accessed via cdn which seems to be the difference in this app compared to another app that I created from scratch.  Given that I cannot get the Tailwindcss installation to work in this app, I have no choice but to access it via cdn.

Suggestions ?

**Comment by patrykszady** [comment]
I'm sorry but this doesn't seem like a flux issue. It's a question better asked on the [livewire discord](https://discord.com/channels/698229985755791471/1285578027148906546). 

Your tailwind integration questions are answered here. [Laravel Vite Install](https://laravel.com/docs/11.x/vite#main-content) and [Tailwind Laravel Install](https://tailwindcss.com/docs/guides/laravel)

**Comment by lcallif** [comment]
The flux issue still stands as an issue.  Flux should work whether tailwindcss is installed or accessed via cdn.  As such, this issue is still relevant and appropriate where asked.

**Comment by lcallif** [comment]
Thank you for the suggestion!!!  On my todo list for this evening.  Thanks!!!!

**Comment by lcallif** [comment]
Om my goshhhh, it is working!  Thank you christopherarter!!  Your suggestion was 99% of the issue, the other part was where I was putting @fluxScripts.  Yeeeehawwwww!!!!!
