### ISSUE TITLE
Unable to clear selected option

### ISSUE THREAD

**Issue by mnabialek** [livewire/flux#555]
Hi there

It seems after selection option via select it's impossible to clear selection. If should be possible to pass some prop like `clearable` to make possible to remove selected option when option was already selected.

Similar discussion: https://github.com/livewire/flux/discussions/346

Sample design I have in my custom select (that I would like to replace by fluxui):

![Image](https://github.com/user-attachments/assets/1e0e4750-bc7c-4081-88f8-96486530b680)

**Comment by jeffchown** [comment]
@mnabialek Can you provide code that reproduces the issue?

**Comment by lotje-kinable** [comment]
@mnabialek Hi, I used the button.group, see screenshot. The code is below. Don't know if that's what you are looking for. I read your issue and I think you just want to replace the select with red x, to flux. You can leave out the tooltip of course! 

![Image](https://github.com/user-attachments/assets/0910f03a-1a9e-4d1b-b887-accf54f43eeb)


```
<flux:field>
      <flux:label>Label</flux:label>
            <flux:button.group>

                <flux:select wire:model='model' variant="listbox" placeholder='Select a model' searchable required>
                    @foreach($options as $option)
                        <flux:option value="{{ $option->id }}">{{ $option->name }}</flux:option>
                    @endforeach
                </flux:select>


                <flux:button wire:click="clearOption" tooltip="Clear option" icon="x-mark"></flux:button>

            </flux:button.group>

            <flux:error name="model" />
        </flux:field>
```

**Comment by jeffchown** [comment]
@mnabialek As you say, this is similar to https://github.com/livewire/flux/discussions/346 - so it's probably best to close this, as it isn't an issue, and continue in that discussion (https://github.com/livewire/flux/discussions/346)

**Comment by calebporzio** [comment]
This has been implemented (and a bunch more "clearable" improvements to other inputs and search fields). Full context here: https://github.com/livewire/flux/discussions/346#discussioncomment-11123405
