### ISSUE TITLE
CSS color-adjust deprecated

### ISSUE THREAD

**Issue by GianfriAur** [livewire/flux#557]
Hi there! 👋

I found this error adding the css file in a scss compilation process.
It doesn't cause errors but it's quite annoying in console

in practice the color-adjust css property was definitively deprecated in 2022 in favor of print-color-adjust
I attach the portion of code to identify the exact point

```css
select[data-flux-select-native] {
    /* ... */
    color-adjust: exact
}
```

I attach links to other issues in the context of tailwind and postcss

https://github.com/postcss/autoprefixer/issues/1471
https://github.com/tailwindlabs/tailwindcss/issues/8250

also by reading on developer.mozilla.org, on all browsers with limited compatibility with the -webkit-* prefix it works

https://developer.mozilla.org/en-US/docs/Web/CSS/print-color-adjust

**Comment by seabasss** [comment]
+1 on this

**Comment by calebporzio** [comment]
Ah, so what would you have me do? just use "print-color-adjust"? or also keep "-webkit-print-color-adjust"?

**Comment by GianfriAur** [comment]
use `print-color-adjust` instead `color-adjust` and keep `-webkit-print-color-adjust`

**Comment by calebporzio** [comment]
Thanks for the info - fixed and will be in the next release
