### ISSUE TITLE
Sidebar Profile: truncate for long names are not working

### ISSUE THREAD

**Issue by BubeDameKoenig** [livewire/flux#558]
If the name is longer, the `truncate` in the `profile` does not work and a horizontal scrollbar is displayed.

![Image](https://github.com/user-attachments/assets/a32f5772-6208-419e-8c43-89d300a1bd61)

I copied the code 1:1 from the sidebar documentation:
https://fluxui.dev/layouts/sidebar

**Comment by calebporzio** [comment]
Good catch - fixed in next release
