### ISSUE TITLE
Validation for nested data array

### ISSUE THREAD

**Issue by stursby** [livewire/flux#561]
Hey there! Not sure if this is a bug or a feature request... but I'm working on a form builder, so the wire model for the component is an array of form fields, and when I add validation, these are the error messages I'm seeing:

![Image](https://github.com/user-attachments/assets/dbc065f1-72f8-4cb6-a3d5-3788888d2f49)

I made a demo repo here --> https://github.com/stursby/flux-form-data-array-error-messages-demo

Mainly the Livewire [Demo](https://github.com/stursby/flux-form-data-array-error-messages-demo/blob/main/app/Livewire/Demo.php) component, the `$fields` array is just for demo purposes, that comes from the Database in my real application.

Is there a way to get the errors to use the friendlier label name? ie: "The Full Name field is required"

**Comment by jeffchown** [comment]
@stursby This is actually a Livewire question, not Flux.  This doc may help: https://livewire.laravel.com/docs/validation#custom-attribute-names

**Comment by stursby** [comment]
@jeffchown got it... not sure how to integrate that with an array tho as the Docs only specific using it with attributes 🤔

Since, in my case, the `$rules` array is dynamic based on the `$fields`

basically:

1. Dynamic fields

```php
public array $fields = [
    [
      'label' => 'Full Name',
      'description' => 'Please enter your full name.',
      'placeholder' => 'John Doe',
      'rules' => 'required|max:255',
    ],
    [
      'label' => 'Email',
      'description' => 'Please enter your email address.',
      'placeholder' => 'john@example.com',
      'rules' => 'required|email|max:255',
    ]
  ];
```

2. Render them out in a loop

```blade
<form wire:submit="save" class="p-6 space-y-6">
    @foreach ($fields as $field)
        <flux:input wire:model="data.{{ $field['label'] }}" label="{{ $field['label'] }}"
            description="{{ $field['description'] }}" placeholder="{{ $field['placeholder'] }}" />
    @endforeach

    <div>
        <flux:button variant="primary" type="submit">Submit</flux:button>
    </div>
</form>
```

3. Dynamic rules based on `$fields`

```php
public function save()
  {
    $rules = [];

    foreach ($this->fields as $field) {
      $rules["data.{$field['label']}"] = $field['rules'];
    }

    $validated = $this->validate($rules);

    dd($validated);
  }
```

**Comment by jeffchown** [comment]
@stursby I see.  That does make things more complicated.

Might be something in this doc section: https://livewire.laravel.com/docs/validation#defining-a-rules-method
that could help.  Specifically, the `validationAttributes()` method that allows you to 'alias' your properties' names in validation messages, e.g.:

```
public function validationAttributes() 
    {
        return [
            'content' => 'description',
        ];
    }
```

**Comment by stursby** [comment]
@jeffchown Nice! That totally works! TIL 😂

Thank you for your help!

Here's what I ended up adding:

```php
public function validationAttributes()
  {
    $attributes = [];

    foreach ($this->fields as $field) {
      $attributes["data.{$field['slug']}"] = $field['label'];
    }

    return $attributes;
  }
```

**Comment by jeffchown** [comment]
Great!  You're welcome, @stursby 👍
