### ISSUE TITLE
Flux pro repository access

### ISSUE THREAD

**Issue by mnabialek** [livewire/flux#562]
Hi there

Is it expected that pro users have access to flux-pro repository?

Without it, it's hard to say what was changed during releases. I'm taking a look at https://github.com/livewire/flux/releases and there are links to MRs in flux-pro repo, but I'm getting 404 errors for them as I don't have access to flux pro repository.

**Comment by itsgrimace** [comment]
Change log for pro can be found here.

[https://changelog.anystack.sh/flux-pro](https://changelog.anystack.sh/flux-pro)

**Comment by lotje-kinable** [comment]
@mnabialek and @itsgrimace I found this yesterday: [blog](https://fluxui.dev/blog)

**Comment by calebporzio** [comment]
I copy the pro changelog over to the public repo. I don't want to make the pro repo public (well private but public to purchasers) at this point.

I will try to start linking blog post URLs in changelogs if blog posts are written for a release.

Thanks.
