### ISSUE TITLE
Checkbox.all not working in table using pagination

### ISSUE THREAD

**Issue by cstisa** [livewire/flux#569]
Hi,

I encountered an unexpected behaviour using checkbox.all with a table using pagination.

On the first page of my table, I can select all rows with a working checkbox.all.
But when I'm switching on the second page using pagination, and going back, all my checkboxes won't be cehcked anymore.

Selecting all rows :

![Image](https://github.com/user-attachments/assets/a80b38f7-428e-4c4a-a3c3-fa21fb970c70)

Going to second page :

![Image](https://github.com/user-attachments/assets/04774e4f-16ef-46d7-b0d7-5b84cd7e6a63)

(first wrong behaviour, the checkbox.all should be indeterminate)

Going back to first page :

![Image](https://github.com/user-attachments/assets/021846a3-cd67-4383-8b5c-9696184e1dec)

(Second wrong behaviour, where all my checkboxes should checked)

Here's my blade template :

```
<flux:card class="min-w-fit max-w-full">

    <flux:checkbox.group wire:model="selectedIds">

        <flux:table :paginate="$this->articles">

            <flux:columns>

                <flux:column>
                    <flux:checkbox.all />
                </flux:column>
            </flux:columns>

            <flux:rows>
                @foreach ($this->articles as $article)
                    <flux:row wire:key="'row-'{{ $article->id }}">

                        <flux:cell>
                            <flux:checkbox value="{{ $article->id }}" />
                        </flux:cell>

                        <flux:cell class="w-96 text-wrap">
                            {{ $article->title }}
                        </flux:cell>

                        <flux:cell>
                            {{ $article->dateForHumans() }}
                        </flux:cell>

                    </flux:row>
                @endforeach
            </flux:rows>
        </flux:table>

    </flux:checkbox.group>

</flux:card>

```

My Livewire component (I just showed the basic) : 

```
<?php

namespace App\Livewire\Article;

use Livewire\Attributes\Computed;
use Livewire\Component;
use App\Models\Article;
use Illuminate\Database\Eloquent\Builder;

class ArticleManagement extends Component
{
    use \Livewire\WithPagination;
    public $sortBy = 'updated_at';
    public $sortDirection = 'desc';
    public array $selectedIds = [];

    public function sort($column)
    {
        if ($this->sortBy === $column) {
            $this->sortDirection = $this->sortDirection === 'asc' ? 'desc' : 'asc';
        } else {
            $this->sortBy = $column;
            $this->sortDirection = 'asc';
        }
    }

    #[Computed]
    public function articles()
    {
        $query = $this->query();

        if ($this->sortBy) {
            $query->orderBy($this->sortBy, $this->sortDirection);
        }

        return $query->paginate(10);
    }

    protected function query(): Builder
    {
        $this->authorize('viewAny', Article::class);

        return Article::query();
    }

    public function render()
    {
        return view('livewire.article.article-management');
    }
}


```

Does anyone have the same problem?

**Comment by ju5t** [comment]
Can you make an example with an array instead of using a model? To speed things up it helps if Caleb, or anyone who tries to help, can just copy/paste your code needing to add models and such.

**Comment by Kh4os-afk** [comment]
Hi Bro!

Just try :checked="in_array($article->id,$selectedIds)"

```
<flux:cell>
          <flux:checkbox value="{{ $article->id }}" :checked="in_array($article->id,$selectedIds)"/>
</flux:cell>
```

**Comment by cstisa** [comment]
> Hi Bro!
> 
> Just try :checked="in_array($article->id,$selectedIds)"
> 
> ```
> <flux:cell>
>      <flux:checkbox value="{{ $article->id }}" :checked="in_array($article->id,$selectedIds)"/>
> </flux:cell>
> ```

Thank you!! It works like a charm!
