### ISSUE TITLE
Checkbox (Error Message) Misaligns Label Text

### ISSUE THREAD

**Issue by WorthLMS** [livewire/flux#57]
<flux:checkbox wire:model="form.enabled" label="Login Enabled" />

![image](https://github.com/user-attachments/assets/6269d8ea-d410-4cfb-aedf-4df6d8a3be72)
![image](https://github.com/user-attachments/assets/a106fe18-d228-4c87-9bd2-8b3aac08e01b)

**Comment by bzarzuela** [comment]
I fixed this by using a checkbox group and binding the model to it. The error text is rendered correctly.

**Comment by joshhanley** [comment]
@WorthLMS I just tested this with the latest version v1.0.6 and it is working as expected, so I'm going to close this issue. Please update and test again. Thanks!

![Image](https://github.com/user-attachments/assets/323bd4ac-3dc5-49a4-b6ac-38ad456aa203)
