### ISSUE TITLE
x-bind:checked on menu.checkbox

### ISSUE THREAD

**Issue by mauritskorse** [livewire/flux#571]
Using `x-bind:checked` on a `flux:menu.checkbox` component does not work. 
On a normal `flux:checkbox` component binding alpine data to the checked attribute does work.

This does not work:

```blade
<div x-data="{columns: { title: true, created_at: true, updated_at: false }}">
  <template x-for="column in Object.keys(columns)" :key="column">
      <flux:menu.checkbox @click="columns[column] = !columns[column]" x-bind:checked="columns[column]">
         <span x-text="column"></span> 
      </flux:menu.checkbox>
  </template>
</div>
```

This works:

```blade
<div x-data="{columns: { title: true, created_at: true, updated_at: false }}">
  <template x-for="column in Object.keys(columns)" :key="column">
    <flux:checkbox @click="columns[column] = !columns[column]" x-bind:checked="columns[column]" />
  </template>
</div>
```

When testing this out, I noticed that `x-bind:label` on `flux:checkbox` doesn't work either.

**Comment by calebporzio** [comment]
I recommend using `x-model="columns[column]"` to control the state instead. because these aren't native checkboxes, Alpine doesn't pick them up as such and set `.checked = ` from the x-binding.
