### ISSUE TITLE
<flux:select> visually flashes on validation errors in full page component

### ISSUE THREAD

**Issue by LasseRafn** [livewire/flux#572]
(info + video below)

Doesn't happen in any other components afaik, only the `<flux:select>` one. 

> [!NOTE]
> It happens even if the validation error is not on the select itself. If there is any validation error in any of the fields, it happens for the select elements in the form.

I have not published/modified the components

Here is a short version

```blade
<form wire:submit="startImport">
  <div class="flex-1 flex flex-col gap-8">
      <flux:input class="w-64" wire:model="cookie_lifetime" type="number" label="Program Cookie Days" description="How many days does the click last"/>
      <flux:select wire:model="price_currency" placeholder="Choose Currency" label="Price Currency" description="Determines how we display which currency the prices are in.">
          @foreach(['DKK', 'USD'] as $currency)
              <flux:option value="{{ $currency }}">{{ $currency }}</flux:option>
          @endforeach
      </flux:select>
  </div>
  <flux:button type="submit" variant="primary">Import</flux:button>
</form>
```

```php
<?php

namespace App\Livewire\Catalogue;

use App\Models\Product;
use App\Models\Site;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Validate;
use Livewire\Component;

class Import extends Component
{
    #[Validate( [ 'required', 'integer' ] )]
    public int $cookie_lifetime = 30;

    #[Validate( [ 'required', 'string', 'min:3', 'max:3' ] )]
    public string $price_currency = '';

    public function render()
    {
        return view( 'livewire.catalogue.import' );
    }

    public function startImport()
    {
        $this->validate();

        $this->validate( [
            'price_currency' => [ Rule::in( ['DKK', 'USD'] ) ], // this is actually a list from a third party package, which I cannot put into #[Validate...] format, hence the separate validation code. Just simplified it here to replicate easier
        ] );

        // logic 

        session()->flash( 'success', 'Products imported successfully.' );
        $this->redirectRoute( 'catalogue.index' );
    }
}
```

Flux + Flux Pro v1.0.18
Browser: Safari Version 17.6 (19618.3.11.11.5)
Video: 

https://github.com/user-attachments/assets/06f670f9-cce3-4763-943c-71157ae69848

**Comment by calebporzio** [comment]
Yeah, I agree that feels weird. What's happening is, Livewire marks select inputs as "disabled" during a form submission and Flux styles disabled fields to be more transparent.

You aren't seeing it on the input above the select because text inputs get marked as readonly instead of disabled.

This is behavior that has been in Livewire for years but I think it's time we revisit it for the next version.

Thanks for the report but I'm going to close this because I don't see anything we can do right now from Flux's end.

Thanks.
