### ISSUE TITLE
Issues with Embedding Additional Form Elements in a Radio Group

### ISSUE THREAD

**Issue by seabasss** [livewire/flux#578]
Hi,

Is there a way to include other form elements within a radio group? In the example below, changing the value in the select box unintentionally alters the payment value, which is unexpected.

```html
<flux:radio.group wire:model.live="payment" label="Select your payment method">
    <flux:radio value="cc" label="Credit Card" checked />
    <flux:radio value="paypal" label="Paypal" />
    <div class="flex space-x-4">
        <flux:radio value="other" label="Other" />
        <flux:select wire:model.live="otherExtraOption">
            @for ($i = 1; $i <= 10; $i++)
                <flux:option value="{{ $i }}">{{ $i }}</flux:option>
            @endfor
        </flux:select>
    </div>
</flux:radio.group>
```

I also tried setting name="payment" on the flux:radio items, but it didn’t help.

Thanks!

**Comment by jeffchown** [comment]
@seabasss Interesting.  Looks like the change event triggered by a change in the `flux:select` also bubbles up to the `flux:radio.group`.  

@calebporzio @joshhanley is this the same behaviour for all input components?  Or do they usually `.stop` the @change from propagation?

**Comment by joshhanley** [comment]
@jeffchown yeah generally inputs (native and flux) will dispatch events that bubble up. The issue is likely that the radio group will be listening for events inside of it, to keep track of which radio button has been selected/ clicked on.

**Comment by jeffchown** [comment]
@joshhanley So, based on that, would a possible workaround for @seabasss 's original question/issue be to `.stop` the `@change` and `@input` from the select from bubbling up? e.g.:

```
<div>
    <flux:radio.group wire:model.live="payment" label="Select your payment method">
        <flux:radio value="cc" label="Credit Card" checked />
        <flux:radio value="paypal" label="Paypal" />
        <div class="flex space-x-4">
            <flux:radio value="other" label="Other" />

            <div @input.stop @change.stop>
                <select wire:model.live="otherExtraOption">
                    @for ($i = 1; $i <= 10; $i++)
                        <flux:option value="{{ $i }}">{{ $i }}</flux:option>
                    @endfor
                </select>
            </div>

        </div>
    </flux:radio.group>
</div>
```

Could there be any unexpected side-effects to this pattern that you can think of?  Or any other events that need to be `.stop`ped?

**Comment by seabasss** [comment]
@jeffchown Thanks! Wrapping the select in `<div @input.stop>` worked. Not sure if there any any other implications.

**Comment by jeffchown** [comment]
You're welcome, @seabasss !

**Comment by calebporzio** [comment]
Glad you got this resolved for now with the workaround - I'll have to think if I want to support other form inputs inside a radio group. I could see the value but also it may not be worth the added complexity. Thanks for the report. I will keep an eye on people needing this behavior to work. Thanks.
