### ISSUE TITLE
No Licence details for flux pro in documentation

### ISSUE THREAD

**Issue by David-Grass-Feria** [livewire/flux#582]
Hello. I miss some details for flux pro. 
I created opensorce cms systems in germany for shared hosting.
Is it possible to publish all the views and remove flux pro from composer dependencies, and make the cms opensource?

Here is are example of tailwind ui license details:
`

Use the Components and Templates to create unlimited End Products for unlimited Clients.
Use the Components and Templates to create End Products where the End Product is sold to End Users.
Use the Components and Templates to create End Products that are open source and freely available to End Users.

`

**Comment by ju5t** [comment]
@David-Grass-Feria it's in the terms, I think they're pretty clear.

> You cannot
> ...
> Use Flux in open source projects or make your End Product open source if it includes Flux components or derivatives.

See: https://fluxui.dev/terms

**Comment by David-Grass-Feria** [comment]
Sorry, i dont know why i have not see the terms. This can closed.
