### ISSUE TITLE
Search modes

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#583]
This is not necessarily a bug, but I'm not sure if it's a feature request either. In [v1.0.15](https://github.com/livewire/flux/releases/tag/v1.0.15) fuzzy search replaced starts with because of #364. Strictly speaking this has been a breaking change.

We have a use-case for starts with but are unable to do so, because the change has been made in JS. I think it makes sense to have starts with, ends with, exact and contains as possible search modes.

**Comment by calebporzio** [comment]
Yeah, I consider this more a feature request. I would be open to adding it but will need more time to make sure we have the right API. Please open a feature request in the discussions if you haven't already.

Also, you're right that it may have been a breaking change - it's hard to say. Many felt it was broken before seeing as how native <datalist> elements use .includes for autocomplete search.

Anyhow, we should probably add it, but yea - it would be more of a feature request.

Thanks

**Comment by ju5t** [comment]
For future readers' reference, the feature request can be found here: https://github.com/livewire/flux/discussions/587.
