### ISSUE TITLE
Checkboxes in a group are not checked

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#585]
This is a follow-up of the discussion in https://github.com/livewire/flux/issues/467#issuecomment-2453083510. There seem to be two different issues with this:

1. Checkboxes are not visually checked.
2. Checkboxes are not checked it's `wire:model`'ed to a property that has no default value or is set to null. 

For the first issue, `$notifications` is set to an empty array.

```blade
<?php
\Livewire\Volt\state(['notifications' => []]);
?>

<div class="flex p-6">
    <div class="space-x-0 space-y-3 lg:space-y-3 lg:space-x-0 lg:mt-0">
        @json($notifications)
        <flux:checkbox.group wire:model.live="notifications" label="Notifications">
            <flux:checkbox label="Push notifications" value="push" />
            <flux:checkbox label="Email" value="email" />
            <flux:checkbox label="In-app alerts" value="app" />
            <flux:checkbox label="SMS" value="sms" />
        </flux:checkbox.group>
    </div>
</div>
```

It does add `data-checked` to the UI element for a checkbox, but visually it remains unchecked.

When the `$notifications` property doesn't have a default value, it doesn't work at all. There is no request going to the backend either because there's a JS error in the console:

```
flux.js?id=42c8a4e8:2071 Uncaught TypeError: Cannot read properties of null (reading 'map')
    at SelectableGroup.setState (flux.js?id=42c8a4e8:2071:47)
    at flux.js?id=42c8a4e8:2328:26
    at Controllable.setterFunc (flux.js?id=42c8a4e8:1522:7)
    at _UICheckboxGroup.set (flux.js?id=42c8a4e8:1853:16)
    at bindInputValue (livewire.js?id=38dc8241:2006:16)
    at bind (livewire.js?id=38dc8241:1960:9)
    at livewire.js?id=38dc8241:3396:23
    at mutateDom (livewire.js?id=38dc8241:885:18)
    at el._x_forceModelUpdate (livewire.js?id=38dc8241:3396:7)
    at livewire.js?id=38dc8241:3403:10
```

**Comment by jeffchown** [comment]
@ju5t I tried your code and:

1. I can't recreate the issue - checkboxes, both if set as default in `$notifications` and if clicked, are correctly visually checked for me
2. I **was** able to recreate this one.  If `$notifications` is == `null`, then I receive the same error in the console and no request to the back-end is sent upon click(s).  I assume this is some check for a valid property type in the JS before bothering with a `livewire/update` network request.

**Comment by DinoVincent** [comment]
Does anyone know a work around around issue 2?

**Comment by jeffchown** [comment]
@DinoVincent I would normally ensure such a property was an array, empty or otherwise.

I'm having a tough time thinking of when this might not be the case - can you describe a scenario in which this wouldn't be possible (or not desired)?

**Comment by ju5t** [comment]
@jeffchown that's odd. I'm testing this on a fresh Laravel installation on the latest version. Caches are cleared. I can replicate it in Chrome, Safari & Firefox on MacOS. I'll do some more debugging.

![Image](https://github.com/user-attachments/assets/d8d244bb-d316-47f8-b2fd-6d996b4042c8)

About 2: setting the property to an empty array solves it. Although it's an easy fix on the PHP side, arguably there's a null-check missing on the JavaScript side of things.

**Comment by calebporzio** [comment]
Thanks for the report - I fixed the second, `null` default, issue. The first one, I too cannot reproduce

**Comment by ju5t** [comment]
@calebporzio thanks, turns out I forgot to run `npm run build` on that one 🤦
