### ISSUE TITLE
Spinner on every row's action button when one button is clicked

### ISSUE THREAD

**Issue by gaelicwinter** [livewire/flux#586]
Hi there! 👋

Not sure if I am missing something or if this is a real issue.  With a table with multiple rows, each row containing a Flux button tied to a component method, the button automatically changes to a spinner icon when clicked, and returns to normal when the component is re-rendered.  However, with multiple rows, even with wire:key on each row and/or on each button, every single button changes to a spinner, not just the clicked button.  Here is a minimal example:

`<?php

namespace App\Livewire;

use Livewire\Component;

class TestTable extends Component
{
    public $people;

    public function mount()
    {
        $this->people =
            [
                ['name' => 'John Doe'],
                ['name' => 'John Smith'],
                ['name' => 'John Rhubarb'],
                ['name' => 'John Johnson'],
        ];
    }

    public function flip($k)
    {
        $this->people[$k]['name'] = strrev($this->people[$k]['name']);
    }

    public function render()
    {
        return view('livewire.test-table');
    }
}
`

`<div>
    {{-- In work, do what you enjoy. --}}
    <flux:table>
        <flux:columns>
            <flux:column>Person</flux:column>
            <flux:column>Manage</flux:column>
        </flux:columns>

        <flux:rows>
            @foreach($people as $k => $person)
{{--                <flux:row wire:key="flip-{{ $k }}">--}}
                <flux:row>
                    <flux:cell>{{ $person['name'] }}</flux:cell>
                    <flux:cell>
{{--                        <flux:button size="sm" wire:click="flip('{{ $k }}')">Flip</flux:button>--}}
                        <flux:button wire:key="flipbtn-{{ $k }}" size="sm" wire:click="flip('{{ $k }}')">Flip</flux:button>
                    </flux:cell>
                </flux:row>
            @endforeach
        </flux:rows>
    </flux:table>
</div>
`![Image](https://github.com/user-attachments/assets/5c6087d2-1ed4-4797-866e-64e277b288bd)

**Comment by calebporzio** [comment]
Please re-submit with copy-pastable code in a single snippet - this issue is malformed
