### ISSUE TITLE
Buttons in table rows show loading spinner for all rows simultaneously

### ISSUE THREAD

**Issue by gaelicwinter** [livewire/flux#588]
Resubmitted with better formatting.

With a table with multiple rows, each row containing a Flux button tied to a component method, the button automatically changes to a spinner icon when clicked, and returns to normal when the component is re-rendered. However, with multiple rows, even with wire:key on each row and/or on each button, every single button changes to a spinner, not just the clicked button. Here is a minimal example:

TestTable.php
```
<?php

namespace App\Livewire;

use Livewire\Component;

class TestTable extends Component
{
    public $people;

    public function mount()
    {
        $this->people =
            [
                ['name' => 'John Doe'],
                ['name' => 'John Smith'],
                ['name' => 'John Rhubarb'],
                ['name' => 'John Johnson'],
        ];
    }

    public function flip($k)
    {
        $this->people[$k]['name'] = strrev($this->people[$k]['name']);
    }

    public function render()
    {
        return view('livewire.test-table');
    }
}
```
test-table.blade.php
```
<div>
    {{-- In work, do what you enjoy. --}}
    <flux:table>
        <flux:columns>
            <flux:column>Person</flux:column>
            <flux:column>Manage</flux:column>
        </flux:columns>

        <flux:rows>
            @foreach($people as $k => $person)
{{--                <flux:row wire:key="flip-{{ $k }}">--}}
                <flux:row>
                    <flux:cell>{{ $person['name'] }}</flux:cell>
                    <flux:cell>
{{--                        <flux:button size="sm" wire:click="flip('{{ $k }}')">Flip</flux:button>--}}
                        <flux:button wire:key="flipbtn-{{ $k }}" size="sm" wire:click="flip('{{ $k }}')">Flip</flux:button>
                    </flux:cell>
                </flux:row>
            @endforeach
        </flux:rows>
    </flux:table>
</div>
```
Instantiation
```
<livewire:test-table />
```
![Image](https://github.com/user-attachments/assets/92dd2e8a-d75b-4098-9a9f-f2e95c36cf8d)

**Comment by DinoVincent** [comment]
using wire:target should do the trick.

From the livewire docs:
>Targeting specific actions
By default, wire:loading will be triggered whenever a component makes a request to the server.

However, in components with multiple elements that can trigger server requests, you should scope your loading indicators down to individual actions.

For example, consider the following "Save post" form. In addition to a "Save" button that submits the form, there might also be a "Remove" button that executes a "remove" action on the component.

By adding wire:target to the following wire:loading element, you can instruct Livewire to only show the loading message when the "Remove" button is clicked:
```
<form wire:submit="save">
    <!-- ... -->
 
    <button type="submit">Save</button>
 
    <button type="button" wire:click="remove">Remove</button>
 
    <div wire:loading wire:target="remove">  
        Removing post...
    </div>
</form>
```
When the above "Remove" button is pressed, the "Removing post..." message will be displayed to the user. However, the message will not be displayed when the "Save" button is pressed.


[https://livewire.laravel.com/docs/wire-loading#basic-usage](url)

**Comment by gaelicwinter** [comment]
That absolutely did the trick thanks for the hint!  Here is my final blade file:

```
<div>
    {{-- In work, do what you enjoy. --}}
    <flux:table>
        <flux:columns>
            <flux:column>Person</flux:column>
            <flux:column>Manage</flux:column>
        </flux:columns>

        <flux:rows>
            @foreach($people as $k => $person)
                <flux:row wire:key="flip-{{ $k }}">
                    <flux:cell>{{ $person['name'] }}</flux:cell>
                    <flux:cell>
                        <flux:button size="sm" wire:target="flip({{ $k }})" wire:click="flip({{ $k }})">
                            Flip
                        </flux:button>
                    </flux:cell>
                </flux:row>
            @endforeach
        </flux:rows>
    </flux:table>
</div>
```

**Comment by jeffchown** [comment]
@gaelicwinter @DinoVincent FYI here's a link to this exact use case in the Livewire docs: https://livewire.laravel.com/docs/wire-loading#targeting-action-parameters
