### ISSUE TITLE
Dropdown offset property?

### ISSUE THREAD

**Issue by tanshiqi** [livewire/flux#59]
In flux video: https://x.com/calebporzio/status/1838227011564679651
I saw that the "offset" property is used to adjust the horizontal offset, but I couldn't find relevant information in the documentation. Additionally, how can I also apply offset in the vertical direction?
<img width="745" alt="CleanShot 2024-09-25 at 11 08 51@2x" src="https://github.com/user-attachments/assets/b22f6b25-0fc1-4150-a221-a32c18ae21c2">

**Comment by calebporzio** [comment]
Mmm good catch - just added to the documentation. Thanks!

https://flux-docs.test/components/dropdown#offset
