### ISSUE TITLE
link component aria-hidden issue

### ISSUE THREAD

**Issue by clarkeash** [livewire/flux#593]
Hi I noticed a potential accessibility issue (not my area of expertise).
I have the following as part of my login form:

```html
<div class="space-y-6">
            <flux:input wire:model='email' label="Email" type="email" placeholder="Your email address" />

            <flux:field>
                <flux:label class="flex justify-between">
                    Password
                    <flux:link href="{{ route('password.reset') }}" variant="subtle">Forgot password?</flux:link>
                </flux:label>

                <flux:input wire:model='password' type="password" placeholder="Your password" />

                <flux:error name="password" />
            </flux:field>

            <flux:checkbox wire:model="remember" label="Remember me" />
</div>
```
When I tab from the username to password the password reset link is focused first and I get this error in the console.

> Blocked aria-hidden on a <a> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. 

```html
<a class="inline text-inherit font-medium underline-offset-[6px] decoration-zinc-800/20 hover:decoration-current no-underline text-zinc-500 dark:text-white/70 hover:text-zinc-800 dark:hover:text-white dark:decoration-white/20" href="http://demo.test/password-reset" data-flux-link="">Forgot password?</a>
```

I am not sure if this is something that can be fixed on the link component or if theres a property I need to set etc, as there are no docs for this component.

Thanks

**Comment by ju5t** [comment]
You shouldn't add links inside a label element. Can you try moving the link elsewhere?

**Comment by clarkeash** [comment]
I was just copying the card example https://fluxui.dev/components/card
But yeah I guess it can be removed from the label

**Comment by calebporzio** [comment]
Yeah good call. I updated all the docs code snippets to use this, accessible version, instead:

```html
<div class="mb-3 flex justify-between">
    <flux:label>Password</flux:label>

    <flux:link href="#" variant="subtle" class="text-sm">Forgot password?</flux:link>
</div>
```
