### ISSUE TITLE
Getting error using @click on checkbox

### ISSUE THREAD

**Issue by DonCamillo11** [livewire/flux#598]
When I use `@click` with a checkbox, I get the following error:
`syntax error, unexpected token "@", expecting variable or "{" or "$"`

it worked until a few updates. It is also working with `x-on:click` but noch with `@click`.

Assigning classes doesn't work anymore either.
`<flux:checkbox class="!bg-sky-200" />`

**Comment by igmltd** [comment]
has a similar issue with shorthand bind `:` , i just use `x-bind:` or `x-on:` , makes the code a little clearer

**Comment by igmltd** [comment]
a bit hacky but this works:

` <flux:checkbox class="[&>div]:!bg-sky-200" />`

**Comment by DonCamillo11** [comment]
> has a similar issue with shorthand bind `:` , i just use `x-bind:` or `x-on:` , makes the code a little clearer

This is a common Alpine shorthand syntax, so I think it should work.

> a bit hacky but this works:
> 
> ` <flux:checkbox class="[&>div]:!bg-sky-200" />`

This doesn’t seem to work for me

**Comment by calebporzio** [comment]
This has been fixed in v1.0.21
