### ISSUE TITLE
`clearable` on `flux:input` does not auto-hide if there is no placeholder specified

### ISSUE THREAD

**Issue by SRWieZ** [livewire/flux#603]
In the current state, `clearable` needs a `placeholder` defined to work properly. 
Without it, it doesn't auto-hide the clear button.

Tested on Safari 18.1 (20619.2.8.11.10)

**Code to reproduce:**

```blade
<flux:input clearable />
```

**Screenshot:**
![Image](https://github.com/user-attachments/assets/c1a5b678-250a-4281-81bb-6e731ae895f1)

**Comment by calebporzio** [comment]
Yeah, this is a side-effect of the CSS property we are using to hide it: `:placeholder-shown`

I don't see a non-hacky way to remove it without a placeholder and I also don't think it's the worst outcome to always show it. Therefore, I'm going to close this - thanks
