### ISSUE TITLE
Flux:button with empty icon crashes app

### ISSUE THREAD

**Issue by danito** [livewire/flux#604]
Hi,

When I add _icon=""_ to a flux:button, I get an time out error.
```html
<flux:button size="sm" variant="ghost" icon=""
                            icon-trailing="arrow-up-right">
                        </flux:button>
```

Best,

Daniel

**Comment by jeffchown** [comment]
@danito Confirmed.  Same thing happens here.  Also when `icon-trailing=""`

**Comment by MathieuB27** [comment]
Why leaving and empty icon="" or icon-trailing="" it's like leaving and empty class="". It's a NO NO ;)
