### ISSUE TITLE
Update 1.0.20 Modal click outside unintentionally when changing tab if smaller content

### ISSUE THREAD

**Issue by MathieuBujold** [livewire/flux#607]
Hi,

When a modal contains tabs of different sizes, clicking on the tab navigation can change the modal’s size to fit the smaller content of the selected tab. This will cause the the mouse release will be outside the modal (perhaps unintentionally), the modal closes.

You can reproduce this by clicking inside the modal, and then releasing the mouse outside the modal area, which causes it to close.

Currently, there’s no option to prevent a modal from closing when clicking outside, and I rely on this feature frequently.

Thanks,
Mathieu

**Comment by bnussbau** [comment]
+1

**Comment by calebporzio** [comment]
Good call. I added the following API to disable this behavior. Will be in the next release.

![Image](https://github.com/user-attachments/assets/90b64a4e-a8a2-4451-bafa-4c06b9f8cfa4)
