### ISSUE TITLE
Clicking X on <flux:select clearable> does not send network request or update wire:model

### ISSUE THREAD

**Issue by booni3** [livewire/flux#614]
While this is not documented, the clearable icon does show, yet does not send a network request.

```html
<flux:select wire:model.live="currency" variant="listbox" searchable clearable>
    <flux:option>GBP</flux:option>
    <flux:option>EUR</flux:option>
    <flux:option>USD</flux:option>
</flux:select>
```

![Image](https://github.com/user-attachments/assets/f774b49a-282f-4660-9675-a28bfcbad6ba)

Potentially similar to #255 

The only way to clear the select at the moment is something like:

```html
<flux:option value="">All</flux:option>
```

**Comment by calebporzio** [comment]
Good catch - fixed and will be in the next release
