### ISSUE TITLE
Simple checkbox component does not react

### ISSUE THREAD

**Issue by RezaODB** [livewire/flux#615]
A very simple checkbox does not react on my form! It works perfectly fine with a non-flux checkbox. Please help! Thanks

CreateQuestion.php

class CreateQuestion extends Component
{
    public $required = false;

    public function save()
    {
        $validated = $this->validate([ 
            'required' => 'nullable|boolean',
        ]);
}

create-question.blade.php

<form wire:submit="save">
    
    <flux:checkbox wire:model="required" label="Marquer la réponse comme requise" />

    @csrf

    <flux:button type="sumbit" variant="primary">Sauvegarder</flux:button>

</form>

**Comment by jeffchown** [comment]
@RezaODB See https://github.com/livewire/flux/issues/611

**Comment by RezaODB** [comment]
Yes you are absolutely right, thanx! It's the same issue with the label!

**Comment by calebporzio** [comment]
Thanks for the report. This has been fixed and will be released shortly
