### ISSUE TITLE
NavBar.item does not match hrefs generated by absolute routes

### ISSUE THREAD

**Issue by drjermy** [livewire/flux#616]
NavBar.Item `will try to automatically detect and mark the current page based on the href attribute passed in`.

If I use `:href="route('my-awesome-route')`, the auto-current matching fails because it's looking for a relative URL, and the route generates the absolute URL.

This is fixable by the user using `route('my-awesome-route', absolute: false)`.

Should the auto-current check match against hrefs generated by absolute routes too?

**Comment by ju5t** [comment]
It depends. If your `APP_URL` is different it doesn't work. We do this `:current="request()->routeIs('my-awesome-route')"`. This also allows us to match wildcards such as `request()->routeIs('pages.*')`. I prefer to be in control.

You may want to check #311 as well.

**Comment by drjermy** [comment]
route('my-awesome-route') produces: `http://localhost/my-awesome-route`
route('my-awesome-route', absolute: false) produces: `/my-awesome-route`

APP_URL is 'http://localhost'

I have already done `request()->routeIs('pages.*')` which works, but it feels like there might be a better default for this component meaning that people don't get confused when they use a route as their href and it doesn't auto-match.

**Comment by calebporzio** [comment]
Thanks for your help on this @ju5t  - if someone can supply something reliably reproducible we can look deeper into this. Otherwise, closing for now.
