### ISSUE TITLE
Using wire:model and x-model in flux:radio.group

### ISSUE THREAD

**Issue by kadcore** [livewire/flux#618]
Not sure if this is a bug or user issue, but using wire:model in the radio.group and x-model on the individual flux radio buttons does not work as supposed to a tradional approach with elements and alpineJS.  The following is what I am trying to achieve:

I am currently using flux version 1.0.19

### <div x-data="{ ifYes: '{{ old('involved') == 'Yes' ? true : false }}', selectedOption: '', setFocus() { this.$nextTick(() => { if (this.selectedOption === 'NO' || this.selectedOption === 'N/A') this.$refs.textarea.focus(); }) } }">
    <div class="flex col-span-12">
        <flux:radio.group wire:model="ethics_fld" class="flex">
            <flux:radio x-on:click="ifYes=true" x-model="selectedOption" value="YES" label="{{  __('Yes') }}" />
            <flux:radio x-on:click="ifYes=false" x-model="selectedOption" value="NO" label="{{  __('No') }}" />
            <flux:radio x-on:click="ifYes=false" x-model="selectedOption" value="N/A" label="{{  __('Not Required') }}" />
        </flux:radio.group>
    </div>
    <div class="col-span-12">
        <flux:textarea
            x-bind:disabled="selectedOption == 'YES'"
            x-ref="textarea"
            x-effect="if (selectedOption === 'NO' || selectedOption === 'N/A') { $refs.textarea.focus(); }"
            placeholder="{{ __('If “No” or “Not required”, please provide a brief but detailed explanation as to why you do not require ethics') }}"
            rows="5"
            wire:model="ebrief"
            class="disabled:!cursor-not-allowed disabled:!opacity-50 disabled:!bg-slate-200 disabled:!placeholder-zinc-700">
                {{ old('ebrief') }}
        </flux:textarea>
    </div>
    <div class="col-span-12 mt-4">
        <x-label for="ethicsFile" :value="__('Upload your ethics approval/certificate')" />
        <input type="file" name="ethicsFile" id="ethicsFile"
            x-bind:disabled="selectedOption !== 'YES'"
            class="block w-full mt-1 text-sm border border-gray-300 rounded-md shadow-sm cursor-pointer focus:z-10 focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed disabled:bg-slate-200 file:cursor-pointer file:disabled:cursor-not-allowed file:bg-cimvhr-red file:border-0 file:text-white file:me-4 file:py-3 file:px-4">
    </div>
</div>

**Comment by calebporzio** [comment]
Please upgrade to v1.0.21 and see if the issues persist. If they do, please re-submit this issue but with a reproducible snippet that takes less work to get going on our end. Thanks!

**Comment by kadcore** [comment]
Thanks Caleb. I will

On Nov 7, 2024, at 12:25, Caleb Porzio ***@***.***> wrote:

﻿

Please upgrade to v1.0.21 and see if the issues persist. If they do, please re-submit this issue but with a reproducible snippet that takes less work to get going on our end. Thanks!
