### ISSUE TITLE
Outline on input field in listbox not showing nicely

### ISSUE THREAD

**Issue by dylanopafstand** [livewire/flux#62]
Because of the negative margins on the 'searchable' input field within a listbox (or any select with searchable enabled) the outline is not shown correctly. I suggest to remove the negative margins by default.

With negative margins:
<img width="682" alt="Screenshot 2024-09-25 at 10 20 24" src="https://github.com/user-attachments/assets/63954730-2867-46f0-8cc4-fcda5b96ef22">

Without negative margins:
<img width="687" alt="Screenshot 2024-09-25 at 10 22 18" src="https://github.com/user-attachments/assets/1ee4ffd0-3457-44d1-bb1b-9dd775b31364">

**Comment by raftia** [comment]
Hi @dylanopafstand ,

As a workaround and without directly modifying the component you can add the following styles to the comand input, that will remove the browser default border/ring.

<flux:command.input class="border-0 focus:border-zinc-200 focus:ring-0" placeholder="Search..."/>

As per docs it should not have any borders or ring at all.

Hope that helps.

**Comment by raftia** [comment]
Hi @dylanopafstand ,

No worries mate, however i do think its an issue with flux as at least myself i see all the inputs in docs with grey focus borders/rings. so defo there is something that needs attention from @calebporzio , as i dont think default browser color fits the aesthetic of the design. non the less super exited for livewire flux! :)

**Comment by calebporzio** [comment]
Currently we are taking a hard stance to just use browser default focus rings to keep things simple and also avoid scenarios where by using custom ones, we are harming the end user experience in some way.

We will definitely keep listening to users about this over time in case we should shift directions. Thanks!

**Comment by lucasromanojf** [comment]
> Currently we are taking a hard stance to just use browser default focus rings to keep things simple and also avoid scenarios where by using custom ones, we are harming the end user experience in some way.
> 
> We will definitely keep listening to users about this over time in case we should shift directions. Thanks!

The documentation example does not have any border/ring and the example code neither. @calebporzio did you add custom CSS to the doc example?

**Comment by lucasromanojf** [comment]
Just realized that this issue is related to using tailwindcss forms plugin. I've removed it and all these visual ring/outline issues are now gone.
