### ISSUE TITLE
Update 1.0.21 : Method Illuminate\View\ComponentAttributeBag::all does not exist.

### ISSUE THREAD

**Issue by mitsswebdesign** [livewire/flux#620]
Hi Fluxers!

After the fix update 1.0.21 we have total dashboard error 1.0.21 Method Illuminate\View\ComponentAttributeBag::all does not exist.

vendor / livewire / flux / stubs / resources/ views / flux/ icon/index.blade.php: 12

It will break code in booting. I think this is urgent.

![Image](https://github.com/user-attachments/assets/6876eba2-7597-4544-aa40-a26984f242b7)

**Comment by ju5t** [comment]
Can you share some code to replicate it with? I cannot replicate it. I've tested with:

```html
<flux:icon.arrow-right />
<flux:button icon="arrow-right">Test</flux:button>
```

**Comment by mitsswebdesign** [comment]
I have it after upgrade composer from 1.0.19 tot 1.0.21. you can run after update?

**Comment by ju5t** [comment]
Yes, I've tested it with 1.0.21. I cleared the cache and ran `npm run build`.

**Comment by mitsswebdesign** [comment]
Thats very strange because error shows up right here: <flux:delegate-component :component="'icon.' . $icon">{{ $slot }}</flux:delegate-component>

**Comment by rzv-me** [comment]
the problem is Laravel 10 doesn't have `all()`, but Laravel 11 has it.

unfortunatelly this is a breaking change

you  can compare these:
https://laravel.com/api/10.x/Illuminate/View/ComponentAttributeBag.html#method_all
https://laravel.com/api/11.x/Illuminate/View/ComponentAttributeBag.html#method_all

**Comment by rzv-me** [comment]
I created a PR(#621) to fix this. It replaces `$attributes->all()` with `$attributes->getAttributes()`, which is the same thing, but available in both Laravel 10.x and Laravel 11.x

**Comment by ju5t** [comment]
@rzv-me that's a great catch.

**Comment by SRWieZ** [comment]
Yep, same error here!

**Comment by calebporzio** [comment]
ugh - fixing thank you
