### ISSUE TITLE
Expandable navlist: expanded false

### ISSUE THREAD

**Issue by ITSYV** [livewire/flux#625]
When using an expandable navlist, the list is automatically opened.
You can close it by using the "expanded" prop (not documented at this moment).

The prop is set to true by default. When trying to close it for a specific item you have to use `expanded=""` as in the code  `@if ($expanded)` is used.
Maybe an idea to switch the prop to "closed = false" instead of "expanded" so we can just use "closed" on the navbar element?

**Comment by jeffchown** [comment]
@ITSYV For anyone to be able to help, the code sample needs to be without any dependencies (e.g. your `$item`, `selectItem()`, etc.
People can't cut & paste your code and run it.
Some people provide one-file Volt components for easier collaboration.

**Comment by ITSYV** [comment]
@jeffchown editted

**Comment by jeffchown** [comment]
See https://github.com/livewire/flux/issues/626#issuecomment-2465216801

**Comment by ITSYV** [comment]
@jeffchown what does this have to do with Livewire? It's a prop on a blade element from Flux?

**Comment by jeffchown** [comment]
@ITSYV You're correct.  My answer applies to your other issue.

Re: `flux:navlist.group` `expanded` attribute, I agree - probably better if it operates in a fashion consistent with `an flux:accordion.item` where is is closed by default and initially opened **only** if the `expanded` attribute is passed e.g. 

```
 <flux:navlist.group heading="Account" expandable expanded>
     <flux:navlist.item href="#">Profile</flux:navlist.item>
     <flux:navlist.item href="#">Settings</flux:navlist.item>
     <flux:navlist.item href="#">Billing</flux:navlist.item>
</flux:navlist.group>
```

**Comment by martenvaino** [comment]
I had the same wish to keep the navlist collapsed by default, and it looks like adding `expanded=""` achieved this behavior.

However, it would be a helpful enhancement if the navlist could automatically expand whenever any of its grouped items are active. This change could make the navigation state more intuitive.

**Comment by roadsend** [comment]
I solved that with:

:expanded="in_array(url()->current(), [route('v2-advertiser.dashboard’),…"

In the future I might use a directory structure or pass the items into a loop so I don’t have to list them - but hope this helps.


Jonathan Michel
CTO 
Lead Marvels, Inc
***@***.***
O: 914.489.0826

On November 13, 2024 at 5:07:39 AM, martenvaino ***@***.***) wrote:

I had the same wish to keep the navlist collapsed by default, and it looks like adding expanded="" achieved this behavior.

However, it would be a helpful enhancement if the navlist could automatically expand whenever any of its grouped items are active. This change could make the navigation state more intuitive.

**Comment by martenvaino** [comment]
Thanks @roadsend , I modified a bit and did like this for now since I use prefixes for the submenu items' routes.
`:expanded="request()->route()->getPrefix() === 'admin/settings'" `

Would be nice though if Flux did this automatically.

**Comment by calebporzio** [comment]
Good call, fixed, will be in the next release. Also added documentation:

![Image](https://github.com/user-attachments/assets/e7c67085-449a-489a-b345-4cee832f82da)

**Comment by jeffchown** [comment]
@calebporzio One last thought... for `flux:navlist` to be consistent with the API for `flux:accordion`, shouldn't the default be **not** expanded on initial render? (unless otherwise indicated)

Or is expanded by default a 'standard' amongst most UIs?

**Comment by martenvaino** [comment]
I agree, the default should be expanded. Fits most of the use cases.
On 16. Nov 2024 at 19:23 +0200, Jeff Chown ***@***.***>, wrote:

@calebporzio<https://github.com/calebporzio> One last thought... for flux:navlist to be consistent with the API for flux:accordion, shouldn't the default be not expanded on initial render? (unless otherwise indicated)

Or is expanded by default a 'standard' amongst most UIs?
