### ISSUE TITLE
Expandable navlist: use of wire:click

### ISSUE THREAD

**Issue by ITSYV** [livewire/flux#626]
I'm creating an interactive tree using the navlist element with grouping.

At this moment, wire:click is placed on the full group (`<ui-disclosure>` element) instead of the button of the group.
Because of this, all child elements of this group are not interactive.

**Comment by jeffchown** [comment]
@ITSYV Can you provide a copyable code example?

**Comment by jeffchown** [comment]
@ITSYV For anyone to be able to help, the code sample needs to be without any dependencies (e.g. your `$item`, `selectItem()`, etc.
People can't cut & paste your code and run it.
Some people provide one-file Volt components for easier collaboration.

**Comment by ITSYV** [comment]
@jeffchown editted!

**Comment by jeffchown** [comment]
@ITSYV This is actually more of a Livewire question.

Your `wire:click` events are 'bubbling up' and triggering the parent `wire:click`s as well.

Here's my edited version of your code with `.stop` directives added to your nested `wire:click`s to stop the clicks from reaching the parents. (I also added some indentation to make it easier to read)

```
<?php

use Livewire\Volt\Component;

new class extends Component {
 public $item;
    public function selectItem($id)
    {
        $item = $id;
    }
} ?>

<flux:navlist.group expandable :expanded="false" heading="Group 1" wire:click="selectItem(1)">
    <flux:navlist.group expandable :expanded="false" heading="Group 2" wire:click.stop="selectItem(2)">
        <flux:navlist.item wire:click.stop="selectItem(2001)">item 2001</flux:navlist.item>

        <flux:navlist.group expandable :expanded="false" heading="Group 3" wire:click.stop="selectItem(3)">
            <flux:navlist.item wire:click.stop="selectItem(3201)">item 3201</flux:navlist.item>
            <flux:navlist.item wire:click.stop="selectItem(3202)">item 3202</flux:navlist.item>
        </flux:navlist.group>
    </flux:navlist.group>

    <flux:navlist.group expandable :expanded="false" heading="Group 4" wire:click.stop="selectItem(4)">
        <flux:navlist.item wire:click.stop="selectItem(4001)">item 4001</flux:navlist.item>
        <flux:navlist.item wire:click.stop="selectItem(4002)">item 4002</flux:navlist.item>
    </flux:navlist.group>

    <flux:navlist.item wire:click.stop="selectItem(1000)">item 1000</flux:navlist.item>
</flux:navlist.group>
```

**Comment by ITSYV** [comment]
@jeffchown in this case it's not the child reaching the parent, but the other way around.
the navlist.group blade file has a <ui-disclosure> element with a button and a div inside.
The wire:click would be better placed on the button element in the ui-disclosure than on itself to get child / nested elements working.
It's the same as for some props (like classes) are placed on inner divs in Flux elements than the outer div itself.

**Comment by jeffchown** [comment]
@ITSYV I understand what you are describing re: the placement of the `wire:click`.  

But, maybe I'm not understanding what your desired result is.  Can you describe the scenario/an example of the desired behaviour re: an interactive child element?  e.g. what you want to happen when clicking on a child element.

**Comment by ITSYV** [comment]
I'm building an interactive tree where also the groups are clickable.

At this moment the flux elements results in:
```
<ui-disclosure  wire:click="set()" ...>
	<button>Name</button>

	<div>
		Child elements...
		<ui-disclosure  wire:click="set()" ...>
			<button>Name</button>

			<div>
				Child elements...
			</div>
		</ui-disclosure>
	</div>
</ui-disclosure>
```
The wire:click is placed on the first element (the ui-disclosure). Because i'm looping the childs with possible groups back into itself (so it's running inside the <div>), the first wire:click is overruling all. 
If the wire:click would be a prop of the button, this wouldn't be a problem, as the childs are rendered inside the div inside the ui-disclosure

```
<ui-disclosure ...>
	<button wire:click="set()">Name</button>

	<div>
		Child elements...
		<ui-disclosure ...>
			<button  wire:click="set()">Name</button>

			<div>
				Child elements...
			</div>
		</ui-disclosure>
	</div>
</ui-disclosure>
```

**Comment by jeffchown** [comment]
@ITSYV I understand the markup that is created by Flux.  This is the same markup created by `flux:accordion`, so there may be a reason the `wire:click` is placed on the `ui-disclosure` (vs the `button`) that we're not aware of (@calebporzio and/or @joshhanley are the ones who will have to answer that part)

What I am trying to help with is to see if there is a way to create the behaviour you want with the Flux markup the way it currently is (in case there is some reason the `wire:click` can't be moved to the `button`).

When I added the `.stop` directive to your code, I thought that might get you one step closer.

If it's only a Flux markup change you feel will work I'll leave this one to @calebporzio and @joshhanley

**Comment by calebporzio** [comment]
Hey @ITSYV, the reason the wire:click is going on ui-disclosure and not the button is that all attributes are forwarded to the ui-disclosure element because that makes the most sense at this point.

You're looking for more in-depth customization for a use-case we don't officially support.

I suggest one of two things:
A) You publish the stubs for the navlist and customize the group to your liking (ideally make it a new component called navtree or something in your own app)
B) Attach a more hacky listener like so:

```
<flux:navlist.group x-on:click="if ($el.querySelector('button').contains($event.target)) $wire.selectItem(...)">
```

**Comment by jeffchown** [comment]
You're welcome @calebporzio
