### ISSUE TITLE
Select is clearable when disabled

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#627]
It is possible to clear the value when the element is disabled.

```php
<?php
\Livewire\Volt\state([
    'selected' => 'bar',
])
?>

<div class="p-6">
    <flux:select wire:model="selected" variant="listbox" :clearable="true" :disabled="true">
        <flux:option value="bar">baz</flux:option>
        <flux:option value="foo">oof</flux:option>
    </flux:select>
</div>
```

**Comment by calebporzio** [comment]
Good call, I made the clearable button hidden on disabled selects and inputs.

Will be in the next release. Good catch!

![Image](https://github.com/user-attachments/assets/3090ace7-1598-41df-85b6-a7fc58ad3926)

**Comment by Pilskalns** [comment]
As funny as it sounds, I relied on this functionality - a disabled && clearable input field.

For me it displays the model title from a relationship - when it is "set" it is just a title. When the user clears the input, I then render a search dropdown with a database search. The user then selects this dropdown and it "locks" back to disabled && clearable input.

Why this way? I needed it to work as a re-useable component that could be used for new models and editing existing ones.

**Comment by jeffchown** [comment]
@Pilskalns That sounds like a very 'non-standard', unique use-case for the control.  

Your usage seems dependent on non-standard UI behaviour that may be changed/broken by future updates - the update solving this issue being a case in point.

Have you tried using an `@if...@else..@endif` around two different controls based on whether the input is set (e.g. 'just a title', thus rendering a readonly input or `flux:heading`) or blank value (rendering a search dropdown w/ database search)?

This still enables you to create a re-useable component while relying on/implementing only 'normal' use of the `flux:select`.

**Comment by joshhanley** [comment]
@Pilskalns interestingly enough, I use a component (non-flux) in one of my apps the same way.

When a client is selected, the input is disabled (so they can't click and the dropdown won't open) and the clear button is active.

![Image](https://github.com/user-attachments/assets/661c48a2-19d9-40c7-9bae-f1c44c4ee419)

But then when they click clear, the selected value is cleared and the input becomes enabled again and the dropdown can be accessed again.

![Image](https://github.com/user-attachments/assets/956bee2d-4284-423e-9ffb-c154021af68c)

I've not converted this app to Flux yet, so haven't run into this. But feel free to open an issue if you think we should get Caleb to have a look at it.

**Comment by Pilskalns** [comment]
@jeffchown I tried at first yes, select is a combobox so it can do a backend search for options. But it was hard to make it work right in all states, like pre-selecting on page load. User also could edit the input value without choosing correct one from dropdown.

**Comment by Pilskalns** [comment]
@joshhanley, this is exactly my use case.

Thanks, I will probably create a new issue - IMHO, if the input is explicitly set to `clearable`, it still should be able to do it.
