### ISSUE TITLE
Switch component does not render with certain attributes

### ISSUE THREAD

**Issue by erikwestlund** [livewire/flux#628]
Switches do not all render when copying directly from: https://fluxui.dev/components/switch

Namely, it appears with label or description fields, things break.

I created a very basic layout and a test component shown below.

Livewire: 3.5.12
Flux: 1.0.22
Flux-pro: 1.0.22

View code:

```
<div>
    <div class="space-y-8">
         <flux:checkbox checked
            value="newsletter"
            label="Newsletter"
            description="Receive our monthly newsletter with the latest updates and offers."
        />

        {{--No switch shown.--}}
        <flux:switch wire:model.live="a" label="Enable notifications" />
        <flux:switch wire:model.live="b" label="Communication emails" description="Receive emails about your account activity." />

        {{--Switch shown.--}}
        <flux:switch wire:model.live="c" />
       <flux:field variant="inline" class="w-full flex justify-between">
            <flux:switch wire:model.live="d" />
            <flux:label>Communication emails</flux:label>
            <flux:error name="email" />
        </flux:field>
    </div>
</div>

```

Component code:

```
class SwitchTest extends Component
{
    public $a;

    public $b;

    public $c;

    public $d;

    public function render()
    {
        return view('livewire.switch-test')
            ->layout('layouts.bare');
    }
}
```

Layout code:

```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Switch Test</title>
    @vite(['resources/css/app.css'])

    @fluxStyles
    @livewireStyles
</head>
<body class="p-8">

    {{ $slot }}

    @livewireScripts
    @fluxScripts
</body>
</html>

```

Screenshot of what renders:

![Image](https://github.com/user-attachments/assets/f57e3339-bfd4-4d11-bf64-e741f84e4da6)

**Comment by jeffchown** [comment]
@erikwestlund I tried your example and can't recreate the issue.

Don't forget, when the switch is on the right side (default layout), it will be far-right justified to the width of the enclosing div/container.  Could your `$a` and `$b` switch examples be off to the far right of the page?

**Comment by erikwestlund** [comment]
🤦🏻🤦🏻🤦🏻🤦🏻🤦🏻🤦🏻🤦🏻🤦🏻🤦🏻

That explains it.

I can see why this is a default when setting a number of settings.

I would suggest noting that on the documentation page.

I would also suggest a left-position switch variant to avoid all the boiler plate just to switch the page.

Thank you. I will close.

**Comment by jeffchown** [comment]
@erikwestlund I had the same issue a while back.  @calebporzio has added a left-aligned section to the docs: https://fluxui.dev/components/switch#left-aligned
