### ISSUE TITLE
flux:button  output with extra spinning svg

### ISSUE THREAD

**Issue by yangsystem** [livewire/flux#629]
So I added a button and I checked the output html and saw an extra spinning svg that should not be there.

in blade the code is 
` <flux:button type="submit">Adauga</flux:button>`
in html the code is 
`<button type="submit" class="relative items-center font-medium justify-center gap-2 whitespace-nowrap disabled:opacity-75 dark:disabled:opacity-75 disabled:cursor-default disabled:pointer-events-none h-10 text-sm rounded-lg px-4 inline-flex  bg-white hover:bg-zinc-50 dark:bg-zinc-700 dark:hover:bg-zinc-600/75 text-zinc-800 dark:text-white border border-zinc-200 hover:border-zinc-200 border-b-zinc-300/80 dark:border-zinc-600 dark:hover:border-zinc-600 shadow-sm [[data-flux-button-group]_&amp;]:border-l-0 [:is([data-flux-button-group]>&amp;:first-child,_[data-flux-button-group]_:first-child>&amp;)]:border-l-[1px] *:transition-opacity [&amp;[disabled]>:not([data-flux-loading-indicator])]:opacity-0 [&amp;[disabled]>[data-flux-loading-indicator]]:opacity-100 [&amp;[disabled]]:pointer-events-none" data-flux-button="data-flux-button" data-flux-group-target="data-flux-group-target">
        <div class="absolute inset-0 flex items-center justify-center opacity-0" data-flux-loading-indicator="">
                <svg class="shrink-0 [:where(&amp;)]:size-4 animate-spin" data-flux-icon="" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" aria-hidden="true" data-slot="icon">
    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
</svg>
                    </div>
            <span>Adauga</span>
    </button>`

This part is not suppose to be here:
`<div class="absolute inset-0 flex items-center justify-center opacity-0" data-flux-loading-indicator="">
                <svg class="shrink-0 [:where(&amp;)]:size-4 animate-spin" data-flux-icon="" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" aria-hidden="true" data-slot="icon">
    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
</svg>`

**Comment by ju5t** [comment]
It should be there, it's a feature.

**Comment by yangsystem** [comment]
Sorry for the time consumed.
