### ISSUE TITLE
Checkboxes in group not being checked

### ISSUE THREAD

**Issue by voicecode-bv** [livewire/flux#63]
As a follow up on[ this issue](https://github.com/livewire/flux/issues/37), I think it's closed too soon. 

Same issue for me:

```
$selectedTeams = [4, 5];
```

```
<div class="col-span-6 sm:col-span-4" x-show="hasTeams" x-cloak>
    <flux:checkbox.group wire:model="selectedTeams" label="Selecteer de deelnemende teams">
        @foreach($teams as $team)
        <flux:checkbox :label="$team->name" :value="$team->id" />
        @endforeach
    </flux:checkbox.group>
</div>
```

The ID's are passed just fine:

```
<ui-checkbox class="***" label="Team 5" value="5" data-flux-control="" data-flux-checkbox="" role="checkbox" tabindex="0" aria-checked="false" aria-labelledby="lofi-label-9dadbe2622fb3"> *** </ui-checkbox>
```

**Comment by lucasromanojf** [comment]
For me it only worked after converting id's to strings

Something like this on mount:

`$this->selectedIds = collect($idsArray)->map(fn ($id) => (string) $id)->toArray();`

**Comment by calebporzio** [comment]
Just fixed this so that Flux input values work with integers initially. Upgrade to the latest version and it should be fixed. Thanks!
