### ISSUE TITLE
Checkbox group wire:model.live not updating when checking the checkbox by clicking on the label

### ISSUE THREAD

**Issue by razvaniacob** [livewire/flux#630]
Hi there! 👋

The bug I found is pretty much explained in the title. 

When using <flux:checkbox.group wire:model.live="selected">, the selected variable does not update when the label, rather than the checkbox itself, is clicked—even though the checkbox visually appears checked.

This seems to be a bug.

Here is my code 

```shell
<?php

use function Livewire\Volt\{layout, state, title};

layout('layouts.admin');
title('Test');

state([
    'selected' => [1],
]);

?>

<div>
    <div class="text-gray-400 mb-8">{{ count($selected) }} Selected</div>
    <flux:checkbox.group wire:model.live="selected">
        @foreach ($genres as $option)
        <flux:checkbox label="{{ $option->name }}" value="{{ $option->id }}"
            :disabled="(count($selected) == 1 && $option->id == $selected[0])" />
        @endforeach
    </flux:checkbox.group>
</div>
```
<hr>

I also have a screen recording of me testing it.

https://github.com/user-attachments/assets/c6b68cb2-fb35-4cc4-91dc-c911f9a7bf22

Thank you!
Raz

**Comment by jeffchown** [comment]
@razvaniacob See https://github.com/livewire/flux/issues/624#issuecomment-2464616283

**Comment by razvaniacob** [comment]
Ok.. I updated it and now it works. Thanks!
