### ISSUE TITLE
1.0.22: Unable to locate a class or view for component [flux::delegate-component].

### ISSUE THREAD

**Issue by DonCamillo11** [livewire/flux#633]
I get the following error after updating to v1.0.22:
`Unable to locate a class or view for component [flux::delegate-component].`

Using the following item on my site:
```
<flux:dropdown>
    <flux:button square class="dark:!text-gray-400 !w-6 hover:dark:bg-gray-600/25" icon="ellipsis-vertical" variant="ghost" x-on:click="event.stopPropagation()" size="sm"></flux:button>
    <flux:menu>
        @if(!$document->fixed)
            <flux:menu.item icon="pencil-square" wire:click.prevent.stop="editDocument('{{ $document->id }}')">{{ __('Edit') }}</flux:menu.item>
        @endif
    </flux:menu>
</flux:dropdown>
```

**Comment by calebporzio** [comment]
Can you run `php artisan view:clear` and try again?

**Comment by DonCamillo11** [comment]
I've already tried that. Tried also a downgrade on 1.0.21 and 1.0.20. It is happening since v1.0.21

**Comment by calebporzio** [comment]
Odd, I just tried with that snippet and it worked fine.

Hmmm. maybe run `composer du`?

For some reason you are on the older flux tag compiler that doesn't have the new `delegate-component` syntax.

**Comment by DonCamillo11** [comment]
Thanks, this seems to solve the issue.
