### ISSUE TITLE
Conditionally adding "checked" to a checkbox or radio group doesn't work. Blade $loop variable not recognised.

### ISSUE THREAD

**Issue by RezaODB** [livewire/flux#637]
When using blade $loop variable inside a loop, the whole component crashes. Same thing using x-if using Alpine. 

<flux:radio.group wire:model="answers.radio.{{ $question->id }}" label="{{ $question->label }}" variant="segmented">
   @foreach ($question->options as $option)
   <flux:radio label="{{ $option }}"  {{ $loop->first ? 'checked' : '' }} />
   @endforeach
</flux:radio.group>

**Comment by jeffchown** [comment]
@RezaODB For Flux components, this should work instead `<flux:radio :label="$option" :checked="$loop->first'' />`

**Comment by RezaODB** [comment]
@jeffchown  No no, this is the first thing I tried of course but still no success :/ Thanks for your help nonetheless. 
@calebporzio Second issue I'm running into in 24hours... Honestly for the price, the whole experience is not great. It feels like a rushed half baked product. I bought Flux to spare times. For the moment, I'm just wasting my time and go mad trying to make it works in a project. Flux is clearly not production ready. Not cool to charge this amount of money.

**Comment by jeffchown** [comment]
@RezaODB I had a 2nd look at your snippet - the `wire:model="answers.radio.{{ $question->id }}"` will override any `:checked` setting.

**Comment by RezaODB** [comment]
@jeffchown Thank you again for your response. But I have the public property $answers declared as an array in my Livewire component, that's it. In my form, I'm looping through a collection of questions to dynamically generate the inputs. For the radio groups, how can I mark the first option as checked by default then?

**Comment by jeffchown** [comment]
@RezaODB One idea (a little 'messy') is to add an `@php` block before the loop to initialize the `flux:radio.group`'s `wire:model` property with the first `$question->options`. something like this:

```
@php
    $answers['radio'][$question->id] = $question->options[0];
@endphp

<flux:radio.group 
    wire:model="answers.radio.{{ $question->id }}" 
    :label="$question->label" 
    variant="segmented"
>
    @foreach($question->options as $option)
        <flux:radio :value="$option" :label="$option" />
    @endforeach
</flux:radio.group>
```

**Comment by RezaODB** [comment]
It still doesn't work :/ 
No matter what I do there's a conflict with the flux component.
@calebporzio I guess Flux just doesn't work with dynamic data... Which is a bummer because I bought the product specifically to generate forms in a cleaner way... Second time that I'm running into issues in 24 hours. Sorry but I don't have time to beta test your product. I will ask for a refund.

**Comment by RezaODB** [comment]
I came up with a solution, using a loop in mount() to set the properties to an empty string  :

public $questions = [];
public $answers = [];

public function mount()
{
    $this->questions = Question::orderBy('order')->get();

    foreach ($this->questions as $question) {
        $this->answers['answer_' . $question->id] = '';
    }
}

<flux:radio.group wire:model.change="answer_{{ $question->id  }}" label="{{ $question->label }}" variant="segmented">
@foreach ($question->options as $option)
<flux:radio value="{{ $option }}" label="{{ $option }}" :checked="$loop->first" />
@endforeach
</flux:radio.group>

**Comment by RezaODB** [comment]
No sorry still not working. And indeed it's messy, which defeat the whole purpose of Flux... 
Please a fix is needed asap ! Second time I'm running into an issue after 2 days of use.

**Comment by RezaODB** [comment]
Update on this? If not I give up and ask for a refund...
