### ISSUE TITLE
Accordion Transition

### ISSUE THREAD

**Issue by eneadrian** [livewire/flux#64]
<flux:accordion **transition**>

If you are using transition in accordion and type something in an input this is happening

https://github.com/user-attachments/assets/23db2424-cfea-41ff-a3a8-a50b13d5d7b8

**Comment by calebporzio** [comment]
Ah yes, the solution is to use `wire:model.self` if you are data binding directly to the accordion.

`<flux:accordion.item transition wire:model.self="foo">`

**Comment by jeffchown** [comment]
@calebporzio This issue occurs for me even when I am not `wire:model`ing any property to the `flux:accordion.item`.

I just updated Flux to 1.0.8 and tested in 2 projects and my transitioned accordions still 'jump' when typing in an enclosed input field.

**Comment by jeffchown** [comment]
@calebporzio Please ignore my previous, all is good.  I had to republish the Flux components in my apps. 🤦‍♂️
