### ISSUE TITLE
flux UI not working properly

### ISSUE THREAD

**Issue by DanielGitUser** [livewire/flux#642]
Hello, fluxUI team: Hello Caleb

Please I purchased flux but is not working as expected, I think is something related to STYLES.... how you can check that?
this is my tailwind setup

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        "./vendor/livewire/flux-pro/stubs/**/*.blade.php",
        "./vendor/livewire/flux/stubs/**/*.blade.php",
    ],

I'm missing the ICONS (you can see that in the button of export is missing icon), and the switch are not working as expected, the circle may be an icon...?

"blade-ui-kit/blade-heroicons": "^2.2”,
"livewire/flux-pro": "^1.0",
"livewire/livewire": "^3.0",

![Image](https://github.com/user-attachments/assets/9b852d58-4e64-4fb2-a761-482a6baf7b14)

I will be waiting for your response, and please let me know if you need more code or any info about my project so I can deliver it to you and check it to solve the integration part, thank you very much.

Best regards
Daniel

**Comment by ju5t** [comment]
I assume you have added `@fluxStyles` and `@fluxScripts` as mentioned in the docs? Did you run `npm run build`?

**Comment by DanielGitUser** [comment]
Hello, sorry for the late reply, yes I added @fluxStyles and @fluxScripts and also I ran NPM RUN BUILD, but there is any change

**Comment by DanielGitUser** [comment]
Hello @calebporzio @ju5t , I found the problem or error, I install laravel 10 with tailwind on year ago in the project, I took the chance to copy paste the CDN 

<script src="//cdn.tailwindcss.com"></script>

and paste it before cling the BODY tag this solve the issue, I share this with you because maybe someone else could need this information - the TAILWIND classes are not loaded completely in order to run the front-end of fluxUI when installed, now I will check if I need to update or what I need to do yo keep the FULL Tailwind code .

thank you

**Comment by DanielGitUser** [comment]
I SOLVE IT!

Please add a small snippet in the FluxUI Documentation explaining that if tailwind is not updated must be updated to the last version

this code updates my tailwinds to the last version, which solves my LARAVEL issue because my tailwind was OLD

**npm install tailwindcss@latest**

then re-run the npm run dev

Okay, I hope this helps others... thanks for your time

Best Regards
Daniel

**Comment by themazim** [comment]
> I SOLVE IT!
> 
> Please add a small snippet in the FluxUI Documentation explaining that if tailwind is not updated must be updated to the last version
> 
> this code updates my tailwinds to the last version, which solves my LARAVEL issue because my tailwind was OLD
> 
> **npm install tailwindcss@latest**
> 
> then re-run the npm run dev
> 
> Okay, I hope this helps others... thanks for your time
> 
> Best Regards Daniel

Thanks a lot! drove me almost crazy. Was checking styles and installation, all good, yet my installation was a little older too.
