### ISSUE TITLE
Input `clearable` missing `x-data`

### ISSUE THREAD

**Issue by edwinvdpol** [livewire/flux#644]
Hi there! 👋

When using the input `clearable` on a page without / outside `x-data`, it does not work.

The difference with, for example `viewable`, is that the `x-data` tag is added by Flux.

```html
<html>
  <head>
    ...
    @fluxStyles
  </head>
  <body>
    <!-- Below does NOT work out of the box -->
    <flux:input name="field" clearable />

    <!-- Below DOES work -->
    <div x-data>
      <flux:input name="field" clearable />
    </div>

    @fluxScripts
  </body>
</html>
```

**Comment by calebporzio** [comment]
Good call, fixed and will be in next release!

**Comment by EWSgithub** [comment]
Hi there,

i use flux-pro and use the searchable select with the search slot and in both the clearable prop only works when you add x-data to the wrapping div tag.

"livewire/flux-pro": "^2.2",


<div x-data class="col-span-12 md:col-span-8 lg:col-span-2">
    <flux:select label="Rubrieken" variant="listbox" searchable placeholder="Kies een rubriek..." clearable>
        <x-slot name="search">
            <flux:select.search class="px-4" placeholder="Zoek een rubriek..."/>
        </x-slot>
        @foreach($arrData['rubrieken'] as $rubriek)
            <flux:select.option>{{ $rubriek->rubriek }}</flux:select.option>
        @endforeach
    </flux:select>
</div>

Without the x-data it does not work.

Greetz Emile

**Comment by joshhanley** [comment]
@EWSgithub can you please open a new issue? Thanks!
