### ISSUE TITLE
Cannot Bind the Variable with `flux:radio`

### ISSUE THREAD

**Issue by littpi** [livewire/flux#645]
Hello. I have a problem on binding the the variable with `wire:model` in `flux:radio`. Here is the code.

## TheForm.php
```php
use App\Enums\Gender;
use Livewire\Component;

class TheForm extends Component
{
    public string $name;
    public string $gender = Gender::Female->value;

    public function render()
    {
        return view('livewire.system.the-form');
    }
}
```

## the-form.blade.php
```blade
<form>
    <flux:field class="mb-6">
        <flux:label>Name</flux:label>
        <flux:input inputmode="text" type="text" wire:model="name" size="sm" autocomplete="name" />
    </flux:field>

    <flux:radio.group wire:model="gender" label="Gender" variant="segmented" size="sm" class="mb-6">
        @foreach(\App\Enums\Gender::cases() as $genderItem)
            <flux:radio :value="$genderItem->value" :label="$genderItem->name" />
        @endforeach
    </flux:radio.group>
</form>
```

## Expected Result
"Female" should be highlighted as it is chosen by default.

## Output
None of the genders have been highlighted.

## Screenshot
![Image](https://github.com/user-attachments/assets/fd0f607a-02a9-41f1-b2c1-d8c1c479483e)

**Comment by jeffchown** [comment]
@littpi Can you post you Gender enum code too?

**Comment by RezaODB** [comment]
I think it's a similar issue as mine. When looping using blade foreach, the $loop variable is not recognise.

**Comment by jeffchown** [comment]
@littpi Your code works as expected for me.

NOTE: I had to add `namespace App\Livewire;` to the top of `TheForm.php` and change `return view('livewire.system.the-form');` to `return view('livewire.the-form');`

And, the `Gender` enum I created was:

```
<?php

namespace App\Enums;

enum Gender: string
{
    case Female = 'Female';
    case Male = 'Male';
    case Other = 'Other';
}
```

**Comment by littpi** [comment]
> [@littpi](https://github.com/littpi) Can you post you Gender enum code too?

## Gender.php
```php
enum Gender: string
{
    case Male = 'm';
    case Female = 'f';
    case Others = 'o';
}
```

TheForm.php is under `app/Livewire/System` folder and the-form.blade.php is under `resources/views/livewire/system`. So I think the view path should be okay? The interaction between other input components like text is okay but the segmented radio just not displayed as preferred. I will try if there are any Livewire debug tools for me to check.

**Comment by littpi** [comment]
I have checked the console and see the errors. I think they are related as they disappeared after I commented out the input radio part in the blade component.

![Image](https://github.com/user-attachments/assets/04025c8e-2a81-40b5-a166-5ea7b8eaa405)

**Comment by littpi** [comment]
Sorry I finally find the reason... I just swapped the position of `@fluxScripts` and `@fluxStyles`... After I swapped back the scripts, it works now. Thanks for all the help...
