### ISSUE TITLE
Modal :dismissible="false" not working in 1.0.22

### ISSUE THREAD

**Issue by MathieuBujold** [livewire/flux#647]
Hi

In the release of the version 1.0.22
I see that the option about dismissible modal is in the release note.

But when I add the :dismissible="false" to my modal they are still dismissible

Mathieu

**Comment by jeffchown** [comment]
@MathieuBujold `:dismissable="false"` is not working in my app either - Flux v1.0.22 - @calebporzio ?

**Comment by calebporzio** [comment]
Ooof - not sure what happened - fixed and will be in the next release
