### ISSUE TITLE
Unable to import the “Lucide” library

### ISSUE THREAD

**Issue by blagapro** [livewire/flux#648]
Hi there! 👋

Sorry you hit a problem with Flux.

When I want to use the command to include Lucide icons, it says that the command doesn't exist, but I have the latest version.

```
   php artisan flux:icon crown grip-vertical github

   ERROR  Command "flux:icon" is not defined. Did you mean one of these?  

  ⇂ flux:activate  
  ⇂ flux:publish 
```

Do you have a solution ?

Thank you

**Comment by oMikeo** [comment]
`php artisan optimize:clear` ?

**Comment by blagapro** [comment]
Hello,

No, this does not solve the problem.

**Comment by calebporzio** [comment]
This has to be something related to what flux version you're on. Make sure you run: `composer update livewire/flux-pro livewire/flux`

If that doesn't do it, run this command and report back on what is listed under "version": 

```
composer show livewire/flux --format=json
```

Here is what is should look like:

![Image](https://github.com/user-attachments/assets/365bf425-b1b8-4c44-b1d6-07d6cd20d986)

Closing - please re-open if you still can't figure it out
