### ISSUE TITLE
flux:toast: Error if no text is specified

### ISSUE THREAD

**Issue by BubeDameKoenig** [livewire/flux#649]
It would be great if the `text` in `flux:toast` was not a mandatory field. Otherwise there is the error below.

```blade
Flux::toast(variant: 'success', heading: 'test');
``` 

Error:
```
Flux\FluxManager::toast(): Argument #1 ($text) not passed
```

**Comment by calebporzio** [comment]
Yeah, you can just leave off the "heading:" part I believe to achieve what you want.

The different variations with and without a heading are demoed in the docs as you've probably seen. Going to close this. thanks!
