### ISSUE TITLE
<flux:input-group> that includes <flux:select variant="combobox"> and radii behaviour

### ISSUE THREAD

**Issue by oMikeo** [livewire/flux#651]
Border radii are not adjusted for comboboxes inside input groups.

![Image](https://github.com/user-attachments/assets/7de587c2-4ef1-4870-9477-f3aa47c7ee24)

**To reproduce:**

```
<flux:field>
    <flux:label>Email address</flux:label>
    <flux:description>Enter the first part of the email address only.</flux:description>
    <flux:input.group>
        <flux:input type="text" icon-trailing="at-symbol"/>
        <flux:select variant="combobox">
            <flux:option value="a" selected>domain.com</flux:option>
            <flux:option value="b">domain.net</flux:option>
            <flux:option value="c">domain.org</flux:option>
            <flux:option value="d">domain.io</flux:option>
            <flux:option value="e">domain.dev</flux:option>
        </flux:select>
    </flux:input.group>
</flux:field>
```

Works fine with both default select and with variant="listbox" 

![Image](https://github.com/user-attachments/assets/07472ac9-a12d-47c1-a9f0-ff5dd55159cf)

![Image](https://github.com/user-attachments/assets/cf59cfa8-95b6-48db-98bf-36dc6680d605)

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
