### ISSUE TITLE
<flux:menu.group> with <flux:menu.submenu> inside the group causes spacing to the left of the group heading

### ISSUE THREAD

**Issue by bjornbjorn** [livewire/flux#655]
To reproduce use this code:

```
   <flux:dropdown position="bottom" align="end">
            <flux:button variant="ghost" size="sm" icon="ellipsis-horizontal" inset="top bottom"></flux:button>
            <flux:menu>
                <flux:menu.group class="items-start" heading="Page settings">
                   <flux:menu.submenu heading="Menu">
                        <flux:menu.radio.group>
                            <flux:menu.radio>Display menu</flux:menu.radio>
                            <flux:menu.radio>Hide menu</flux:menu.radio>
                        </flux:menu.radio.group>
                    </flux:menu.submenu>
                </flux:menu.group>
            </flux:menu>
        </flux:dropdown>
```

You'll see that the group heading "Page settings" has space on the left side:

![Image](https://github.com/user-attachments/assets/c669d62e-b717-4ad5-834e-c802351f1a37)

It's caused by the display:block which overrides the default 'hidden' on the div, if you toggle this off it looks correct:

![Image](https://github.com/user-attachments/assets/0cff918b-9aa6-42dd-af9c-f1f155ed2cfe)

**Comment by bjornbjorn** [comment]
It actually looks like it's the `flux:menu.radio` causing it, with this code the spacing shows up:

```<flux:menu.group class="items-start" heading="Page settings">
                            <flux:menu.item>
                                Test
                            </flux:menu.item>
                    
                            <flux:menu.submenu heading="Sort by">
                                <flux:menu.radio checked>Name</flux:menu.radio>
                                <flux:menu.radio>Date</flux:menu.radio>
                                <flux:menu.radio>Popularity</flux:menu.radio>
                            </flux:menu.submenu>


                </flux:menu.group>```


But if I remove the `<flux:menu.radio>` elements it goes away:

```

 <flux:menu.group class="items-start" heading="Page settings">
                            <flux:menu.item>
                                Test
                            </flux:menu.item>

                            <flux:menu.submenu heading="Sort by">
                            </flux:menu.submenu>


                </flux:menu.group>

**Comment by calebporzio** [comment]
Good catch - it was a bad CSS selector. Fixed (will be in the next release):

![Image](https://github.com/user-attachments/assets/02ca6fc9-8236-4ffd-90eb-99e1380839f8)
