### ISSUE TITLE
The text of the flux:option component is not visible if there is a wire:click

### ISSUE THREAD

**Issue by fabio-algomera** [livewire/flux#661]
Hi there! 👋

There is a problem with Select on Flux v1.0.23 (Livewire v3.5.12).

I have a list of `flux:option` inside `flux:select`, every option has a `wire:click` event that need to change a status of an order.

The click and the call to the method works, but if there is `wire:click` attribute the slot (the text of the option) isn't visible.

NOT WORK:
`<flux:option wire:click="changeStatus({{ $order->id }}, '{{App\Models\Order::NEW}}')" :selected="$order->status === App\Models\Order::NEW" class="status-new">{{ __(App\Models\Order::NEW) }}</flux:option>`

WORK:
`<flux:option :selected="$order->status === App\Models\Order::NEW">{{ __(App\Models\Order::NEW) }}</flux:option>`

Any workaround or any fix for this?

Thank you! :)

**Comment by jeffchown** [comment]
@fabio-algomera Adding a `wire:click` to each options seems a little complex to me (and could interfere with default functionality).
Suggestion - why not do something like this instead, e.g.:

In your Blade/view file
```
<flux:select wire:model.live="status" placeholder="Choose status...">
    <flux:option :value="App\Models\Order::NEW">{{ __(App\Models\Order::NEW) }}</flux:option>
    ...
</flux:select>
```

in your Livewire component:
```
<?php

namespace App\Livewire;

use Livewire\Attributes\Computed;
use App\Models\Order;

class OrderStatus extends Component
{
    public int $id; // pass this via e.g. <livewire:order-status :id="12" />

    public string $status = '';

    public function mount(int $id): void
    {
        $this->id = $id;

        // ...other initialization, if needed...
    }

    #[Computed]
    public function Order(): Order
    {
        return Order::findOrFail($this->id);
    }
    
    public function updatedStatus(string $newStatus): void
    {
        $this->order->status = $newStatus;
        $this->order->save();
    }
}
```

**Comment by calebporzio** [comment]
Thanks for pointing in the right direction @jeffchown. Yeah it looks like you are either using the select wrong (by not using it for state selection), or you would be better served by something like a <flux:menu>

Thanks

**Comment by fabioserembe** [comment]
Yea.. thank you @jeffchown I use it wrong..
Now everything works as expected
