### ISSUE TITLE
select `listbox` variant not searching options when typing

### ISSUE THREAD

**Issue by jeffchown** [livewire/flux#663]
I'm not sure if something's changed recently, but my `flux:select`s with `variant="listbox"` no longer highlight an option when I start typing the matching first character(s) of an option.

I'm running Flux 1.0.23 after running `php artisan view:clear` with NO published Flux components.

e.g.: (using code samples from docs)
- first (native) select acts as expected and highlights `Legal services` if I type `L`
- 2nd `variant="listbox"` doesn't highlight anything when focused and I start typing
- 3rd `variant="combobox"` acts as expected (using .includes() so I can search in middle of options as well)

```
<div class="space-y-2">
    <flux:select placeholder="Choose industry..." label="No variant">
        <flux:option>Photography</flux:option>
        <flux:option>Design services</flux:option>
        <flux:option>Web development</flux:option>
        <flux:option>Accounting</flux:option>
        <flux:option>Legal services</flux:option>
        <flux:option>Consulting</flux:option>
        <flux:option>Other</flux:option>
    </flux:select>

    <flux:select variant="listbox" placeholder="Choose industry..." label="listbox variant">
        <flux:option>Photography</flux:option>
        <flux:option>Design services</flux:option>
        <flux:option>Web development</flux:option>
        <flux:option>Accounting</flux:option>
        <flux:option>Legal services</flux:option>
        <flux:option>Consulting</flux:option>
        <flux:option>Other</flux:option>
    </flux:select>

    <flux:select variant="combobox" placeholder="Choose industry" label="combobox variant">
        <flux:option>Photography</flux:option>
        <flux:option>Design services</flux:option>
        <flux:option>Web development</flux:option>
        <flux:option>Accounting</flux:option>
        <flux:option>Legal services</flux:option>
        <flux:option>Consulting</flux:option>
        <flux:option>Other</flux:option>
    </flux:select>
</div>
```

**Comment by jeffchown** [comment]
UPDATE: I assume this has something to do with the issue - via devtools, I see that all `flux:options` for both the `listbox` and `combobox` have a leading and trailing space (not sure why)

**Comment by calebporzio** [comment]
Hmmm that's odd - I don't see an implementation for this in the source code at all. Only for the menu component.

Anyhow, I added it in and made the search "running" with a 300ms debounce for both this and the menu component as well while we were at it so that it mirrors native select behavior as best as possible.

Good catch, will be in the next release.

**Comment by jeffchown** [comment]
Thanks, @calebporzio !

**Comment by jeffchown** [comment]
@calebporzio in v1.0.24 and v1.0.25 I still have to add a leading space to my search (due to the leading and trailing space in the `flux:select variant="listbox"`) to get a `listbox` to find a matching option.

e.g. to search `Web` to highlight `Web Development` I have to type `space+w` (vs. just `w` with a native select)
