### ISSUE TITLE
Modal :dismissible="false" not working in 1.0.23

### ISSUE THREAD

**Issue by MathieuBujold** [livewire/flux#664]
Hi

In the release of the version 1.0.22 hehe and 1.0.23

But when I add the :dismissible="false" to my modal they are still dismissible.

HAHA the fix that can't be fixed

@calebporzio 
Mathieu

**Comment by calebporzio** [comment]
Sorry about that, this has been patched but is still unreleased. Hoping to release this week or early next week. Thanks!

![Image](https://github.com/user-attachments/assets/f5c423cd-da06-4f31-a75c-d1a9bf7b7958)
