### ISSUE TITLE
<flux:switch> component - Label click not updating property value

### ISSUE THREAD

**Issue by hidicamar** [livewire/flux#668]
Hello,

I’m using the flux:switch component as documented:

`<flux:switch wire:model.live="notifications" label="Enable notifications" />`

or when used within:

```
 <flux:field variant="inline" class="w-full flex justify-between">
        <flux:switch wire:model.live="notifications" />
        <flux:label>Notifications</flux:label>
        <flux:error name="notifications" />
</flux:field>
```

When this code is implemented, both a label and switch button are generated. While clicking on the label does toggle the switch's visual state, it doesn’t actually update the notifications property value in the component. The value only updates when I click directly on the switch itself, not the label.

I've tried to dump value on submit or use livewire's updated hook to check state change but as described, it only triggers when switch is clicked and not the label connected to it. I've used the switch inside of standalone livewire component, full-page component and volt component, same result.

Could this be a bug, or is there a workaround? Or, am I potentially missing something in the implementation?

![Image](https://github.com/user-attachments/assets/a35c2142-bafd-46eb-b7bc-c3cfea958da8)

Here I've used full page component with switch, and described issue occurs. I've been using latest flux version.

**Comment by ju5t** [comment]
@hidicamar can you share the code in backticks on Github instead of sharing a screenshot? This helps debugging this issue.

**Comment by hidicamar** [comment]
Of course, my bad.

Here is volt component:

switch-test-component.blade.php

```
<?php

use Livewire\Volt\Component;

new class extends Component
{
    public $notifications;

    public function updatedNotifications($value)
    {
        dd($value);
    }

    public function submit()
    {
        dd($this->notifications);
    }
}; ?>

<div>
    <flux:switch wire:model.live="notifications" label="Enable notifications" />

    <flux:button wire:click="submit">
        Submit
    </flux:button>
</div>
```

Or a normal livewire component

SwitchTestComponent.php

```
<?php

namespace App\Livewire;

use Livewire\Component;

class SwitchTestComponent extends Component
{
    public $notifications;

    public function updatedNotifications($value)
    {
        dd($value);
    }

    public function submit()
    {
        dd($this->notifications);
    }
    
    public function render()
    {
        return view('livewire.switch-test-component');
    }
}
```

switch-test-component.blade.php

```
<div>
    <flux:switch wire:model.live="notifications" label="Enable notifications" />

    <flux:button wire:click="submit">
        Submit
    </flux:button>
</div>
```

Whatever suits the best.

**Comment by jeffchown** [comment]
@hidicamar I just tried your Volt component and it works properly for me when clicking the switch and/or the label.

Have you?:
- compiled your assets (`npm run build`)
- run `composer update` to make sure you have the latest Flux v1.0.23
- deleted any previously published Flux components
- run `php artisan view:clear`

**Comment by hidicamar** [comment]
@jeffchown 

Composer update, deleting previously published component and publishing it again alongside view:clear, solve the problem for me.

That was the only thing I forgot to do while clearing the cache, dumping autoload etc...

Thank you and sorry for a little time-waster.

**Comment by jeffchown** [comment]
You're welcome @hidicamar - happened to me too once before I realized what was happening 🙂
