### ISSUE TITLE
Button Width is not correct when using icons only

### ISSUE THREAD

**Issue by alexanderkroneis** [livewire/flux#670]
Hi! 👋 

We tried to use `flux:button` by using `icon` and `icon-trailing` only and saw that the button width is not correctly.

```html
<flux:button size="sm">
    <x-slot:icon>
        <flux:icon.swatch variant="solid" class="size-4"/>
    </x-slot:icon>
    
    <x-slot:icon-trailing>
        <flux:icon.chevron-down variant="solid" class="size-4"/>
    </x-slot:icon-trailing>
</flux:button>
```

![Image](https://github.com/user-attachments/assets/4baab3a1-d91c-4745-a2c5-66296abe0f94)

**Comment by jeffchown** [comment]
@alexanderkroneis When you pass either the `icon` or `icon-trailing` attribute to a `flux:button` it sets itself to `square`.
So, when you pass both via `x-slot`, I believe that the `flux:icon` doesn't account for two icons and still sets itself to square.

If you don't use `x-slot` and instead:

```
<flux:button size="sm">
    <flux:icon.swatch variant="solid" class="size-4"/>

    <flux:icon.chevron-down variant="solid" class="size-4"/>
</flux:button>
```

Your button should size correctly to the width of your button's content (in this case 2 icons)

**Comment by alexanderkroneis** [comment]
That honestly makes so much sense. 😂 It's working fine, thanks.

**Comment by jeffchown** [comment]
You're welcome @alexanderkroneis
