### ISSUE TITLE
Select size does not work in combination with a variant

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#68]
Alpine components always struggled searching through larger datasets, e.g. a list of countries. Happy to see this resolved with Flux! There are two things that do not seem right though.

1. The outline on the search box has some issues with the rounded corners. Edit: I should've searched. This is already reported in #62. 
2. `size` has no effect, perhaps related to it being a listbox variant?

Screenshots for the first issue:

![CleanShot 2024-09-25 at 17 33 00](https://github.com/user-attachments/assets/323da866-3af1-4f22-bafa-22129bbed32d)

The second issue kind of speaks for itself :)

This is how we use it:

```blade
<flux:select {{ $attributes->whereStartsWith('wire') }} size="sm" variant="listbox" searchable :placeholder="$placeholder">
    <x-slot name="search">
        <flux:select.search placeholder="Search..." />
    </x-slot>

    @foreach ($combobox as $option)
        <flux:option value="{{ $option['id'] }}">{{ $option['name'] }}</flux:option>
    @endforeach
</flux:select>
```

If anything is missing please let me know!

**Comment by wevertondcl** [comment]
Item 1 are same problem here, i just published the select component and removed the outline for the moment...
The second one i jsut created my custom variants for Lg size, cause listbox variant dont have bigger size than sm.

**Comment by calebporzio** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps to reproduce. Then, we will be happy to help.
