### ISSUE TITLE
flux:modal: Hide body scrollbar when modal is opened

### ISSUE THREAD

**Issue by BubeDameKoenig** [livewire/flux#680]
If you open a `flux:modal` and the page has a scrollbar, this leads to strange user handling.
It becomes very strange if it is a `flyout` and it is longer. So there are two scrollbars next to each other.

Here in Github the body scrollbar is hidden.

Alpine suggestion:
```javascript
x-init="$watch('show', value => {
      if (value) {
          document.body.classList.add('overflow-y-hidden');
      } else {
          document.body.classList.remove('overflow-y-hidden');
      }
  })"
``` 

![Image](https://github.com/user-attachments/assets/70943d86-a067-4820-b127-e7680654828e)

**Comment by calebporzio** [comment]
This has been fixed in the latest version: https://github.com/livewire/flux/releases/tag/v1.0.29
