### ISSUE TITLE
select variant listbox adds an extra comma after placeholder

### ISSUE THREAD

**Issue by yangsystem** [livewire/flux#686]
Latest flux, latest livewire, tailwind from cdn.

```
    <flux:select variant="listbox" searchable placeholder="Choose industries...">
        <flux:option>Photography</flux:option>
        <flux:option>Design services</flux:option>
    </flux:select>
    <flux:select placeholder="Choose industries...">
        <flux:option>Photography</flux:option>
        <flux:option>Design services</flux:option>
    </flux:select>
```

![Image](https://github.com/user-attachments/assets/49b7e632-9a23-4cf7-b8ec-73a0430bdd49)

**Comment by jeffchown** [comment]
Or maybe you published the Flux select component and edited the list box variant file?

**Comment by yangsystem** [comment]
Nope, I tend to not publish anything.(just use them as is.)
And yes the code is copy paste from my test file.

I have php 8.3.6 (should no matter)
chrome 131.0.6778.70 (should no matter) / edge 131.0.2903.48 (should no matter)
laravel/framework 11.32
livewire/flux-pro 1.0.23
livewire/livewire 3.5.12

as you can see the comma appears only to the variant="listbox" with or without searchable

**Comment by jeffchown** [comment]
@yangsystem I see it in your screenshot (the comma), but when I copy/paste your code example, I do not see a comma in my test app.

**Comment by yangsystem** [comment]
I have just published the component 
``` php artisan flux:publish ```
and selected select
and the comma disappeared, then I deleted the published files reloaded the page and the comma appeared.

![Image](https://github.com/user-attachments/assets/aca6aeec-f167-4a2f-b968-0b37ac633350)

**Comment by jeffchown** [comment]
@yangsystem Strange...
Did you run `php artisan view:clear` then `npm run build` after deleting the published files?

**Comment by yangsystem** [comment]
```php artisan view:clear```
Fixed the problem.
10Q
