### ISSUE TITLE
flux:link always leaves a trailing space.

### ISSUE THREAD

**Issue by GuidoVeltmaat** [livewire/flux#687]
Hi there!   👋

Problem i am having is that flux:link always leaves a trailing space: 

`<flux:link class="underline">Space</flux:link>, after link.`
result in 
<ins>Space</ins>  , after link.

Whereas a normal <a /> tag leaves no space:
`<a class="underline>No space</a>, after link.`
result in 
<ins>No space</ins>, after link

Im guessing its a bug?

**Comment by calebporzio** [comment]
Because there's a trailing newline character on every Flux Blade component file, rendering a component inline will show up as an errant space like you've found.

I just removed that trailing line and we seem to be good now. Fix will be in the next release. Thanks!

**Comment by GuidoVeltmaat** [comment]
Thanks @calebporzio ! 

It worked for some time, but now it seems im getting the trailing spaces back again everywhere.

**Comment by GuidoVeltmaat** [comment]
Thank you @joshhanley, the trailing space problem was on version 1.0.29. 

When copy your code, i found out it was unrelated to flux. Rather a problem in my PHPStorm IDE.

After autosave it reformatted your code to

```
<div>
   <flux:link href="#">Test</flux:link>
   , something.
</div>
```

For anyone interested;
What i did in PHPStorm to resolve it, was to disable Reformat code on save for Blade.
Specifically for _Settings>Tools>Actions On Save_:
Reformat code _enabled_, and Blade _enabled > disabled_.

I suspect my  _Settings > Editor > Code Style > Blade_ settings to be the problem somehow. Here is what i have:
![Image](https://github.com/user-attachments/assets/2062187a-dd7d-475e-8f1d-9cf26b4fa86f)

**Comment by joshhanley** [comment]
@joshhanley ah no worries! Thanks for posting the solution 🙂
