### ISSUE TITLE
Print issue for Selected Checkbox and Radio element

### ISSUE THREAD

**Issue by joalea** [livewire/flux#695]
Hi,

When printing a page that has a checkbox or radio with a selected value, the selected elements disappear from the print.

**Example**
![Image](https://github.com/user-attachments/assets/8fbe707b-3ca8-47fc-a4dc-1823494a9474)

**How to reproduce**
Latest version of Windows, Chrome, Livewire and Flux
Copy standard code for a checkbox group from documentation:
`<flux:checkbox.group wire:model="notifications" label="Notifications">
<flux:checkbox label="Push notifications" value="push" checked />
    <flux:checkbox label="Email" value="email" checked />
    <flux:checkbox label="In-app alerts" value="app" />
    <flux:checkbox label="SMS" value="sms" />
</flux:checkbox.group>`

Click CTRL+P / Command+P to see the issue in the preview.

**Comment by calebporzio** [comment]
Mmmm good catch. Fixed, will be in the next release:

![Image](https://github.com/user-attachments/assets/c6ee658e-1767-436c-bbf9-3b082f39a414)

**Comment by calebporzio** [comment]
Uncovered a handful of other components that needed updating along the way (went through every component checking for print issues)

![Image](https://github.com/user-attachments/assets/1205a46c-e43c-4db2-a4f1-91686fbdf434)

**Comment by calebporzio** [comment]
Scratch that, I just learned about print-color-adjust in CSS. Now print looks the same as the page

![Image](https://github.com/user-attachments/assets/8c1034b9-d0a0-4be4-9e1a-d2e1354fdcff)
