### ISSUE TITLE
Component <flux:option> fails to handle value of 0

### ISSUE THREAD

**Issue by KFoobar** [livewire/flux#696]
The component for rendering `<option>` tags within a `<select>` field fails to correctly handle when the value is set to 0. The issue occurs because the conditional logic in the Blade template skips over values that are set to 0, treating them as falsy.

The issue is in the following code block from `flux-pro/stubs/resources/views/flux/option.blade.php`:

```
<?php else: ?>
    <option
        {{ $attributes }}
        @if ($value) value="{{ $value }}" @endif
        @if ($value) wire:key="{{ $value }}" @endif
    >{{ $slot }}</option>
<?php endif; ?>
```

### Reproduction
```
<flux:select wire:model="type" label="Type" placeholder="Choose type...">
    <flux:option value="1">Type 1</flux:option>
    <flux:option value="0">Type 0</flux:option>
</flux:select>
```

### Solution
```
@if (isset($value) || $value === 0) value="{{ $value }}" @endif
```

**Comment by jeffchown** [comment]
Related to https://github.com/livewire/flux/issues/667

**Comment by calebporzio** [comment]
Thanks for this, there was a loose equality check on the `$value` prop in the option component instead of checking for a strict `null`.

Will be fixed in the next release. Thanks.
