### ISSUE TITLE
Navigating to page and going back causes placeholder of `flux:select multiple` to be duplicated when using `wire:navigate`.

### ISSUE THREAD

**Issue by SeraphixMD** [livewire/flux#697]
When no placeholder text is present, a space is duplicated.

In another case, the `x selected` text is being duplicated, but I couldn't replicate this in a standalone example. 
```blade
<flux:select variant="listbox" wire:model.live="filteredIngredients" multiple searchable>
    @foreach($ingredients as $ingredient)
        <flux:option value="{{ $ingredient->id }}">{{ $ingredient->name }}</flux:option>
    @endforeach
</flux:select>
``` 
Minimal example: 
```php
<?php

namespace App\Livewire;

use Illuminate\View\View;
use Livewire\Component;

class SelectTest extends Component
{
    public function render(): View
    {
        return view('livewire.select-test')
            ->layout('layouts.guest');
    }
}
```
```blade
<div>
    <flux:select variant="listbox" multiple placeholder="Choose industries...">
        <flux:option>Photography</flux:option>
        <flux:option>Design services</flux:option>
        <flux:option>Web development</flux:option>
        <flux:option>Accounting</flux:option>
        <flux:option>Legal services</flux:option>
        <flux:option>Consulting</flux:option>
        <flux:option>Other</flux:option>
    </flux:select>
    
    <flux:button href="{{ route('pages.home') }}" wire:navigate>
        Click me!
    </flux:button>
</div>
```  
```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=inter:400,500,600&display=swap" rel="stylesheet"/>

    <!-- Styles / Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    @livewireStyles
    @fluxStyles
</head>
<body class="min-h-screen bg-white dark:bg-zinc-800">

<flux:main container>
    {{ $slot }}
</flux:main>

@livewireScripts
@fluxScripts
</body>
</html>
``` 
```blade
<x-guest-layout>
    My Super Duper Awesome Home Page!
</x-guest-layout>
``` 
```php
Route::get('/', function () {
    return view('pages.home');
})->name('pages.home');

Route::get('/test', \App\Livewire\SelectTest::class)
     ->name('test');
```

**Comment by SeraphixMD** [comment]
Another things I noticed, when selecting a couple things, navigating to a different page and then going back, the select still says x selected, but nothing in the list is actually selected. I'd guess this is because there's no binding, but then the select still shouldn't show x selected.

**Comment by jeffchown** [comment]
@SeraphixMD Can you show your `app.js` file as well?

**Comment by SeraphixMD** [comment]
@jeffchown 
`app.js`:
```javascript
import './bootstrap';
``` 
`bootstrap.js`:
```javascript
import axios from 'axios';
window.axios = axios;

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
```

**Comment by jeffchown** [comment]
@SeraphixMD I tested your code and can't recreate the issue.

These are the navigation steps I tried:

- Started on `/` (`pages.home` view)
- edited browser url to `/test`
- selected a couple of options in multiple select
- edited browser url to `/` (back to `pages.home`)
- pressed back button in browser to return to `/test`

Everything worked as expected for me.

If you are using different navigation steps, please provide the process.

**Comment by SeraphixMD** [comment]
Yeah, it's clear that _something_ is broken, but I'm also having difficulties reliably replicating the the other case I mentioned😒

I'll create a new project from scratch and see where I end up.

**Comment by SeraphixMD** [comment]
@jeffchown https://github.com/SeraphixMD/select-test.git This reproduces the placeholder text being duplicated. Created a new blank project through Herd, added Flux as a dependency, followed installation guide, and added the minimal code necessary to reproduce 👍 How did you reproduce the `x selected` being duplicated? Could you maybe add it to that repo as a quick PR for Caleb?

**Comment by SeraphixMD** [comment]
Well, I **can** replicate the `x selected` being duplicated issue, by selecting something, switching pages and going back and selected something, which then shows `x selected` for as many times as you do it, but in my main project the `x selected` is duplicating itself just like the placeholder is duplicating itself, without having to select new items in between...

**Comment by jeffchown** [comment]
@SeraphixMD I used your code from above to reproduce the `x selected`.  Went to `/test`, selected a few options, clicked your `Click me!` button to go to `pages.home`, then click the browser's back button.

**Comment by SeraphixMD** [comment]
Just to make sure we're not talking alongside each other, are you not seeing this behavior? This is on the new project I just shared: https://github.com/user-attachments/assets/d9b77b0d-9f2d-4fe0-a7f7-646e34e599d1

**Comment by jeffchown** [comment]
Gotcha - with your added detail(s), I was able to recreate that issue as well (using your original code and the steps you mentioned)

![Image](https://github.com/user-attachments/assets/a6569566-15ae-492c-8e16-c1147f90a110)

**Comment by calebporzio** [comment]
I confirmed the issue exists - thanks for helping on this @jeffchown.

I had to add some code to cleanup any leftover elements generated by <ui-selected> that might get cached by Livewire when navigating forward and back.

Fixed and will be in the next release.

**Comment by RezaODB** [comment]
I'm still having this with this code:
`<flux:select wire:change="setGroup({{ $user->id }}, $event.target.value)" variant="listbox" searchable size="sm" :placeholder="__('Select store...')">
                        @foreach ($groups as $group)
                        <flux:option :value="$group->id" wire:key="{{ $group->id }}" :selected="$user->group_id === $group->id">{{ $group->name }}</flux:option>
                        @endforeach
                    </flux:select>`
