### ISSUE TITLE
Styling problem when I'm in dark mode (select multiple)

### ISSUE THREAD

**Issue by blagapro** [livewire/flux#699]
Hello,

I hope you are well. I'm having a styling problem with the new version. When I'm in dark mode and I put the multiple select, I get this display.

Any idea where the problem might come from?

Thanks

![Image](https://github.com/user-attachments/assets/ce0124c1-b155-4cbd-bd6c-3d967f21ee1b)

**Comment by raftia** [comment]
Hi @blagapro , check if you are using tailwindcss forms plugin, if you are you need to disable it.

Cheers!

**Comment by calebporzio** [comment]
Hope that helped @blagapro. (thanks @raftia) - please re-open a new issue if the problem persists. Closing for now.
