### ISSUE TITLE
Pls help with select multiple

### ISSUE THREAD

**Issue by tm-blg** [livewire/flux#705]
### Discussed in https://github.com/livewire/flux/discussions/666

<div type='discussions-op-text'>

<sup>Originally posted by **tm-blg** November 13, 2024</sup>
Hi, there! I'm trying to save array into model 

```
<flux:select wire:model.live="var.product_kinds" variant="listbox" multiple placeholder="Choose industries...">
        <flux:option>bulb</flux:option>
        <flux:option>partnumber</flux:option>
        <flux:option>projector</flux:option>
</flux:select>
```

```
#[Validate([
    'var.product_kinds' => 'array|nullable',
])]
public Feature $var;

public function mount()
{
    $this->var = new Feature();
}
```

Where i choose more than two option, i get LogicException "Something went wrong"

![image](https://github.com/user-attachments/assets/44212ac6-5b60-4079-8b2d-3682153aeac9)
![image](https://github.com/user-attachments/assets/f23959b8-7cda-4c7f-9e1b-0cf7b6d547c7)

</div>

**Comment by tm-blg** [comment]
In Livewire2 we dont need to do anything, all is work. is it possible to at least create some kind of comparison of versions and principles of work, so as not to mislead fans of livewire. It seemed logical to me to validate only the array.

**Comment by jeffchown** [comment]
@tm-blg See:

- https://livewire.laravel.com/docs/upgrading
- https://livewire.laravel.com/docs/upgrading#eloquent-model-binding

**Comment by ju5t** [comment]
Arguably, questions should be posted in discussions; this is not a Flux issue.

**Comment by tm-blg** [comment]
> [@tm-blg](https://github.com/tm-blg) See:
> 
> * https://livewire.laravel.com/docs/upgrading
> * https://livewire.laravel.com/docs/upgrading#eloquent-model-binding

dear, it's not like I read all the documentation three times, I also rewatched Caleb's video courses.

your links don't have any info on such a small detail. you couldn't figure it out last time, remember?

Okay, forget it, I'm very emotional because I spent a lot of effort. Thanks everyone, bye!

**Comment by joshhanley** [comment]
@tm-blg yeah you need to ensure the rules exist (as you discovered) if using legacy_model_binding to ensure that any required attributes are sent to the front-end. We don't recommend using model binding going forward, so I would suggest refactoring away from it when you can. As you seem to have solved the issue, I'm going to close this. If you still have problems, please open a new issue.

@ju5t I asked them to raise this as an issue as they had raised it as a feature request discussion which was the wrong place. At this stage we don't have a help discussion label as we don't want people to think they will get support there when we are only checking issues. So questions should just be issues for now.
