### ISSUE TITLE
Bug: breadcrumbs.item not working with wire:navigate

### ISSUE THREAD

**Issue by trimline-gaiustemple** [livewire/flux#71]
When using wire:navigate on breadcrumb items (https://fluxui.dev/components/breadcrumbs), nothing happens on click.  Possbily because the wire:navigate isn't getting added to the `<a>` tag but the parent div?

Working:
`<flux:breadcrumbs.item href="{{ route('dashboard.index') }}">Dashboard</flux:breadcrumbs.item>`

Not Working:
`<flux:breadcrumbs.item href="{{ route('dashboard.index') }}" wire:navigate>Dashboard</flux:breadcrumbs.item>`

**Comment by beneyraheem** [comment]
```
<flux:breadcrumbs.item>
  <a wire:navigate href="{{ route('welcome') }}">Dashboard</a>
</flux:breadcrumbs.item>
```

I guess you can pass to the slot.

**Comment by gaiustemple** [comment]
Yes, I can't open a PR as it's a private repo but the fix is
```
<div {{ $attributes->class($classes)->except(['wire:navigate']) }} ... >
    <?php if ($href): ?>
        <a ... href="{{ $href }}" {{ $attributes->only('wire:navigate') }}>
```

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
