### ISSUE TITLE
Flux input of type file

### ISSUE THREAD

**Issue by Jaiieq** [livewire/flux#711]
When using a flux input of type file, is there a way to clear the filename?  It appears to set a 
```php
<div x-ref="name">
```
 and I can't find a way to clear it.

I have a modal that allows for a file upload.  When dismissed, the filename persists and I want to clear that.  Validation still work though if the file is null, but its disjointed when a name still exists there.

**Comment by lotje-kinable** [comment]
@Jaiieq maybe you can use the [@close](https://fluxui.dev/components/modal#close-events) from the modal to call a method like 'clearFileUpload' and clear the filename there? 

and use:  

```
   <flux:modal.close>
          <flux:button wire:click="clearFileUpload"  variant="ghost">Cancel</flux:button>
   </flux:modal.close>
```

Or is that not what you are asking?

**Comment by Jaiieq** [comment]
@lotje-kinable I have already tried clearing it via $this->reset, setting the wire:model to null, and even clearing the input via the console but as part of the component itself is this:

```php
<div x-ref="name" class="cursor-default select-none truncate whitespace-nowrap text-sm text-zinc-500 dark:text-zinc-400 font-medium" aria-hidden="true">file.csv</div>
```

...which persists and I can't find a way to clear it.

**Comment by lotje-kinable** [comment]
@Jaiieq I tried it in a Volt component and have the same problem!

```

<?php

use Livewire\Volt\Component;
use Livewire\WithFileUploads;
use Livewire\Attributes\Computed;

new class extends Component {

    use WithFileUploads;
    public $file;


    public function clear()
    {
        $this->file = null;
    }


}; ?>

<div class="mt-24 space-y-24">

    <div class="px-12 pt-2 space-y-3">
        File: {{ $file }}

        <flux:input type="file" wire:model.live="file" label="Logo"/>

        <flux:button wire:click="clear">Clear</flux:button>
    </div>
</div>


```

**Comment by Jaiieq** [comment]
The blade component
```blade
<div>
    <div>
        <flux:heading size="lg" class="text-xl mb-6">Add Attachment(s)</flux:heading>
    </div>
    <form wire:submit='save'>
        <flux:input type="file" wire:model="attachments" />
        <flux:error name="attachments" />
        <div class="flex items-center justify-center gap-x-4 mt-6">
            <flux:modal.close>
                <flux:button variant="ghost" class="!w-[175px] !p-4 !text-xl" wire:click='cancel' >Cancel</flux:button>
            </flux:modal.close>
            <flux:button type="submit" variant="primary" class="!w-[175px] !p-4 !text-xl">Submit</flux:button>
        </div>
    </form>
</div>
```

And both the 'save' and 'cancel' methods do this

```php
$this->reset('attachments');
$this->resetErrorBag();
$this->resetValidation();
```

However, the filename(s) are kept in the 'x-ref' tag and not the input tag as shown in my previous reply.

**Comment by lotje-kinable** [comment]
@Jaiieq I have the exact same issue, so there might be something missing in the "/flux/input/file.blade.php" but I can't point it out. Sorry

**Comment by Jaiieq** [comment]
Aye, it is this part of the file.blade.php, line 54. 

```blade
<div x-ref="name" class="..." aria-hidden="true">
        {!! __('No file chosen') !!}
</div>
```

Techincally, everything works just fine but visually that x-ref  still references the file name. Maybe there might be a livewire/alpine.js hook to modify that divs contents, but my baby brain hasn't figured it out (yet).

**Comment by calebporzio** [comment]
Wew, that was a bugger. Basically, the native input element doesn't dispatch a `change` event when it is cleared via `el.value = null`.

Truly the only way I can find to hook into "clearing" is to hijack the object descriptor of the input element and intercept the setting of the `.value` property and dispatch my own event.

Gross, but I don't see another way. As always, everything in a browser is way more involved than you think.

Fix will be in the next release.

Here's the grossness:

![Image](https://github.com/user-attachments/assets/b9239a72-cef1-42fa-8ce3-576016c59a20)

**Comment by Jaiieq** [comment]
Well, that's pretty gnarly.  Thanks @calebporzio for all your hard work!
