### ISSUE TITLE
Unintended border around multiselects.

### ISSUE THREAD

**Issue by ArcanaLLC** [livewire/flux#717]
I am getting a black rectangular border around my multiselects on the latest Safari & Firefox on MacOS Sequoia. I am just using the default multiple select example from the docs.

```
<flux:select variant="listbox" multiple placeholder="Choose industries...">
            <flux:option>Photography</flux:option>
            <flux:option>Design services</flux:option>
            <flux:option>Web development</flux:option>
            <flux:option>Accounting</flux:option>
            <flux:option>Legal services</flux:option>
            <flux:option>Consulting</flux:option>
            <flux:option>Other</flux:option>
</flux:select>
```

In inspector it looks as if some default Tailwind styling is the issue? See attached screenshot. I am on the latest version of Tailwind
![Image](https://github.com/user-attachments/assets/d891709d-3697-4c09-87b2-2e76fe6bd45d)

Edit: Narrowed this down to the Tailwind Forms plugin. Issue resolved on my end by removing the plug in. Will leave up for visibility but feel free to remove if already aware of the overlap.

**Comment by jeffchown** [comment]
@ArcanaLLC The incompatibility with Tailwind Forms is documented in the Installation docs (https://fluxui.dev/docs/installation) at the bottom of the section titled **4. Set up Tailwind CSS**

![Image](https://github.com/user-attachments/assets/51062683-d10c-4300-9047-696e2e4c7dc5)
