### ISSUE TITLE
Problems when running composer update

### ISSUE THREAD

**Issue by spitfire64** [livewire/flux#722]
When I run composer update (edit: ...on my live server...) to install a completely different package I am promted to give my Flux usernamne and password:

```Loading composer repositories with package information
    Authentication required (composer.fluxui.dev):
      Username: my-flux-username
      Password: my-flux-password
```
When I do so, I get this:
```
In AuthHelper.php line 216:
  Invalid credentials (HTTP 401) for 'https://composer.fluxui.dev/packages.js
  on', aborting.
```

Edit: I just moved my project from www.my-old-appname to www.my-new-appname

**Comment by joshhanley** [comment]
@spitfire64 can you please email support@fluxui.dev with your account email so we can investigate the authentication issue? Also can you include whether you can authenticate locally (remove your auth.json and try to activate flux again).

Going to close this so we can handle it in support.
