### ISSUE TITLE
[1.0.25] modal: x-on:close syntax throws alpine expression error

### ISSUE THREAD

**Issue by lotje-kinable** [livewire/flux#724]
Hi! 👋

When using the x-on:close syntax for closing a modal, the following errors show: 

![Image](https://github.com/user-attachments/assets/bee54256-9807-48d1-8bcf-2c76b67118ce)

The other 2 options @close and wire:close [suggested here](https://fluxui.dev/components/modal#close-events) work as expected! I added a minimal Volt component, where the working options can be uncommented to check. 

```
<?php
use Livewire\Volt\Component;

new class extends Component {

    public bool $showTheModal = false;

    public function closeTheModal()
    {
        $this->showTheModal = false;
    }

}; ?>


<div class="space-y-28">


    <flux:button x-on:click="$wire.showTheModal = true">Show modal</flux:button>

 
    {{--  <flux:modal wire:model.self="showTheModal" @close="closeTheModal" class="min-w-72">     --}}
    {{--  <flux:modal wire:model.self="showTheModal" wire:close="closeTheModal" class="min-w-72"> --}}

    <flux:modal wire:model.self="showTheModal" x-on:close="closeTheModal" class="min-w-72">

        <div>
            <flux:heading size="lg">Test modal</flux:heading>
        </div>

        <div class="flex">
            <flux:spacer />

            <flux:modal.close>
                <flux:button variant="primary">Cancel</flux:button>
            </flux:modal.close>

        </div>

    </flux:modal>

</div>

```

Thanks again!

**Comment by jeffchown** [comment]
@lotje-kinable as `x-on` is Alpine, shouldn't it be `x-on:close="$wire.closeTheModal"`?

**Comment by lotje-kinable** [comment]
@jeffchown this is in the docs: "You can also use wire:close or x-on:close if you prefer those syntaxes" and I did not think about adding the < $wire. > . Of course I works fine now! 

Thank you!
