### ISSUE TITLE
`flux:select variant="listbox"` requires a `space+<first character>` when searching options

### ISSUE THREAD

**Issue by jeffchown** [livewire/flux#726]
(reopening https://github.com/livewire/flux/issues/663)

@calebporzio in v1.0.24 and v1.0.25 I still have to add a leading space to my search (due to the leading and trailing space in the `flux:select variant="listbox"`'s `option`s) to get a `listbox` to find a matching option.

e.g. when the `listbox` is focused, to search `Web` to highlight `Web Development` I have to type `space+w` (vs. just `w` with a native select)

**Comment by jeffchown** [comment]
UPDATE: Further to my original post, I am referring to typing when the `flux:select` is focused but the dropdown is **not** open

@calebporzio Are alpha `keydown`s not processed unless the dropdown is open?

**Comment by tjgore** [comment]
> Are alpha keydowns not processed unless the dropdown is open?

Yes, that's the case. The listbox seems to wait for either an `ArrowDown` or `Space` keydown event to open the list of options. The odd thing here is I do see logic for the `ArrowDown` key event but nothing for `Space` event.
I can also use chrome devtools debugger to pause execution on `ArrowDown` event but not on the `Space`. I'm wondering if the `Space` key event is a browser behavior.

I checked out other component libraries and they seem to handle listboxes in a similar way. Wait to be open before you can search the options.
I do like the idea of making the listbox work like the select. It provides a better user experience.

Looking into a possible solution that requires an update to the internals of flux select.js. Still testing it out. Will keep you posted.

**Comment by jeffchown** [comment]
Thanks for digging in to this @tjgore 👍

I think you're right re: the `space` key behaviour being browser-related.

An update/solution would/will indeed require an update to select.js

**Comment by tjgore** [comment]
@jeffchown Was wondering does switching your listbox components to the select component give you what you need? Is there a specific reason for using the listbox component? After looking through a few UI libraries, it looks like listboxes generally work in the way you described.
Here are 2 examples: [Headless UI Listbox](https://headlessui.com/react/listbox) and [React Aria Listbox](https://react-spectrum.adobe.com/react-aria/ListBox.html).

**Comment by jeffchown** [comment]
@tjgore It does, but then I lose the ability to add some formatting, icons, etc. to each `flux:option` which in this case are needed for the UX in my app.

Thanks for asking and for the links.

**Comment by calebporzio** [comment]
Finally got this fixed and merged - will be out soon - thanks Jeff!

**Comment by jeffchown** [comment]
Thanks, @calebporzio !
