### ISSUE TITLE
Flux:buttons are at different vertical offsets and sizes, depending on content

### ISSUE THREAD

**Issue by rikh42** [livewire/flux#728]
This means that they appear out of line, with some higher up than other.

For example, with the following markup...

```
<div class="my-12">
    <flux:button icon-trailing="chevron-down">Layout</flux:button>
    <flux:button icon-trailing="chevron-down"></flux:button>
    <flux:button><flux:icon.chevron-down /></flux:button>
    <flux:button square><flux:icon.chevron-down /></flux:button>
</div>
```

Results in the following buttons that are all over the place...

![Image](https://github.com/user-attachments/assets/2bb17345-df27-4a27-ab97-564c713d52fd)

I have tried this in Chrome and Firefox, with the same result.

I would expect all the buttons to have the same vertical height and same baseline

Thank you!

**Comment by jeffchown** [comment]
@rikh42 See @calebporzio 's response (underneath my comment) here https://github.com/livewire/flux/issues/499#issuecomment-2429221899

**Comment by rikh42** [comment]
OK, but is it possible to create a flux:button with only an icon in it, that lines up with a flux:button that also contains text?

In the example above, the only difference between the first two is that the first also has some text content.

If I adjust the other two, which involve a separate flux:icon, to use the micro size, they still don't line up with the first example.

**Comment by jeffchown** [comment]
@rikh42 I usually wrap my button groups like this:
```
<div class="flex items-center space-x-3">
    <flux:button type="submit" variant="primary">Save</flux:button>

    <flux:button type="button" variant="filled">Cancel</flux:button>

    ...more buttons...
</div>
```

That way, as long as the buttons are the same height, they will align properly.

**Comment by joshhanley** [comment]
@rikh42 I'm going to close this as @jeffchown is correct that you should use `flex items-center` to align all the buttons. I believe the alignment is due to the different content types and sizes (text + icon, no text + icon), so using flex fixes that. Feel free to open a new issue if you don't agree.

```blade
<div class="flex items-center space-x-1">
    <flux:button icon-trailing="chevron-down">Layout</flux:button>
    <flux:button icon-trailing="chevron-down"></flux:button>
    <flux:button><flux:icon.chevron-down /></flux:button>
    <flux:button square><flux:icon.chevron-down /></flux:button>
</div>
```

<img width="291" alt="Image" src="https://github.com/user-attachments/assets/d26e5f13-ef77-41ca-83f9-d93351fa7ce9" />
