### ISSUE TITLE
Multiple file input not clearing when property defaults to an array

### ISSUE THREAD

**Issue by Jaiieq** [livewire/flux#729]
References: https://github.com/livewire/flux/issues/711

I've done a full composer update so I have the latest flux and the 'x-ref' field that references the filename still is not clearing itself of the last selected filename (or filenames, e.g. '2 files')

Here is my simple blade component:

```blade
<form wire:submit='save'>
      <flux:input type="file" wire:model="attachments" multiple />
      <flux:error name="attachments" />
      <div class="flex items-center justify-center gap-x-4 mt-6">
          <flux:modal.close>
              <flux:button variant="ghost" wire:click='cancel' id='test'>Cancel</flux:button>
          </flux:modal.close>
          <flux:button type="submit" variant="primary">Submit</flux:button>
      </div>
</form>
```

For completeness, this is the wire:click cancel function. The same happens on a successful 'save' as well

```php
public function cancel()
{
    $this->reset('attachments');
    $this->resetErrorBag();
    $this->resetValidation();
}
```
I've tried all of the following, which properly clears the input field value, but not the x-ref value that is displayed.  I've also tried clearing the input via the console with vanilla javascript, but nothing seems to trigger the change to the x-ref div

```php
$this->reset('attachments');
$this->attachments = [];
$this->attachments = null;
```
The only way I can get it to clear the x-ref is after clicking the "Choose Files" button is to then click  cancel out of the open file dialog.

Am I missing something?  Thanks in advance!

**Comment by joshhanley** [comment]
@calebporzio just tested this with v1.0.28 and can confirm that the file inputs still do not clear correctly. It works fine when clearing a single file input, but when using a multiple file input it still says "x files" after the property has been cleared.

**Comment by Jaiieq** [comment]
Thanks @joshhanley.  I just did some additional testing that backs up yours and I think further clarifies the issue.

It doesn't matter if the input type has the multiple tag in it, it has to do with the declaration of the wire:model variable.  A declaration of:

```php
public attachment;
```
...will clear the x-ref regardless of the multiple tag on the input, however, if you do this:

```php
public attachment = [];
```
...the x-ref does not properly clear.

**Comment by tjgore** [comment]
This seems to break when  the `wire:model property` is not undefined, null, or an empty string.

If you define or set `$attachments` as one of the following types, this works fine.
This is probably due to file `input.value`s  only being able to accept null, undefined, or an empty string.

If an array is passed to the input value, the input just ignores it and the change event is never fired. The  x-ref div is controlled by js and needs the input change event to be called to update.

If you still want to use an array, you can do the following and this will work as expected.
```php
    public ?array $attachments = [];

    public function cancel()
    {
        $this->attachments = null; // or ''
    }
```
I'm not sure what the solution would be to trigger an event with an array value for the file input. Maybe, if we can access the input value before the component gets it, we can check if the value is an empty array and set it to an empty string.

**Comment by jeffchown** [comment]
@joshhanley I profusely apologize in advance for the off topic, ocd-in-me request ;) - could you please update the `reproducable` label to `reproducible`?  My eye/brain won't let me ignore it 🤪

**Comment by joshhanley** [comment]
@Jaiieq thanks for testing! I always initialise using `public array $attachments = [];` for multiple files, etc. so we will try and see if there is a way to fix this in Flux as it should work with setting the type/initial value, it's how people expect it to work.

@jeffchown done!

**Comment by joshhanley** [comment]
@Jaiieq it turns out that this was actually an issue in Livewire, as it was still happening when I tested with non-flux inputs.

I'm submitted a PR #9106 to Livewire with a fix.

**Comment by Jaiieq** [comment]
Thanks @joshhanley!  Appreciate you guys!
