### ISSUE TITLE
Flux option group - using boolean not working

### ISSUE THREAD

**Issue by codeldev** [livewire/flux#73]
I have seen this closed issue here #42 , however I cannot seem to get this working for the following:

```
<flux:radio.group
    wire:model.boolean="form.use_system_mailer"
    :label="trans('config.mailer.system')"
    :description="trans('config.mailer.system.helper')">
    <flux:radio 
        value="true"
        :label="trans('config.mailer.system.yes')" />
    <flux:radio
        value="false"
        :label="trans('config.mailer.system.no')" />
</flux:radio.group>
```

In the above, nothing is showing as checked even when form.use_system_mailer is loaded as true/false.

I have other form fields on the page which show/hide based on the selected radio via $wire.form.use_system_mailer, but these are not being triggered to show/hide.

Removing the boolean from the wire:model doesn't help either.

Any help appreciated!

**Comment by codeldev** [comment]
Just to add, that in the livewire component:

```
public MailerConfigForm $form;
```

in that file:

```    
#[Validate(['required', 'boolean'])]
public bool $use_system_mailer = true;
```

**Comment by lghcdh** [comment]
Some additional information. I decided to test the radio group with integers and regular strings. Results as follows:

Livewire Component

```
    #[Validate(['required', 'string'])]
    public string $with_string = '1';

    #[Validate(['required', 'integer'])]
    public int $with_integer = 1;

    #[Validate(['required', 'boolean'])]
    public bool $with_boolean = false;
```

Blade component

```
    {{-- Works: YES --}}
    <flux:radio.group wire:model="with_string" label="Works with a string?">
        <flux:radio value="1" label="Yes" />
        <flux:radio value="0" label="No" />
    </flux:radio.group>

    <flux:separator />
    
    {{-- Works: NO --}}
    <flux:radio.group wire:model.number="with_integer" label="Works with an integer?">
        <flux:radio value="1" label="Yes" />
        <flux:radio value="0" label="No" />
    </flux:radio.group>

    <flux:separator />
    
    {{-- Works: NO --}}
    <flux:radio.group wire:model="with_boolean" label="Works with a boolean?">
        <flux:radio value="true" label="Yes" />
        <flux:radio value="false" label="No" />
    </flux:radio.group>
```

Only seems to work with strings. Using integers or booleans along with the required modifier do not work. Hope that helps.

**Comment by bzarzuela** [comment]
Yup, I have this issue as well. 

Using `:value="true"` doesn't work either. I hoped it would cast to a primitive so that the check will pass but no luck.

**Comment by satoved** [comment]
I have troubled with integers as well

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
