### ISSUE TITLE
Expanded prop in collapsible navbar does not react dynamically

### ISSUE THREAD

**Issue by webmakac** [livewire/flux#730]
Hi,
expanded prop in collapsible navbar does not react dynamically to property value changes.

I show a simple example with a sidebar livewire component

```
class Sidebar extends Component
{
    public $open = false;
}

<flux:navlist.group heading="Account" expandable :expanded="$open">
        <flux:navlist.item href="#">Profile</flux:navlist.item>
        <flux:navlist.item href="#">Settings</flux:navlist.item>
        <flux:navlist.item href="#">Billing</flux:navlist.item>
</flux:navlist.group>

<flux:button wire:click="$wire.set('open', !$wire.open)">toggle navlist</flux:button>
```

When I change "open" property value with button, nothing happens on navlist collapse status.

**Comment by jeffchown** [comment]
@webmakac One way I've found to make this work is to 'force' Livewire to re-render your group on a `livewire/update` call (updating `$open`) by adding a changing `wire:key` to the `flux:navlist.group` (essentially, making your `navlist.group` reactive to the toggling of `$open`.

PS you don't need the `$wire` in your `wire:click="$wire.set..."`, and, you can shorten it by using `$toggle` (see below)

e.g.

```
<div>
    <flux:navlist.group
        :wire:key="$open ? 'open' : 'closed'"
        heading="Account"
        expandable
        :expanded="$open"
    >
        <flux:navlist.item href="#">Profile</flux:navlist.item>
        <flux:navlist.item href="#">Settings</flux:navlist.item>
        <flux:navlist.item href="#">Billing</flux:navlist.item>
    </flux:navlist.group>

    <flux:button wire:click="$toggle('open')">
        toggle navlist
    </flux:button>
</div>
```

**Comment by jeffchown** [comment]
You're welcome, @webmakac

**Comment by jeffchown** [comment]
@webmakac Don't forget to close this issue

**Comment by joshhanley** [comment]
Just tested this and for it to be reactive you need to use Livewire. So try adding `wire:model="open"` to your `navlist.group` instead of using the expanded prop.

Also there is an error with your button, you can't call `$wire.` from a `wire:click`, so instead it needs to be `wire:click="$set('open', !$wire.open)"` or shorthand you can just to `wire:click="$toggle('open')"`

Here's a working Volt component for you to test with. Going to close this for now, but if you still have any issues, please open a new issue.

```blade
<?php

use App\Models\Post;
use App\Models\User;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Validate;
use Livewire\Volt\Component;
use Livewire\WithFileUploads;

new class extends Component {
    public $open = false;
};

?>

<div>
    <flux:navlist.group heading="Account" expandable wire:model="open">
        <flux:navlist.item href="#">Profile</flux:navlist.item>
        <flux:navlist.item href="#">Settings</flux:navlist.item>
        <flux:navlist.item href="#">Billing</flux:navlist.item>
    </flux:navlist.group>

    <flux:button wire:click="$toggle('open')">toggle navlist</flux:button>
</div>
```

**Comment by jeffchown** [comment]
Very cool, @joshhanley!  I didn't realize we could data bind in a `flux:navlist` as well 👍
Could that be added to the https://fluxui.dev/docs/patterns#data-binding docs page?

**Comment by joshhanley** [comment]
@jeffchown yep possibly, where/how do you think it should be added in to that page?

**Comment by jeffchown** [comment]
@joshhanley How about in this section:

![Image](https://github.com/user-attachments/assets/67a15341-8eab-4cee-a434-a011e6518095)

**Comment by joshhanley** [comment]
@jeffchown cool, submitted a PR to add it 🙂
