### ISSUE TITLE
Input for file uploads displays incorrectly in light mode.

### ISSUE THREAD

**Issue by maparfitt** [livewire/flux#731]
The input with file="type" displays incorrectly in light mode, I think. It shows the browser's default "browse" button instead of the "Choose file" text shown in the docs.

<flux:input type="file" wire:model="form.headshot" label="Headshot" />

![Image](https://github.com/user-attachments/assets/91ff41e9-a958-4518-9e9e-448ea105d58e)
#

**Comment by maparfitt** [comment]
Yes, I’ve run npm run build. Well, it’s probably not a bug on your end if you’re getting what the docs mention. Must be something on my end, so I’ll figure it out.

Thanks for getting back to me so quickly — on a Saturday!  -- Matt

On Nov 24, 2024, at 8:05 AM, Jeff Chown ***@***.***> wrote:



@maparfitt<https://github.com/maparfitt> When I copy/paste your code, I get what matches the docs:

***@***.*** (view on web)<https://github.com/user-attachments/assets/2d5f9a84-7228-44e2-be68-71a8de2d5926>

Have you followed the Flux instructions and run npm run build?

**Comment by Kh4os-afk** [comment]
It only worked for me after running `Npm run build`

But I don't think that's a problem....
