### ISSUE TITLE
switch selected?

### ISSUE THREAD

**Issue by bradders** [livewire/flux#733]
Is there an equivalent of `checked` for `<flux:switch>`? Or is it not intended as a component that can be loaded as pre-selected? I noticed that clicking one toggles the `data-checked` but adding that manually doesn't seem to stick.

**Comment by jeffchown** [comment]
@bradders Have you tried `<flux:switch checked label="Enable notifications" />`?  Works for me.

**Comment by bradders** [comment]
Seems like my `wire:model` was scuppering me. I'd manually added the `checked` to see if it was working but that was being overridden by the fact that I'd wired the switch up to a property but not specifically set a value (so it was always false)

My dumb, just sharing for the record!

```
<?php

use Livewire\Volt\Component;
use App\Models\Region;
use \Flux\Flux;

new class extends Component {
    
    public Region $region;
    public $daily;

    public function mount() {
        // I forgot to add this...
        // $this->daily = Auth::user()->region_emails_daily()->where('region_id', $this->region->id)->exists();
    }

    public function updatedDaily($value) {

        if($value === false) {
            Auth::user()->region_emails_daily()->detach($this->region->id);
            Flux::toast(variant: "success", text: "Unsubscribed");
        } else {
            Auth::user()->region_emails_daily()->syncWithoutDetaching($this->region->id);
            Flux::toast(variant: "success", text: "Subscribed");
        }
        
    }

    
};
?>
<div>
    <flux:switch wire:model.live="daily" label="Daily email updates" />
</div>
```

**Comment by jeffchown** [comment]
@bradders Yeah, that'll (`wire:model`) do it! 👍
