### ISSUE TITLE
Last version update has a downgrade?

### ISSUE THREAD

**Issue by jcerdan** [livewire/flux#735]
Hi there! 👋

I have checked 

```composer update --dry-run```

and see that output

```
 - Downgrading laravel/prompts (v0.3.2 => v0.2.1)
  - Upgrading livewire/flux (v1.0.23 => v1.0.26)
  - Downgrading livewire/flux-pro (1.0.23 => 1.0.4)

```

Is this a mistake?

**Comment by calebporzio** [comment]
Can you update to version 1.0.27 of each package? livewire/flux and livewire/flux-pro and tell me if this persists?

**Comment by calebporzio** [comment]
great, thanks!
