### ISSUE TITLE
undefined array key ./flux.css since 1.0.26

### ISSUE THREAD

**Issue by lloydowen** [livewire/flux#736]
Since upgrading to the latest version of flux (1.0.26) i now get error:
```
Undefined array key "/flux.css"
```

from `@fluxStyles` in my blade layout.

![Image](https://github.com/user-attachments/assets/3f792207-8824-4987-a6a2-0eb94e8cb3f1)

**Comment by calebporzio** [comment]
Can you run `php artisan view:clear` to make sure it's not that? thanks

**Comment by calebporzio** [comment]
Ok, upgrade livewire/flux and livewire/flux-pro, that should fix it (sorry had a bad dependancy in version 1.0.26 of livewire/flux-pro)
