### ISSUE TITLE
<flux:option> value must be an integer? [Uncaught Could not find option for value]

### ISSUE THREAD

**Issue by magarrent** [livewire/flux#737]
Hi there! 👋

I'm trying to create a dynamic Select listbox.
But when the option value is a string (like uuid or something else), there is some JS crashing:

```
retrying...
Uncaught Could not find option for value "9d133cdc-100b-4fa6-b32a-2c7be9de71d6"
```

I've tried using a number and it works, it's just with a string values.

This is my current code, but you can try any OPTION with a string value:

**value="{{ $variant['uuid'] }}"**
```
<flux:select wire:model="selectedVariantUuid"
             variant="listbox"
             :filter="false"
             wire:key="variant-select-{{ $categoryName }}"
             placeholder="Choose variant...">
    @foreach($variants as $pos => $variant)
        <flux:option
            class="cursor-pointer"
            value="{{ $variant['uuid'] }}"
            @mouseover="hoverVariant('{{ $variant['uuid'] }}')"
            @mouseout="hoverVariant(null)"
            data-variant-id="{{ $variant['uuid'] }}">
            {{ $variant['name'] }}
        </flux:option>
    @endforeach
</flux:select>
```

flux.js error![Image](https://github.com/user-attachments/assets/38aa74a7-f0a1-4b14-a194-79f5280196c7)

**Comment by jeffchown** [comment]
@magarrent Have you tried it with `:value="$variant['uuid']"` instead?

**Comment by magarrent** [comment]
> [@magarrent](https://github.com/magarrent) Have you tried it with `:value="$variant['uuid']"` instead?

Yep! Also with filter false/true on select (Don't know exactly what it does)

**Comment by jeffchown** [comment]
@magarrent I tried to emulate your code with a simplified version of the code and it works OK for me.
Can you try this? (and see if you still get the error):

```
@php
    $options = [
        ['value' => 'a', 'label' => 'First (A)'],
        ['value' => 'b', 'label' => 'Second (B)'],
        ['value' => 'c', 'label' => 'Third (C)'],
        ['value' => 'd', 'label' => 'Fourth (D)'],
    ];
@endphp

<flux:select placeholder="Choose industry...">
    @foreach ($options as $option)
        <flux:option value="{{ $option['value'] }}">{{ $option['label'] }}</flux:option>
    @endforeach
</flux:select>
```

**Comment by lotje-kinable** [comment]
@magarrent long shot but: maybe the uuid field is hidden in the model?

**Comment by jeffchown** [comment]
@magarrent If my simplified code snippet is giving you an error (I don't get an error with that snippet), have you tried creating a brand new Laravel app, installing Flux and testing it there?  

I suspect there may be something in your current app's layout file, `app.js`, etc. that could be causing the error.

I can't help/recreate your issue in my test app, so if it were me I would test/confirm the error exists even in a brand new app before continuing to diagnose my current app as it might provide more information.

**Comment by magarrent** [comment]
Lol it's getting more annoying...

If I copy the uuid and paste it manually to the option value, it works.

With error or not, the value is sent to the Livewire component, so "it works" but don't know why JS crashes.

I'll keep investigating...

[https://streamable.com/z55kw0](https://streamable.com/z55kw0)

**Comment by magarrent** [comment]
@jeffchown try to put a Str::random on your code:

This is crashing right now

```
@php
    $options = [
        ['value' => '9d133cdc-100b-4fa6-b32a-2c7be9de71d6', 'label' => 'First (A)'],
        ['value' => '9d133cdc-100b-4fa6-b32a-3c7be9de71d6', 'label' => 'Second (B)'],
        ['value' => '9d133cdc-100b-4fa6-b32a-4c7be9de71d6', 'label' => 'Third (C)'],
    ];
@endphp

<flux:select wire:model.live="selectedVariantUuid" variant="listbox" placeholder="Choose industry...">
    @foreach ($options as $option)
        <flux:option value="{{ Str::random(10) }}">{{ $option['label'] }}</flux:option>
    @endforeach
</flux:select>
```

**Comment by jeffchown** [comment]
Hi @magarrent We're going in circles here... I can't recreate your issue.  I just tested the above snippet:

```
<div>
    @php
        $options = [
            ['value' => '9d133cdc-100b-4fa6-b32a-2c7be9de71d6', 'label' => 'First (A)'],
            ['value' => '9d133cdc-100b-4fa6-b32a-3c7be9de71d6', 'label' => 'Second (B)'],
            ['value' => '9d133cdc-100b-4fa6-b32a-4c7be9de71d6', 'label' => 'Third (C)'],
        ];
    @endphp

    <flux:select wire:model.live="selectedVariantUuid" variant="listbox" placeholder="Choose industry...">
        @foreach ($options as $option)
            <flux:option value="{{ Str::random(10) }}">{{ $option['label'] }}</flux:option>
        @endforeach
    </flux:select>
</div>
```

And I do not get any console error.  It works as expected in my Flux test app.

As I've said, I suspect it is something elsewhere in your app that may be causing the issue and it is impossible for anyone here to recreate the issue outside of the context of your project.  Therefore, testing these simplified snippets (and getting different results) is not testing apples-to-apples.

If you can provide a Volt component example that reliably recreates the issue, then people may be able to help figure out what is going on.

**Comment by magarrent** [comment]
Hey @jeffchown I think I found something.
The problem might be when there are multiple selects on the same component with the same model.

[https://streamable.com/dy94ln](https://streamable.com/dy94ln)

Sorry about that, this one is tough

**Comment by dajoeberlei** [comment]
I do have the same issue. When using only one <flux:select /> on the view then it works but using multiple causes the error:
`Uncaught Could not find option for value "3"`

**Comment by jeffchown** [comment]
> Hey [@jeffchown](https://github.com/jeffchown) I think I found something. The problem might be when there are multiple selects on the same component with the same model.
> 
> https://streamable.com/dy94ln
> 
> Sorry about that, this one is tough

I have many forms that use a **lot** of `flux:selects` on the same form with no issues.

@magarrent What do you mean by 'same model'?  Do you mean the same `wire:model` on multiple selects in the same form?  If so, I could understand that maybe being an issue.

Maybe add a unique `wire:key` to each select to make sure Livewire can tell them apart during render.  See if that makes a difference.

**Comment by magarrent** [comment]
> > Hey [@jeffchown](https://github.com/jeffchown) I think I found something. The problem might be when there are multiple selects on the same component with the same model.
> > https://streamable.com/dy94ln
> > Sorry about that, this one is tough
> 
> I have many forms that use a **lot** of `flux:selects` on the same form with no issues.
> 
> [@magarrent](https://github.com/magarrent) What do you mean by 'same model'? Do you mean the same `wire:model` on multiple selects in the same form? If so, I could understand that maybe being an issue.
> 
> Maybe add a unique `wire:key` to each select to make sure Livewire can tell them apart during render. See if that makes a difference.

Yep same wire:model. Already tried wire:key and ID



```
@php
    $options = [
        ['value' => '9d133cdc-100b-4fa6-b32a-2c7be9de71d6', 'label' => 'First (A)'],
        ['value' => '9d133cdc-100b-4fa6-b32a-3c7be9de71d6', 'label' => 'Second (B)'],
        ['value' => '9d133cdc-100b-4fa6-b32a-4c7be9de71d6', 'label' => 'Third (C)'],
    ];
@endphp

<flux:select  wire:model.live="selectedVariantUuid" :filter="false" wire:key="1" variant="listbox" placeholder="Choose industry...">
    @foreach ($options as $option)
        <flux:option value="{{ $option['value'] }}">{{ $option['label'] }}</flux:option>
    @endforeach
</flux:select>
<flux:select  wire:model.live="selectedVariantUuid" :filter="false" wire:key="2" variant="listbox" placeholder="Choose industry...">
    @foreach ($options as $option)
        <flux:option value="123456789">{{ $option['label'] }}</flux:option>
    @endforeach
</flux:select>
```

**Comment by jeffchown** [comment]
@magarrent My money is on using multiple selects on the same page using the exact same `wire:model="propertyName"` causing the problem.  It must make it difficult for Livewire and Flux to keep everything straight.

Not sure what your use case is for the need to do that, but I would recommend refactoring the form/component to make that unnecessary.

**Comment by dajoeberlei** [comment]
@jeffchown seems reasonable. My view has 6 child livewire components which all use 

`<flux:select :key="$uniqueId" wire:model.live="value" ... `

and i get the error. So your guess could be true

**Comment by magarrent** [comment]
@jeffchown alright then, let's see what I can do.

For example, what I have here is a _Product variant_ where each variant belongs to a category.

Category 1
    - Variant 1 (Select)

Category 2
    - Variant 2 (Select)

So I want to know the **selected Variant**, which can be on the first select or the second one

**Comment by jamesautodude** [comment]
> [@jeffchown](https://github.com/jeffchown) alright then, let's see what I can do.
> 
> For example, what I have here is a _Product variant_ where each variant belongs to a category.
> 
> Category 1 - Variant 1 (Select)
> 
> Category 2 - Variant 2 (Select)
> 
> So I want to know the **selected Variant**, which can be on the first select or the second one

What I would do, and this is just me, is have a single parent select to decide which categories and variants to choose.

Example:

Select drop-down for:
What store do you want to shop at?
-walmart-
-amazon-

Then depending on which one they choose, using if/else statements, you can show the category and variant drop-downs with the same wire:models

Otherwise yeah, you'll need to add a number to the end of the models or something

**Comment by magarrent** [comment]
Yep I have to do it differently.

So having multiple same wire:models at the same component might be a problem? Not only for flux, for livewire?

Just to know it

**Comment by jamesautodude** [comment]
> Yep I have to do it differently.
> 
> So having multiple same wire:models at the same component might be a problem? Not only for flux, for livewire?
> 
> Just to know it

As far as I remember, it was when I tried to do similar. Unless I wrapped them in an else/if statement

It also gets messy when you're trying to fill it with pre-existing data

**Comment by jeffchown** [comment]
@magarrent If you use the same `wire:model` in multiple `flux:select`s in the same form (or any other type of control), any time you change the select in one place it will change the value in the other places you use the same `wire:model` making it impossible to set the 'connected' `flux:select`s to different values (in your case, categories).

If I understand your usage correctly, wouldn't it make more sense to use an array element for each `flux:select` so its setting is maintained separately from each of the others?

e.g. I have a form with multiple contacts (for a client) and each contact can be assigned a type, this is an excerpt from that form:

Blade view
```
<div for="form.contacts.{{ $key }}.type" class="col-span-2">
    <flux:select wire:model="form.contacts.{{ $key }}.type">
        <option selected disabled value>Select</option>
        <option value="primary">Primary</option>
        <option value="home">Home</option>
        <option value="work">Work</option>
        <option value="mobile">Mobile</option>
        <option value="family">Family</option>
        <option value="facility">Facility</option>
        <option value="remote">Remote</option>
        <option value="other">Other</option>
    </flux:select>
</div>
```

And the property in the Livewire Form object is:
ContactsForm.php
```
public array $contacts = [];

// with each $contact being an array in the form 
// [
//     'id' => null,
//     'type' => '',
//     'relation' => '',
//     'name' => '',
//     'receives' => 'none',
//     'phone' => '',
//     'email' => '',
// ];

...

/** @var array */
protected $rules = [
    'contacts.*.id' => 'sometimes',
    'contacts.*.type' => 'required',
    'contacts.*.relation' => 'sometimes',
    'contacts.*.name' => 'required',
    'contacts.*.receives' => 'required',
    'contacts.*.phone' => 'sometimes',
    'contacts.*.email' => 'sometimes',
];

```
```

**Comment by magarrent** [comment]
@jeffchown yep it's an option too!

**Comment by joshhanley** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available and your videos are no longer accessible. Please re-submit this issue with a code snippet we can copy and paste into our own apps (ideally Volt components) with steps to reproduce. Please include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Then, we will be happy to help.
