### ISSUE TITLE
Editor link not working in safari

### ISSUE THREAD

**Issue by philippbuerger** [livewire/flux#745]
When I'm trying to add a link to an element the popup closes but the link is not inserted. Tested in safari

**Comment by philippbuerger** [comment]
It seems that #749 fixed a part of it. But it only works pressing enter when adding a link. Pressing the add button has no effect. Maybe its again something with the form element?

**Comment by joshhanley** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps with steps to reproduce. Please include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Then, we will be happy to help.
