### ISSUE TITLE
Dark and light theme

### ISSUE THREAD

**Issue by jaakkoijas** [livewire/flux#747]
There is no information in documentation how themes work. They don't seem to work very well. I get different results with different browsers.

Here is the same view with Chrome and Firefox. Both browsers are in light mode.

![Image](https://github.com/user-attachments/assets/74688878-4bd7-447d-aa59-e31b1c0f9d12)
![Image](https://github.com/user-attachments/assets/4fd4556f-028e-4dfb-aaad-265f6d38f84a)

It seems that in Chrome flux elements are rendered like they are in dark theme.

**Comment by ju5t** [comment]
@jaakkoijas that depends on your Tailwind configuration. See https://tailwindcss.com/docs/dark-mode.

**Comment by joshhanley** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps with steps to reproduce. Please include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Then, we will be happy to help.
