### ISSUE TITLE
Having trouble getting dynamic components to work

### ISSUE THREAD

**Issue by fruske** [livewire/flux#748]
Hello,

I am not sure if this is a flux issue or only me but somehow I can’t get the dynamic components to work.
Maybe someone can give me a hint?

A lot of the dynamic components I copy and paste from https://fluxui.dev/components/ do not work for me.

sh-5.2# composer show -i | grep -e  laravel/framework -e livewire

_laravel/framework                  11.33.2 The Laravel Framework.
livewire/flux                      1.0.27  The official UI component library for Livewire.
livewire/flux-pro                  1.0.27  The pro version of Flux, the official UI component library for Livewire.
livewire/livewire                  3.5.12  A front-end framework for Laravel._

Most components are rendered just fine (not all):

Example:
![Image](https://github.com/user-attachments/assets/705a8816-9ce6-43e5-b738-871d6fc14552)

But as as soon as I try dynamic components I get JavaScript errors or warnings. The component renders but cant’t  be used (e.q. checkbox not clickable). See some examples below:

![Image](https://github.com/user-attachments/assets/f03cfd8f-5659-4dc3-a337-90dd4e4d8a64)

![Image](https://github.com/user-attachments/assets/ad2bd6ab-f559-4dda-b8c2-13909f0162fa)

![Image](https://github.com/user-attachments/assets/1b328145-3d67-4011-9ec2-a4c7f07dea40)

Any ideas? Thank you a lot!

**Comment by fruske** [comment]
![Image](https://github.com/user-attachments/assets/8d0e0310-2f56-41a6-a7a0-babf8223339d)
![Image](https://github.com/user-attachments/assets/0e1b98eb-9012-4c81-8f5d-8731f097559d)

**Comment by jeffchown** [comment]
@fruske Can you post your layout file and your `app.js`?

**Comment by fruske** [comment]
@jeffchown 
sure. Got those from a tutorial a while ago from the Livewire Video Tutorials. Im not that good in JS thats why Livewire is so great for me :)

**_base.blade.php_**

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>{{ config('app.name') }}</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script src="{{ asset('js/app.js') }}" defer></script>

    <link rel="stylesheet"  href="{{ asset('css/choices.css') }}" />
    <script src="{{ asset('js/choices.min.js') }}" ></script>

    {{-- Inter font loaded by tailwind.cfg @see: https://rsms.me/inter/ --}}

    @livewireStyles
    @fluxStyles

    @stack('styles')
    @stack('scripts')
</head>
<body class="antialiased font-sans bg-gray-100">

@livewireScripts
@fluxScripts

{{ $slot }}

</body>
</html>
```

**_app.js_**

```
require('./bootstrap');

// ---------------------- Pikaday Date Picker and needed moment lib  --------------------
import Pikaday from 'pikaday/pikaday.js';
window.Pikaday = Pikaday;
import * as moment from 'moment-timezone';

// ---------------------- choices.js  --------------------
import Choices from 'choices.js';

// ---------------------- apexcharts  --------------------
import ApexCharts from 'apexcharts';
window.ApexCharts = ApexCharts; // return apex chart

```

**_app.scss_**
@tailwind base;
```
@tailwind components;
@tailwind utilities;

@import 'flag-icons';
@import 'pikaday/css/pikaday.css';
@import "inter-ui/inter.css";

@layer components {

    .-left-22 {
        left: -5.5rem;
    }

    .text-xxs {
        font-size: 0.675rem;
    }

}

```

Thank you!

**Comment by jeffchown** [comment]
@fruske And now can you please post a Blade file example that causes the error (not in a screenshot), that can be copy/pasted?

**Comment by fruske** [comment]
@jeffchown 

Sure. Just a pretty simple one copied from the components library. https://fluxui.dev/components/accordion

```
<div>
    <div class="text-red-500">Just a flux test!</div>

    <flux:accordion>
        <flux:accordion.item>
            <flux:accordion.heading>What's your refund policy?</flux:accordion.heading>

            <flux:accordion.content>
                If you are not satisfied with your purchase, we offer a 30-day money-back guarantee. Please contact our support team for assistance.
            </flux:accordion.content>
        </flux:accordion.item>

        <flux:accordion.item>
            <flux:accordion.heading>Do you offer any discounts for bulk purchases?</flux:accordion.heading>

            <flux:accordion.content>
                Yes, we offer special discounts for bulk orders. Please reach out to our sales team with your requirements.
            </flux:accordion.content>
        </flux:accordion.item>

        <flux:accordion.item>
            <flux:accordion.heading>How do I track my order?</flux:accordion.heading>

            <flux:accordion.content>
                Once your order is shipped, you will receive an email with a tracking number. Use this number to track your order on our website.
            </flux:accordion.content>
        </flux:accordion.item>
    </flux:accordion>
</div>
```
Accordion is not working.
![Image](https://github.com/user-attachments/assets/0c1934a7-801c-4375-a2fa-6706eee00434)



Or even this simple one does not work (cant check checkbox)
```
<div>
    <div class="text-red-500">Just a flux test!</div>

    <flux:checkbox wire:model="test" label="I agree to the terms and conditions" />
</div>
```

![Image](https://github.com/user-attachments/assets/d55e9530-3440-4f6e-a2db-3cc3f13241d2)

I removed all unnecessary styling so this HTML is rendered for above example:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>csv2.ai</title>

    <!-- Styles -->
    <link href="https://surge.dev.localhost/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script src="https://surge.dev.localhost/js/app.js" defer></script>

    
    <link rel="stylesheet"  href="https://surge.dev.localhost/css/choices.css" />
    <script src="https://surge.dev.localhost/js/choices.min.js" ></script>

    


    <!-- Livewire Styles --><style >[wire\:loading][wire\:loading], [wire\:loading\.delay][wire\:loading\.delay], [wire\:loading\.inline-block][wire\:loading\.inline-block], [wire\:loading\.inline][wire\:loading\.inline], [wire\:loading\.block][wire\:loading\.block], [wire\:loading\.flex][wire\:loading\.flex], [wire\:loading\.table][wire\:loading\.table], [wire\:loading\.grid][wire\:loading\.grid], [wire\:loading\.inline-flex][wire\:loading\.inline-flex] {display: none;}[wire\:loading\.delay\.none][wire\:loading\.delay\.none], [wire\:loading\.delay\.shortest][wire\:loading\.delay\.shortest], [wire\:loading\.delay\.shorter][wire\:loading\.delay\.shorter], [wire\:loading\.delay\.short][wire\:loading\.delay\.short], [wire\:loading\.delay\.default][wire\:loading\.delay\.default], [wire\:loading\.delay\.long][wire\:loading\.delay\.long], [wire\:loading\.delay\.longer][wire\:loading\.delay\.longer], [wire\:loading\.delay\.longest][wire\:loading\.delay\.longest] {display: none;}[wire\:offline][wire\:offline] {display: none;}[wire\:dirty]:not(textarea):not(input):not(select) {display: none;}:root {--livewire-progress-bar-color: #2299dd;}[x-cloak] {display: none !important;}</style>
    <link rel="stylesheet" href="[/flux/flux.css?id=ec781681](https://surge.dev.localhost/flux/flux.css?id=ec781681)">

        </head>
<body class="antialiased font-sans bg-gray-100">


<script src="https://surge.dev.localhost/vendor/livewire/livewire.min.js?id=38dc8241"   data-csrf="F65Qfox4DLD9upKtSpr30cXGwYX1auzKOlj0ycee" data-update-uri="/livewire/update" data-navigate-once="true"></script>
<script src="[/flux/flux.min.js?id=35212b07](https://surge.dev.localhost/flux/flux.min.js?id=35212b07)" data-navigate-once></script>

<div wire:snapshot="{&quot;data&quot;:{&quot;modelname2&quot;:[[],{&quot;s&quot;:&quot;arr&quot;}],&quot;languages3&quot;:null,&quot;test&quot;:null},&quot;memo&quot;:{&quot;id&quot;:&quot;Q05ESm60Fliw36vmySw1&quot;,&quot;name&quot;:&quot;test&quot;,&quot;path&quot;:&quot;test&quot;,&quot;method&quot;:&quot;GET&quot;,&quot;children&quot;:[],&quot;scripts&quot;:[],&quot;assets&quot;:[],&quot;errors&quot;:[],&quot;locale&quot;:&quot;de&quot;},&quot;checksum&quot;:&quot;27fecab509ed9810b64f4b350f84e792ac4f092cba46e34b4db171d02a69310e&quot;}" wire:effects="[]" wire:id="Q05ESm60Fliw36vmySw1">
    <div class="text-red-500">Just a flux test!</div>

    <ui-field class="min-w-0 [&amp;:not(:has([data-flux-field])):has([data-flux-control][disabled])&gt;[data-flux-label]]:opacity-50 [&amp;:has(&gt;[data-flux-radio-group][disabled])&gt;[data-flux-label]]:opacity-50 [&amp;:has(&gt;[data-flux-checkbox-group][disabled])&gt;[data-flux-label]]:opacity-50 grid gap-x-3 gap-y-1.5 has-[[data-flux-label]~[data-flux-control]]:grid-cols-[1fr_auto] has-[[data-flux-control]~[data-flux-label]]:grid-cols-[auto_1fr] [&amp;&gt;[data-flux-control]~[data-flux-description]]:row-start-2 [&amp;&gt;[data-flux-control]~[data-flux-description]]:col-start-2 [&amp;&gt;[data-flux-control]~[data-flux-error]]:col-span-2 [&amp;&gt;[data-flux-control]~[data-flux-error]]:mt-1 [&amp;&gt;[data-flux-label]~[data-flux-control]]:row-start-1 [&amp;&gt;[data-flux-label]~[data-flux-control]]:col-start-2" data-flux-field>
    <ui-checkbox class="flex size-[1.125rem] rounded-[.3rem] mt-px outline-offset-2" wire:model="test" label="I agree to the terms and conditions" data-flux-control data-flux-checkbox>
        <div class="shrink-0 size-[1.125rem] rounded-[.3rem] flex justify-center items-center text-sm text-zinc-700 dark:text-zinc-800 shadow-sm [ui-checkbox[disabled]_&amp;]:shadow-none [ui-checkbox[data-checked]_&amp;]:shadow-none [ui-checkbox[data-indeterminate]_&amp;]:shadow-none [ui-checkbox[data-checked]:not([data-indeterminate])_&amp;&gt;svg:first-child]:block [ui-checkbox[data-indeterminate]_&amp;&gt;svg:last-child]:block border border-zinc-300 dark:border-white/10 [ui-checkbox[disabled]_&amp;]:border-zinc-200 dark:[ui-checkbox[disabled]_&amp;]:border-white/5 [ui-checkbox[data-checked]_&amp;]:border-transparent [ui-checkbox[data-indeterminate]_&amp;]:border-transparent [ui-checkbox[disabled][data-checked]_&amp;]:border-transparent [ui-checkbox[disabled][data-indeterminate]_&amp;]:border-transparent [print-color-adjust:exact] bg-white dark:bg-white/10 dark:[ui-checkbox[disabled]_&amp;]:bg-white/5 [ui-checkbox[data-checked]_&amp;]:bg-zinc-800 dark:[ui-checkbox[data-checked]_&amp;]:bg-white [ui-checkbox[disabled][data-checked]_&amp;]:bg-zinc-500 dark:[ui-checkbox[disabled][data-checked]_&amp;]:bg-white/60 [ui-checkbox[data-checked]:hover_&amp;]:bg-zinc-800 dark:[ui-checkbox[data-checked]:hover_&amp;]:bg-white [ui-checkbox[data-checked]_&amp;]:focus:bg-zinc-800 dark:[ui-checkbox[data-checked]_&amp;]:focus:bg-white [ui-checkbox[data-indeterminate]_&amp;]:bg-zinc-800 dark:[ui-checkbox[data-indeterminate]_&amp;]:bg-white [ui-checkbox[data-indeterminate]_&amp;]:hover:bg-zinc-800 dark:[ui-checkbox[data-indeterminate]_&amp;]:hover:bg-white [ui-checkbox[data-indeterminate]_&amp;]:focus:bg-zinc-800 dark:[ui-checkbox[data-indeterminate]_&amp;]:focus:bg-white">
    <svg class="shrink-0 [:where(&amp;)]:size-4 hidden text-white dark:text-zinc-800" data-flux-icon xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" data-slot="icon">
  <path fill-rule="evenodd" d="M12.416 3.376a.75.75 0 0 1 .208 1.04l-5 7.5a.75.75 0 0 1-1.154.114l-3-3a.75.75 0 0 1 1.06-1.06l2.353 2.353 4.493-6.74a.75.75 0 0 1 1.04-.207Z" clip-rule="evenodd"/>
</svg>

            <svg class="shrink-0 [:where(&amp;)]:size-4 hidden text-white dark:text-zinc-800" data-flux-icon xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" data-slot="icon">
  <path d="M3.75 7.25a.75.75 0 0 0 0 1.5h8.5a.75.75 0 0 0 0-1.5h-8.5Z"/>
</svg>

        </div>
    </ui-checkbox>

                    <ui-label class="text-sm font-medium select-none text-zinc-800 dark:text-white" data-flux-label>
    I agree to the terms and conditions

    
    </ui-label>
        
        
        <div aria-live="assertive" class="mt-3 text-sm font-medium text-red-500 dark:text-red-400 hidden" data-flux-error>
    </div>
</ui-field>

</div>


</body>
</html>

```

All assets are loaded successfully with HTTP Status Code 200:
![Image](https://github.com/user-attachments/assets/62ebeeec-f2d7-47b3-9b16-bf71c62e5813)


Thank you!

**Comment by jeffchown** [comment]
@fruske I do not get any errors when testing your snippets.

Have you run `npm run build`?  and `php artisan view:clear`?

Have you tried them in a 'clean' (new) Laravel app with just Flux (no choices.js, pikaday, apexcharts, etc.) to see if you can get Flux to work on its own?

**Comment by fruske** [comment]
@jeffchown yes i ran 
_npm run dev and artisan view:clear._
I did not tested it on a clean laravel app yet. I will test this later today or tomorrow. But i assume it will work. :(
What i tested already is removing thoose libs from my app but without success.

**Comment by jamesautodude** [comment]
> [@jeffchown](https://github.com/jeffchown) sure. Got those from a tutorial a while ago from the Livewire Video Tutorials. Im not that good in JS thats why Livewire is so great for me :)
> 
> **_base.blade.php_**
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
>     <meta charset="UTF-8">
>     <title>{{ config('app.name') }}</title>
> 
>     <link href="{{ asset('css/app.css') }}" rel="stylesheet">
>     <script src="{{ asset('js/app.js') }}" defer></script>
> 
>     <link rel="stylesheet"  href="{{ asset('css/choices.css') }}" />
>     <script src="{{ asset('js/choices.min.js') }}" ></script>
> 
>     {{-- Inter font loaded by tailwind.cfg @see: https://rsms.me/inter/ --}}
> 
>     @livewireStyles
>     @fluxStyles
> 
>     @stack('styles')
>     @stack('scripts')
> </head>
> <body class="antialiased font-sans bg-gray-100">
> 
> @livewireScripts
> @fluxScripts
> 
> {{ $slot }}
> 
> </body>
> </html>
> ```
> 
> **_app.js_**
> 
> ```
> require('./bootstrap');
> 
> // ---------------------- Pikaday Date Picker and needed moment lib  --------------------
> import Pikaday from 'pikaday/pikaday.js';
> window.Pikaday = Pikaday;
> import * as moment from 'moment-timezone';
> 
> // ---------------------- choices.js  --------------------
> import Choices from 'choices.js';
> 
> // ---------------------- apexcharts  --------------------
> import ApexCharts from 'apexcharts';
> window.ApexCharts = ApexCharts; // return apex chart
> ```
> 
> **_app.scss_**
> 
> ```
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> 
> @import 'flag-icons';
> @import 'pikaday/css/pikaday.css';
> @import "inter-ui/inter.css";
> 
> @layer components {
> 
>     .-left-22 {
>         left: -5.5rem;
>     }
> 
>     .text-xxs {
>         font-size: 0.675rem;
>     }
> 
> }
> ```
> 
> Thank you!

In your base.blade.php, inside of the head tags, put:

`@vite('resources/css/app.css')`

And see if that changes anything?

**Comment by jamesautodude** [comment]
> Good catch, @jamesautodude !
> 
> I'd add `app.js` to @jamesautodude 's suggestion, e.g.:
> 
> `@vite(['resources/css/app.css', 'resources/js/app.js'])`
> 
> As most of the errors seem to be js-related.

Ah yes app.js as well, thank you for adding that!

**Comment by fruske** [comment]
Hi @jamesautodude 

Thank you for the hint.
Currently i am using mix and not vite.
Everything compiles successfully and is loaded. So i am confused.
I will try it out "vite" but takes some time cause i have everything in docker containers and so on.
I will update here.
Thank you.

**Comment by jamesautodude** [comment]
> Hi @jamesautodude 
> 
> Thank you for the hint.
> Currently i am using mix and not vite.
> Everything compiles successfully and is loaded. So i am confused.
> I will try it out "vite" but takes some time cause i have everything in docker containers and so on.
> I will update here.
> Thank you.
> 

Okay if that's the case then you need to put this in the header:

`<link href="/css/app.css" rel="stylesheet">`

And

`<script src="/js/app.js"></script>`

But yeah I'd upgrade to Vite. There's a program online that can upgrade your GitHub repo to Vite for you called Laravel Shift

**Comment by jamesautodude** [comment]
> Hi @jamesautodude 
> 
> Thank you for the hint.
> Currently i am using mix and not vite.
> Everything compiles successfully and is loaded. So i am confused.
> I will try it out "vite" but takes some time cause i have everything in docker containers and so on.
> I will update here.
> Thank you.
> 

@fruske Okay if that's the case then you need to put this in the head:

`<link href="/css/app.css" rel="stylesheet">`

And

`<script src="/js/app.js"></script>`

But yeah I'd upgrade to Vite. There's a program online that can upgrade your GitHub repo to Vite for free for you called Laravel Shift: https://laravelshift.com/convert-laravel-mix-to-vite but you have to have your project in GitHub 

Here's a guide for mix by the way: 
[https://laravel.com/docs/8.x/mix](https://laravel.com/docs/8.x/mix)

**Comment by fruske** [comment]
> 
> [@fruske](https://github.com/fruske) Okay if that's the case then you need to put this in the head:
> 
> `<link href="/css/app.css" rel="stylesheet">`
> 
> And
> 
> `<script src="/js/app.js"></script>`
> 
The tags are already in my <head> (See above) and the files are loaded with http status 200. 

> But yeah I'd upgrade to Vite if your project allows. There's a program online that can upgrade your GitHub repo to Vite for free for you called Laravel Shift: https://laravelshift.com/convert-laravel-mix-to-vite but you have to have your project in GitHub. Otherwise just add the tags for css and js (above)
> 
> Here's a guide for mix by the way: https://laravel.com/docs/8.x/mix

Thank you. I have all running in docker containers so it takes me some time. I'll try to fix it with mix for one more day. Then i'll try vite.
Does anyone using FLUX successfully with mix? Cause i never had problems so far using mix.

Thank you again for your support!

**Comment by jeffchown** [comment]
Maybe post that as a new issue with an appropriate title to get feedback from any mix users.

**Comment by fruske** [comment]
Now i migrated my app to vite. Same problem :(
Thus i assume it must be something incompatible in my app or setup.
I am a little clueless right now but I'll continue to investigate.

**Comment by calebporzio** [comment]
Sorry @fruske, I too cannot reproduce (thanks for the all the initial help on this @jeffchown )

If you can reproduce this somehow in a laravel app that we can install as a dedicated repository maybe we can help pin it down for you?

**Comment by fruske** [comment]
Thanks @calebporzio .

I will do a complete fresh Laravel installation within the next days and first i will integrate Livewire and Flux. If it works i continue to add all my app features until it stops working.

If it does not work with only Livewire and Flux i assume it can only be my docker setup. But i doubt that. 
I will update you here on that issue.

Thank you all for your help so far!

BTW.: I used your surge example code from some older video tutorials to get started with my app. But all is up to date now.

**Comment by jeffchown** [comment]
Sounds like a solid play/approach, @fruske   Good luck! 🤞

**Comment by joshhanley** [comment]
@fruske good plan! I'm going to close this issue for now, but please open a new one if you manage to replicate this issue in your test app and we'd be more than happy to have a look.
