### ISSUE TITLE
Muliple editors on the same page makes for a noisy console

### ISSUE THREAD

**Issue by edgrosvenor** [livewire/flux#753]
Update: The actual problem here was the prevention of form submission that was resolved by the latest release. Now, multiple editors on a page work fine. It turns out that the other place I was using the editor had a wire:click handler on the submit button, which caused me to misdiagnose the actual problem. That said, the console does still show this error when multiple editors exist on a page, but it's not actually causing any failures (at least in my app). 

Because the editor script is loaded inline with the editor itself, it loads for every instance of the editor that is loaded on the page. That results in an error since the editor has already been defined as a custom element. The obvious solution would be to publish the stubs, remove the script loader from the stubs, and place it somewhere that will only load once on the page. However, the editor is not one of the options to publish.

The error I receive is `Uncaught DOMException: CustomElementRegistry.define: 'ui-editor' has already been defined as a custom element`, but if I reach into the vendor folder, strip the script loader out of the stub, and slap it into the layout, it works as expected.

I guess the possible solutions are:

1. Make the editor publishable
2. Have the script check to see if the definition already exists and if it does, just skip it
3. Add a `no-script` parameter to the editor that can be used to stop the script from loading inline with the editor
4. Something else maybe?

Anyway, other than that (and the already reported issue of the editor preventing the submission of the form), I am super happy with this component!

**Comment by joshhanley** [comment]
@edgrosvenor are you able to provide us with a Volt component so we can copy paste it into our test apps to replicate the issue?

**Comment by calebporzio** [comment]
Yeah, the editor component uses `@assets` to include the JS - this should intelligently make sure that it's only included once per JS runtime so you shouldn't be getting those notices. May be a problem with `@assets` and something about your setup.

But yeah, this doesn't happen for us locally - we will need something we can copy/paste to reproduce

**Comment by joshhanley** [comment]
@edgrosvenor going to close this for now. Please feel free to open a new issue that includes code that we can use to reproduce the issue.
