### ISSUE TITLE
Modal events

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#760]
### Summary

At the moment you can only make limited use of modal events. You can only access it by adding `x-on:close` on the `flux:modal`. This is probably a bit limited. There's also a [`cancel`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/cancel_event) event and you may want to listen to such events in Livewire too. 

So here's my wishlist:

- More (access to) events for modals. `cancel` is missing, and `modal-show` and `modal-close` are not accessible in Livewire.
- More freedom to add listeners to `flux:modal`. It's currently limited to `x-on:close` and `wire:close`.

Something that I found when testing is that you can still close a modal with `Esc` when you have `dismissable` set to true.

### Monologue

I have a few questions about modals in Flux. In our app we have a modal to change a text field:

```blade
<flux:modal>
    ...
    <flux:textarea rows="auto" wire:model="items.{{ $key }}.text" />
    ...
</flux:modal>
```

As this is bound directly to a prop in our Livewire component, we do not have a `save` action. We do have a 'Update text'-button, but this isn't linked to a method. It is just meant to close the modal, the property will be updated when the full component gets saved. It gets tricky when you want to close the modal and reset its changes. More on that later.

My first question is about closing the modal. In the [docs](https://fluxui.dev/components/modal) there are two variants:

```blade
<flux:button type="submit">Update text</flux:button>
```

and

```blade
<flux:modal.close>
    <flux:button>Update text</flux:button>
</flux:modal.close>
````

I assume you'd always use the latter, as setting the `type` to `submit` on a button has no effect on the modal. Am I right about that?

My second question is a follow-up on the first. Assuming you'd have to wrap the 'Update text'-button with `flux:modal.close`, how would we know when to undo the changes made to that text area? I was hoping to hook into the close event and call `reset` on the Livewire-method. This isn't possible right now. I wouldn't know if the user clicked away, clicked on the `x` or clicked on save. The hook will always run.

How can I differentiate between a cancel/close and a save/close? And is there an `open`-event JS too?

There is another issue with all of this, but that's a [Livewire thing](https://github.com/livewire/livewire/discussions/9039).

**Comment by ju5t** [comment]
@jeffchown I don't want to call any method when a user clicks 'Update text', I just want to close the modal. This is not difficult, but I want to call a method to reset the field when a user closes or clicks outside the modal.

The modal close event is limited to one event. I can't distinguish it from whatever way is used to close it. I think it boils down to needing more events to hook into. Something like: open, close, cancel.

Our version would look closer to this one:

```
<flux:modal @close="resetText({{ $key }})">
    <flux:textarea rows="auto" wire:model="items.{{ $key }}.text" />

    <flux:modal.close>
        <flux:button>Update text</flux:button>
    </flux:modal.close>
</flux:modal>
```

But this would call `resetText` too when you click the 'Update text'-button. I don't want that as it would undo the change again.

**Comment by ju5t** [comment]
I found that `<dialog>`'s do have a `cancel`-event but it only gets dispatched when you press `Esc`. `dismissable` and `closable` do not prevent it. I think `dismissable` should disable that too.

**Comment by ju5t** [comment]
I found another scenario where some more events would be beneficial. 

Let's say you use a Livewire component inside a modal.

```blade
<flux:modal name="add-inventory" class="w-full max-w-full sm:max-w-md md:max-w-xl lg:max-w-2xl">
    <livewire:inventory.add-inventory :id="$this->product->getKey()" lazy="on-load" />
</flux:modal>
```

When the modal gets closed I want to reset its state. It would be great if I could address this from inside the Livewire component. I've tried this with `#[On('modal-close')]` but that's not reaching the component.

I'll sum things up in the original post.

**Comment by joshhanley** [comment]
@ju5t we've added support for the dialog cancel event and has been released in v1.1.1. Docs are here https://fluxui.dev/components/modal#cancel-events

**Comment by ju5t** [comment]
@joshhanley that's awesome, thanks!

**Comment by ju5t** [comment]
@joshhanley I don't know how I never thought of this before, but Alpine's Intersect plugin is by far the best solution.

```blade
<div x-data x-intersect:leave="$wire.clear()">
```

Where `clear` is our own method to reset state and clear the error bag.

**Comment by joshhanley** [comment]
Oh nice!
