### ISSUE TITLE
Removing classes doesn't work on modals

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [livewire/flux#762]
Using the following code

```PHP
<flux:card class="!p-6">
```

I would expect to have Flux create the card wrapper div without the `p-6` class, according to the [customization docs.](https://fluxui.dev/docs/customization)

But the output div is unchanged and still contains the `p-6` class.

```PHP
<div class="p-6 rounded-xl bg-white dark:bg-white/10 border border-zinc-200 dark:border-white/10 **!p-6**" data-flux-card="">
```

**Comment by jeffchown** [comment]
@ChrisThompsonTLDR That's not how the `!` operator works in Tailwind CSS, it overrides the previous `p-` setting.  For example, if the default padding in `flux:card` is `p-4` and you passed `!p-6`, your `p-6` takes precedence.

**Comment by ChrisThompsonTLDR** [comment]
@jeffchown ya, that's why I promptly close this issue.  I realized I was programming and sleeping at the same time and forgot out Tailwind CSS works.

**Comment by joshhanley** [comment]
@ChrisThompsonTLDR for some reason you closed it as "not planned" have just re-closed it as "completed" incase anyone else runs into the issue.
