### ISSUE TITLE
Incorrect button variant throwing `Unhandled match` error

### ISSUE THREAD

**Issue by jaakkoijas** [livewire/flux#768]
When you have a typo in button variant property, then you get internal server error: Unhandled match case '...' .

Try this:
`<flux:button variant="dander">Delete</flux:button>`

**Comment by lloydowen** [comment]
I think this is correct behaviour

**Comment by calebporzio** [comment]
Yeah, it would be nice if it had a more friendly error message, however. Just want to make sure it doesn't add unnecessary runtime overhead.

**Comment by ju5t** [comment]
@calebporzio you could throw a `FluxException` when the default of the match case gets hit? That would at least give you control over the error message.

**Comment by pantheon-apps** [comment]
Or just use the default case as the default variant. If you set a variant and you see it behaving like the default one, I think your first instinct is to doublecheck your code and you will see your typo.

**Comment by joshhanley** [comment]
I think changing the button to have the `default` match throw an exception, as @just said, would be better. Then there wouldn't be any overhead. Where as at the moment you'd have to wrap the match in a try/catch to catch the `Unhandled match case` exception, which could potentially add overhead.

I believe still throwing an error if there is a typo/ unsupported variant is a good ideas as it's immediate feedback that something isn't correct.

**Comment by calebporzio** [comment]
I think I want to punt on this one guys - it IS a valid exception as-is. Let's see if this is frustrating for users and see if people bring it back up as an issue. Thanks for the input.

**Comment by snapey** [comment]
Slight variation on this. when switching button types, there is a temptation to enter `variant="default"` which you might think would work, but throws Unhandled match case 'default'

If you realise it's the button that is causing the issue (Ignition response is next to useless). It's made worse by looking through the code and not seeing any typos.  its then a dive into the docs to find there is no variant of default, just leave it out altogether. 

No complex try catch here?  Just set default match case to be the default styling. This would also swallow any typo issue.
