### ISSUE TITLE
fresh installation of flux. Where is flux:editor. How to install it?

### ISSUE THREAD

**Issue by junn-mendoza** [livewire/flux#776]
Hi there! 👋

Thank you for using Flux!

Many of the people who help resolve issues here are enthusiastic Fluxers like yourself who volunteer their time to support fellow community members.

To respect everyone's valuable time and help you resolve your issue as quickly as possible, before posting an issue, please:

* Make sure you have followed each step in the installation instructions: https://fluxui.dev/docs/installation (step 5 is optional)
* Update to the latest version of Flux by running `composer update livewire/flux livewire/flux-pro`
* Delete any previously published Flux components (to avoid usage of old versions)
* Run `npm run build` to compile all CSS and JS assets
* Clear the view cache by running `php artisan view:clear`

If these steps do not resolve the issue, please provide us with:

* A concise description of the problem
* Minimal, copy-pastable code (with no dependencies) to reproduce the bug (Volt components are great for this!)
* Screenshots if relevant

We will close this issue for any of the following reasons:

* The code snippets contain unrelated code such as left-over Blade variables
* We cannot reproduce the issue with the provided code snippets
* The issue is a duplicate

Thank you!

**Comment by pantheon-apps** [comment]
Did you purchase a license for flux-pro? Because it is a flux-pro feature. From my knowledge, only buttons, icons, menus and tooltips are included in the flux free package.

**Comment by ju5t** [comment]
@junn-mendoza if you're not following the steps that are in the bug report instructions it's impossible to help you.

**Comment by junn-mendoza** [comment]
surely I can use all the component. only missing is flux:editor

**Comment by junn-mendoza** [comment]
![Image](https://github.com/user-attachments/assets/5bbeaa74-66ac-4a03-a1ad-268a7609a7dc)

everything is here and I can use it. I can customize it. unfortunately. the flux editor is not in. Even I follow the above steps

**Comment by ju5t** [comment]
What is the output of:

```bash
composer show livewire/flux-pro
```

**Comment by junn-mendoza** [comment]
name     : livewire/flux-pro
descrip. : The pro version of Flux, the official UI component library for Livewire.
keywords : components, flux, laravel, livewire, ui
versions : * 1.0.13
type     : library
license  : proprietary
homepage :
source   : []
dist     : [zip] https://composer.fluxui.dev/download/9d44c509-a136-4094-93a4-1de1b01f8295/flux-pro-1.0.13.zip 16a469b5805566831e6e80f7c735620b10c9ef8e
path     : C:\Users\emera\Herd\supervate-web2\vendor\livewire\flux-pro
names    : livewire/flux-pro

autoload
files
psr-4
FluxPro\ => src/

requires
illuminate/console ^10.0|^11.0
illuminate/support ^10.0|^11.0
illuminate/view ^10.0|^11.0
laravel/prompts ^0.1.24|^0.2|^0.3
livewire/flux 1.0.13
livewire/livewire ^3.5
php ^8.1
symfony/console ^6.0|^7.0

**Comment by junn-mendoza** [comment]
Part of the steps if giving concise information. The only thing you initially did is change the title. That's not how you ask for support. - sorry for this mate. This is the first I bought a plugin and first time to use the ticket support. I'm again sorry for this

**Comment by ju5t** [comment]
In that case you haven't followed the instructions. Your running version 1.0.13. The latest version is 1.0.28.

- Update to the latest version of Flux by running `composer update livewire/flux livewire/flux-pro`

**Comment by junn-mendoza** [comment]
still my flux verion is not update 

**composer update livewire/flux livewire/flux-pro**
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
Class App\Dictionary\Params located in C:/Users/emera/Herd/supervate-web2/app\Http\Dictionary\Params.php does not comply with psr-4 autoloading standard. Skipping.                                                                                                                                 
Class App\View\Components\AppLayout located in C:/Users/emera/Herd/supervate-web2/app\View\Components\NavMain.php does not comply with psr-4 autoloading standard. Skipping.                                                                                                                        
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.

  laravel/breeze .......................................................................................................................... DONE  
  laravel/sail ............................................................................................................................ DONE  
  laravel/tinker .......................................................................................................................... DONE  
  livewire/flux ........................................................................................................................... DONE  
  livewire/flux-pro ....................................................................................................................... DONE  
  livewire/livewire ....................................................................................................................... DONE  
  livewire/volt ........................................................................................................................... DONE  
  nesbot/carbon ........................................................................................................................... DONE  
  nunomaduro/collision .................................................................................................................... DONE  
  nunomaduro/termwind ..................................................................................................................... DONE  
  pestphp/pest-plugin-laravel ............................................................................................................. DONE  
  wire-elements/modal ..................................................................................................................... DONE  

89 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force

   INFO  No publishable resources for tag [laravel-assets].

Found 3 security vulnerability advisories affecting 3 packages.
Run composer audit for a full list of advisories.

 **composer show livewire/flux-pro**
name     : livewire/flux-pro
descrip. : The pro version of Flux, the official UI component library for Livewire.
keywords : components, flux, laravel, livewire, ui
versions : * 1.0.13
type     : library
license  : proprietary
homepage :
source   : []
dist     : [zip] https://composer.fluxui.dev/download/9d44c509-a136-4094-93a4-1de1b01f8295/flux-pro-1.0.13.zip 16a469b5805566831e6e80f7c735620b10c9ef8e
path     : C:\Users\emera\Herd\supervate-web2\vendor\livewire\flux-pro
names    : livewire/flux-pro

autoload
files
psr-4
FluxPro\ => src/

requires
illuminate/console ^10.0|^11.0
illuminate/support ^10.0|^11.0
illuminate/view ^10.0|^11.0
laravel/prompts ^0.1.24|^0.2|^0.3
livewire/flux 1.0.13
livewire/livewire ^3.5
php ^8.1
symfony/console ^6.0|^7.0

**Comment by junn-mendoza** [comment]
now its ok. what I did is delete the vendor folder. delete the composer.lock then composer install. [SOLVED]

**Comment by joshhanley** [comment]
@junn-mendoza it's possible you didn't have a compatible version of Livewire as there have recently been some updates that are required. So it's best to use the `-W` flag when running `composer update livewire/flux... -W` as it will allow composer to also update Livewire if required.
