### ISSUE TITLE
Select multiple

### ISSUE THREAD

**Issue by jaakkoijas** [livewire/flux#778]
Select box with multiple is rendered with borders in Windows 11 Chrome and Firefox

![Image](https://github.com/user-attachments/assets/8c1377bc-2994-4383-981a-d45705f0c5d0)

**Comment by jeffchown** [comment]
@jaakkoijas Previous issue, see: https://github.com/livewire/flux/issues/717

**Comment by joshhanley** [comment]
@jaakkoijas yeah Flux isn't compatible with Tailwind Forms plugin. So you will need to remove that for it to display correctly.

Going to close this issue. But if you don't have Tailwind Forms or are still having issues after, then please open a new issue.
