### ISSUE TITLE
Pointer cursor on buttons hover - weird behavior

### ISSUE THREAD

**Issue by orchidcode** [livewire/flux#779]
Hi there! 👋

I just noticed a problem with the cursor on buttons during mouse over. Please see the attached video, recorded on the official docs page for easy reproduction. I am using the current macOS, and the same issue occurs in Safari and Chrome.

https://github.com/user-attachments/assets/9a6672a8-f6b0-4124-9a04-b92198ac8220

**Comment by ju5t** [comment]
I'm on MacOS 15.1.1 and tested it in Safari & Chrome but everything looks fine over here. I have seen the cursor misbehaving before in the browser, but that's unrelated to Flux. It sounds a bit strange but have you tried restarting your machine and see if that resolves it?

**Comment by joshhanley** [comment]
@orchidcode I just tested this as well on MacOS 14 with Safari 17.5 and Chrome 131.0.6778.86 and everything is working normally for me.

I'm going to close this issue for now as I don't believe it's a Flux issue. Can you follow @ju5t's suggestions and see if there an issue with your OS. If you feel this is actually a Flux issue, please open a new issue and include your OS and browser versions. Thanks!
