### ISSUE TITLE
Date and Multiple Select Input Styling

### ISSUE THREAD

**Issue by CRippingham** [livewire/flux#780]
Hello!  I recently started using Flux in one of my projects and love it so far however I've been struggling with the styling on two elements, the date input and multiple select.  Below are images of the styling issues I'm seeing that I'm assuming are caused by something on my end as they look perfect on the docs website.  I've followed the steps outlined below including running "php artisan view:clear" but no luck.  Any suggestions?

Thanks,
Chris

**Light Mode**
![Image](https://github.com/user-attachments/assets/b56db26a-f797-428e-b69c-d73e77465493)

**Dark Mode**
![Image](https://github.com/user-attachments/assets/fa0a4697-23f9-4d5e-bade-5bab4ac9dc93)

**Steps Followed**
* Make sure you have followed each step in the installation instructions: https://fluxui.dev/docs/installation (step 5 is optional)
* Update to the latest version of Flux by running `composer update livewire/flux livewire/flux-pro`
* Delete any previously published Flux components (to avoid usage of old versions)
* Run `npm run build` to compile all CSS and JS assets
* Clear the view cache by running `php artisan view:clear`

**Comment by jeffchown** [comment]
@CRippingham I suspect your issue(s) may be related to https://github.com/livewire/flux/issues/717

**Comment by joshhanley** [comment]
@CRippingham yeah Flux isn't compatible with Tailwind Forms plugin. So you will need to remove that for it to display correctly.

Going to close this issue. But if you don't have Tailwind Forms or are still having issues after, then please open a new issue.
