### ISSUE TITLE
Horizontal Fieldset Styling

### ISSUE THREAD

**Issue by CRippingham** [livewire/flux#781]
Hello, I am trying to work with the horizontal fieldset to horizontally align checkboxes however the styling of those elements appears to be off.  I'm assuming the the flux:legend component should match the flux:label stlying and then I'm guessing the flux:fieldset is causing an overflow with inside a div smaller than the length of the fieldset.  Should the fieldset component wrap in this situation?  I have run the steps below.

Thanks,
Chris

![Image](https://github.com/user-attachments/assets/faa6964a-6c27-41b5-94ac-a27d02e90308)

* Make sure you have followed each step in the installation instructions: https://fluxui.dev/docs/installation (step 5 is optional)
* Update to the latest version of Flux by running `composer update livewire/flux livewire/flux-pro`
* Delete any previously published Flux components (to avoid usage of old versions)
* Run `npm run build` to compile all CSS and JS assets
* Clear the view cache by running `php artisan view:clear`

**Comment by ju5t** [comment]
Can you share a copy/pasteable example to reproduce the issue?

**Comment by joshhanley** [comment]
@CRippingham thank you for the report, however we have been unable to reproduce this given the information available. Please provide a code snippet we can copy and paste into our own apps with steps to reproduce. Please include any Blade variable definitions that are used and use a little code as possible to reproduce the issue.

**Comment by CRippingham** [comment]
Hi @joshhanley. I initially submitted this as a support request but was asked to submit it as a bug (you responded to the support email =o).  Using the templates found on the documentation cause the styling issues in my project but they look perfect in the documentation site so I'm assuming its an issue on my end as well.  Should I resubmit this as a support email or do you have any ideas what may be causing it on my end?  I've run composer update, npm update, npm run dev, and php artisan view:clear...

**Comment by joshhanley** [comment]
@CRippingham here is the correct place, the support email is only for account queries. Can you provide some code, as I asked above, so we can investigate it? Thanks! 🙂

**Comment by joshhanley** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps with steps to reproduce. Be sure to include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Then, we will be happy to help.
