### ISSUE TITLE
VS Code auto formatter adds spaces on <flux> tags

### ISSUE THREAD

**Issue by nerisonpitogo** [livewire/flux#788]
I have "format on save" enabled in my vscode and I want it to keep this way. However when using flux, the code is altered during formatting. 

ex. Working code. 
 ```
              <flux:badge size="sm" :color="$user->status_color" inset="top bottom">
                    {{ $user->status }}
                </flux:badge>
```

But during save (pressing ctrl + s), the code becomes.

```
               <flux:badge size="sm" :color="$user - > status_color" inset="top bottom">
                    {{ $user->status }}
                </flux:badge>
```

Notice the spaces in `$user - > status_color` which causes error.

**Comment by ju5t** [comment]
I doubt this is something Flux can fix. What formatter are you using? And have you reached out to them? As somehow it does not recognize Flux as a Blade component. I assume you do not have this issue with other Blade components?
