### ISSUE TITLE
Expand navbar menu when submenu is active

### ISSUE THREAD

**Issue by ibalat** [livewire/flux#789]
My sidebar have many navbar item, so all of them have `expandable :expanded="false"`. But when I visit a submenu, its parent navbar is closing and we don't see current submenu. How can we auto expand parent navbar if its submenu is active?

Related discussion: https://github.com/livewire/flux/discussions/785

![Image from Photopea](https://github.com/user-attachments/assets/cc8f1f4e-f8d9-42dd-b811-9eb376d03106)

Code:

```
<flux:navlist variant="outline">
    <flux:navlist.group expandable :expanded="false" heading="Favorites" class="hidden lg:grid">
        <flux:navlist.item href="/">Marketing site</flux:navlist.item>
        <flux:navlist.item href="/blank" wire:navigate>Android app</flux:navlist.item>
        <flux:navlist.item href="#">Brand guidelines</flux:navlist.item>
    </flux:navlist.group>
</flux:navlist>
```

```
Route::get('/', App\Livewire\Dashboard\Index::class);
Route::get('/blank', App\Livewire\Dashboard\Blank::class);
```

Note: I use menu links with `wire:navigate`

**Comment by tjgore** [comment]
The parent navbar can be expanded by using the `request()->is('..')` method in the `expanded` prop.
```blade
<flux:navlist variant="outline">
    <flux:navlist.group expandable :expanded="request()->is(['/', '/blank', '/guidelines'])" heading="Favorites" class="hidden lg:grid">
        <flux:navlist.item href="/">Marketing site</flux:navlist.item>
        <flux:navlist.item href="/blank" wire:navigate>Android app</flux:navlist.item>
        <flux:navlist.item href="/guidelines">Brand guidelines</flux:navlist.item>
    </flux:navlist.group>
</flux:navlist>
```
This way the `expanded` props receives true or false depending on the current path.

This can also be simplified by provide the navlist items with a parent path such as `/favorites`.
Now, instead of using `:expanded="request()->is(['/', '/blank', '/guidelines'])"`, you can use `:expanded="request()->is('favorites/*')"` to catch all nav items, if you have many.

**Comment by ibalat** [comment]
Thank you so much, I will use these methods.

**Comment by joshhanley** [comment]
Thanks @tjgore! @ibalat I'm going to close this as it looks like @tjgore has solved your issue. If you feel like it hasn't feel free to open a new issue.
