### ISSUE TITLE
Flux and PageSpeed insights

### ISSUE THREAD

**Issue by holubar** [livewire/flux#792]
When testing my website with PageSpeed Insights, I am getting low score and one of the issues are flux scripts. I am using latest version 1.0.28, I followed installation instructions. Website runs on DO using forge. 

Can I do anything to fix the compression issue? 

![Image](https://github.com/user-attachments/assets/0535ea55-2ef7-478f-a635-be6854afd382)

**Comment by heydeez** [comment]
@lloydowen I am using forge and I believe compression is enabled by default. I am getting this issue only with flux.js file, not the others so maybe problem lies somewhere else.
