### ISSUE TITLE
Dropdown not closed upon clicking navitem

### ISSUE THREAD

**Issue by marczh** [livewire/flux#793]
Hi

I am using dropdown in navbar as suggested in the docs.
The dropdown does not always hide after nav item link is clicked.

```php
    @foreach ($menus as $menu)
        <flux:dropdown class="max-lg:hidden">
            <flux:navbar.item icon-trailing="chevron-down">{{ $menu->name }}</flux:navbar.item>
            @if ($menu->menuItems)
                <flux:navmenu>
                    @foreach ($menu->menuItems as $menuItem)
                         <flux:navmenu.item href="{{ url('/') . '/' . $menuItem->url }}">{{ $menuItem->label }}</flux:navmenu.item>
                    @endforeach
                </flux:navmenu>
            @endif
        </flux:dropdown>
    @endforeach
```

https://github.com/user-attachments/assets/2dcc2ed1-f237-474e-bc3a-f8dd921b046d

Thanks.

**Comment by marczh** [comment]
Found out that this occurs only with url containing hash.
I want to link the navitem to scroll to an element on page.

**Comment by joshhanley** [comment]
@marczh Thank you for the report, however we have been unable to reproduce this given the information available. Please submit a code snippet we can copy and paste into our own apps with steps to reproduce. Please include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Then, we will be happy to help.

**Comment by marczh** [comment]
Thanks, Josh. I actually dropped the idea of navigating with # in url and implemented some scrollIntoView event Listener for DOMContentLoaded. Without hash in url the Dropdown works just fine.

**Comment by joshhanley** [comment]
@marczh no worries! If you do run into it again, feel free to open a new issue and we'll happily look into it 🙂
