### ISSUE TITLE
Using Flux Components In Blade Components Not Working Properly

### ISSUE THREAD

**Issue by achatzi78** [livewire/flux#794]
Hello.

I have created a blade component to show buttons based on policies.  When  I use a link button it does not show, only the regular buttons seem to be rendered.

This is my blade components (simplified)
```
@props([
    'model' => null,
    'prefix' => '',
    'parameter' => '',
])

<div class="flex gap-2">
    <div class="flex-auto">
        <flux:button
            wire:key="viewModelBtn_{{ Str::ulid() }}"
            id="viewModelBtn_{{ Str::ulid() }}"
            href="{{ route('home') }}"
            variant="primary"
            size="xs"
            icon="magnifying-glass"
            tooltip="{{ __('view') }}"
            class="w-full"
        />
    </div>

    <div class="flex-auto">
        <flux:button
            wire:key="removeModelBtn_{{ Str::ulid() }}"
            wire:click="removeModel('{{ Str::ulid() }}')"
            wire:confirm="{{ Str::ucfirst(translate('are you sure?')) }}"
            wire:target="removeModel('{{ Str::ulid() }}')"
            id="removeModelBtn_{{ Str::ulid() }}"
            variant="danger"
            size="xs"
            icon="trash"
            tooltip="{{ __('delete') }}"
            class="w-full"
        />
    </div>
</div>
```

I use it in a table
```
<flux:cell class="first:pl-3">
    <x-html.buttons-crud :model="new Model()" :prefix="'primary-data.permissions'" :parameter="'permission'" />
</flux:cell>
```

Only the second button (the delete one) is shown and when I inspect the page, the first one shows as `flux:button`
![Image](https://github.com/user-attachments/assets/b84a4ad6-5efa-4895-85c6-a37cda3a75bb)

Am I doing something wrong or is it a bug?

Thanks.

**Comment by joshhanley** [comment]
@achatzi78 thanks for reporting! I've just copied and tested out your code (I had to modify it slightly to function, but no major changes) and it all worked fine for me and the link and the button both render happily (see screenshot and code I used below).

That suggests to me that there might be something wrong with your set up.

I'm going to close this issue for now, but if you can reliably reproduce the issue, please feel free to open a new issue and we'd be happy to investigate further.

Please make sure that all code you provide in future works directly when we copy and paste it, to make it easier for us to investigate (`new Model()` didn't work as you can't instantiate a base Eloquent model for example).

---

![Image](https://github.com/user-attachments/assets/26f9da2a-1ccd-46c9-9470-cbc02eea92bf)

Here's the Volt component and Blade components that I used.

```php
<?php

use Livewire\Volt\Component;

new class extends Component {
    //
};
?>

<div>
    <x-test :model="new \App\Models\User()" :prefix="'primary-data.permissions'" :parameter="'permission'" />
</div>
```

```blade
{{-- resources/views/components/test.blade.php --}}
@props([
    'model' => null,
    'prefix' => '',
    'parameter' => '',
])

<div class="flex gap-2">
    <div class="flex-auto">
        <flux:button
            wire:key="viewModelBtn_{{ Str::ulid() }}"
            id="viewModelBtn_{{ Str::ulid() }}"
            href="{{ route('home') }}"
            variant="primary"
            size="xs"
            icon="magnifying-glass"
            tooltip="{{ __('view') }}"
            class="w-full"
        />
    </div>

    <div class="flex-auto">
        <flux:button
            wire:key="removeModelBtn_{{ Str::ulid() }}"
            wire:click="removeModel('{{ Str::ulid() }}')"
            wire:confirm="{{ Str::ucfirst(__('are you sure?')) }}"
            wire:target="removeModel('{{ Str::ulid() }}')"
            id="removeModelBtn_{{ Str::ulid() }}"
            variant="danger"
            size="xs"
            icon="trash"
            tooltip="{{ __('delete') }}"
            class="w-full"
        />
    </div>
</div>
```

**Comment by achatzi78** [comment]
@joshhanley Thanks for trying and I will keep in mind what you said about working code.

I solved the issue when I changed the href from `href="{{ route("{$prefix}.edit", [$parameter => $model]) }}"` to `:href="route($prefix . '.edit', [$parameter => $model])"`.

In my effort to simplify the code (because you wouldn't have the route in your project) I changed the part to `href="{{ route('home') }}"` in the code I provided here, which actually works (I didn't try it before) but when a variable is introduced (like in the actual code I use) then it will not work.

Anyway, thanks again and sorry for the semi working code sample.

**Comment by joshhanley** [comment]
@achatzi78 ah right, yeah there can be issues with using `href="{{ route(...) }}"` with Blade components (not just Flux) as it escapes the rendered URL causing problems (`{{ }}` escapes by default). So it's always best to use `:href="route(...)"` to stop the escaping.
