### ISSUE TITLE
Loading indicator shows on all buttons when clicked

### ISSUE THREAD

**Issue by lloydowen** [livewire/flux#798]
Hey,

The might be something i'm _not_ doing with keys/uniqueness. 

When i have a button in a loop i.e. a grid/table of tasks and I use `wire:click` when clicked, the loading indicator shows on all instances of the button. 

```html
<flux:button wire:key="send-reminder-{{$task->id}}" wire:click="sendReminder('{{$task->id}}')" variant="filled" class="w-full" icon="envelope">Send Reminder</flux:button>

```

![Image](https://github.com/user-attachments/assets/e461e3b8-a01d-4c78-87a5-f685620df9c1)

**Comment by jeffchown** [comment]
@lloydowen See previously reported issue https://github.com/livewire/flux/issues/588

**Comment by jeffchown** [comment]
Great, @lloydowen !

**Comment by sjwatts119** [comment]
> using `wire:target` on button elements fixed it!

Thank you for this! Saved me a headache :)

**Comment by jeffchown** [comment]
Thanks to @joshhanley's PR (https://github.com/livewire/flux/pull/849), manually adding the `wire:target` to each button is no longer needed.

If you update to Flux v1.0.30, it should 'just work' now :)
