### ISSUE TITLE
Select variant="listbox" don't accept required attribute

### ISSUE THREAD

**Issue by wevertondcl** [livewire/flux#80]
Using the required on select inputs not working when submiting form.

` <flux:select  wire:model.live="contaProgramaSelecionada"  variant="listbox" searchable  placeholder="Escolha ou busque pelo nome" required>`

**Comment by calebporzio** [comment]
Currently, custom inputs do not support native input affordances like the `required` attribute. You will have to rely on server-side validation for that user experience unfortunately.
