### ISSUE TITLE
Flux Editor - contents changing to include toolbar text when using Alpine.js sort

### ISSUE THREAD

**Issue by mikecchops** [livewire/flux#809]
I've ran into an issue with multiple Flux editors on the same page that are sorted using Alpine.js. 

Example blade code:

```blade
<div>
    <ul x-sort>
        <li x-sort:item><flux:editor
                wire:model.lazy="content1"
                toolbar="heading bold bullet ordered link"
                wire:key="block-editor-1"
            /></li>
        <li x-sort:item><flux:editor
                wire:model.lazy="content2"
                toolbar="heading bold bullet ordered link"
                wire:key="block-editor-2"
            /></li>
        <li x-sort:item><flux:editor
                wire:model.lazy="content3"
                toolbar="heading bold bullet ordered link"
                wire:key="block-editor-3"
            /></li>
    </ul>
</div>

``` 

Adding some text to each editor and then changing the order results in the contents of one of the editor blocks changing to include empty paragraph lines, along with some of the toolbar text:

`
        

            Text

    Styles

    
        

            Text

        

            Heading 1

            Heading 2

        

            Heading 3

    
    Bold

            ⌘B

    
            

    Bullet list

    Ordered list

    

    

                                                                            

    

    

        

            

    

            

    Insert link

            ⌘K

    

    

    

        

            

            

                

    

                            

                    

            

    Insert link

    

    

                

    

                                      

                    

            

    Unlink

    

    

            

        

    

                                        

            dsfsd`

**Comment by jeffchown** [comment]
@mikecchops Have you tried moving the `wire:key`s to the `li` tags?

**Comment by mikecchops** [comment]
@jeff

> [@mikecchops](https://github.com/mikecchops) Have you tried moving the `wire:key`s to the `li` tags?

Just tried that now, same result.

**Comment by ju5t** [comment]
Is this not related to #806?

**Comment by mikecchops** [comment]
@ju5t good spot. Yes could well be, I get the same error in the console

```
Uncaught TypeError: can't redefine non-configurable property "disabled"
``` 

Yes - this is just a simplified demo, in my application x-sort:item has a value.

**Comment by jeffchown** [comment]
Per @ju5t Definitely looks to be related to #806

**Comment by joshhanley** [comment]
@mikecchops yeah your issue looks similar to mine #806, so I'm going to close this issue for now and we will keep investigating in #8076. Once it has been fixed, if you're still experiencing your issue, then feel free to open a new issue.
