### ISSUE TITLE
[Visual issue] flux:table pagination with many items

### ISSUE THREAD

**Issue by dicktornfeldt** [livewire/flux#81]
When there are many pages in the pagination, buttons in the thousands after the ... are a bit jammed. Seems like the buttons have a hardcoded width which makes the page numbers to overflow each other.

<img width="840" alt="Skärmavbild 2024-09-25 kl  21 01 49" src="https://github.com/user-attachments/assets/ac3eb4d4-cb66-483c-9f7f-cf7748b5b838">

**Comment by schonhoff** [comment]
same for me and we got 70k+ items

**Comment by patrykszady** [comment]
Also, regarding tables: When inside a small card or container the pagination overflows. 

![Image](https://github.com/user-attachments/assets/ce15bba4-6989-460c-98d3-b6a1968e8717)

**Comment by MartijnCuppens** [comment]
Replacing `size-6` with `h-6 min-w-6 px-0.5` should do the trick I think.

**Comment by joshhanley** [comment]
Thanks for reporting! I have submitted a PR to fix this.
