### ISSUE TITLE
Flux Select with Searchable + Multiple resets search after each selection

### ISSUE THREAD

**Issue by bawbanksy** [livewire/flux#813]
### Flux version

v1.0.29

### Livewire version

v3.5.16

### What is the problem?

Hi,

Absolutely loving flux!!! Have found what seems to be a bug. 

After running a search to filter options then making a selection the search criteria clears. I believe it should persist so you're able to make multiple selections based on your search.

### Code snippets

       <flux:select variant="listbox" searchable multiple  placeholder="Choose industries...">
    <flux:option>Photography</flux:option>
    <flux:option>Design services</flux:option>
    <flux:option>Web development</flux:option>
    <flux:option>Accounting</flux:option>
    <flux:option>Legal services</flux:option>
    <flux:option>Consulting</flux:option>
    <flux:option>Other</flux:option>
</flux:select>

### How do you expect it to work?

Search results your persist after selection unless there is only one result then it should clear.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@bawbanksy This is the same as https://github.com/livewire/flux/issues/581 - please scroll to the bottom of that issue to read @calebporzio 's response

**Comment by bawbanksy** [comment]
> [@bawbanksy](https://github.com/bawbanksy) This is the same as [#581](https://github.com/livewire/flux/issues/581) - please scroll to the bottom of that issue to read [@calebporzio](https://github.com/calebporzio) 's response

just did some further digging around and noticed I missed this part of the docs-

[https://fluxui.dev/components/select#clearing-search](url)

adding `clear="close"` fixed the problem I was facing. Thank you @jeffchown for your reply anyhow :)

**Comment by jeffchown** [comment]
Great, @bawbanksy .  I forgot @calebporzio had made that change (in response to reports like yours and #581)
