### ISSUE TITLE
Wierd border and padding on select multiple

### ISSUE THREAD

**Issue by RezaODB** [livewire/flux#817]
### Flux version

Latest

### Livewire version

Latest

### What is the problem?

I added a select multiple today on my forms and I have this weird black border and padding. Is it a tailwind issue?
![Image](https://github.com/user-attachments/assets/40e876d8-561c-4466-9fca-9104205ca563)

### Code snippets

{{-- MULTIPLE --}}
                @if ($question->component === 'multiple')
                <flux:select variant="listbox" multiple wire:model.change="answers.{{ $question->id }}" wire:key="{{ $question->id }}" :label="$question->{'label_' . app()->getLocale()}" :placeholder="__('Select')">
                    @foreach ($question->{'options_' . app()->getLocale()} as $key => $option)
                    <flux:option wire:key="{{ $key }}">{{ $option }}</flux:option>
                    @endforeach
                </flux:select>
                @endif``

### How do you expect it to work?

No border and no padding

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@RezaODB This is a duplicate of multiple issues including this one: https://github.com/livewire/flux/issues/717 - if you use Tailwind's forms plugin it is incompatible with Flux and you need to remove it, then `npm run build` and `php artisan view:clear`.

**Comment by RezaODB** [comment]
Bim! You're the man! Thanks for the quick answer it works

**Comment by jeffchown** [comment]
You're welcome, @RezaODB
