### ISSUE TITLE
Modal inside dropdown causes immediate modal closure

### ISSUE THREAD

**Issue by dev-idkwhoami** [livewire/flux#819]
### Flux version

v1.0.29

### Livewire version

v3.5.16

### What is the problem?

When you place a modal inside a dropdown it gets closed immediately after opening. 

> [!TIP]
> This is circumventable by either "placing" the modal outside the `flux:dropdown` element or using the `@teleport` directive to move it outside. 

Im suspecting that the **close event** of the `flux:dropdown` element somehow propagates down to the modal and triggers its close event.

_It is important to note the modal does not close properly as the backdrop remains "open" and locks any further interactions with elements._

![Image](https://github.com/user-attachments/assets/7436a62b-2120-4f21-94e2-bc179ed6bb89)

### Code snippets

```blade
        <flux:dropdown>
            <flux:button variant="ghost" icon-trailing="chevron-down">Dropdown</flux:button>

            <flux:menu>
                <div>
                    <flux:modal.trigger name="modal-name">
                        <flux:menu.item icon="plus">Modal Trigger</flux:menu.item>
                    </flux:modal.trigger>

                    <flux:modal name="modal-name">
                        <flux:heading>Modal Title</flux:heading>
                    </flux:modal>
                </div>
            </flux:menu>
        </flux:dropdown>
```

### How do you expect it to work?

I would expect the modal close event to **not be triggered** by a some other close event of one of its parents.
It should be able to differentiate between "dropdown close event" and "modal close event"

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@dev-idkwhoami thanks for reporting!

I believe the issue will be that when an item is clicked in a dropdown, the dropdown is then closed. What that means is the dropdown and all of it's contents will be hidden (which includes the modal).

There are a couple of ways you can get around that:
- Move the modal outside of the dropdown, but leave the modal trigger inside of it
- Or if you like the trigger and modal together, you can wrap the `<flux:modal>` in `@teleport('body')/ @endteleport`

See both examples below.

I'm going to close this, but feel free to reopen if you don't feel like this solves your problem.

**Move modal outside of dropdown**
```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    //
};

?>

<div class="p-4">
    <flux:dropdown>
        <flux:button variant="ghost" icon-trailing="chevron-down">Dropdown</flux:button>

        <flux:menu>
            <div>
                <flux:modal.trigger name="modal-name">
                    <flux:menu.item icon="plus">Modal Trigger</flux:menu.item>
                </flux:modal.trigger>
            </div>
        </flux:menu>
    </flux:dropdown>

    <flux:modal name="modal-name">
        <flux:heading>Modal Title</flux:heading>
    </flux:modal>
</div>
```

**Use teleport**
```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    //
};

?>

<div class="p-4">
    <flux:dropdown>
        <flux:button variant="ghost" icon-trailing="chevron-down">Dropdown</flux:button>

        <flux:menu>
            <div>
                <flux:modal.trigger name="modal-name">
                    <flux:menu.item icon="plus">Modal Trigger</flux:menu.item>
                </flux:modal.trigger>

                @teleport('body')
                <flux:modal name="modal-name">
                    <flux:heading>Modal Title</flux:heading>
                </flux:modal>
                @endteleport
            </div>
        </flux:menu>
    </flux:dropdown>
</div>
```
