### ISSUE TITLE
[Visual issue] flux:input with icon and size="sm"

### ISSUE THREAD

**Issue by dicktornfeldt** [livewire/flux#82]
Flux input with an icon and size="sm" does not change the size of the icon, only the input.

This code:
```
<flux:input icon="magnifying-glass" placeholder="Search" />
<flux:input size="sm" icon="magnifying-glass" placeholder="Search" />
```

Looks like this:
<img width="441" alt="Skärmavbild 2024-09-25 kl  21 25 21" src="https://github.com/user-attachments/assets/e7f409b3-3c30-48c2-9c98-7ffb2b7a0582">

**Comment by beneyraheem** [comment]
Works fine for me, May be clear view cache

**Comment by joshhanley** [comment]
@dicktornfeldt thanks for reporting! I just tested this and it works fine, so going to close this issue. Make sure you update to the latest version of Flux v1.0.6 incase there was an issue with this component.

![Image](https://github.com/user-attachments/assets/84c99949-a7eb-420d-9e3a-38924053bd96)
