### ISSUE TITLE
Some colors are not working on the flux button

### ISSUE THREAD

**Issue by thenibirahmed** [livewire/flux#820]
### Flux version

3.5.12

### Livewire version

1.0.17

### What is the problem?

Tailwind bg-indigo-600 not working on button

### Code snippets

```blade
<flux:button class="bg-indigo-600 hover:bg-indigo-600">My Button</flux:button>
```

![Image](https://github.com/user-attachments/assets/29b1f42a-1366-4bdc-92a6-2909610ab242)

### How do you expect it to work?

The color should work

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by ju5t** [comment]
This is somewhat related to #691. A quick and dirty solution would be:

```html
<flux:button class="!bg-indigo-600 !hover:bg-indigo-600">My Button</flux:button>
```

**Comment by joshhanley** [comment]
@thenibirahmed yeah @ju5t is correct you need to use `!` to tell Tailwind that these colours should be applied, see details here in the docs https://fluxui.dev/docs/customization#tailwind-overrides

The only small change to @ju5t's code is that it should be `hover:!bg-indigo-600`, the `!` must go after any modifiers like `hover:`.

```blade
<flux:button class="!bg-indigo-600 hover:!bg-indigo-600">My Button</flux:button>
```

Going to close this, but feel free to open a new issue if you don't feel like this solves your problem.
