### ISSUE TITLE
DOMException: Node.removeChild: The node to be removed is not a child of this node

### ISSUE THREAD

**Issue by PHPieter** [livewire/flux#821]
Using firefox 133.0
When using `wire:model.live` in the root component. The root component has a child component which is bound using wire.model.
When changing the value of the root input. We get an error: 
`DOMException: Node.removeChild: The node to be removed is not a child of this node`

It looks like this error only exist when using a form object.
Also when changing the input of the child component we get an error:
`Uncaught TypeError: object is null`

This error occurs when the child component has at least two input fields.

### Root component
```
<?php

namespace App\Livewire;

use App\Livewire\Forms\TestForm;
use Livewire\Component;

class Test extends Component
{
    public TestForm $form;

    public $boatTypeOptions = ['option1' => 1, 'option2' => 2];

    public function render()
    {
        return view('livewire.test');
    }
}
```

### Root component template
```
<div>
    <flux:select class="mb-3" wire:model.live="form.live_updated_attribute" variant="listbox" >
        @foreach($boatTypeOptions as $option =>$val)
            <flux:option :value="$val">{{ $option }}</flux:option>
        @endforeach
    </flux:select>

    <livewire:address-section wire:model="form.child_component"/>
</div>
```

### Root component form class
```
<?php

namespace App\Livewire\Forms;

use Livewire\Attributes\Validate;
use Livewire\Form;

class TestForm extends Form
{
    public $live_updated_attribute;
    public $child_component;

}

```

### Child component
```
<?php

namespace App\Livewire;

use App\EnumClasses\DutchProvinceEnum;
use App\Rules\ZipCodeRule;
use Livewire\Attributes\Modelable;
use Livewire\Attributes\Validate;
use Livewire\Component;

class AddressSection extends Component
{
    #[Modelable]
    public $address = [];

    public function render()
    {
        return view('livewire.address-section');
    }
}

```

### Child component template
```
<div>
    <flux:input type="text" wire:model.live.debounce="address.street" label="{{__('address.Street')}}" :placeholder="__('address.Street')" />
    <flux:input type="text" wire:model.live.debounce="address.house_number" :label="__('address.House number')" :placeholder="__('address.House number')" />number')" />

</div>

```

**Comment by PHPieter** [comment]
Also when removing attributes _**:label**_ and _**:placeholder**_ from the the child component inputs. there is no error.

**Comment by jeffchown** [comment]
@PHPieter NOTE: You have an extra `number')" />` at the end of the second `flux:input` in the Child component template

**Comment by jeffchown** [comment]
@PHPieter After implementing your code and having a look at it, I believe this is a Livewire question, not a Flux issue.

That said, I'm not sure a Livewire Form object can properly handle/utilize a #[Modelable] property bound to one of its (the Form object's) properties dynamically.  And, the fact that you say "This error occurs when the child component has at least two input fields." hints that the issue could be connected to its handling of the array needed for 2 or more multiple input fields.

This one will probably need the expertise of @calebporzio @joshhanley 

IMHO, your code's structure looks complicated to me - if there is a way to simplify it to remove the tight coupling of the Root component -> Form Object -> Child Component the issue might disappear.

**Comment by PHPieter** [comment]
Thanks for you response. And sorry for the typo.

I created a new situation without the form. So the public properties live direct on the root component.
The errors remain the same.

In real live this is a massive form that is why i choose for this more complicated setup.
I think you right about this being a Livewire issue instead of flux. Ill see if i can add this issue to the Livewire github.

Again thanks for having a look at it.

**Comment by jeffchown** [comment]
You're welcome @PHPieter 

I understand re: large forms. 
(Sometimes when me forms get too large, I use that as a signal to refactor my UI - not sure if that makes sense in your case.)

Good luck!

**Comment by joshhanley** [comment]
@PHPieter I'll dig into this properly on Monday (it's Saturday here), but I do have one quick question, how did you submit this issue? Just curious as you seem to have bypassed the issue form template we have setup.

**Comment by PHPieter** [comment]
Super good to hear @joshhanley 
I submitted this issue thru https://fluxui.dev/docs/help  -> "Submit a bug report"

**Comment by joshhanley** [comment]
@PHPieter ah thanks for that! Looks like we missed updating that link to the new template. We've fixed that now 🙂

I've had a look into this issue but I wasn't able to replicate the problem. When you open the issue on the Livewire repo, can you be sure to include some step-by-step instructions on what I need to do to replicate the issue. Like, what input should I type into to generate the error, etc.

Going to close this as I agree with @jeffchown's it sounds more like a Livewire issue. If you feel otherwise, please feel free to open a new issue.
