### ISSUE TITLE
Docs Command example

### ISSUE THREAD

**Issue by clarkeash** [livewire/flux#827]
### Flux version

v1.0.29

### Livewire version

v3.5.17

### What is the problem?

In the docs for the command component you have the following code:

```
<flux:modal.trigger name="search" shortcut="cmd.k">
    <flux:input as="button" placeholder="Search..." icon="magnifying-glass" kbd="⌘K" />
</flux:modal.trigger>

<flux:modal name="search" variant="bare" class="min-h-[30rem] w-full max-w-[30rem] px-6" x-on:keydown.cmd.k.document="$el.showModal()">
    <flux:command class="border-none shadow-lg">
        <flux:command.input placeholder="Search..." closable />

        <flux:command.items>
            <flux:command.item icon="user-plus" kbd="⌘A">Assign to…</flux:command.item>
            <flux:command.item icon="document-plus">Create new file</flux:command.item>
            <flux:command.item icon="folder-plus" kbd="⌘⇧N">Create new project</flux:command.item>
            <flux:command.item icon="book-open">Documentation</flux:command.item>
            <flux:command.item icon="newspaper">Changelog</flux:command.item>
            <flux:command.item icon="cog-6-tooth" kbd="⌘,">Settings</flux:command.item>
        </flux:command.items>
    </flux:command>
</flux:modal>
```

Where the modal has `min-h-[30rem]` I assume to adjust the position on the page, it might be worth changing that to a `mb-[25rem]` or something as the height creates an area where you cannot click to dismiss the modal.

![Image](https://github.com/user-attachments/assets/fb6b1e73-b73f-42af-8aff-a848c59d1de6)

### Code snippets

See above

### How do you expect it to work?

It works fine, just a suggestion for the docs.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@clarkeash If that is anyone would prefer in their apps, they have the ability to code the appropriate CSS.
Personally, I don't think it makes sense to change the current default.

**Comment by clarkeash** [comment]
@jeffchown I struggle to see a scenario where people would prefer a small invisible section of the page not be usable to dismiss the modal. I am only suggesting updating the example in the docs, it doesn't change any of the component code.
Ultimately its Caleb’s call, just seems a bit weird to me.

**Comment by jeffchown** [comment]
@clarkeash I misunderstood your original post.

I agree that the area below the command modal should be clickable to dismiss the modal.
Your suggestion is one way to adjust the example.

**Comment by clarkeash** [comment]
@jeffchown Yeah there might be a better solution than adding margin to the bottom, css is not my strength.

**Comment by joshhanley** [comment]
@clarkeash thanks for reporting! I've submitted a fix to the docs to remove the `min-h-[30rem]` altogether as from my testing I don't think it's actually needed.
