### ISSUE TITLE
Premature Validation on Masked Input Fields

### ISSUE THREAD

**Issue by marchershey** [livewire/flux#829]
### Flux version

v1.0.29

### Livewire version

v3.5.17

### What is the problem?

Input fields with masks can inadvertently initiate validation upon page rendering. Disabling immediate validation (`onUpdate: false`) can mitigate this, but it restricts validation to form submission events.

### Code snippets

```php
#[Validate('required')]
public $zip;
```
```html
<flux:input mask="99999" wire:model.blur="zip" />
```
![https://i.imgur.com/yBPocBf.png](https://i.imgur.com/yBPocBf.png)

### How do you expect it to work?

I expect validation to trigger on the given events, like `.live` or `.blur`, and not automatically on page load.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@marchershey thanks for reporting!

I've just tested with the code supplied and I can't replicate your issue. For me the validation only fires if I focus in the input and then tab away. It's not being displayed on page load as you've reported.

Below is the Volt component that I used for testing. I'm going to close this issue as we can't replicate it. Feel free to open a new issue if you can consistently replicate it, but please make sure it include a full Volt component like below that we can copy directly into a projects to test with.

```blade
<?php

use Livewire\Attributes\Validate;
use Livewire\Volt\Component;

new class extends Component {
    #[Validate('required')]
    public $zip;
};

?>

<div>
    <flux:input label="Zip" mask="99999" wire:model.blur="zip" />
</div>
```

![Image](https://github.com/user-attachments/assets/3cb3424e-a03e-4d51-aa02-3579371dc8e2)

**Comment by joshhanley** [comment]
@marchershey thanks for the investigation! I will have a look at it tomorrow, for now I will reopen the issue 🙂

**Comment by jeffchown** [comment]
@joshhanley Doesn't the `wire:init="load"` perform a Livewire update call to run the `load` method which triggers the evaluation of all `#[Validation...]` attributes which would explain the validation error rendered post-`load()`?  Per the docs: "Livewire will automatically run the properties validation rules before each update".

Therefore, if the `$zip` property isn't initialized either in its declaration, or within a `mount()` method (e.g. before `load()` is called), won't it fail validation?

**Comment by joshhanley** [comment]
@jeffchown validate only runs on property update calls, so it should only run validate for zip if zip has been updated. Where as `wire:init` should only be running a method call 'load'

**Comment by jeffchown** [comment]
@joshhanley That's what I originally thought but thought I might be missing a special case re: `wire:init` or when Livewire/Alpine has to init a property that is originally `null` to enable it to be used with a `mask="..."`.

**Comment by joshhanley** [comment]
@jeffchown you are correct, when the mask is initialised, the value of `zip` is being set to an empty string.

Using the below component, if you type a letter into the description textarea, in the update request, we can see `zip` and `description` both being sent. Hence why it would be running the validation for `zip`.

@marchershey I actually managed to replicate this using plain html inputs (see Volt component below), as such this isn't a Flux issue and probably an Alpine issue (as Flux is using `x-mask` under the hood). So I'm going to close this.

![Image](https://github.com/user-attachments/assets/70b37ca0-9a94-4310-9c9a-c585baf370dc)

```blade
<?php

use Livewire\Attributes\Validate;
use Livewire\Volt\Component;

new class extends Component {
    #[Validate('required')]
    public $zip;
    public $description;
};

?>

<div>
    <input x-mask="99999" wire:model="zip" class="border border-zinc-300" />
    @error('zip')
        <span class="text-red-500">{{ $message }}</span>
    @enderror
    <textarea wire:model.live="description" class="border border-zinc-300">
    </textarea>
</div>
```
