### ISSUE TITLE
Modal can't not be closable

### ISSUE THREAD

**Issue by Supernova3339** [livewire/flux#832]
### Flux version

V1.0.29

### Livewire version

V3.5.17

### What is the problem?

Modal can not have the close button removed.

### Code snippets

Try to use closable="false" in <flux:modal

### How do you expect it to work?

adding closable="false" hides the close button.

Solution code:

```php
<?php if ($closable === true): ?>
    {{-- This "[&[hidden]]:block" hack is here to prevent this element from effecting classes like "space-y-6" --}}
    <div class="absolute top-0 right-0 mt-4 mr-4 [&[hidden]]:block" hidden>
        model is {{ $closable }}
        <flux:modal.close>
            <flux:button variant="ghost" icon="x-mark" size="sm" alt="Close modal" class="!text-zinc-400 hover:!text-zinc-800 dark:!text-zinc-500 dark:hover:!text-white"></flux:button>
        </flux:modal.close>
    </div>
<?php endif; ?>
```

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@Supernova3339 I've just tested this and it works as expected. See working Volt component below. In future please make sure you submit code that we can directly copy and paste that demonstrates your issue (that includes the actual modal code). Thanks!

```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    //
};

?>

<div class="p-4">
    <flux:modal.trigger name="edit-profile">
        <flux:button>Edit profile</flux:button>
    </flux:modal.trigger>

    <flux:modal name="edit-profile" class="md:w-96 space-y-6" :closable="false">
        <div>
            <flux:heading size="lg">Update profile</flux:heading>
            <flux:subheading>Make changes to your personal details.</flux:subheading>
        </div>

        <flux:input label="Name" placeholder="Your name" />

        <flux:input label="Date of birth" type="date" />

        <div class="flex">
            <flux:spacer />

            <flux:button type="submit" variant="primary">Save changes</flux:button>
        </div>
    </flux:modal>
</div>
```

**Comment by Supernova3339** [comment]
> [@Supernova3339](https://github.com/Supernova3339) I've just tested this and it works as expected. See working Volt component below. In future please make sure you submit code that we can directly copy and paste that demonstrates your issue (that includes the actual modal code). Thanks!
> 
> <?php
> 
> use Livewire\Volt\Component;
> 
> new class extends Component {
>     //
> };
> 
> ?>
> 
> <div class="p-4">
>     <flux:modal.trigger name="edit-profile">
>         <flux:button>Edit profile</flux:button>
>     </flux:modal.trigger>
> 
>     <flux:modal name="edit-profile" class="md:w-96 space-y-6" :closable="false">
>         <div>
>             <flux:heading size="lg">Update profile</flux:heading>
>             <flux:subheading>Make changes to your personal details.</flux:subheading>
>         </div>
> 
>         <flux:input label="Name" placeholder="Your name" />
> 
>         <flux:input label="Date of birth" type="date" />
> 
>         <div class="flex">
>             <flux:spacer />
> 
>             <flux:button type="submit" variant="primary">Save changes</flux:button>
>         </div>
>     </flux:modal>
> </div>
> ![Image](https://github.com/user-attachments/assets/8fbbb378-f9e7-4571-8977-48e7b116c8b1)

Will do! Not a user of Volt so I didn't really know how I would provide reproducible code.

I'll make a note of this for the future, thanks for your help!

**Comment by joshhanley** [comment]
@Supernova3339 thanks! A Livewire component class and view is also fine 🙂 Volts just easier because it's one file, but not a big issue if it's a LW component.
