### ISSUE TITLE
Publish assets like livewire

### ISSUE THREAD

**Issue by labomatik** [livewire/flux#840]
### Flux version

v1.0

### Livewire version

3.5

### What is the problem?

I'm using flux in a NativePhp project, when lauching the app an error is throwed:
Failed to load resource: the server responded with a status of 500 (Internal Server Error) http://127.0.0.1:8100/flux/flux.css?id=3324411c

In sentry we have more details:
filemtime(): stat failed for /Users/cris/project_nativephp/vendor/livewire/flux/src/../../flux-pro/dist/flux.css

Seems to point to my own folder while it should be relative on the nativePhp app, the electron mechanism seems to not support the /flux path...

### Code snippets

To reproduce, just create a new nativePhp app with a brand new laravel app and FluxUi, execute the app on another machine (to avoid pointing to the /Users/XXX local files)

### How do you expect it to work?

For livewire we used the livewire:publish --asset to have the files in our public folder.
I was expecting the same for fluxui...

Can i just copy/paste the js and css from flux?

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@labomatik to save us time, can you share an example nativePhp repo that demonstrates the issue, that we can pull down and investigate? Thanks!

**Comment by joshhanley** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps with steps to reproduce. Be sure to include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Then, we will be happy to help.

**Comment by labomatik** [comment]
Hello, i'll leave it closed, i've opened a ticket at NativePhp's repo.
For the moment i've copied the css and js generated by Flux and it's working (not ideal but working)

**Comment by ChaerilM** [comment]
i would like this as well, my case was in cpanel i use its git version control which replicate repo at /repositories/name. and i put modified index.php and other public files in /public_html. the index.php opens vendor dir and bootstrap from /repositories/name
