### ISSUE TITLE
A navbar item wrapped in a form (e.g. logout button) does not take full width of dropdown element

### ISSUE THREAD

**Issue by Kturva** [livewire/flux#842]
### Flux version

v1.0.29

### Livewire version

v3.5.17

### What is the problem?

A `flux:navbar.item` wrapped in a form does not take full width of the dropdown element like a plain navbar item does. 

![Image](https://github.com/user-attachments/assets/2970a385-5a28-412e-830e-8a011037f354)

### Code snippets

```blade
<?php

use Livewire\Volt\Component;

new class extends Component
{
    //
}; ?>

<flux:dropdown>
    <flux:navbar.item icon-trailing="chevron-down">Account</flux:navbar.item>
    <flux:navmenu>
        <flux:navbar.item href="/profile">Profile</flux:navbar.item>
        <form method="POST" action="/logout">
            @csrf
            <flux:navbar.item type="submit">Logout</flux:navbar.item>
        </form>
    </flux:navmenu>
</flux:dropdown>

```

### How do you expect it to work?

Button should be full width of the dropdown like plain navbar items. Unless there is a better way to implement POST logout in flux.

![Image](https://github.com/user-attachments/assets/f25c69ad-c38c-41df-8414-78f71f63b4df)

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@Kturva When no `href` is passed to a `flux:navbar.item`, Flux makes that item a `button` which is rendered differently.  One way I have worked around this when adding a Log Out option to my menus is to add an `href` so Flux renders the `navbar.item` as an `<a>` tag, then I add a little Alpine code to submit the form:

```
<form x-ref="logout_form" method="POST" action="/logout">
    @csrf
    <flux:navbar.item href="#" x-on:click="$refs.logout_form.submit()">Logout</flux:navbar.item>
</form>
```

**Comment by joshhanley** [comment]
@Kturva thanks for reporting!

Yeah I can confirm this is an issue where the button is being rendered differently than the a tag.

Here's a Volt component that demonstrates the issue using a navbar.item as a general button (even without the form tags).

```blade
<?php

use Livewire\Volt\Component;

new class extends Component
{
    //
};
?>

<flux:navbar>
    <flux:dropdown>
        <flux:navbar.item icon-trailing="chevron-down">Account</flux:navbar.item>
        <flux:navmenu>
            <flux:navbar.item href="/profile">Profile</flux:navbar.item>
            <flux:navbar.item wire:click="doSomething">Do Something</flux:navbar.item>
        </flux:navmenu>
    </flux:dropdown>
</flux:navbar>
```

**Comment by joshhanley** [comment]
@Kturva thanks for reporting!

It looks like you are using a `navbar.item` inside a navbar dropdown, but you should be using a `navmenu.item`.

I've done a test with a form and a standalone button and they're both happy when you use `navmenu.item`.

I'm going to close this issue for now. Feel free to open a new issue if this doesn't fix your problem.

```blade
<?php

use Livewire\Volt\Component;

new class extends Component
{
    //
};
?>

<flux:navbar>
    <flux:dropdown>
        <flux:navbar.item icon-trailing="chevron-down">Account</flux:navbar.item>
        <flux:navmenu>
            <flux:navmenu.item href="/profile">Profile</flux:navmenu.item>
            <form wire:submit="logout">
            @csrf
                <flux:navmenu.item type="submit">Logout</flux:navmenu.item>
            </form>
            <flux:navmenu.item wire:click="doSomething">Do Something</flux:navmenu.item>
        </flux:navmenu>
    </flux:dropdown>
</flux:navbar>
```
