### ISSUE TITLE
Wire:current highlight mispositioned for current route navbar item inside dropdown

### ISSUE THREAD

**Issue by Kturva** [livewire/flux#843]
### Flux version

v1.0.29

### Livewire version

v3.5.17

### What is the problem?

Flux highlights current route in navbar items but inside a dropdown the position seems to be off.
 
![Image](https://github.com/user-attachments/assets/a09fcfa6-2799-42e5-8f16-f5621c31a968)

### Code snippets

```blade
<?php

use Livewire\Volt\Component;

new class extends Component
{
    //
}; ?>

<flux:dropdown>
    <flux:navbar.item icon-trailing="chevron-down">Account</flux:navbar.item>
    <flux:navmenu>
        <flux:navbar.item href="/profile">Profile</flux:navbar.item>
        <flux:navbar.item href="/component-test">Component test</flux:navbar.item> <!-- Your test route here -->
        <flux:navbar.item href="/logout">Logout</flux:navbar.item>
    </flux:navmenu>
</flux:dropdown>
```

### How do you expect it to work?

Highlight border thing should not be on the navbar item below current route.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@Kturva Have you run `npm run build` and `php artisan view:clear`?

**Comment by jeffchown** [comment]
@Kturva You need to wrap your `flux:dropdown` in a `flux:navbar` as there is CSS that will be applied only if the `flux:dropdown` is nested.

If you want a dropdown that is 'standalone', use `flux:menu` (https://fluxui.dev/components/dropdown)

**Comment by joshhanley** [comment]
@Kturva thanks for reporting!

@jeffchown is correct, the styles you are seeing are because the `navbar.item` should only be used in the `navbar` element directly, for a dropdown in the navbar, you should be using `navmenu.item` inside the `navmenu`.

Going to close this, but feel free to open a new issue if you feel this hasn't solved your problem.
