### ISSUE TITLE
Loading indicator scope is not working on some specific cases

### ISSUE THREAD

**Issue by zaxxo-dkraemer** [livewire/flux#856]
### Flux version

v1.0.30

### Livewire version

v3.5.16

### What is the problem?

I have just updated Livewire to new version v1.0.30 because of the new automatic scoping of the loading indicators.
In most cases it works perfectly, but I have discovered two cases, where it's not working properly:

- String parameters in double quotes
- wire:click with modifiers like .stop

### Code snippets

```blade
<flux:button wire:click="add(&quot;NEW&quot;)">New</flux:button>
```
will be rendered as
```blade
<button wire:click="add(&quot;NEW&quot;)" wire:target="add(&amp;quot;NEW&amp;quot;)">New</button>
```
-> The parameter in wire:target is escaped twice

```blade
<flux:button wire:click.stop="add(1)">New</flux:button>
```
will be rendered as
```blade
<button wire:click.stop="add(1)">New</button>
```
-> No wire:target added

### How do you expect it to work?

```blade
<button wire:click="add(&quot;NEW&quot;)" wire:target="add(&quot;NEW&quot;)">New</button>
```

```blade
<button wire:click="add(1)" wire:target="add(1)">New</button>
```

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by zaxxo-dkraemer** [comment]
Fix for wire:click with modifiers:

In button/index.blade.php, line 36, use
```php
$attributes->whereStartsWith('wire:click')->first()
```
instead of
```php
$attributes->get('wire:click')
```

**Comment by zaxxo-dkraemer** [comment]
Fix for string parameters in double quotes:

In button/index.blade.php, line 37, use:

```php
$attributes->merge(['wire:target' => $target], false)
```

instead of

```php
$attributes->merge(['wire:target' => $target])
```

**Comment by zaxxo-dkraemer** [comment]
I just realized that Button is not Flux Pro, should I make Pull Requests in this repo? 😄

**Comment by joshhanley** [comment]
@zaxxo-dkraemer thanks for reporting! We've just pushed a fix, so it should be in the next release 🙂

Note for self: For debugging this I used the following Volt component and Blade component

```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    public function clear($id)
    {
        sleep(1);
    }
};
?>

<div>
    <x-other test="clear('1')" />
    <flux:button icon="trash" wire:click.stop="clear(2)" />
    <flux:button icon="trash" wire:click="clear(3)" />
</div>
```

```blade
{{-- resources/views/components/other.blade.php --}}
@props(['test'])

<flux:button icon="trash" wire:click.stop="{{ $test }}" />
```
