### ISSUE TITLE
Editor: cursor jumps to wrong position in the editor after inserting text

### ISSUE THREAD

**Issue by DonCamillo11** [livewire/flux#863]
### Flux version

v1.0.32

### Livewire version

v3.5.15

### What is the problem?

I don't know if this is a Flux or a Tiptap issue. I would like to insert text at the current cursor position in the editor. If I leave the cursor where it is, it works. As soon as I change the cursor position manually, it inserts the text, but the cursor jumps to the beginning. If I insert more text, it inserts the text at the right position, but the visual cursor is still at the beginning.
I tried to correct this behavior using a script, but there must be a problem somewhere. It would be nice if it worked without my fix.

https://github.com/user-attachments/assets/915a5b93-6a71-4613-81bf-4da03ae2d8b1

### Code snippets

```
namespace App\Livewire\Test;

use Livewire\Component;

class Test3 extends Component
{
    public function render()
    {
        return <<<'HTML'
        <div>
            <flux:editor>
                <flux:editor.toolbar>
                <flux:dropdown position="bottom end" offset="-15">
                    <flux:editor.button icon="code-bracket-square" tooltip="Placeholder" />
                    <flux:menu>
                        <flux:menu.item @click="$el.closest('[data-flux-editor]').editor.commands.insertContentAt($el.closest('[data-flux-editor]').editor.state.selection.$anchor.pos, $el.innerText)">{Insert text at current cursor position}</flux:menu.item>
                        <flux:menu.item @click="$el.closest('[data-flux-editor]').editor.commands.insertContentAt($el.closest('[data-flux-editor]').editor.state.selection.$anchor.pos, $el.innerText)">{Insert another text at current cursor position}</flux:menu.item>
                        <flux:menu.item @click="$el.closest('[data-flux-editor]').editor.commands.insertContentAt($el.closest('[data-flux-editor]').editor.state.selection.$anchor.pos, $el.innerText)">{Text 3}</flux:menu.item>
                        <flux:menu.item @click="insertPlaceholder($el, $el.innerText)">{Insert text at current cursor position and fix position}</flux:menu.item>
                        <flux:menu.item @click="insertPlaceholder($el, $el.innerText)">{Insert another text at current cursor position and fix position}</flux:menu.item>
                        <flux:menu.item @click="insertPlaceholder($el, $el.innerText)">{Text 6}</flux:menu.item>
                    </flux:menu>
                </flux:dropdown>
                </flux:editor.toolbar>

                <flux:editor.content />
            </flux:editor>
        </div>

        <script>
            function insertPlaceholder(e, placeholder) {
                pos = e.closest('[data-flux-editor]').editor.state.selection.$anchor.pos; 
                e.closest('[data-flux-editor]').editor.commands.insertContentAt(pos, placeholder); 
                e.closest('[data-flux-editor]').editor.commands.focus(pos+placeholder.length);
            }
        </script>
        HTML;
    }
}
```

### How do you expect it to work?

The cursor should always remain at the last position.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@DonCamillo11 I tried your snippet and couldn't consistently reproduce what your video showed as I had issues intermittent issues with focus remaining on the menu trigger after testing the first 3 menu items then had to use the tab key to tab back to the editor.  When I edited the code for the first 3 menu items to chain a `focus()` command at the end, the insertion and cursor position seemed to work ok for me.  Can you try this and let me know?:

```
<flux:menu.item
    @click="$el.closest('[data-flux-editor]')
        .editor
        .chain()
        .insertContentAt($el.closest('[data-flux-editor]').editor.state.selection.$anchor.pos, $el.innerText)
        .focus()
        .run()"
>
```

**Comment by DonCamillo11** [comment]
Wow, It seems to work like a charm. I will do some more test later.
Thanks @jeffchown

**Comment by jeffchown** [comment]
Great, @DonCamillo11 !  You're welcome.  Hope it does the trick.
