### ISSUE TITLE
Checkbox and radio group

### ISSUE THREAD

**Issue by celentano99** [livewire/flux#870]
### Flux version

v1.0.32

### Livewire version

3.5.17

### What is the problem?

Hello. 
On a page, I need to have the structure from the image.
The client should chose what items he needs ( using the ckeckbox ) and what is the latest item ( using the radio input )
![Image](https://github.com/user-attachments/assets/1cada9fb-7e56-48b0-8fc9-6e09642d09a1)
If I put 
            <flux:checkbox.group wire:model="cantitati_utilizate_id">
            <flux:radio.group wire:model="cantitate_ultima">
before the loop for the elements, I get the error. All is stuck.
![Image](https://github.com/user-attachments/assets/6dfe6279-ff9a-4744-a37d-f27fb3ceb4bd)

At the moment, I get around by using the normal radio  input, not flux items
I suspect that the issue is related to this groups are overlapping somehow. 
Maybe I do not use this in the correct way. The doc page has nothing related to my situation, using checkbox and radio inside the same loop.

### Code snippets

wrong blade file 

            <flux:checkbox.group wire:model="cantitati_utilizate_id">
            <flux:radio.group wire:model="cantitate_ultima">
            @foreach($cantitati_manuale as $loop_item)
            <flux:row :key="$loop_item->id">
                @if($x_admin_debug)<flux:cell>{{$loop_item->id}}</flux:cell>@endif
                <flux:cell>
                    <flux:checkbox wire:model="cantitati_utilizate_id" :value="$loop_item->id" />
                </flux:cell>
                <flux:cell>
                    <flux:radio wire:model="cantitate_ultima" :value="$loop_item->id" />
                </flux:cell>
                <flux:cell> {{$loop_item->cantitate - $loop_item->cantitate_cover}}</flux:cell>
                <flux:cell>{{$loop_item->cantitate}}</flux:cell>
                <flux:cell>{{$loop_item->firma_slug}}</flux:cell>
                <flux:cell>{{$loop_item->pv_serie}}</flux:cell>
                <flux:cell>
                    @if(count($loop_item->document_orig)>0)
                    <flux:icon.check variant="micro" class="text-lime-500 dark:text-lime-300" /> @else <flux:icon.x-mark variant="micro" class="text-red-500 dark:text-red-300" /> @endif
                </flux:cell>
                <flux:cell>
                    @if ($loop_item->pv_invoice == 1)
                    @if(count($loop_item->document_factura)>0)
                    <flux:icon.check variant="micro" class="text-lime-500 dark:text-lime-300" /> @else <flux:icon.x-mark variant="micro" class="text-red-500 dark:text-red-300" /> @endif
                    @endif
                </flux:cell>
            </flux:row>
            @endforeach
            </flux:radio.group>
            </flux:checkbox.group>

working blade file
<flux:checkbox.group wire:model="cantitati_utilizate_id">
            @foreach($cantitati_manuale as $loop_item)
            <flux:row :key="$loop_item->id">
                @if($x_admin_debug)<flux:cell>{{$loop_item->id}}</flux:cell>@endif
                <flux:cell>
                    <flux:checkbox wire:model="cantitati_utilizate_id" :value="$loop_item->id" />
                </flux:cell>
                <flux:cell>
                    <input type="radio" wire:model="cantitate_ultima" value="{{$loop_item->id}}">
                </flux:cell>
                <flux:cell> {{$loop_item->cantitate - $loop_item->cantitate_cover}}</flux:cell>
                <flux:cell>{{$loop_item->cantitate}}</flux:cell>
                <flux:cell>{{$loop_item->firma_slug}}</flux:cell>
                <flux:cell>{{$loop_item->pv_serie}}</flux:cell>
                <flux:cell>
                    @if(count($loop_item->document_orig)>0)
                    <flux:icon.check variant="micro" class="text-lime-500 dark:text-lime-300" /> @else <flux:icon.x-mark variant="micro" class="text-red-500 dark:text-red-300" /> @endif
                </flux:cell>
                <flux:cell>
                    @if ($loop_item->pv_invoice == 1)
                    @if(count($loop_item->document_factura)>0)
                    <flux:icon.check variant="micro" class="text-lime-500 dark:text-lime-300" /> @else <flux:icon.x-mark variant="micro" class="text-red-500 dark:text-red-300" /> @endif
                    @endif
                </flux:cell>
            </flux:row>
            @endforeach
            </flux:checkbox.group>

### How do you expect it to work?

I expect to have this groups working in the same time. 

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by igmltd** [comment]
Had a similar issue - using wire:key in the foreach with a random string and the id solved the issue.

**Comment by joshhanley** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps with steps to reproduce. Be sure to include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Then, we will be happy to help.
