### ISSUE TITLE
Console warnings (Firefox)

### ISSUE THREAD

**Issue by 0hra** [livewire/flux#88]
I get the following warnings in Firefox console:
<img width="559" alt="Screenshot 2024-09-26 at 00 23 25" src="https://github.com/user-attachments/assets/b8792851-4a8d-4ddb-a685-8abf7232d9be">

No warnings in Safari. 
I have not checked other browsers.

**Comment by calebporzio** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please re-submit this issue with a code snippet we can copy and paste into our own apps to reproduce. Then, we will be happy to help.
