### ISSUE TITLE
Accent color not applied to select checkbox/radio indicators

### ISSUE THREAD

**Issue by rickdubiel** [livewire/flux#881]
### Flux version

v1.1.0

### Livewire version

v3.5.17

### What is the problem?

The accent colors aren't being applied to the checkbox/radio items within the select dropdowns.

<img width="316" alt="Image" src="https://github.com/user-attachments/assets/1e7a8df6-292e-4ff9-a174-39959f6dc102" />
<img width="309" alt="Image" src="https://github.com/user-attachments/assets/3eafa14b-4a72-4b21-ac84-004527a56306" />

### Code snippets

**Select with Checkbox Indicators**
```
<flux:checkbox.group label="Notifications">
    <flux:checkbox label="Push notifications" value="push" checked />
    <flux:checkbox label="Email" value="email" checked />
    <flux:checkbox label="In-app alerts" value="app" />
    <flux:checkbox label="SMS" value="sms" />
</flux:checkbox.group>

<flux:select indicator="checkbox" variant="listbox">
    <flux:option>Photography</flux:option>
    <flux:option>Design services</flux:option>
    <flux:option selected>Web development</flux:option>
    <flux:option>Accounting</flux:option>
    <flux:option>Legal services</flux:option>
    <flux:option>Consulting</flux:option>
    <flux:option>Other</flux:option>
</flux:select>
```

**Select with Radio Indicators**
```
<flux:radio.group label="Select your payment method">
    <flux:radio value="cc" label="Credit Card" checked />
    <flux:radio value="paypal" label="Paypal" />
    <flux:radio value="ach" label="Bank transfer" />
</flux:radio.group>

<flux:select indicator="radio" variant="listbox">
    <flux:option>Photography</flux:option>
    <flux:option>Design services</flux:option>
    <flux:option selected>Web development</flux:option>
    <flux:option>Accounting</flux:option>
    <flux:option>Legal services</flux:option>
    <flux:option>Consulting</flux:option>
    <flux:option>Other</flux:option>
</flux:select>
```

### How do you expect it to work?

The selected items in the dropdowns should match the configured accent color.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@rickdubiel thanks for reporting! I've submitted a PR with a fix.
