### ISSUE TITLE
Border classes don't get applied to the Modal due to a missing [space]

### ISSUE THREAD

**Issue by MaartenCradeq** [livewire/flux#882]
### Flux version

v.1.1.0

### Livewire version

v3.5.17

### What is the problem?

The default classes for the Modal component are missing a [space] in `borderborder-transparent`, resulting in the border and border color not getting applied to the Modal. Visually, this mainly impacts dark mode, as the `border` class needs to be present in addition to the `border-color`.

### Current
<img width="1512" alt="bug" src="https://github.com/user-attachments/assets/1efb5df9-daa8-41cb-8a1c-9a8f9ba4cd96" />

### Fixed
<img width="1512" alt="fix" src="https://github.com/user-attachments/assets/f112698e-ac74-463b-97c3-9fbf3b217c30" />

---
PS: It's great that a Flux principle is "to bring your own spacing", but this might be taking it too literally! 😉

### Snippets from file
`resources/views/flux/modal/index.blade.php`

### Current 
```blade
default => 'bg-white dark:bg-zinc-800 borderborder-transparent dark:border-zinc-700',
```

### Fixed
```blade
default => 'bg-white dark:bg-zinc-800 border border-transparent dark:border-zinc-700',
```

### How do you expect it to work?

That the default border classes get applied.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@MaartenCradeq thanks for reporting! I've submitted a PR with a fix for this.
