### ISSUE TITLE
Dark mode switch not working

### ISSUE THREAD

**Issue by caioalbuquerquet** [livewire/flux#888]
### Flux version

v1.1.0

### Livewire version

v3.5.17

### What is the problem?

I followed the steps in the documentation to enable dark mode, but it didn't work.
I think to enable dark mode just need to modify the tailwind.config.js. I tried npm run build and php artisan view:clear. 

### Code snippets

layout.blade.php
````
<flux:menu>
    <flux:menu.radio.group>
        <flux:menu.radio checked>Olivia Martin</flux:menu.radio>
        <flux:menu.radio>Truly Delta</flux:menu.radio>
        
        <flux:button x-on:click="$flux.dark = ! $flux.dark" icon="moon" variant="subtle" aria-label="Toggle dark mode" />
    </flux:menu.radio.group>

    <flux:menu.separator />

    <flux:menu.item icon="arrow-right-start-on-rectangle" href="{{ route('logout') }}">Sair</flux:menu.item>
</flux:menu>
````
tailwind.config.js
````
import defaultTheme from 'tailwindcss/defaultTheme';
import colors from 'tailwindcss/colors';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'selector',
    theme: {
        extend: {
            colors: {
                // Re-assign Flux's gray of choice...
                zinc: colors.gray,

                // Accent variables are defined in resources/css/app.css...
                accent: {
                    DEFAULT: 'var(--color-accent)',
                    content: 'var(--color-accent-content)',
                    foreground: 'var(--color-accent-foreground)',
                },
            },
        },
    },
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
        "./vendor/livewire/flux-pro/stubs/**/*.blade.php",
        "./vendor/livewire/flux/stubs/**/*.blade.php",
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
            },
        },
    },
    plugins: [],
};

````

### How do you expect it to work?

Dark mode should be triggered

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by lonebadger99** [comment]
Hi. You need to add x-data to an encasing element somewhere.

Example: <html lang="en" xml:lang="en" x-data>

**Comment by caioalbuquerquet** [comment]
its working now, thanks 👍

**Comment by joshhanley** [comment]
@caioalbuquerquet I dont recommend putting x-data on the html or body elements as it means alpine has to track everything. Put it on your menu:item or wrap that in a fib and put it there instead. 

Cc @lonebadger99 FYI
