### ISSUE TITLE
Modal variant flyout removes all select options

### ISSUE THREAD

**Issue by patrykszady** [livewire/flux#89]
The below works when inside a `<flux:modal>` **without** a variant but when variant="flyout" is added options do not display.

```
<flux:select wire:model="form.vendor_id" placeholder="Choose vendor...">
    @foreach($vendors as $vendor)
        <flux:option value="{{$vendor->id}}">{{$vendor->business_name}}</flux:option>
    @endforeach
</flux:select>
```

**Comment by joalea** [comment]
Can confirm this.

**Comment by craigcordell** [comment]
Can also confirm this.

**Comment by patrykszady** [comment]
Also, something is happening with `variant="combobox"` on `<flux:select>`. If value of form.vendor_id isset it does not preselect the item by default like it does without the variant. Sometimes it shows the id by default instead. (Similar with autocomplete).

**Comment by thomaskenne** [comment]
Can confirm too.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.
