### ISSUE TITLE
Little bug in Accordian "exclusive"

### ISSUE THREAD

**Issue by dr-codswallop** [livewire/flux#9]
Expanded accordion items aren't treated as exclusive. 

Additionally when expanding the first item - then expanding second item - the first tem requires 2 clicks to collapse again.

[https://fluxui.dev/components/accordion#exclusive](url)

**Comment by michaeldojcar** [comment]
Same behaviour in docs example. All items can be expanded. (Tested on Safari, iOS 18).

<img width="791" alt="Snímek obrazovky 2024-09-23 v 21 45 28" src="https://github.com/user-attachments/assets/dd73cb89-af26-4693-9148-fc656c9f6fe2">

**Comment by calebporzio** [comment]
Fixed this, will be in next release. thanks
