### ISSUE TITLE
Select variant="listbox" error on listing selected option on "edit" mode

### ISSUE THREAD

**Issue by wevertondcl** [livewire/flux#90]
When listing values using a select with the listbox variant, the previously saved option is not automatically selected according to the wire:model passed in, eg: <flux:select wire:model=form.variable>

**Comment by wevertondcl** [comment]
Ok, this is related when using integer variable on wire:model=form.INTEGER.VARIABLE.
When using as string, everything works as expected.

**Comment by craigcordell** [comment]
Should this be closed? Can we not use an integer as the value to select?
