### ISSUE TITLE
Dark mode dropdown menu in header not working

### ISSUE THREAD

**Issue by dudelisius** [livewire/flux#900]
### Flux version

v1.1.0

### Livewire version

v3.4.0

### What is the problem?

I want to have the dark mode dropdown menu in my apps header as seen here; https://fluxui.dev/docs/dark-mode#dropdown-menu

However all contents is shown and the buttons do not work / toggle dark mode.

<img width="731" alt="Image" src="https://github.com/user-attachments/assets/43633d1d-90a5-438f-a21a-6c07a5bf154b" />

Other examples, like the segmented radio buttons do work. 

Small note, there is no copy button on the code blocs on this page in the docs.

### Code snippets

```
<flux:header class="border-b lg:hidden bg-zinc-50 dark:bg-zinc-900 border-zinc-200 dark:border-zinc-700">
        <flux:sidebar.toggle class="lg:hidden" icon="bars-3" inset="left" />

        <flux:spacer />

        <flux:dropdown>
            <flux:button variant="subtle" square class="group" aria-label="Preferred color scheme">
                <flux:icon.sun x-show="$flux.appearance === 'light'" variant="mini" class="text-zinc-500 dark:text-white" />
                <flux:icon.moon x-show="$flux.appearance === 'dark'" variant="mini" class="text-zinc-500 dark:text-white" />
                <flux:icon.moon x-show="$flux.appearance === 'system' && $flux.dark" variant="mini" />
                <flux:icon.sun x-show="$flux.appearance === 'system' && ! $flux.dark" variant="mini" />
            </flux:button>

            <flux:menu>
                <flux:menu.item icon="sun" x-on:click="$flux.appearance = 'light'">Light</flux:menu.item>
                <flux:menu.item icon="moon" x-on:click="$flux.appearance = 'dark'">Dark</flux:menu.item>
                <flux:menu.item icon="computer-desktop" x-on:click="$flux.appearance = 'system'">System</flux:menu.item>
            </flux:menu>
        </flux:dropdown>

        <flux:separator vertical class="my-2" />

        <flux:dropdown position="top" alignt="start">
            <flux:profile avatar="https://fluxui.dev/img/demo/user.png" />
        </flux:dropdown>
    </flux:header>
```

### How do you expect it to work?

I expect that the provided example code from the docs work when copy/pasting it into the application.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@dudelisius You need to add an `x-data` to your `flux:dropdown`, e.g. 
```
<flux:dropdown>
```

becomes

```
<flux:dropdown x-data>
```

**Comment by dudelisius** [comment]
Hi @jeffchown, thanks, that does indeed work :)

I do think flux needs to handle this automatically though.

**Comment by jeffchown** [comment]
Great, @dudelisius .

There should be some documentation added to the https://fluxui.dev/docs/dark-mode page to explain the need for an `x-data` and/or `x-data`s added where applicable in the related code snippets.

**Comment by joshhanley** [comment]
@dudelisius thanks for reporting! Yep @jeffchown is correct it needs the `x-data`. I've submitted a PR to the docs to add `x-data to the dark mode examples, as it's one of the few components that are likely to be used outside of a Livewire component (which will set `x-data` for you).
