### ISSUE TITLE
Modal: Calling wrong method in javascript example. (Documentation)

### ISSUE THREAD

**Issue by dennisfransen** [livewire/flux#902]
### Flux version

v1.1.0

### Livewire version

v3.5.17

### What is the problem?

In the example. Show() is called when pressinc Close button.

Link: https://fluxui.dev/components/modal#javascript-methods

### Extra note
>Not using `<flux:button>...</flux:button>` in example. Idk if that's the intention. But it probably is.

![Image](https://github.com/user-attachments/assets/69675540-266c-4d3a-ab79-75173776076b)

### Code snippets

```html
<button x-on:click="$flux.modal('confirm').show()">
    Open modal
</button>

<button x-on:click="$flux.modal('confirm').show()">
    Close modal
</button>

<button x-on:click="$flux.modals().close()">
    Close all modals
</button>
```

### How do you expect it to work?

I expect the javascript example to look like this

```html
<button x-on:click="$flux.modal('confirm').show()">
    Open modal
</button>

<button x-on:click="$flux.modal('confirm').close()">
    Close modal
</button>

<button x-on:click="$flux.modals().close()">
    Close all modals
</button>
```

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@dennisfransen thanks for reporting! I've submitted a PR with a fix.
