### ISSUE TITLE
Using indicator="checkbox" on select-component doesn't respect theme-settings

### ISSUE THREAD

**Issue by LuciusAB** [livewire/flux#905]
### Flux version

v1.1.0

### Livewire version

v3.5.17

### What is the problem?

When using indicator="checkbox" on the flux:select-component, the checkboxes in the select dropdown are not in the theme-color but just in black.

### Code snippets

```blade
                <flux:select 
                    variant="listbox" 
                    multiple 
                    indicator="checkbox"
                    selected-suffix="kategorier valda"
                    x-data="{ selected: ['alla'] }"
                    x-model="selected">
                    <flux:option value="alla">Alla kategorier</flux:option>
                    <flux:option value="restauranger">Restauranger</flux:option>
                    <flux:option value="cafe">Caféer</flux:option>
                    <flux:option value="butiker">Butiker</flux:option>
                    <flux:option value="parker">Parker</flux:option>
                </flux:select>
```

### How do you expect it to work?

I expect it to have the Flux-theme color, like the other checkboxes do if you dont use them via the flux:select-component.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@LuciusAB thanks for reporting! This has already been reported in #881. A fix has been merged and will be available in the next release 🙂
