### ISSUE TITLE
Navbar - fixed 1) Moves the menu lower than when not using "fixed"  2) I assumed that fixed meant the menu would be protected at the top

### ISSUE THREAD

**Issue by lcallif** [livewire/flux#906]
### Flux version

1.1.0

### Livewire version

 v3.5.12 

### What is the problem?

Software Versions
------------------
livewire/flux                        v1.1.0 
livewire/flux-pro                  1.1.0 
livewire/livewire                  v3.5.12 
laravel/jetstream                  v5.3.3 

### Code snippets

1) a.The menu is displayed lower than when not using "fixed"
   b) The background is no longer displayed  

2) I assumed that "fixed" meant the menu would be protected at the top, nothing on the form would scroll over the top of the menu.  The Form
    has more items than what is displayed on the initial form.  When scrolling down to see more items, the menu stays, but the form's items go over the top and look horrible.

Is "fixed" not to be used for navbar ?

```
        <div class="ml-48 bg-blue-200">
            <flux:navbar class="fixed">
                <flux:navbar.item icon="home" href="{{ url('/dashboard') }}"></flux:navbar.item>
                <flux:dropdown>
                    <flux:navbar.item icon-trailing="chevron-down">{{ __('Project Phases') }}</flux:navbar.item>
                    <flux:navmenu>
                        <flux:navmenu.item class="!text-lg" href="{{ url('/customerproposalprojects') }}">{{ __('Projects') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="{{ url('/customerinvoices') }}">{{ __('Invoice(s)') }}</flux:navmenu.item>
                    </flux:navmenu>
                </flux:dropdown>
                <flux:dropdown>
                    <flux:navbar.item class="!text-black" icon-trailing="chevron-down">{{ __('Reports') }}</flux:navbar.item>
                    <flux:navmenu>
                        <flux:navmenu.item class="!text-lg" href="#">{{ __('Proposal(s)') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="#">{{ __('Invoice(s)') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="#">{{ __('Employee(s)') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="#">{{ __('Lead(s)') }}</flux:navmenu.item>
                    </flux:navmenu>
                </flux:dropdown>
                <flux:dropdown>
                    <flux:custom.bct-navbar.item class="!text-black " icon-trailing="chevron-down">{{ __('Maintenance') }}</flux:navbar.item>
                    <flux:navmenu  class="!text-lg">
                        <flux:navmenu.item class="!text-lg" href="">{{ __('Bill of Materials') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="">{{ __('Customer(s)') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="">{{ __('Employee(s)') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="">{{ __('Inventory(s)') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="">{{ __('Lead Management') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="">{{ __('Proposal / Invoice Section(s)') }}</flux:navmenu.item>
                        <flux:navmenu.item class="!text-lg" href="">{{ __('Tool(s)') }}</flux:navmenu.item>
                    </flux:navmenu>
                </flux:dropdown>
                <flux:navbar.item class="!text-black"  href="">{{ Auth::user()->name }} - Manage</flux:navbar.item>
            </flux:navbar>
        </div>
```

### How do you expect it to work?

![Image](https://github.com/user-attachments/assets/b5753b8f-4cd5-46b7-8ddc-a57f4da78f5e)
![Image](https://github.com/user-attachments/assets/db5330b4-d468-4172-9681-257e3561f2d9)
![Image](https://github.com/user-attachments/assets/cd595a8d-dc35-461a-a5fc-3a0b425e712a)

I would expect for the fixed menu to:
  - Be fixed in the same area that the non-fixed menu would display
  - The background of the menu would be retained
  - The form when scrolled up would not overwrite the menu

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@lcallif This sounds more like a Tailwind CSS question and probably involves z-indexes.

**Comment by lcallif** [comment]
Wellll, crud.  Thank you.  off to Livewire I go.
