### ISSUE TITLE
Theming: Base color replacement priority is too low

### ISSUE THREAD

**Issue by BubeDameKoenig** [livewire/flux#911]
### Flux version

1.1.0

### Livewire version

3.5.12

### What is the problem?

Theming:
In `tailwind.config.js` I make a Zinc replacement with `zinc: colors.red`.
Zinc is also replaced but the priority is too low for it to be displayed.

![Image](https://github.com/user-attachments/assets/ebe4b547-99ba-4f7d-802b-41d08ffd5c0a)

### Code snippets

I use `<flux:text>Test</flux:text>` as the element.

### How do you expect it to work?

I think that the replaced code would have to have a higher priority to be effectively replaced.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@BubeDameKoenig can you try moving flux styles above your vite app.css and see if that works?

**Comment by BubeDameKoenig** [comment]
@joshhanley 
Unfortunately this did not help.

`npm run build` and `php artisan view:clear` were also executed.

```blade
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    @fluxStyles

    <script src="https://cdn.tailwindcss.com"></script>

    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <script src="{{ asset('js/all.js') }}"></script>
</head>
```

**Comment by joshhanley** [comment]
@BubeDameKoenig maybe the Tailwind CDN is conflicting with it? Try removing that and see if it helps. If not, please share your full layout file and your Tailwind config

**Comment by BubeDameKoenig** [comment]
@joshhanley 
You were right. Tailwind CDN confuses this.
Perhaps it could be included in the documentation that this should be removed.

**Comment by joshhanley** [comment]
@BubeDameKoenig glad you got it sorted! I think the issue was the fact that you had both Tailwind compiled using Vite and also the CDN, so I'd think that's more of a Tailwind issue. But if other people run into it, then we can look at adding a warning to the Flux docs 🙂
