### ISSUE TITLE
Table horizontal sizing - scrollbar

### ISSUE THREAD

**Issue by CodeAn** [livewire/flux#915]
### Flux version

v1.1.0

### Livewire version

v.3.5.17

### What is the problem?

When the last column is sortable and has a larger name the table will get a horizontal scrollbar.
![Image](https://github.com/user-attachments/assets/8e63075b-e8ab-4c98-a9f3-0e72cd529f5d)

As an example I have set the latest flux column to whitespace-normal.

When I remove sortable, the table shows as this:
![Image](https://github.com/user-attachments/assets/8525521d-0f53-4678-b9c8-8c451e417947)

It seems to happen when you start to resize the window down. I have a 3440x1440 screen and 50% is 1720 instead of 1920. Also seems to happen on laptop screen with resolution of 2560x1600 and scaling set to 175%, 150% seems to be ok.
-> Edit. This is depending on the data in the table in combination with space available. It's easy to simulate with any table as soon as you start resizing your screen. It should still fit, but it's a few px of and therefore giving you the scrollbar.

### Code snippets

```
@php
  $elements = [
    [
    'id' => 1,
    'name' => 'Acme Inc.',
    'description' => 'A description of Acme Inc.',
    'city' => 'New York',
    ],
    [
    'id' => 2,
    'name' => 'Beta Corp.',
    'description' => 'A description of Beta Corp.',
    'city' => 'Los Angeles',
    ],
    [
    'id' => 3,
    'name' => 'Gamma Ltd.',
    'description' => 'A description of Gamma Ltd.',
    'city' => 'Chicago',
    ],
    [
    'id' => 4,
    'name' => 'Delta LLC',
    'description' => 'A description of Delta LLC',
    'city' => 'Houston',
    ]
  ];
@endphp

<div>

  <flux:table>
    <flux:columns>
      <flux:column sortable :sorted="$sortBy === 'id'" :direction="$sortDirection" wire:click="sort('id')">
        {{ __('ID') }}
      </flux:column>
      <flux:column sortable :sorted="$sortBy === 'name'" :direction="$sortDirection" wire:click="sort('name')">
        {{ __('Name') }}
      </flux:column>
      <flux:column sortable :sorted="$sortBy === 'city'" :direction="$sortDirection" wire:click="sort('city')">
        {{ __('Description') }}
      </flux:column>
      <flux:column sortable :sorted="$sortBy === 'city'" :direction="$sortDirection" wire:click="sort('city')">
        {{ __('Description') }}
      </flux:column>
      <flux:column sortable :sorted="$sortBy === 'city'" :direction="$sortDirection" wire:click="sort('city')">
        {{ __('Description') }}
      </flux:column>
      <flux:column sortable :sorted="$sortBy === 'city'" :direction="$sortDirection" wire:click="sort('city')">
        {{ __('Description') }}
      </flux:column>
      <flux:column class="!whitespace-normal" sortable :sorted="$sortBy === 'description'" :direction="$sortDirection" wire:click="sort('description')">
        {{ __('Description with a big header') }}
      </flux:column>
    </flux:columns>
    <flux:rows>
      @forelse ($elements as $element)
      <flux:row :key="$element['id']">
      <flux:cell>
        {{ $element['id'] }}
      </flux:cell>
      <flux:cell>
        {{ $element['name'] }}
      </flux:cell>
      <flux:cell>
        {{ $element['description'] }}
      </flux:cell>
      <flux:cell>
        {{ $element['description'] }}
      </flux:cell>
      <flux:cell>
        {{ $element['description'] }}
      </flux:cell>
      <flux:cell>
        {{ $element['description'] }}
      </flux:cell>
      <flux:cell>
        {{ $element['city'] }}
      </flux:cell>
      </flux:row>
    @empty
      <flux:row>
      <flux:cell colspan="3">
        {{ __('No elements found') }}
      </flux:cell>
      </flux:row>
    @endforelse
    </flux:rows>
  </flux:table>

</div>
```

### How do you expect it to work?

As the second image, no scrollbar. I'd expect the table to consume full 100% width, not go past it.

When every single flux:column and flux:cell has whitespace-normal as a class, it will scale correctly.
-> Edit, tested this with some live tables I have, this is not always true.

A simple workaround is adding an empty column and empty cell at the end.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@CodeAn thanks for reporting! I've submitted a PR with a fix.
