### ISSUE TITLE
[Tabs] href trailing slash is added automatic

### ISSUE THREAD

**Issue by darviscommerce** [livewire/flux#93]
When i put an url to href the codes add an trailing slash
Maybe my procedure is wrong for Flux

`<flux:tab href="https://laravel11/cms/page/read/1?locale=nl">READ</flux:tab>`

OUTPUT (with an slash)

https://laravel11/cms/page/read/1?locale=nl/

**Comment by joshhanley** [comment]
@darviscommerce thanks for reporting! I have submitted a PR with a fix.
