### ISSUE TITLE
Issues with Dark Mode Disabling and Button Loading During Pagination in Flux v1.1.2

### ISSUE THREAD

**Issue by ReignInfotech** [livewire/flux#930]
### Flux version

v1.1.2

### Livewire version

v3.5.18

### What is the problem?

I updated to Flux v1.1.2 and am facing issues where disabling dark mode is not working, and the button loading state does not work during pagination. After the update, dark mode was automatically turned on. These features were working smoothly in the previous version.

This version dark mode being automatically turned on after the update.

### Code snippets

Disabling dark mode
tailwind.config.js

```
import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: null,
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        "./vendor/livewire/flux-pro/stubs/**/*.blade.php",
        "./vendor/livewire/flux/stubs/**/*.blade.php",
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
            },
        },
    },

    plugins: [forms],
};
```

Loading Button
```
<flux:button variant="danger" size="xs" wire:click="Print({{ json_encode($data->pur_inv_no) }}, {{ json_encode($data->supplier_code) }})">
                        Print
</flux:button>
```
https://github.com/user-attachments/assets/9aff3a69-83e3-4c69-9315-7c9da5a97e72

### How do you expect it to work?

When installing or initializing Flux, the setup process should include a clear prompt asking whether the user wants to enable dark mode by default.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@ReignInfotech as in the docs:

```
export default {
    darkMode: null,
    ...
};
```

Have you tried the `null` without quotes around it?

PS Please post each issue separately.

**Comment by joshhanley** [comment]
@ReignInfotech I'm going to close this as there are multiple issues here. Please open new separate issues. Don't put it all in one issue as it's hard to track what has been sorted and what hasn't. Thanks
