### ISSUE TITLE
Uncaught Could not find option for value "" for select component when

### ISSUE THREAD

**Issue by mariano55555** [livewire/flux#939]
### Flux version

v1.1

### Livewire version

v3.4

### What is the problem?

when adding wire:model.live="property" to the select component it shows the error "Uncaught Could not find option for value " in the browser console, if I remove the wire:model.live the error in the browser console disappear 

![Image](https://github.com/user-attachments/assets/f221ebb4-02a1-4e12-b17f-00b7ade520b5)

![Image](https://github.com/user-attachments/assets/274f5f2e-751d-46f8-bcc8-4ff51042c5b8)

### Code snippets

```
 <flux:select variant="listbox"
        clear="close" id="filter1" name="filter1"
        selected-suffix="departamentos seleccionados" wire:model.live='filters.departamentosSelected'
        multiple placeholder="Choose industries...">
            @foreach ($departamentos as $key => $value)
                <flux:option value="{{ $key }}">{{ $value }}</flux:option>
            @endforeach
</flux:select>`
```

in the Livewire class I am simply using a call to the db 

```
'departamentos' => \App\Models\Departamento::where('fkCodeCountry', $this->pais->codigo)
                                    ->orderBy("name")->pluck("name", "state"),
```

### How do you expect it to work?

without a warning when using the component

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@mariano55555 Two suggestions:

- remove the `id="filter1" name="filter1"` as it is unnecessary and doesn't match the `wire:model` value
- make sure the `wire:model` property is of type array (initialize it to an empty array if needed `[]`)

**Comment by mariano55555** [comment]
Thank you! it worked, I did both, remove id and  name and initialize with empty array and the warning is gone, thank you!

**Comment by jeffchown** [comment]
You're welcome, @mariano55555 !
