### ISSUE TITLE
<flux:autocomplete> wipes out other JS inputs

### ISSUE THREAD

**Issue by aurawindsurfing** [livewire/flux#941]
### Flux version

v1.1.0

### Livewire version

v.3.5.17

### What is the problem?

I'm using [https://github.com/jackocnr/intl-tel-input](https://github.com/jackocnr/intl-tel-input) for phone input where all the rest of the page is flux. 

The issue is that as soon as I start to search autocomplete input it removes all of the js or css reverting it back to standard input. The same happens if i use both ```<flex:input>``` and ```<input>```.

I should also add that everything works as expected if the page does not have <flux:autocomplete>.

Thank you!

https://github.com/user-attachments/assets/1b22aaf5-03eb-4d84-bcc8-1c6690b6a112

https://github.com/user-attachments/assets/c794ed59-8f72-41de-af63-33e2d44ee105

### Code snippets

```blade
<div>
    <flux:heading size="xl" level="1">Add new classified</flux:heading>
    <flux:spacer size="lg" />

    <form wire:submit="store" class="w-full lg:w-2/3 xl:w-1/2 space-y-4">

        <div class="space-y-6">
            <flux:input wire:model="title" label="Title" />
            <flux:textarea wire:model="content" label="Description" rows="10"/>

            <div>
                <flux:label class="mb-4">Photos</flux:label>
                <flux:card>
                    <livewire:media-library
                        wire:model="images"
                        multiple
                        max-items="3"
                        rules="mimes:png,jpeg,heic,heif"
                    />
                </flux:card>
            </div>

            <div class="flex space-x-4">
                <div class="mt-0 w-1/3">
                    <flux:label class="mb-3">Price</flux:label>
                    <flux:input.group>
                        <flux:input.group.prefix>€</flux:input.group.prefix>
                        <flux:input wire:model="price" placeholder="0.00"/>
                    </flux:input.group>
                </div>

                <div class="w-full">
                    <flux:autocomplete wire:model.live="city" label="Location" name="city" placeholder="Search for a city, town, village, etc.">
                        @foreach ($cities as $key => $value)
                            <flux:autocomplete.item wire:click="city_id = {{$key}}">{{$value}}</flux:autocomplete.item>
                        @endforeach
                    </flux:autocomplete>
                </div>
            </div>
        </div>

        <div class="flex space-x-4">
            <flux:input label="Name" placeholder="Your name" wire:model="name" class="w-1/2" />
            <flux:input label="Phone" type="tel" id="phone" wire:key="donottouch" name="phone" wire:model="phone" class="w-full" />
        </div>

        <div class="flex mt-12">
            <flux:spacer size="lg" />
            <flux:button type="submit" variant="primary">Save</flux:button>
        </div>

    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/intl-tel-input@25.2.0/build/js/intlTelInput.min.js"></script>
<script>
    const input = document.querySelector("#phone");
    window.intlTelInput(input, {
        initialCountry: "IE",
        onlyCountries: ["IE", "GB"],
        placeholderNumberType: 'MOBILE',
        loadUtils: () => import("https://cdn.jsdelivr.net/npm/intl-tel-input@25.2.0/build/js/utils.js"),
    });
</script>

```

I also have css imported in the header:

```blade
<head>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/intl-tel-input@25.2.0/build/css/intlTelInput.css">
        @mediaLibraryStyles
        @fluxStyles

    </head>
```

### How do you expect it to work?

Not to influence other inputs

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
Thank you for the report, however we have been unable to reproduce this given the information available. Please submit a code snippet we can copy and paste into our own apps with steps to reproduce. Be sure to include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Then, we will be happy to help.

**Comment by igmltd** [comment]
I think that’s more of a livewire thing on a network round trip.

use wire:ignore

https://livewire.laravel.com/docs/wire-ignore


As a further read also look up @script and @asset tag in the livewire docs 

https://livewire.laravel.com/docs/javascript

**Comment by aurawindsurfing** [comment]
@joshhanley thank you for taking time and looking into this.

@igmltd is right it was enough to use ```wire:ignore``` to get the script to work as expected. Good knowladge of Livewire is essential to get the most of the flux!

Thank you again!

**Comment by joshhanley** [comment]
@aurawindsurfing oh sorry, I misunderstood the issue. Yep @igmltd is correct and glad you got it sorted 🙂 In future please only include as little code as possible and ideally a Volt or Livewire component class to demonstrate the issue to make it easier for us to review. Thanks!

**Comment by aurawindsurfing** [comment]
Will do! I still need to get my head around Volt 😜

**Comment by joshhanley** [comment]
@aurawindsurfing thanks! If you are used to Livewire, then my recommendation is use the Volt class API instead of functional, as it's basically the same as a Livewire component, but shorter and in one single copy-pasteable file 🙂

That way a Livewire component that might be like this:

```php
use Livewire\Attributes\Validate;
use Livewire\Component;

class MyComponent extends Component {
    #[Validate(['required'])]
    public $content;

    public function save()
    {
        $this->validate();
    }

    public function render()
    {
        return view('livewire.my-component');
    }
};
```

```blade
<div>
    <flux:editor label="Editor" wire:model.live="content" />

    <flux:button wire:click="save">Save</flux:button>
</div>
```

Becomes this:

```blade
<?php

use Livewire\Attributes\Validate;
use Livewire\Volt\Component;

new class extends Component {
    #[Validate(['required'])]
    public $content;

    public function save()
    {
        $this->validate();
    }
};

?>

<div>
    <flux:editor label="Editor" wire:model.live="content" />

    <flux:button wire:click="save">Save</flux:button>
</div>
```
