### ISSUE TITLE
Flux:toast  not working in livewire component

### ISSUE THREAD

**Issue by mmittal2021** [livewire/flux#96]
Flux:toast in only working in Livewire Volt class and not in livewire component

**Comment by Ashraam** [comment]
I'm using toast inside a Livewire component and it's working:

```
Flux\Flux::toast(
    heading: "User created,
    text: "An email has been sent to {$user->email}"
);
```

**Comment by WorthLMS** [comment]
It works fine, if you are redirecting you might not be seeing it. Please look at @persist to keep the <flux:toast /> alive during redirects

**Comment by mmittal2021** [comment]
for some reason I'm getting this error : Class "App\Livewire\Customers\Flux\Flux" not found

**Comment by mmittal2021** [comment]
OK now it's working. I didn't import Flux in the component. Thanks all.
